### ISSUE TITLE
[10.0] web_ir_actions_act_window_message does not give back context

### ISSUE THREAD

**Issue by Cedric-Pigeon** [OCA/web#1002]
If you define a buttons pointing to a method on server side. Whenyou clic on it you loose the context.
Is it expected ?

**Comment by Cedric-Pigeon** [comment]
@hbrunn

**Comment by hbrunn** [comment]
just a case that never occurred to me, but so obvious that I'd call it a bug. You'll probably have to take the current context and add it to the kwargs in https://github.com/OCA/web/blob/10.0/web_ir_actions_act_window_message/static/src/js/web_ir_actions_act_window_message.js#L80

**Comment by Cedric-Pigeon** [comment]
@hbrunn Any clue for me ? I am not really used with js...

**Comment by hbrunn** [comment]
here's how the web client adds the context: https://github.com/OCA/OCB/blob/10.0/addons/web/static/src/js/framework/view.js#L109 (i think you should add it to the kwargs though, with checking if there's already a context) but the more difficult question is where to get it from.

For this, you can query the current view as in https://github.com/OCA/web/blob/10.0/web_ir_actions_act_window_message/static/src/js/web_ir_actions_act_window_message.js#L92 and from there get its dataset's context as done in https://github.com/OCA/OCB/blob/10.0/addons/web/static/src/js/framework/view.js#L74
