### ISSUE TITLE
Notification not received by Logged Out users

### ISSUE THREAD

**Issue by Gokulakannanaj** [OCA/web#1009]
In web notifier module notification sent but not read by user.
Examples:
 Admin sent the notification to 5 users. 3 users working currently and they are receiving notification. But another two users not receiving notification.
Thanks

**Comment by Tardo** [comment]
I think that longpolling clean notifications after 50 seconds

**Comment by pedrobaeza** [comment]
And I see this as an interactive notification system, so no for the use you intend about persistent notifications. You already have that on standard mail system.

**Comment by lmignon** [comment]
@Gokulakannanaj as well explained by @pedrobaeza web_notifier is an instant message notification system.
