### ISSUE TITLE
[11.0][web_tree_dynamic_colored_field] Breaks Internet Explorer 11 compatibility

### ISSUE THREAD

**Issue by grzekru** [OCA/web#1011]
After installation of web_tree_dynamic_colored_field Odoo do not load menus on Internet Explorer 11

**Comment by simahawk** [comment]
@grzekru pls, reload w/ `?debug=assets` and check the log in the inspector. Then report here the full traceback.

**Comment by grzekru** [comment]
It load properly with ?debug=assets but do not load menus in normal mode.
![image](https://user-images.githubusercontent.com/5862658/43688115-2c1ec1ec-98e3-11e8-8baf-d6ac14b5764a.png)
![image](https://user-images.githubusercontent.com/5862658/43688117-387ac332-98e3-11e8-8835-dc4aea787023.png)

**Comment by Tardo** [comment]
IE11 is an 'old' browser... Arrows (ES6) aren't compatible.
https://kangax.github.io/compat-table/es6/#ie11

**Comment by simahawk** [comment]
seems same issue already reported here https://github.com/OCA/web/issues/903
