### ISSUE TITLE
[11.0] web_responsive Field `chatter_position` does not exist 

### ISSUE THREAD

**Issue by Boss1669** [OCA/web#1016]
When trying to upgrade web_reponsive 
Field `chatter_position` does not exist 
`odoo.tools.convert.ParseError: "Error while validating constraint

Field `chatter_position` does not exist

Error context:
View `res.users form`
[view_id: 2135, xml_id: n/a, model: res.users, parent_id: 148]
None" while parsing /odoo-production/odoo-production-server/addons/web_responsive/views/inherited_view_users_form_simple_modif.xml:11, near
<record id="view_users_form_simple_modif" model="ir.ui.view">
        <field name="model">res.users</field>
        <field name="inherit_id" ref="base.view_users_form_simple_modif"/>
        <field name="arch" type="xml">
            <xpath expr="//field[@name='email']" position="after">
                <field name="chatter_position" readonly="0"/>
            </xpath>
        </field>
    </record>`

Do i need to installed any other modules ?

**Comment by pedrobaeza** [comment]
Just update the module for example via command line with `-u web_responsive`.

**Comment by ShopNix** [comment]
Tried to follow your advice, but have no success. Neither by command line nor by web interface. 
I tried to upgrade from  v 11.0.1.0.2 to 11.0.2.0.3

Any more advice for a newbie?

**Comment by yajo** [comment]
Try to uninstall it and install it again.

**Comment by mfmkhatri** [comment]
Were you able to solve the issue? If so, please let me know how. I am facing the same issue.

**Comment by rcserkan** [comment]
> Were you able to solve the issue? If so, please let me know how. I am facing the same issue.
