### ISSUE TITLE
[11.0]web_responsive sticky list header only works on firefox

### ISSUE THREAD

**Issue by youring** [OCA/web#1018]
Sticky Header & Footer in List View not work on Chrome. Because sticky for thead or tfoot is not supported by Chrome.
See Chrome bug https://caniuse.com/#search=sticky. 
So you have to stick with Firefox v61 or later.
Add to Know Issues?

**Comment by Tardo** [comment]
I think that yes...

**Comment by pedrobaeza** [comment]
I have added the known issue in 1f364867b442f4cc36ee910dd7e1251e67be2b38
