### ISSUE TITLE
[Question] I had installed web_widget_text_markdown how to use it?

### ISSUE THREAD

**Issue by v3ss0n** [OCA/web#1021]
This is a question , not an issue , feel free to close it.
module: web_widget_text_markdown
version: 11.0
I am new to developing modules for odoo , and i would like to use markdown widget for HTML Area in Project with odoo11.
I had changed version inside mainfest to 11.0 , and it installed successfully.
How can i replace the html area widget?

**Comment by pedrobaeza** [comment]
The idea is:

* On edit mode, you have the normal text.
* On read mode, the text is rendered in rich text using Markdown syntax.
