### ISSUE TITLE
[10.0] web_widget_color doubles up text in tree views

### ISSUE THREAD

**Issue by Shike019** [OCA/web#1023]
After installing web_widget_color into our existing odoo all of the text doubles up within a tree view.

![image](https://user-images.githubusercontent.com/38432219/44464308-72187000-a5e8-11e8-9248-6fc1eb76d2d4.png)

**Comment by pedrobaeza** [comment]
I don't observe that problem on runbot, so it should be a collision with one of your custom modules.

![seleccion_004](https://user-images.githubusercontent.com/7165771/44469947-d78c5100-a628-11e8-8959-3161f6e10463.png)
