### ISSUE TITLE
Notification not displayed

### ISSUE THREAD

**Issue by Gokulakannanaj** [OCA/web#1025]
In local web notify properly display the message.
At the same time message not displayed when i work in remote or server.
What went wrong ? 
But i don't know what am i missing. Local code also present in remote
Thanks.

**Comment by pedrobaeza** [comment]
Do you have workers and your bus is working?

**Comment by Gokulakannanaj** [comment]
Yes I have. My calendar event reminder notifications are displayed properly.

**Comment by pedrobaeza** [comment]
Can you put your code here?

**Comment by Gokulakannanaj** [comment]
message = "Record cannot be modified right now: \n"
message += "This cron task is currently being executed and may not be modified \n"
message += "Please try again in a few minutes"
self.env.user.notify_warning(title='Approval', message=message, sticky=True)

**Comment by pedrobaeza** [comment]
@lmignon do you see any problem in that code?

**Comment by Gokulakannanaj** [comment]
Nope. Its work properly on my local machine.
When it move to remote, i'm not getting notification. But the same time i'm getting calendar reminder.

**Comment by Gokulakannanaj** [comment]
@pedrobaeza want to make any configuration in my config file ?

**Comment by pedrobaeza** [comment]
@Gokulakannanaj what do you mean?

**Comment by Gokulakannanaj** [comment]
@pedrobaeza whether to make any changes in my configuration file

**Comment by pedrobaeza** [comment]
I think it can be something on your proxy configuration and `proxy_mode=True` in configuration, but I can't say. Any way, it's not a problem of the module itself, so I'm going to close this, sorry.

**Comment by Gokulakannanaj** [comment]
@pedrobaeza proxy_mode is also True. Any way thank you. I'll go with my custom model.

**Comment by Gokulakannanaj** [comment]
@pedrobaeza Please check below link, In runbot bus notification not displayed
http://3362419-12-0-e4e84f.runbot2.odoo-community.org/web?debug=1#id=2&action=68&model=res.users&view_type=form&menu_id=4
