### ISSUE TITLE
Uncaught Error: QWeb2: Template 'TimelineView' not found

### ISSUE THREAD

**Issue by alcool179** [OCA/web#1035]
After installing Timeline view on ODOO 10 and click on the button with the clock, this message appear
"Uncaught Error: QWeb2: Template 'TimelineView' not found"
which kind of modify are needed for enable this addon??

**Comment by pedrobaeza** [comment]
Which module are you installing? `web_timeline` per se doesn't add any view.

**Comment by alcool179** [comment]
Hi Pedro,
thank you for your answer.
I installed web_timeline and project_timeline. 
Following the configuration instructions here (https://www.odoo.com/apps/modules/10.0/web_timeline/) seems to be necessary create a xml file with a view... but I don't know where put this file and which name to use..

Any suggestions?

**Comment by pedrobaeza** [comment]
That module already includes the proper XML definition. You just have to install modules, maybe restart service depending on the technique and refresh view. Try on https://runbot.odoo-community.org/runbot/build/3337856 (when it finishes of building)

**Comment by alcool179** [comment]
The configuration instructions suggest to 
_"You need to define a view with the tag <timeline> as base element. These are the possible attributes for the tag:   [...]"_
and
_"You also need to declare the view in an action window of the involved model."_

and reports an example.

Also after an /etc/init.d/odoo restart the problem remains

**Comment by ValentinVinagre** [comment]
Hello @alcool179,
I have had the same problem, I have solved it by restarting the server and updating the Project timeline module.

**Comment by pedrobaeza** [comment]
Yes, that's it
