### ISSUE TITLE
web_easy_switch_company 9.0: unable to uninstall

### ISSUE THREAD

**Issue by AlainVanUtterbeeck** [OCA/web#1036]
I'm trying to upgrade from V9 to V10 using OpenUpgrade.
As this module does no longer exist for V10 (apparantly, functionality is now standard), I try to uninstall this module before upgrading but that does not work, I uninstall the module, do an -u all, but when I then restart Odoo, the module seems to be still installed.

**Comment by pedrobaeza** [comment]
The module is seamlessly merged on core web module following OpenUpgrade migration, so you don't need to uninstall it.

**Comment by AlainVanUtterbeeck** [comment]
Ok, thanks for the info

Op di 2 okt. 2018 17:36 schreef Pedro M. Baeza <notifications@github.com>:
