### ISSUE TITLE
Advanced search cannot select from dropdown list, advanced filter is not useful.

### ISSUE THREAD

**Issue by hydrosIII** [OCA/web#1049]
Example:

Go to inventory -> Master Data -> products.

Try to create a filter with vendors. Advanced search will pop out a drop down list with vendors, you Can select the vendor, and press enter but the filter will be empty and the filter will come out undefined. I have tried this with this example, but is very possible that the behaviour is this, when advanced search tries to search and gives a drop down list. Also it is nos usable the filter with CONTAINS option, as it gives again an undefined filter.

**Comment by pedrobaeza** [comment]
Are you using latest version. Specifically, with this PR: https://github.com/OCA/web/pull/1040. It solves that problem in theory.

**Comment by hydrosIII** [comment]
Let me check, with that version

**Comment by hydrosIII** [comment]
Rechecking this. It is solved.
