### ISSUE TITLE
Error: QWeb2: Template 'web_responsive.MenuStatusbarButtons' not found

### ISSUE THREAD

**Issue by iamsurawee** [OCA/web#1052]
Odoo 11 Please advise error below after click menu setting in SALE AND CRM

Error: QWeb2: Template 'web_responsive.MenuStatusbarButtons' not found

**Comment by pedrobaeza** [comment]
You have to properly install the module, maybe restarting the Odoo service and refreshing browser. Check also that there's no incompatible module also installed.

**Comment by Ark74** [comment]
> also that there's no incompatible module 

Very important to check if you have being messing with updates, upgrades or migrations.

**Comment by TheDailySpank** [comment]
```sudo /opt/bitnami/ctlscript.sh restart``` and a browser refresh worked for me.
