### ISSUE TITLE
web_responsive kanban view

### ISSUE THREAD

**Issue by levkar** [OCA/web#1053]
Kanban views does not work properly with web_responsive when resized to small resolutions. They are stacked and some items are missing.

**Comment by pedrobaeza** [comment]
Can you be more specific, with screenshots and so on? Take into account also that when switching to mobile view on PC browsers, you have to refresh view for elements to be properly in place due to some JS working on background.

**Comment by levkar** [comment]
Problems are due to switching to mobile through browser. Reloading fixes them. I am closing this issue.

Sorry for taking your time.
