### ISSUE TITLE
[11.0]web_group_expand: groupsexpand/ collapse very slow

### ISSUE THREAD

**Issue by RamlaFtouh** [OCA/web#1063]
I have a liste with about 290 record, I group by 'name' . I get  about 290 groups.
If i try to expand/ collapse 290 groups, the action is so slow that the browser thinks Odoo is not reacting (s. Screenshot).
![image](https://user-images.githubusercontent.com/30926992/46445164-48b53d00-c76d-11e8-8f5d-0f5a133d1126.png)

Would it be possible to optimize the performance of these functions ?
Regards.

**Comment by pedrobaeza** [comment]
This is something not about the module, but how Odoo fetches data when you ungroup, so nothing to do in this side.
