### ISSUE TITLE
web_widget_datepicker_options: allow to set `minDate` via variable / field

### ISSUE THREAD

**Issue by vbezl** [OCA/web#1065]
Hi, 

This works:
```
<field name="relocation_date" options="{'datepicker': {'minDate': '0'}}"/>
<field name="relocation_date" options="{'datepicker': {'minDate': '2018-09-25'}}"/>
```

This DOES NOT work:
```
<field name="relocation_date" options="{'datepicker': {'minDate': 'minimum_relocation_date'}}"/>
```

It gives an error:
Uncaught TypeError: minDate() Could not parse date parameter: minimum_relocation_date (this is a model field and I put it to the form as invisible also...)

**Comment by tarteo** [comment]
Hello @vbezl, I don't see the images. :smile: Can you try to upload them again, please.

**Comment by vbezl** [comment]
@tarteo Sorry, those were not images, but code snippets - please see updated comment above :)
Thanks for answer!

**Comment by tarteo** [comment]
No problem :smile: This is because it's not implemented for fields yet it just passes it to the jQuery datepicker plugin. If you want you can make a PR with this improvement. Otherwise you have to wait for another developer to make this. or for now use @api.contrains to make a server side constraint.

**Comment by vbezl** [comment]
I got it. Will definitely submit PR in case we make this improvement.

**Comment by simahawk** [comment]
@vbezl version?

**Comment by vbezl** [comment]
@simahawk we haven't yet made this feature

**Comment by simahawk** [comment]
@vbezl question is: which version are you using? 10? 11? :)

**Comment by vbezl** [comment]
@simahawk oh, sorry, it's Odoo 11.

**Comment by simahawk** [comment]
thanks :)

**Comment by ZERO20** [comment]
<field name="date_action" options="{'datepicker': {'minDate': '0'}}"/>

i get a error picker.options.minDate.year is not a function im using openErp 9

**Comment by ZERO20** [comment]
> thanks :)

can u help me? picker.options.minDate.year is not a function

**Comment by ZERO20** [comment]
> @simahawk oh, sorry, it's Odoo 11.

can u help me?

**Comment by simahawk** [comment]
> i get a error picker.options.minDate.year is not a function im using openErp 9

doing what? where's the code?
Also, this is an issue for v11 and you say v9: your comment is completely out of scope.
Open another issue if you need help. Thanks.

**Comment by ZERO20** [comment]
> > i get a error picker.options.minDate.year is not a function im using openErp 9
> 
> doing what? where's the code?
> Also, this is an issue for v11 and you say v9: your comment is completely out of scope.
> Open another issue if you need help. Thanks.

thanks for nothing! :)
