### ISSUE TITLE
[10.0] Travis is broken

### ISSUE THREAD

**Issue by SimoRubi** [OCA/web#1072]
I have noticed that Travis's odoo (and OCB) tests are broken from a while in branch 10.0, the recurring error is in phantomjs:
```
phantomjs: global failure in section  failed: SyntaxError: Unexpected token '('
```

Looking at its history I have found out that https://travis-ci.org/OCA/web/jobs/397176092 is green and the following https://travis-ci.org/OCA/web/jobs/410322124 is red (error line: https://travis-ci.org/OCA/web/jobs/410322124#L1471), but I can't find what is the change that broke it.

**Comment by pedrobaeza** [comment]
It's a problem with `web_widget_slickroom` module. @hbrunn and me suggested, although not the best option, to simply disable that tour, as the maintainer of that module is not anymore in Odoo.

**Comment by hbrunn** [comment]
ah, thanks for triaging this. What PhantomJS complains about is https://travis-ci.org/OCA/web/jobs/410322122#L923, which is https://github.com/OCA/web/commit/b4ba0eeb4a8c857eb9b488ddaf80a2af9929ccba#diff-f139359382dd29d8fd35d34d1a80df72R43

So there's a chance stuff just works when you bring this in normal form as in `name: function(parameter1, parameter2)`

**Comment by hbrunn** [comment]
PS: we should take our linters more seriously...

**Comment by hbrunn** [comment]
@moylop260 is there any chance to have pylint fail on parsing errors? Currently, that's just a warning

**Comment by SimoRubi** [comment]
Thanks @hbrunn I created https://github.com/OCA/web/pull/1073 to fix that
