### ISSUE TITLE
[12.0] UI/UX Stuff

### ISSUE THREAD

**Issue by Tardo** [OCA/web#1076]
Hi, i know that this is a interpretable stuff... but i want share my point of view.

- In App list, same button (Position, size, etc..) have two different actions... this can be confused:
![same_button](https://user-images.githubusercontent.com/731270/46897245-cff76480-ce81-11e8-8ee9-fff8b892315b.png)
- Selected check's looks like read-only control:
![check_readonly](https://user-images.githubusercontent.com/731270/46897376-86f3e000-ce82-11e8-877f-961c6249c1d0.png)
- Menu section looks like selectable item:
![menu_active](https://user-images.githubusercontent.com/731270/46897392-9a9f4680-ce82-11e8-9339-de7d342aa572.png)

**Comment by pedrobaeza** [comment]
But shouldn't this go to odoo/odoo and not here?

**Comment by simahawk** [comment]
@Tardo are you referring to any particular OCA/web feature?
If not, pls close this and report on odoo/odoo, thanks.
