### ISSUE TITLE
[11.0][web_widget_x2many_2d_matrix] cannot store fields values not included in the matrix

### ISSUE THREAD

**Issue by simahawk** [OCA/web#1084]
Origin: https://github.com/OCA/product-variant/pull/109#discussion_r225880090

Fields not included in the matrix are not considered on save.

@pedrobaeza @Yajo is that all? Have you identified specific flaws or possible solutions?

**Comment by pedrobaeza** [comment]
Thanks for continuing this. You can check on the module `sale_order_variant_mgmt` in version 10, that the model shown on the matrix contains an extra field:

https://github.com/OCA/product-variant/blob/249bea07fcf1b202254c953d09c8b5d740f06ad6/sale_order_variant_mgmt/wizard/sale_manage_variant.py#L96-L105

which is `product_id`. That field was used for storing a temp value for finding the line.

Now on v11, extra values are not stored, giving an error with the same code (on v11 there's a workaround in this case).

**Comment by GSLabIt** [comment]
@simahawk do u know if it is possible to show fields not included in matrix (before/after it)? Thx
