### ISSUE TITLE
[11.0][web_listview_range_select] Can not delete multiple records selected by holding Shift

### ISSUE THREAD

**Issue by novawish** [OCA/web#1095]
# Current situation
When select multiple records on list view (with Shift) and click _Action > Delete_, the system will only delete the first and the last record, records within the range are not affected.
Same issue happens with _Export_ and _Invoice Orders_ on Sale Order list view.

# Expected behavior
Should be able to do all the options inside `Action` with list view range selection

**Comment by pedrobaeza** [comment]
Version?

**Comment by novawish** [comment]
I tested on odoo version 11.0 but i think it would be the same for 10.0 and 12.0

**Comment by tarteo** [comment]
I tested it it's only for 11.0. I've to see what changed in the migration to 11.0 https://github.com/OCA/web/pull/910

**Comment by novawish** [comment]
Hello @tarteo , thanks for your reply, do you have any news on this?

**Comment by tarteo** [comment]
@novawish Hey, I created a fix: #1127

**Comment by metalmonkey69** [comment]
@tarteo I've tested your fix. If i apply it for range export, the last record will be exported twice. I guess it works for range delete because you cannot delete a record twice. I am using Odoo11 latest version.

**Comment by tarteo** [comment]
@peterhoth Thanks, I also fixed this in the pull request. Can you check and leave a review. #1127
