### ISSUE TITLE
[11.0][BUG] web_export_view: empty column w/ group by on

### ISSUE THREAD

**Issue by angelmoya** [OCA/web#1099]
In any list view with group, if you export view, the excell generated add a void field on header.

![contacts odoo](https://user-images.githubusercontent.com/6750341/48143517-3c158e80-e2af-11e8-9b5d-b22ef9a0d23b.png)

![export](https://user-images.githubusercontent.com/6750341/48143524-3fa91580-e2af-11e8-94f2-d13f7ca2fafc.png)

Maybe the problem is related with javascript that get header names, and don't take care agout grouping add a void field on header.

https://github.com/OCA/web/blob/11.0/web_export_view/static/src/js/web_export_view.js#L53

**Comment by simahawk** [comment]
tested on runbot: confirmed.

**Comment by bistaray** [comment]
Is there any update on the export bug. We are also facing the same issue.

**Comment by HaGuesto** [comment]
@angelmoya Thanks for reporting the bug!

However, I cannot reproduce it. I tried to for the PR #1169. Could you please write down your steps?

**Comment by Tardo** [comment]
@HaGuesto 
- Go tree view
- Use filter 'Group By'
- Select a record
- Use export button
