### ISSUE TITLE
[11.0] - web_tree_dynamic_colored_field: Check condition with fields value

### ISSUE THREAD

**Issue by sudhir-erpharbor** [OCA/web#1103]
How can we check the condition by using field's value in XML attribute.

**Ex:** `<field name="date_start" options='{"bg_color":"#ffdd99: state != cancel"}'/>`

When I load the view, I see JS error: `Error: NameError: name 'cancel' is not defined`
Is it a bug or I am doing something wrong? I checked the examples of the module but all examples use the boolean field. Please let me know if there is a any way.

**Comment by pedrobaeza** [comment]
Please don't spam in other threads for your question.

You have to enclose `cancel` value between quotes.

**Comment by sudhir-erpharbor** [comment]
@pedrobaeza 
Thanks for your reply. Sorry about that, I removed the thread from the PR.

But how do I enclose the value in quote because options dictionary is already in a single quote and the key and value of the dictionary is also in quote, so how is it possible to have another quote for the value (cancel)?

Do you mean like this: `options='{"bg_color":"#ffdd99: state != 'cancel' "}'` or `options='{"bg_color":"#ffdd99: state != "cancel" "}'`

I don't think this will work. It would be great if you can provide example.

@simahawk @gurneyalex @hbrunn
