### ISSUE TITLE
[11.0] - web_tree_dynamic_colored_field: Check condition with fields value

### ISSUE THREAD

**Issue by sudhir-erpharbor** [OCA/web#1105]
Sorry guys but I had to write this issue again as the answer given in my previous issue #1103  does not help me.

**Issue:**
How can we check the condition by using field's value in XML attribute.

**Ex:** `<field name="date_start" options='{"bg_color":"#ffdd99: state != cancel"}'/>`

When I load the view, I see `JS error: Error: NameError: name 'cancel' is not defined`
Is it a bug or I am doing something wrong? I checked the examples of the module but all examples use the boolean field. Please let me know if there is a any way.

How do I enclose the value in quote because options dictionary is already in a single quote and the key and value of the dictionary is also in quote, so how is it possible to have another quote for the value (cancel)?

Does it mean like this: `options='{"bg_color":"#ffdd99: state != 'cancel' "}'` or `options='{"bg_color":"#ffdd99: state != "cancel" "}'` but XML does not allow something like this.

I will appreciate your help and would be much helpful if anyone can give the solution with the example.

@simahawk @gurneyalex @hbrunn @pedrobaeza

**Comment by simahawk** [comment]
you have to escape quotes https://stackoverflow.com/questions/3961505/how-to-escape-double-quotes-in-xml-attributes-values

**Comment by sudhir-erpharbor** [comment]
@simahawk Thanks for your reply and for the example. I tried that `<field name="date_start" options='{"bg_color":"#ffdd99: state != &quot;cancel&quot;"}'/>` but it does not work. When I try to reload the view I see following error from the JS.
`Uncaught Error: Expected "}", got "(name)"`

Error:
Uncaught Error: Expected "}", got "(name)"

http://localhost:9898/web/content/541-4cfaf93/web.assets_backend.js:142
Traceback:
Error: Expected "}", got "(name)"
    at advance (http://localhost:9898/web/content/541-4cfaf93/web.assets_backend.js:142:50)
    at F.symbol.nud (http://localhost:9898/web/content/541-4cfaf93/web.assets_backend.js:131:1)
    at expression (http://localhost:9898/web/content/541-4cfaf93/web.assets_backend.js:140:146)
    at Object.py.parse (http://localhost:9898/web/content/541-4cfaf93/web.assets_backend.js:257:462)
    at Object.py.eval (http://localhost:9898/web/content/541-4cfaf93/web.assets_backend.js:272:296)
    at Object.py_eval (http://localhost:9898/web/content/541-4cfaf93/web.assets_backend.js:401:42)
    at Class._processField (http://localhost:9898/web/content/541-4cfaf93/web.assets_backend.js:586:301)
    at http://localhost:9898/web/content/541-4cfaf93/web.assets_backend.js:601:57
    at Object.traverse (http://localhost:9898/web/content/498-ef7145d/web.assets_common.js:4033:320)
    at http://localhost:9898/web/content/498-ef7145d/web.assets_common.js:4033:368

I think something needs to be changed in the JS engine of the module.

**Comment by sudhir-erpharbor** [comment]
@simahawk Would you please re-open the issue and guide me how to do it or fix it?

**Comment by lijoantony** [comment]
Use `&apos;` instead of `&quot;`.
`&apos;` stands for apostrophe or single-quote character (')

**Comment by sudhir-erpharbor** [comment]
Does not matter. Nothing works. Just try that your own on runbot or on your machine as per my example and check if that really works or not.

I am wondering why no-one has this issue yet.

**Comment by lijoantony** [comment]
This does work for me.

`<field name="state" options='{"bg_color": "red: state == &apos;free&apos;"}'/>`
