### ISSUE TITLE
Unable to install module "web_widget_bokeh_chart"

### ISSUE THREAD

**Issue by ferharo1** [OCA/web#1111]
I'm trying to install it on Ubuntu Server 18.04 LTS and appears this error:
Unable to install module "web_widget_bokeh_chart" because an external dependency is not met: No module named bokeh.
I already installed bokeh library and the error persist.

**Comment by pedrobaeza** [comment]
No, you haven't in your correct environment. Closing as this is not a problem of the module, but your deployment.
