### ISSUE TITLE
web.assets_backend.js:504      View type 'timeline' is not present in the view registry.

### ISSUE THREAD

**Issue by qvinh222** [OCA/web#1112]
Odoo V12.
I install the module web_timeline. 
After install and create view for project.task then update module.
I open menu Tasks but there is no button for view 'timeline' view.  In the chrome console show error: web.assets_backend.js:504      View type 'timeline' is not present in the view registry.

**Comment by pedrobaeza** [comment]
It seems you haven't restart your Odoo server and refresh browser.

**Comment by qvinh222** [comment]
Unlucky me!
I have tried to restart my server and frefresh browser many time.

**Comment by moblesmarti** [comment]
Could it be that you are looking for the characteristics of project_timeline instead of web_timeline?

**Comment by qvinh222** [comment]
I found the issue, I download the failure module from here: https://odoo-community.org/shop/product/web-timeline-2812?search=timeline&attrib=2-14. 
I re-download module from this repo. It work well.

Thank you very much.
