### ISSUE TITLE
Edit a second model via Timeline 

### ISSUE THREAD

**Issue by Raffxyz** [OCA/web#1115]
I have a timeline view that display my model called "event".
My "event" is related (many2one) to another model called "appointment".
My objective is to be able to edit the appointment datas when i click on the event.
Is it possible?

I've seen that in the controller.js code there is a code to relate with the records of the group model. How can I do the same with my "appointments"?

**Comment by pedrobaeza** [comment]
This has been created as a view, not a widget, so that's not possible unless you define the view and navigate (by code or UI) to the other model, or you can refactor the module to work as view and widget.
