### ISSUE TITLE
[11.0] Making <timeline> nodes readonly (disable drag&drop).

### ISSUE THREAD

**Issue by kmmm16** [OCA/web#1120]
Hi,
Is it possible to make `<timeline>` view nodes readonly (i mean disabling drag&drop option of selected node)?
I tried to figure out that, but without any positivie result.

README file doesn't consider this, but maybe there is a way to achive that, which is not documented.

Thanks.

**Comment by pedrobaeza** [comment]
Have you used `attrs` as any other standard view?

**Comment by kmmm16** [comment]
Yes, but probably i am doing it wrong.
This is my code (view.xml):

```
<record id="test_my_model_timeline" model="ir.ui.view">
    <field name="model">test.my_model</field>
    <field name="type">timeline</field>
    <field name="arch" type="xml">
      <timeline date_start="date_start"
                date_stop="date_end"
                default_group_by="user_id"
                event_open_popup="false"
                attrs = "{'readonly' : True }"
                />
    </field>
  </record>
```
With that, i am still enabled to drag and drop nodes.
Last time i use attrs, was for field, i didn't use it for view.

Could you tell me how to do it properly?

**Comment by pedrobaeza** [comment]
OK, it's not about granularity of each item (I was talking at field level...). Then put `edit="0"` in the view.

**Comment by kmmm16** [comment]
Okay, so i tried edit="0", just like for `<tree>` view in base, and nodes are still draggable.
I also tried to do it at the field level and i get exception:

> 
> Uncaught TypeError: Cannot read property 'tag' of undefined
> 
> http://localhost:8069/web/content/389-8ca936d/web.assets_common.js:4023
> Traceback:
> TypeError: Cannot read property 'tag' of undefined
>     at Object.json_node_to_xml (http://localhost:8069/web/content/389-8ca936d/web.assets_common.js:4023:238)
>     at Class.init_timeline (http://localhost:8069/web/content/414-af44150/web.assets_backend.js:2460:561)
>     at http://localhost:8069/web/content/414-af44150/web.assets_backend.js:2459:139
>     at http://localhost:8069/web/content/389-8ca936d/web.assets_common.js:802:681
>     at fire (http://localhost:8069/web/content/389-8ca936d/web.assets_common.js:796:299)
>     at Object.add [as done] (http://localhost:8069/web/content/389-8ca936d/web.assets_common.js:797:467)
>     at Array.<anonymous> (http://localhost:8069/web/content/389-8ca936d/web.assets_common.js:802:649)
>     at Function.each (http://localhost:8069/web/content/389-8ca936d/web.assets_common.js:625:767)
>     at Object.<anonymous> (http://localhost:8069/web/content/389-8ca936d/web.assets_common.js:802:560)
>     at Function.Deferred (http://localhost:8069/web/content/389-8ca936d/web.assets_common.js:803:194)

**Comment by pedrobaeza** [comment]
OK, then it seems there's no support yet for this. @tarteo do you know about this option?

**Comment by kmmm16** [comment]
So i figure out how to avoid exception (if you use `<field>` in `<timeline>` node, you also have to use formula with `<templates>` (just like in README file).
FYI, codes without exception, but also without effect:
First approach:

```
<record id="test_my_model_timeline" model="ir.ui.view">
    <field name="model">test.my_model</field>
    <field name="type">timeline</field>
    <field name="arch" type="xml">
      <timeline date_start="date_start"
                date_stop="date_end"
                default_group_by="user_id"
                event_open_popup="false"
                edit="0"
                />
    </field>
  </record>
```

Second approach:
```
 <record id="test_my_model_timeline" model="ir.ui.view">
    <field name="model">test.my_model</field>
    <field name="type">timeline</field>
    <field name="arch" type="xml">
      <timeline date_start="date_start"
                date_stop="date_end"
                default_group_by="user_id"
                event_open_popup="false">
               <field name="user_id"/>
               <field name="date_start" readonly="1"/>
               <field name="date_end" readonly="1"/>
               <templates>
                    <div t-name="timeline-item">
                         <div t-esc="record.display_name"/>
                     </div>
               </templates>
      </timeline>
    </field>
  </record>
```

Third approach:

`

```
<record id="test_my_model_timeline" model="ir.ui.view">
    <field name="model">test.my_model</field>
    <field name="type">timeline</field>
    <field name="arch" type="xml">
      <timeline date_start="date_start"
                date_stop="date_end"
                default_group_by="user_id"
                event_open_popup="false">
               <field name="user_id"/>
               <field name="date_start" attrs="{'readonly': True}"/>
               <field name="date_end" attrs="{'readonly': True}"/>
               <templates>
                    <div t-name="timeline-item">
                         <div t-esc="record.display_name"/>
                     </div>
               </templates>
      </timeline>
    </field>
  </record>
```

**Comment by tarteo** [comment]
There's no support for this. It's only controlled by `ir.model.access`.

**Comment by kmmm16** [comment]
Okay, i will try manage `ir.model.access`. And see if drag is still possible.

**Comment by kmmm16** [comment]
With `ir.model.access` i achieve my goal in acceptable level. Thank you all!

**Comment by pedrobaeza** [comment]
Any way, we should add the possibility of `edit="0"` in the view. @tarteo can you add it to the ROADMAP?

**Comment by kmmm16** [comment]
In my opinion, the most awsome feature would be enabling change readonly value for specyfic nodes on timeline chart (like for tasks with special status etc.). It could be changed by e.g. `is_editable` field. Also for me now it is quite annoying that i have global `event_open_popup` value (i tried to bind it with model computed field, but it was impossible). But i made some workaround with groups and `ir.model.access` and `ir.rule`, and it is fine for me ;). For now, i am not that deep into Odoo to change behavior of that module (need quite good understanding of creating views from scratch in this framework), but maybe in future.

**Comment by pedrobaeza** [comment]
Yes, that's another extra feature for the roadmap: making `attrs` to works well (`readonly` and I don't know if `invisible` is already processed).
