### ISSUE TITLE
[RFC] Module that enhances datetime entry

### ISSUE THREAD

**Issue by alexey-pelykh** [OCA/web#1122]
In Xero, I've seen pretty neat datetime parsing where "Oct 4" and "4th oct" would be parsed regardless of the locale. In addition to that, it seems that datetime locate / format should be something separate from language of account in Odoo. And I'd like to request more opinions on that matter.

**Comment by alexey-pelykh** [comment]
@pedrobaeza @tarteo

**Comment by pedrobaeza** [comment]
Well, I haven't felt the need of improving that for now, as we have these options:

* Write a number: it's taken as day, adding automatically current month and year.
* Write number, `/` and other number, or four digits: it's taken as day and month according locale.
* Write 6 digits: it's taken as day, month and year according locale.

With that, the date entry is very neat and enough for all my use cases.

**Comment by alexey-pelykh** [comment]
@pedrobaeza thanks for the feedback!
@hbrunn your name came up related to the topic (https://apps.odoo.com/apps/modules/7.0/web_lib_moment/), it would be great to get your input as well
