### ISSUE TITLE
[web_timeline] 2 records with date_start = date_end do not appear on the same line (or how to implement margin.item.horizontal support ?)

### ISSUE THREAD

**Issue by cvinh** [OCA/web#1133]
I'm looking forward to show 2 successive items on the same line in a timeline view, can anybody help ?

steps to reproduce : 
- build a timeline view (in our case hr_contract)
- set 2 records (hr_contract) with date_start of the second one = date_end of the first one (in our case a rotation of 2 persons for the same job)

result : 
- the 2 blocks are not aligned
expected behavior : 
- the 2 blocks are aligned on the same line

**Comment by pedrobaeza** [comment]
This is automatically done by the JS library. Any way, I would go for grouping at employee level and don't worry about that.

**Comment by cvinh** [comment]
Dear @pedrobaeza thank you, that's the point... The js lib does not do the job. Grouping by job_id do group the 2 blocks in the same group but they appear one over the other one. After testing they go on the same line if date_start = date_end + 2 days... We would like to have them on the same line as long as date_start = date_end...
(We have more than 30 jobs on the same view and would like a good looking Tetris)
If somebody could point out where to search in the js lib... we would open an issue at vis.js...

**Comment by pedrobaeza** [comment]
Bundled vis.js library included is minified, so you have to go to the source: https://github.com/almende/vis/tree/master/lib/timeline. But I can't say anything more about that as I barely know that source code. @tarteo maybe you can give us a hint about that.

**Comment by tarteo** [comment]
@invitu You can use the option 'stack'. This works for your case, but this also make items overlap.

> If true (default), items will be stacked on top of each other such that they do not overlap.
--






http://visjs.org/docs/timeline/

**Comment by cvinh** [comment]
@tarteo thank you for your tip
btw, I added stack="false" in view definition but the items stay on 2 lines. (I flushed my browser cache)
Do you see something bad on my side (odoo v12) ?

**Comment by tarteo** [comment]
It's not an option in the view definition, but of the visjs timeline. You can change it with Javascript.

**Comment by cvinh** [comment]
@tarteo thank you again but I'm afraid I don't see where to change it... in the vis.js library itself ? or is there an option file somewhere for vis.js ?

**Comment by tarteo** [comment]
Before line 226 in /web_timeline/static/src/js/timeline_renderer.js

**Comment by cvinh** [comment]
thank you @tarteo I do a PR for stack support : https://github.com/OCA/web/pull/1134

**Comment by cvinh** [comment]
@tarteo oula... my PR supports stack option but that's not exactly what I wanted ...
Now all the items do overlap... I just wanted the items not to overlap when date_end (previous record) = date_start (next record).
If the items overlap, we would need to see them stacked

Our use case is : 
we have hr contracts for job positions in departments. every contracts are successive for a given job position in a given department. Employees do rotations on job positions for every contract...
For a timeline view grouped by department, we would like to have a "Tetris" that do not overlap.
Of course when we have a rotation of employees, date_end for the first one = date_start for the next one (as we do not want empty job position even for one day)
I hope my explanation is clear...

**Comment by tarteo** [comment]
@invitu Yes, this what I said in my previous comment. I think it's still nice to expose this option for the view definition. You can create an issue in the visjs repository if you want the stacking behavior changed.

**Comment by cvinh** [comment]
https://github.com/almende/vis/issues/4214

**Comment by cvinh** [comment]
it works with margin: { item: { horizontal: -1 } } }

**Comment by cvinh** [comment]
PR with margin support : https://github.com/OCA/web/pull/1135
