### ISSUE TITLE
web_widget_color: Download issue in v11

### ISSUE THREAD

**Issue by nikul-serpentcs** [OCA/web#1143]
@pedrobaeza @jbeficent @OCA/web-maintainers 
If I am clone module in here `https://github.com/OCA/web/tree/11.0` that work is fine, 

But if I download `https://apps.odoo.com/apps/modules/11.0/web_widget_color/` here then the same issue 
 #1139

How can we solve it?

**Comment by sudhir-erpharbor** [comment]
@nikul-serpentcs 
I think new changes are not yet reflected (synced) in odoo apps which is causing such issue

CC: @pedrobaeza .

**Comment by nikul-serpentcs** [comment]
> @nikul-serpentcs
> I think new changes are not yet reflected (synced) in odoo apps which is causing such issue
> 
> CC: @pedrobaeza .

Yes, @sudhir-erpharbor new changes are not synced in App store.
