### ISSUE TITLE
[11.0] web_tree_image, is this working?

### ISSUE THREAD

**Issue by GSLabIt** [OCA/web#1148]
Trying to use this module with no success using `widget="image"` on character field with both icon name and` path/to/image`.

database field value: 

`/mymodule/static/src/img/icons8-filled-circle-filled-48.png`

on javascript console getting:

`data:image/png;base64,/mymodule/static/src/img/icons8-filled-circle-filled-48.png net::ERR_INVALID_URL`

Not sure what i'm doing wrong, any hint on how to make it work?

**Comment by pedrobaeza** [comment]
The error seems clear: you haven't put the image in the proper path. I'm seeing there an absolute path, and that's something invalid.

**Comment by GSLabIt** [comment]
@pedrobaeza ..i'm not yet that stupid. On documentation, I read:

 If you use the widget with a character field, the content of the field can be any of the following:

The absolute or relative location of an image. For example, "/<module>/static/src/img/youricon.png"

Ref to: https://github.com/OCA/web/tree/11.0/web_tree_image
So, what that means?

**Comment by moylop260** [comment]
Hi @joezsweet 
I don't know this module so much.

But I have a guess, reading the documentation:

```markdown
If you use the widget with a character field, the content of the field can be any of the following:

1. The absolute or relative location of an image. For example, "/<module>/static/src/img/youricon.png"
2. A standard icon from the web distribution, without path or extension, For example, 'gtk-open'
3. A dynamic image in a data url base 64 format. Prefix with 'data:image/png;base64,'
```

You can use a path like 1. but you are using the prefix like 3.
Then could you trying removing the prefix and told us about.

**Comment by GSLabIt** [comment]
@pedrobaeza @moylop260  Problem is exactly that one. I'm not adding the prefix, for some unknown (for me) reason the module is adding it; seems like module is not recognizing it's not an image but a relative path.

**Comment by GSLabIt** [comment]
@pedrobaeza, could you reopen the issue?

**Comment by nikul-serpentcs** [comment]
@joezsweet This module used for in tree view, we saw the image using `wedget=image`.

In XML, You can add  `wedget=image` in fields, that time saw an image in a tree view with default width is 30px.

**Comment by nikul-serpentcs** [comment]
> Hi @joezsweet
> I don't know this module so much.
> 
> But I have a guess, reading the documentation:
> 
> ```gfm
> If you use the widget with a character field, the content of the field can be any of the following:
> 
> 1. The absolute or relative location of an image. For example, "/<module>/static/src/img/youricon.png"
> 2. A standard icon from the web distribution, without path or extension, For example, 'gtk-open'
> 3. A dynamic image in a data url base 64 format. Prefix with 'data:image/png;base64,'
> ```
> 
> You can use a path like 1. but you are using the prefix like 3.
> Then could you trying removing the prefix and told us about.

@joezsweet @moylop260 In v11 we have widget image in a tree view, in v10 or v9 above 1 and other points are covered.

**Comment by nikul-serpentcs** [comment]
> @pedrobaeza, could you reopen the issue?

@joezsweet It's No need to reopen the issue Because it's module limit per this functionality.

Thanks

**Comment by GSLabIt** [comment]
@nikul-serpentcs thanks  for clarification, would be nice to change documentation
