### ISSUE TITLE
[11.0][web_timeline] empty group -

### ISSUE THREAD

**Issue by ruben-tonetto** [OCA/web#1153]
A group with text '-' is always displayed, even if i have set default_group_by; in this case the '-' group is empty.
I imagine that is necessary if default_group_by is not set, so an empty group with no name is set.

`groups.push({id: -1, content: _t('-')});`

ref:
https://github.com/OCA/web/blob/9f91d5d9a9e2a5e602d1beb70598aa102da15409/web_timeline/static/src/js/timeline_renderer.js#L366

is it possible to move it just before return if groups is empty?
for example:

if (groups.length == 0){
groups.push({id: -1, content: _t('-')});
}
return groups

regards
Ruben

**Comment by pedrobaeza** [comment]
If you have the solution, you can do the PR.
