### ISSUE TITLE
New Widget: "Like Github Contributions Widget" for Partner

### ISSUE THREAD

**Issue by agent-z28** [OCA/web#1157]
the description of your feature : I suggest a widget like the GitHub Contributions Widget.
the Odoo version you expect it to run on: v11+
mockups and visual materials
![bildschirmfoto vom 2019-01-17 23-06-11](https://user-images.githubusercontent.com/7473428/51351950-8768cc00-1aac-11e9-97ba-f64958ffd040.png)

e.g. in client view, it could be used to visualize all order dates. in some industries its from importance to see order behaviour.

**Comment by pedrobaeza** [comment]
This is a kind of heatmap. Are you going to implement it?

**Comment by agent-z28** [comment]
Maybe yes, if nobody did it already. My first attempt was to bring the idea in:)

**Comment by pedrobaeza** [comment]
Let's see if somebody has made something...

**Comment by hbrunn** [comment]
gather the data in some model, override the matrix widget to show blocks instead of inputs, should be quite straight forward

**Comment by pedrobaeza** [comment]
Well, the design with that will be very ugly, but it can be a rudimentary solution for someone in a hurry

**Comment by hbrunn** [comment]
it takes only some css to make this beautiful in my opinion

**Comment by agent-z28** [comment]
Nice Idea!

**Comment by nikul-serpentcs** [comment]
Good Idea! :bulb:

**Comment by tarteo** [comment]
Very cool. Maybe this will help: https://github.com/bachvtuan/Github-Contribution-Graph

Looking forward to try it out.

**Comment by agent-z28** [comment]
JS Base : https://cal-heatmap.com/
We Sponsored IT PROJECTS LLC to realize a first Version.
It looks as they did a pretty Good job
Pull Request is almost ready.
Now we need to get it oca compliant

**Comment by agent-z28** [comment]
This is the repository https://github.com/it-projects-llc/addons-dev/pull/642

**Comment by pedrobaeza** [comment]
Are they going to do the pull request here?

**Comment by agent-z28** [comment]
Thats the idea, i come back later with an answer. But at the end we will have a pull request here.

**Comment by pedrobaeza** [comment]
Great

**Comment by GabbasovDinar** [comment]
Hello @pedrobaeza @agenterp 

Today I will send the PR with this module, I will be glad to any feedback and suggestions

**Comment by pedrobaeza** [comment]
Great, please include a sample.
