### ISSUE TITLE
web_easy_switch_company: menu items wrapping

### ISSUE THREAD

**Issue by thomaspaulb** [OCA/web#116]
I've noticed an issue that when the "easy switch company" menu item is inserted into the top bar, the other menu items don't "contract" to make space for this new item, and thus the new item wraps to the next line. 

However, on screen resize the "menu_bound" event is executed and the size of the section with normal menu items is recalculated, some items are shifted to the "More" menu, and it all fits again.

I've found a workaround which is to add the following code to instance.web.UserMenu.init in switch_company.js,

```
        $(document).ready(function(ev) {
            openerp.web.bus.trigger('resize');
        });
```

It doesn't seem to be the cleanest solution, but at least it works. Anybody else has noticed the same?

**Comment by legalsylvain** [comment]
Hi, thanks for reporting this bug. Can you indicate the version you use ? 7.0 / 8.0 ?
- i use this module in 7.0, and I don't have any problem, but I'll take a look. 
- I didn't test the  module ported in V8.0.

**Comment by sbidoul** [comment]
Hi, we are using the module on 8.0 and I did not notice anything wrong. Can you post a small screenshot or video illustrating the issue?

**Comment by pedrobaeza** [comment]
Hi, I confirm that this happens sometimes when you update browser page, switching for example the company, but I don't have an exact trace.

**Comment by antiflu** [comment]
![screenshot from 2015-04-15 17 58 48](https://cloud.githubusercontent.com/assets/1466356/7163255/56a5515e-e399-11e4-8cd3-e92e5a112c67.png)

**Comment by thomaspaulb** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/1466356/7163338/b8f50b7e-e399-11e4-9668-0dc855ef8f23.png)

**Comment by legalsylvain** [comment]
@antiflu : Could you realize a PR with your fix ?

**Comment by thomaspaulb** [comment]
It feels like an ugly workaround but at least it works for my client. In my experience this only occurs in 8.0, in Chrome, and only when there are a lot of menu items obviously. Also, the problem disappears when you somehow resize the screen (eg by opening the Javascript console or moving the window). That's also the nature of this workaround it triggers a resize event after things are rendered

**Comment by pedrobaeza** [comment]
Was this fixed in OCA?

**Comment by pedrobaeza** [comment]
No news, so I close.
