### ISSUE TITLE
[12.0] web_widget_x2many_2d_matrix total cell not calculated

### ISSUE THREAD

**Issue by tarteo** [OCA/web#1160]
The total cell of the widget (web_widget_x2many_2d_matrix) doesn't work. It's displayed but not calculated.

From web_widget_x2many_2d_matrix_example:
![image](https://user-images.githubusercontent.com/10028499/51398601-4c19dc00-1b44-11e9-8ad7-6d4dfe046c22.png)

From hr_timesheet_sheet:
![image](https://user-images.githubusercontent.com/10028499/51398932-03aeee00-1b45-11e9-8d5c-99bd9fb07835.png)

**Comment by alexey-pelykh** [comment]
Addressed in #1174

**Comment by simahawk** [comment]
#1174 merged
