### ISSUE TITLE
[11.0] web_responsive

### ISSUE THREAD

**Issue by etobella** [OCA/web#1163]
When a user writes and search, the user can see all options, it does not matter if he can read them or not:

https://github.com/OCA/web/blob/11.0/web_responsive/static/src/js/web_responsive.js#L324

On 12.0 is fixed, as it has been fixed.

**Comment by pedrobaeza** [comment]
@Yajo wasn't this already fixed?

**Comment by etobella** [comment]
I tested on runbot, version 11.0. 
I Accessed with demo and wrote Users, I was able to see the Users Menu.

**Comment by yajo** [comment]
This is a core problem, to be fixed in https://github.com/odoo/odoo/pull/30401.
