### ISSUE TITLE
[12.0] web_responsive in Appstore?

### ISSUE THREAD

**Issue by mgielissen** [OCA/web#1168]
I have my backend theme ready (depends on web_responsive) for 12.0. Can web_responsive be published in the Odoo Appstore?

**Comment by tarteo** [comment]
The PR is already merged but it probably takes some time to update in the app store. It can probably be updated manually, but I don't know how / don't have access to it.

**Comment by pedrobaeza** [comment]
With each version, a manual operation for registering each of the branches has to be done, which is a very tedious work and not easily to automatize. I will try later to find a method.

**Comment by elicoidal** [comment]
and that is one of the reasons why we implemented our own shop :wink: 
https://odoo-community.org/shop?&search=responsive

![image](https://user-images.githubusercontent.com/7600613/52057156-88960080-2564-11e9-9f49-2acd57ec23d0.png)

**Comment by pedrobaeza** [comment]
The module is now on Odoo Apps Store:

https://apps.odoo.com/apps/modules/12.0/web_responsive/

thanks to the initial work from @alexey-pelykh in https://github.com/OCA/maintainer-tools/pull/409 that I'm refining right now.
