### ISSUE TITLE
[10.0][web_x2m_options] Limit in Search More

### ISSUE THREAD

**Issue by rousseldenis** [OCA/web#1175]
The problem with https://github.com/OCA/web/commit/ea3f9a39def94850bcc613e98642f4bec50be7f4 and https://github.com/OCA/web/commit/5573c9b73ef6f5dfc2d997b115eaeb1eeb6424a9 is that if there is a 'search_default_' in field context, it does not apply on search popup display.

Indeed, if there is more than 160 results in the data returned by the first search() (with maybe a domain), some ids could be excluded. So, in the tree view popup, you see a default filter, but maybe no records.

Is that clear ?

As there is the pager on that tree view, we could reasonably restore the 'false' limit value.

@hbrunn @chienandalu @Yajo @yvaucher @lmignon

**Comment by rousseldenis** [comment]
I confirm that a search_read() is called from js to server at every pagination.

**Comment by lmignon** [comment]
IMO. If there is a pager, we must restore the 'false' limit value.
