### ISSUE TITLE
[12.0] web_responsive: Improvement - Make chatter top bar sticky

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/web#1177]
I think that to make this sticky can be a good idea, but only when chatter is on right side, and including the attachment widget:

![seleccion_006](https://user-images.githubusercontent.com/7165771/52294732-5593a880-297a-11e9-944d-c75e2a58193e.png)

@Tecnativa

**Comment by pedrobaeza** [comment]
What do you think, @Tardo @Yajo ?

**Comment by yajo** [comment]
I like it.

**Comment by Tardo** [comment]
Looks good! i like it too

**Comment by pedrobaeza** [comment]
Then which volunteer to do it? :angel:

**Comment by Tardo** [comment]
If @Yajo doesn't mind, I can try.

**Comment by yajo** [comment]
Yes, I don't mind at all. Thanks! :wink:
