### ISSUE TITLE
[10.0] web_widget_text_markdown: Cannot be used

### ISSUE THREAD

**Issue by Tardo** [OCA/web#1184]
If you have installed "web_widget_text_markdown" any text field will be rendered as markdown in list view (included tree view). In some forms with lists it broke the view.
![screenshot_20190209-021246_1920x1080](https://user-images.githubusercontent.com/731270/52514263-6cebc380-2c10-11e9-9449-3d2c49676b5d.png)

**Comment by pedrobaeza** [comment]
@njeudy can you please check?
