### ISSUE TITLE
[web_timeline-question] special color if date_start < today

### ISSUE THREAD

**Issue by cvinh** [OCA/web#1188]
@tarteo we would like to have a special color if date_start < today..., would you give advice on how to do it ?
We tried a lot of syntaxes but nothing worked
`#2ecb71:date_start &lt; context_today().strftime('%Y-%m-%d')
#2ecb71:date_start &lt; datetime.today().strftime('%Y-%m-%d')
...etc
`
Thanks in advance

**Comment by tarteo** [comment]
The expressions are validated client side. 
So for example strftime and other python will not work. The syntax for the expression is not flexible only this will work `{field} {opt} {value}` e.g. state == 'done'.

The easiest thing to do is to make a computed boolean field with the logic in it and for the colors expression do something like `#FF0000: red_bool == true; #00FF00: green_bool == true;`. Or you could make a better syntax for attribute color :smile:
