### ISSUE TITLE
[12.0] web_responsive: Shrinking window with sided chat hides some buttons

### ISSUE THREAD

**Issue by yajo** [OCA/web#1189]
Just see those buttons at the right, for followers, attachments and notifications:

![peek 14-02-2019 08-34](https://user-images.githubusercontent.com/973709/52773696-796a8480-3033-11e9-9a07-57854ad0b0e9.gif)

I should fix this, but in case someone wants to volunteer, this one should be easy.

**Comment by gaikaz** [comment]
https://github.com/Tardo/web/commit/ac656d7499207a76db33f10bbe486ace91b12f91 fixed the sheet going under the sideded chatter, but chatter toolbars items getting misplaced (the described issue) problem is still there. Should this be re-opened as a new issue?

**Comment by yajo** [comment]
The fix is in a009528. If you see further problems please publish a new issue. Thanks!

**Comment by gaikaz** [comment]
Sorry to bother, but I double checked now on the runbot (and locally). The exact problem is still there.
Fresh screenshot from runbot:
![3367603-12-0-501adc runbot3 odoo-community org_web_debug=1](https://user-images.githubusercontent.com/17097810/57128357-d1e03100-6d9b-11e9-961b-2c819f5e24c9.png)

As this is not a different problem, I think it's best discussed here. If not, I can publish a new issue and could even try to fix it myself. Already have been fiddling with CSS here and might have a solution.

**Comment by yajo** [comment]
OK, yes it seems the same. Then may you open the PR?

**Comment by gaikaz** [comment]
This can probably be closed now as it's fixed by #1305

**Comment by pedrobaeza** [comment]
Yes, thanks for the reminder.
