### ISSUE TITLE
[web_responsive] Having trouble with Menu images

### ISSUE THREAD

**Issue by taOsemc** [OCA/web#1190]
Odoo version: V12 CE

Hi, 

First, it's a fantastic module, thank you!

I'm having a trouble with the images in main menu:

![2019-02-14 10 22 33](https://user-images.githubusercontent.com/32459602/52776834-c0ac4180-3042-11e9-91ca-50854b291931.png)

![2019-02-14 10 32 06](https://user-images.githubusercontent.com/32459602/52777347-da9a5400-3043-11e9-9237-d5c78c084e82.png)

**Comment by pedrobaeza** [comment]
Your deployment should be somehow broken, but has nothing to do with the module itself (which you don't say which is by the way, although deduced by context that is `web_responsive`). Follow standard guides for deploying Odoo and you won't have problems.

**Comment by taOsemc** [comment]
Well, thank you for your answer. I will try to investigate. Howvever, all other modules are working fine. That's weird.
