### ISSUE TITLE
Get the html components and convert them to string into the field.

### ISSUE THREAD

**Issue by Dhrupesh** [OCA/web#1191]
Hello,

How can i define component and convert into string ?

Can you please give example ?

Thanks,

**Comment by tarteo** [comment]
Which module and version?

**Comment by Dhrupesh** [comment]
web_widget_bokeh_chart

**Comment by tarteo** [comment]
@Dhrupesh and version?

**Comment by yajo** [comment]
html_text

**Comment by Dhrupesh** [comment]
I got solution, Thanks a lot for you support.

**Comment by GERINNOV** [comment]
can you help me with method components came from?
