### ISSUE TITLE
[web_edit_user_filter] : Conditions with Operator OR 

### ISSUE THREAD

**Issue by Boudmir-Ibrahim** [OCA/web#1201]
### Impacted versions:
 V12
### Steps to reproduce:
1-Go to a list view. In my example, Sales's.
2- Add search filter and _add it as Favorite filter_. It must contain a Union of conditions. For example :  
Currency is set **OR** customer is set
3- Open the 'Favorites' menu;
4- Click on the pencil icon to start editing the filter.
5- Click on the condition that contains the Union of two conditions. 
6- Click on Customer is set For example. 

### Current behavior:
The condition :  Currency is set **OR** customer is set is completely removed. Not only  Customer is set that you have chosen to not be considered.

### Expected behavior:
AFAIK, After clicking on _Customer is set_, he other condition _Currency is set_ must remain as the menu shows both conditions separetely and the user chooses the one to remove. 

###Video:
https://drive.google.com/file/d/1QiEDRDZEEKeFSDobdiimIig5IKKRbhPv/view

**Comment by tarteo** [comment]
Thanks, I'll look into it.
