### ISSUE TITLE
[web_edit_user_filter] : Cannot read property 'filterId' of undefined

### ISSUE THREAD

**Issue by Boudmir-Ibrahim** [OCA/web#1202]
### Impacted versions:
V12

### Steps to reproduce:
1-Go to a list view. In my example, Sales's.
2- Add search filter and _add it as Favorite filter_.
3- Open the 'Favorites' menu;
4- Click on the pencil icon to start editing the filter.

### Current behavior:
Returns Error : **Cannot read property 'filterId' of undefined**

### Expected behavior:
a Facet is displayed. On click, a menu is shown that will allow the user to remove values from the facet.

### Video:
https://drive.google.com/file/d/1Q5jabT5wv0CPOMUUm0mu3h1OhBHcM9nL/view

**Comment by tarteo** [comment]
Thanks, I'll look into it.
