### ISSUE TITLE
[12.0] Project timeline

### ISSUE THREAD

**Issue by fietiger** [OCA/web#1212]
A:If there are so many Projects or tasks ,no scroll bar on right side.
steps to repeat:
1.Install Project and Project timeline;
2.Create a Project named Project_1;
3.Create 16 Tasks named Task_1~16,or more Tasks;assign start time and end time for each task;
4.View time line of all tasks, you will see no scroll bar on right side.

B:After uninstall Project timeline ,App Project reports " No default view of type 'timeline' could be found !",and crashed.
steps to repeat:
1.Install Project and Project timeline;
2.Uninstall Project timeline;
3.Try Click Project button from home page you will see a warn dialog,and fail open project page.
 

can not upload picture.Sorry for that.
@tarteo 
@Nikul-Chaudhary

**Comment by tarteo** [comment]
You can drag click anywhere to 'scroll'.
I tested locally and uninstalling the module project_timeline indeed generates problems:

The action is not reverted when uninstalled:
```

     <record id="project.action_view_task" model="ir.actions.act_window">
        <field name="view_mode">kanban,tree,form,calendar,timeline,pivot,graph</field>
    </record>

    <record id="project.act_project_project_2_project_task_all" model="ir.actions.act_window">
        <field name="view_mode">kanban,tree,form,calendar,timeline,pivot,graph</field>
    </record>
```

**Comment by pedrobaeza** [comment]
A uninstall_hook may be needed.

**Comment by fietiger** [comment]
>         <field name="view_mode">kanban,tree,form,calendar,timeline,pivot,graph</field>

So there will no scroll bar any more?

If there only few tasks,time line bars start from bottom,all large area on the top left blank.What should I do to get time line bars start from the top?
Sorry for no picture again.

**Comment by pedrobaeza** [comment]
@fietiger please stop reporting different things in the same issue. Put new issues for new topics.

**Comment by pedrobaeza** [comment]
And with meaningful subjects
