### ISSUE TITLE
To install a module, click search more, and do not see a check box

### ISSUE THREAD

**Issue by hermitguo** [OCA/web#1215]
module: web_widget_many2many_tags_multi_selection
version: 12.0

**Steps to reproduce**
- ...
To install a module, 

**Current behavior**
click search more, and do not see a check box

**Expected behavior**
purchase,sales

**Comment by tarteo** [comment]
I tested it on runbot this is not the case it's probably another module that's causing this problem

![image](https://user-images.githubusercontent.com/10028499/54264879-62587d00-4574-11e9-9bfd-afffaf4e3650.png)
