### ISSUE TITLE
[12.0] web_responsive Look and feel enhancements

### ISSUE THREAD

**Issue by jusle** [OCA/web#1221]
- When clicking empty area in the apps view, user is forwarded back to previous view.
- When opening an app in the apps view, the previous view is shown for the time the selected app is loaded.
- When creating a note in activies on mobile device, the calendar is shown outside of the screen.

**Comment by pedrobaeza** [comment]
This is not something about `web_responsive`, but the web client behavior, and they are debatable. Any way, you should do them on Odoo itself.
