### ISSUE TITLE
[12.0] Notification not displayed in Web Notify

### ISSUE THREAD

**Issue by Gokulakannanaj** [OCA/web#1227]
Hi,

I'm trying to use web_notify module. It installed without any error. But when i click Test info notification or Test warning notification, Notification not displayed. In runbot also notification not displayed.

For reference please check below link,

http://3418854-12-0-7be7fd.runbot1.odoo-community.org/web?debug=1#id=6&action=68&model=res.users&view_type=form&menu_id=4

Thanks.

**Comment by pedrobaeza** [comment]
I think in runbot, there are no workers, and thus the longpolling is not working.

**Comment by Gokulakannanaj** [comment]
@pedrobaeza  thanks for your instant response. But in runbot calendar reminder displyed.

**Comment by pedrobaeza** [comment]
OK, then it should be other thing. @lmignon can you help?

**Comment by pedrobaeza** [comment]
@Gokulakannanaj one thing: are you sending the message to other user or to yourself?

**Comment by Gokulakannanaj** [comment]
@pedrobaeza  thanks, Myself only.

**Comment by pedrobaeza** [comment]
Then that can be the problem: I think you should send the message to other person.

**Comment by Gokulakannanaj** [comment]
Ok. I'll try.

**Comment by Gokulakannanaj** [comment]
Hi @pedrobaeza  I tried. For other persons too, no response.

**Comment by pedrobaeza** [comment]
OK, let's see if other gives us a clue.

**Comment by simmatica** [comment]
in web_client.js replace
  this.call(
        'bus_service', 'on', 'notification',
         this, this.bus_notification);
with
  this.call('bus_service', 'onNotification', this, this.bus_notification);

also it is better if every notify_??? in res_users.py return True otherwise calling xmlrpc API return "cannot marshal None unless allow_none is enabled".

**Comment by Gokulakannanaj** [comment]
Hi, Thanks @simmatica . The code you have entered does not exist in web_client.js File.

**Comment by simmatica** [comment]
Look at web_notify/static/src/js/web_client.js row 34

**Comment by Gokulakannanaj** [comment]
Hi @simahawk  Sorry for a delayed response, That's also not working.

**Comment by andreampiovesana** [comment]
you write in the installation istructions that:
the server must be launched in gevent mode
this need workers>1?

**Comment by Gokulakannanaj** [comment]
@andreampiovesana  workers are 4. That time also not displaying.
Kindly check-in following link
http://3418854-12-0-7be7fd.runbot1.odoo-community.org/web?debug=1#id=6&action=68&model=res.users&view_type=form&menu_id=4

**Comment by KKamaa** [comment]
Hello guys the web_notify is not working as designed sometimes it works and other times it doesn't.
