### ISSUE TITLE
[12.0] web_responsive section change delay

### ISSUE THREAD

**Issue by AdriaGForgeFlow** [OCA/web#1228]
In the web_responsive module once you want to change sections as shown in the gif below, the interface will dismiss the Apps menu and will remain for some time in the previous section while it charges and goes to the next one. 
![GIFrecord_2019-03-27_111936](https://user-images.githubusercontent.com/44768500/55068720-cace5080-5082-11e9-9378-9fc926d28d4d.gif)
This can be a little bit confusing for the user experience when the charging takes more than a few seconds.

I'm working on finding a clean fix to this trying to make the dropdown menu to be dismissed once the new section has been fully charged instead of when the user has clicked the app icon.
Any help is welcomed.

**Comment by pedrobaeza** [comment]
Uhm, not sure this will be easily done... Any way, this depends on where do you click. For most elements, it's barely instant access.

@Yajo any clue?

**Comment by yajo** [comment]
This is async, it happens. If you can capture the promise that resolves when the new UI is loaded, you can put a "loading" message in the mean time.

**Comment by pedrobaeza** [comment]
Is this something like #1240, but for v12?

**Comment by yajo** [comment]
Not, you can see in the bottom-right corner of the gif that the loading panel displays ok.

**Comment by pedrobaeza** [comment]
OK

**Comment by AdriaGForgeFlow** [comment]
Closing, solved here #1305
