### ISSUE TITLE
Standardize web_m2x_options boolean parameters

### ISSUE THREAD

**Issue by ecino** [OCA/web#123]
Boolean parameters in module web_m2x_options are declared with lowercase characters in views (true/false) and in capital letters in the system parameters (True/False).

One way should be chosen and used everywhere, or they should be automatically put to lowercase so that the user can use both ways.

**Comment by pedrobaeza** [comment]
I think we can make it tolerant to upper/lowercase, uniformizing on the comparison to any of them.

**Comment by pedrobaeza** [comment]
This was fixed, so I close.
