### ISSUE TITLE
[12] web_responsive: How to make the view the same as version 11

### ISSUE THREAD

**Issue by dungxboss** [OCA/web#1233]
How to make version 12 look like version 11?
Version 12: ![image](https://user-images.githubusercontent.com/40818338/55271114-50980900-52da-11e9-95ad-106e6ea65bc8.png)
Version 11: 
![image](https://user-images.githubusercontent.com/40818338/55271174-462a3f00-52db-11e9-9813-234d0b4bb9f6.png)

Thanks
@Yajo

**Comment by pedrobaeza** [comment]
The screenshots don't belong to web_responsive module, but other.
