### ISSUE TITLE
Webcam.js Error: No supported webcam interface found.[web_widget_image_webcam]

### ISSUE THREAD

**Issue by jayo2005** [OCA/web#1236]
Using odoo 11 

I get following error when trying to use web_widget_image_webcam.

Webcam.js Error: No supported webcam interface found.[

**Comment by pedrobaeza** [comment]
The error is clear: your browser doesn't recognize your webcam with current JS library, or you have blocked the access to it.

**Comment by jayo2005** [comment]
Issue was flash not installed
