### ISSUE TITLE
[Whishlist] web_tree_image: No way to reduce Image size in tree view

### ISSUE THREAD

**Issue by Swapnesh-SerpentCS** [OCA/web#1238]
Module `web_tree_image` doesn't provide any solution to Render Small sized images from the server, Which cause Unnecessary Loading when there are large Images with more records.

Proposed Solution: (Works well for v9 in Production.)

Add new attribute on the field in XML where widget="image" is applied.
Eg,` image_preview_field="image_small"` (or maybe we can add on `options` too)

On JS function:

```
if (this.image_preview_field) {
    imageArgs.field = this.image_preview_field;
}
```

This is the use case when we want to store all sized Image (Eg, `image`, `image_medium`, `image_small`)

**Comment by Swapnesh-SerpentCS** [comment]
@nikul-serpentcs @pedrobaeza  
May I have your suggestion on this ?

**Comment by legalsylvain** [comment]
Closed as implemented here in V12. feel free to (back)port : https://github.com/OCA/web/pull/2163
