### ISSUE TITLE
web_decimal_numpad_dot not run?

### ISSUE THREAD

**Issue by pepitovadecurt** [OCA/web#1246]
Hello, I have installed the web_decimal_numpad_dot module but it does not seem to work.
For example: in an invoice I write the price 42.23 and when pressing tab it is corrected to 4.223,00
I am using the community 10 version and the module I got it from https://github.com/OCA/web/tree/10.0

**Comment by pedrobaeza** [comment]
You have to use a language with that separator.

**Comment by pepitovadecurt** [comment]
Ah ok, I thought the module was useful to enter the numbers both with comma and with decimal point.
Thanks Pedro.
