### ISSUE TITLE
[12.0] web_responsive: App drawer search menus not working properly from mobile phone. 

### ISSUE THREAD

**Issue by GSLabIt** [OCA/web#1251]
Tested in runbot, after last commits search menu doesn't work with virtual keyboard on mobile. 

Whatever key is pressed, search input loose focus and doesn't show search results.

Have a look at video: 
![20190413114412-4b38295101 gif-2-mp4 com](https://user-images.githubusercontent.com/11652845/56077194-7b558780-5dd9-11e9-89da-9dcc6e293c5e.gif)

Can someone double check and confirm? 

Thx

**Comment by Tardo** [comment]
Tested on runbot and local... all works as expected.
Env. Specs: Firefox 66.0.2 running under LineageOS 15.1 (Android 8.1.0)

**Comment by GSLabIt** [comment]
I tested using Samsung internet browser and Chrome on emui 8 (andori 8.0.1)

@Tardo, any idea why I'm facing the issue?

**Comment by Tardo** [comment]
@GSLabIt confirmed bug with Chrome 73.0.3683.90
🐞🔍 ...

**Comment by GSLabIt** [comment]
@Tardo same version here...

**Comment by Tardo** [comment]
@GSLabIt Does the same thing happen to you outside of runbot? I'm not able to replicate the bug in local env.

**Comment by GSLabIt** [comment]
@Tardo yup, u can test on odoo.gslab.it:8069

**Comment by Tardo** [comment]
@GSLabIt i can't reproduce it out of runbot... :S
**http:// 217 . 182 . 67 . 159 : 12069** (OCB 12.0 with OCA/web repository and only web_responsive installed)

**Comment by GSLabIt** [comment]
can u install more apps and update to last web_responsive version?

thx

**Comment by GSLabIt** [comment]
@Tardo i've create a db from scratch and installed web_responsive and few other apps. You can test at http://test.gslab.it:8069 - demo/demo. 

I'm facing the issue from mobile phone uning both chrome and Samsung Internet Browser.

Could u test? 

Thx

**Comment by yajo** [comment]
Fix in #1252. Thanks for the report!

**Comment by GSLabIt** [comment]
@Yajo @Tardo could you please double check runbot from mobile chrome? I've installed more apps (actually mode than 10 apps) and it seems the issue is back. 😬

**Comment by yajo** [comment]
Open a new issue then. It must be a different problem.
