### ISSUE TITLE
[12.0] web_responsive: Menu issue

### ISSUE THREAD

**Issue by DaimSayed** [OCA/web#1258]
When installed in a fresh database the module gives an error of unmet dependency for web.Menu.
In Odoo the menu click also does not seem to be triggering any action.
![odoo_responsive_isse](https://user-images.githubusercontent.com/49861038/56493066-6bd9eb00-650b-11e9-9125-4f3762cf71f8.png)

**Comment by pedrobaeza** [comment]
Module is incompatible with enterprise interface.
