### ISSUE TITLE
[11.0] web_responsive app drawer search menus not working properly from mobile phone

### ISSUE THREAD

**Issue by rifdy** [OCA/web#1262]
App Drawer Search Menus immediately closed when it's click search logo (in mobile phone)

![fr](https://user-images.githubusercontent.com/38850083/56712751-bfda0f00-6759-11e9-8778-19dbeb684cee.gif)

**Comment by pedrobaeza** [comment]
Are you using latest version?

**Comment by rifdy** [comment]
i'm using branch 11.0. with latest commit

**Comment by GSLabIt** [comment]
possible same problem of https://github.com/OCA/web/issues/1254#issuecomment-484060826?

**Comment by rifdy** [comment]
Looks like same, but this issue in branch 11.0

**Comment by yajo** [comment]
I can reproduce on chrome on Android.

For now, as a workaround, use Firefox or do not use the search feature.
