### ISSUE TITLE
[question][web_widget_x2many_2d_matrix] How show fields not included in matrix (before/after it)?

### ISSUE THREAD

**Issue by GSLabIt** [OCA/web#1264]
Hi all, any hint on how to implement?

Thx

**Comment by pedrobaeza** [comment]
Duplicated of #1084

**Comment by GSLabIt** [comment]
is this duplicated? the #1084 focus on unsaved values, i need to show that values in widget ..

**Comment by pedrobaeza** [comment]
Well, then this module is not for that.

**Comment by GSLabIt** [comment]
Got it, i was asking for hints to implement an extension to allow showing also other fields ..do you have any ideas?

**Comment by pedrobaeza** [comment]
Well, visually the widget will look weird that way IMO, but check the source code and you'll find how this is populated. You have to do the same for several values.

**Comment by GSLabIt** [comment]
Well that's not a look and feel prob. In this case we need to show and populate other values as well, show totals as qty * price .. i'm not sure but looks like the EE grid view would work in that way.

**Comment by pedrobaeza** [comment]
I'm not able to visualize what you want.

**Comment by GSLabIt** [comment]
<img width="1273" alt="Schermata 2019-04-29 alle 11 37 46" src="https://user-images.githubusercontent.com/11652845/56888107-8d8b2300-6a73-11e9-9843-041b56ebee08.png">
does it make sense?

**Comment by pedrobaeza** [comment]
Uhm, not too much with this widget, as it's a mix of one2many tree view widget with 2D matrix widget. You can do it with 2D matrix, but you have to start mostly from scratch, needing to populate the rest of the fields, acting like a tree view, and so on.

I also find this a bit confusing from UI perspective, but that's a personal opinion.

**Comment by GSLabIt** [comment]
@pedrobaeza i do find a bit confusing as well .. but, you know, client want absolutely like this one ..

**Comment by pedrobaeza** [comment]
Well, it requires a deep knowledge of JS for creating and doing parametric that kind of widget. I'm not able to do it with my current skills. And even knowing enough, it will require a good budget for developing. Maybe that discourages your customer, hehe.

**Comment by simahawk** [comment]
I agree w/ Pedrio. Stay away from this solution if you don't want to go through a valley of pain :smile: 
Maybe you have to re-think better on the problem you are trying to solve rather than thinking about a UI that looks nice to the customer :wink:

**Comment by GSLabIt** [comment]
@pedrobaeza @simahawk Let's say client would like to invest 😬  ..do you know anyone who could develop it? thx

**Comment by pedrobaeza** [comment]
I'm afraid not, but you can write to contributors list to see if any contributor wants to do it. Just put as requirement that they contribute the development to OCA :wink:

**Comment by GSLabIt** [comment]
can u share email for contributor list? thx

**Comment by pedrobaeza** [comment]
contributors@odoo-community.org

**Comment by GSLabIt** [comment]
thx, will send an email ..hopefully some will answer 😬
