### ISSUE TITLE
web_widget_timepicker setting date to 0:00 shows current time

### ISSUE THREAD

**Issue by Fdfyheryery** [OCA/web#1267]
While using the 11.0 version of web_widget_timepicker, if I set my value to 0:00 it instantly get set to the current time instead of 0:00.

To replicate: 
- Create a form with the timepicker
- Set minutes to 00
- Set hour to 0
The time shown should be your current time.

The issue seems to be coming from this line in **web_widget_timepicker.js:28**:
`var formatted_value = value ? this._formatClient(value) : null;`

If the hours and minutes are set to 0 value will be exactly 0 and the condition evaluates to false.

**Comment by pedrobaeza** [comment]
Can you propose a fix for this?

**Comment by Fdfyheryery** [comment]
To make it work I've changed the two following lines:

**web_widget_timepicker.js:28**
Old:  `var formatted_value = value ? this._formatClient(value) : null;`
New: `var formatted_value = value != null ? this._formatClient(value) : null;`

**web_widget_timepicker.js:39**
Old:  `return value ? this._formatClient(value) : null;`
New: `return value != null ? this._formatClient(value) : null;`

**Comment by JonathanOsAlc** [comment]
PR: #1274
