### ISSUE TITLE
[11.0] Web Widget Bokeh Chart. Bokeh 1.1.0

### ISSUE THREAD

**Issue by luandv1995** [OCA/web#1268]
Hi ALL,
I am using Web Widget Bokeh Chart (11.0) and Bokeh (0.12.7). I wish everyone to upgrade the bokeh library to 1.1.0.
Thanks All

**Comment by pedrobaeza** [comment]
If you are able to do it, please propose a PR.

**Comment by luandv1995** [comment]
@pedrobaeza 
I see https://github.com/OCA/web/pull/1222. It migrate success. can i take code to using v11?

**Comment by luandv1995** [comment]
Sorry @pedrobaeza,
https://github.com/OCA/web/pull/1224
It used bokeh==1.0.4. I wish it to upgrade v11.

**Comment by pedrobaeza** [comment]
Sorry, but this is a voluntary effort and then you can contribute with the PR, but no possible to be done by other if there's no interest on that.
