### ISSUE TITLE
web_widget_timepicker: not able to pass options="{'timeFormat': 'h:i A'}"

### ISSUE THREAD

**Issue by dek-odoo** [OCA/web#1271]
When we try something like

`<field name="time_from" widget="timepicker" options="{'timeFormat': 'h:i A'}"/>`

We get the following error

![image](https://user-images.githubusercontent.com/10609055/57177829-d54fe700-6e85-11e9-874c-3418ac3d28a7.png)

![image](https://user-images.githubusercontent.com/10609055/57177794-ac2f5680-6e85-11e9-8b99-5b6f26425140.png)

Thank you

**Comment by dek-odoo** [comment]
Here I am trying to have am/pm for selection as we can pass options that [jquery-timepicker](https://github.com//jonthornton//jquery-timepicker#timepicker-plugin-for-jquery) accepts.

**Comment by dek-odoo** [comment]
I fixed it with some workaround to pass value without am/pm in the string and in case of pm we add 12 (both of this applied if there is am/pm in string).

**Comment by dek-odoo** [comment]
@docmfried @smurf-U

**Comment by Tardo** [comment]
@dek-odoo web_widget_timepicker is based on "FloatTime"... It is not intended to reflect the hours of the day, but as a generic time meter.
Possibly you can use a formatted datetime field instead.

Anyway I'm going to do a PR to update the README

**Comment by docmfried** [comment]
@dek-odoo : Did you create a PR for you workaround. What is the actual status?

**Comment by dek-odoo** [comment]
@docmfried I did not make any PR yet.

Not on our priority list currently. Would you like to have it ? if you can fund the efforts, I can have it ready.
