### ISSUE TITLE
Make the widget work directly on one2many fields, without adding a new 'empty' field

### ISSUE THREAD

**Issue by eilst** [OCA/web#1273]
For web widget tale, add this feature: Make the widget work with many2many field. So in the data table, the selected fields related to this many2many field are displayed. But giving the possibility to include in the table fields on the current model different than the many2many field working with the widget.

"Is it possible to make the widget work directly on one2many fields, without adding a new 'empty' field?" https://github.com/OCA/web/pull/1230#discussion_r271268283

**Comment by pedrobaeza** [comment]
As this module is not merge, please comment directly on the PR.
