### ISSUE TITLE
[12.0] web_timeline: item orientation

### ISSUE THREAD

**Issue by PauliusP17** [OCA/web#1278]
I'm using `web_timeline` to for my custom model and I need the items to start from the top rather than the default bottom ([the relevant example](http://visjs.org/examples/timeline/styling/axisOrientation.html)). You set the orientation by providing a string to the orientation parameter [(docs)](http://visjs.org/docs/timeline/#Configuration_Options).

I tried doing this by directly editing web_timeline, but it just does not work for the items. The time axis orientation parameter works, but items always stay at the bottom. 

Has anyone achieved configuring this module so that the items are at the top?

**Comment by pedrobaeza** [comment]
Check how support for other options has been added in the past:

https://github.com/OCA/web/pull/1134

and try to imitate it (preferably with a PR here).

**Comment by PauliusP17** [comment]
I actually think that the parameter works, but the first item is always a dash characater `-` which seems to be taking up all the space. Maybe I should open a different Issue regarding that.

**Comment by pedrobaeza** [comment]
or rename this one and add enough relevant details.
