### ISSUE TITLE
[12.0] web_advanced_search contains returns False

### ISSUE THREAD

**Issue by CasVissers-360ERP** [OCA/web#1284]
See video here;
https://drive.google.com/file/d/17nIxtRDpG_XZm8ydpZ8TeW6pCRiqFekZ/view
While using the constains option the search value is replaced by False.

**Comment by pedrobaeza** [comment]
@Yajo I remember this already happened

**Comment by CasVissers-360ERP** [comment]
@Yajo 
Is there anything I can do to help here? My JS knowledge is minimal, but the customers using the module keep spamming me :)

**Comment by CasVissers-360ERP** [comment]
Another issue in the module:
https://drive.google.com/file/d/1owTaxeu5pjdEHliFq0CC0D-Op07Qe9ZJ/view

When using contains for example when searching accounts which have a number in it the name it actually searches for ID. This is really confusing for end-users.

**Comment by CasVissers-360ERP** [comment]
Bump..

**Comment by pedrobaeza** [comment]
@CasVissers sorry, but this is not impacting us right now and we don't have time for checking it nor fixing it.
