### ISSUE TITLE
[12.0] web_responsive: The icons on the dashboard are displayed disproportionately (In Google Chrome only)

### ISSUE THREAD

**Issue by dntq83** [OCA/web#1309]
The icons on the dashboard are displayed disproportionately (In Google Chrome only)
![IconDasboard](https://user-images.githubusercontent.com/5275039/59731892-2703d380-9272-11e9-9324-1aa481756d70.jpg)

**Comment by Tardo** [comment]
Thanks @dntq83, this issue should be fixed on this WIP PR: https://github.com/OCA/web/pull/1305/
Concretely here: https://github.com/OCA/web/pull/1305/commits/f5a421f223660576f1bdf4dd7f8dcc8a4b790391#diff-7fb4a82b29100601ff8d920b1a553684L221
