### ISSUE TITLE
[web_responsive] Odoo 12 app drawer bug

### ISSUE THREAD

**Issue by aleexnl** [OCA/web#1316]
In a 1920x1080p monitor (google chrome, windows 01)the app drawer isn't showing correctly; the app icons expand so much. Any idea why this happens?
![image](https://user-images.githubusercontent.com/50357555/60494589-6210f880-9caf-11e9-8f10-7194edb146ae.png)

**Comment by pedrobaeza** [comment]
This was fixed some weeks ago. Please update to latest code.
