### ISSUE TITLE
[Question] - Add new operators to the standard advanced search

### ISSUE THREAD

**Issue by sbejaoui** [OCA/web#1319]
Hi,
I wondering if there is an oca module module or some how to add new options to the standard advanced search.
I am looking for this operators to be available to any user:
- start with
- don't start with
- end with
- don't end with

![Capture d’écran de 2019-07-03 16-00-51](https://user-images.githubusercontent.com/12665409/60598078-5f47fd80-9dac-11e9-8301-44c3bdcac4e1.jpg)

cc/ @gva-acsone, @sbidoul

**Comment by pedrobaeza** [comment]
Not exactly the same, but similar, is:

https://github.com/OCA/web/tree/10.0/web_advanced_search_wildcard

Another interesting related modules:

* https://github.com/OCA/web/tree/12.0/web_advanced_search for using domain widget for performing an advanced search in more visual mode (and this one complementing it: https://github.com/OCA/web/tree/12.0/web_widget_domain_editor_dialog).
* https://github.com/OCA/web/tree/11.0/web_search_with_and for allowing in the search bar to add the same condition several times with AND instead than OR.

**Comment by sbejaoui** [comment]
Thank you @pedrobaeza ,
`web_advanced_search_wildcard`  it's what I am looking for. I think we may soon start its migration to 12.0 and we will decide how to implement the don't start/end with.

**Comment by sbejaoui** [comment]
The #1328 migrate the `web_advanced_search_wildcard` and add the two new options.
