### ISSUE TITLE
[12] After install web modules error on all options

### ISSUE THREAD

**Issue by josepmy** [OCA/web#1323]
Hi,

After install the web modules nothing work and each time I get this error.

Error: QWeb2: Template 'SearchView.addtodashboard' not found

http://88.99.170.219:8069/web/static/lib/qweb/qweb2.js:48
Rastreo de error:
exception@http://88.99.170.219:8069/web/static/lib/qweb/qweb2.js:48:19
_render@http://88.99.170.219:8069/web/static/lib/qweb/qweb2.js:482:35
render@http://88.99.170.219:8069/web/static/lib/qweb/qweb2.js:450:26
start@http://88.99.170.219:8069/board/static/src/js/favorite_menu.js:27:53
OdooClass.extend/Class.include/</prototype[name]</<@http://88.99.170.219:8069/web/static/src/js/core/class.js:123:38
_widgetRenderAndInsert/<@http://88.99.170.219:8069/web/static/src/js/core/widget.js:399:25
then/</</<@http://88.99.170.219:8069/web/static/lib/jquery/jquery.js:3276:89
fire@http://88.99.170.219:8069/web/static/lib/jquery/jquery.js:3119:58
add@http://88.99.170.219:8069/web/static/lib/jquery/jquery.js:3165:49
then/</<@http://88.99.170.219:8069/web/static/lib/jquery/jquery.js:3275:77
each@http://88.99.170.219:8069/web/static/lib/jquery/jquery.js:383:58
then/<@http://88.99.170.219:8069/web/static/lib/jquery/jquery.js:3272:56
Deferred@http://88.99.170.219:8069/web/static/lib/jquery/jquery.js:3332:30
then@http://88.99.170.219:8069/web/static/lib/jquery/jquery.js:3271:55
_widgetRenderAndInsert@http://88.99.170.219:8069/web/static/src/js/core/widget.js:393:33
appendTo@http://88.99.170.219:8069/web/static/src/js/core/widget.js:164:21
start@http://88.99.170.219:8069/web/static/src/js/views/search/search_view.js:438:42
start@http://88.99.170.219:8069/web_edit_user_filter/static/src/js/backend.js:240:35
OdooClass.extend/Class.include/</prototype[name]</<@http://88.99.170.219:8069/web/static/src/js/core/class.js:123:38
_widgetRenderAndInsert/<@http://88.99.170.219:8069/web/static/src/js/core/widget.js:399:25
then/</</<@http://88.99.170.219:8069/web/static/lib/jquery/jquery.js:3276:89
fire@http://88.99.170.219:8069/web/static/lib/jquery/jquery.js:3119:58
add@http://88.99.170.219:8069/web/static/lib/jquery/jquery.js:3165:49
then/</<@http://88.99.170.219:8069/web/static/lib/jquery/jquery.js:3275:77
each@http://88.99.170.219:8069/web/static/lib/jquery/jquery.js:383:58
then/<@http://88.99.170.219:8069/web/static/lib/jquery/jquery.js:3272:56
Deferred@http://88.99.170.219:8069/web/static/lib/jquery/jquery.js:3332:30
then@http://88.99.170.219:8069/web/static/lib/jquery/jquery.js:3271:55
_widgetRenderAndInsert@http://88.99.170.219:8069/web/static/src/js/core/widget.js:393:33
appendTo@http://88.99.170.219:8069/web/static/src/js/core/widget.js:164:21
_createSearchView@http://88.99.170.219:8069/web/static/src/js/chrome/action_manager_act_window.js:176:27
_executeWindowAction/<@http://88.99.170.219:8069/web/static/src/js/chrome/action_manager_act_window.js:338:28
then/</</<@http://88.99.170.219:8069/web/static/lib/jquery/jquery.js:3276:89
fire@http://88.99.170.219:8069/web/static/lib/jquery/jquery.js:3119:58
fireWith@http://88.99.170.219:8069/web/static/lib/jquery/jquery.js:3231:49
Deferred/</deferred[tuple[0]]@http://88.99.170.219:8069/web/static/lib/jquery/jquery.js:3321:62
then/</</<@http://88.99.170.219:8069/web/static/lib/jquery/jquery.js:3276:89
fire@http://88.99.170.219:8069/web/static/lib/jquery/jquery.js:3119:58
fireWith@http://88.99.170.219:8069/web/static/lib/jquery/jquery.js:3231:49
Deferred/</deferred[tuple[0]]@http://88.99.170.219:8069/web/static/lib/jquery/jquery.js:3321:62
then/</</<@http://88.99.170.219:8069/web/static/lib/jquery/jquery.js:3276:89
fire@http://88.99.170.219:8069/web/static/lib/jquery/jquery.js:3119:58
fireWith@http://88.99.170.219:8069/web/static/lib/jquery/jquery.js:3231:49
then/</</<@http://88.99.170.219:8069/web/static/lib/jquery/jquery.js:3283:104
fire@http://88.99.170.219:8069/web/static/lib/jquery/jquery.js:3119:58
fireWith@http://88.99.170.219:8069/web/static/lib/jquery/jquery.js:3231:49
Deferred/</deferred[tuple[0]]@http://88.99.170.219:8069/web/static/lib/jquery/jquery.js:3321:62
genericJsonRpc/<@http://88.99.170.219:8069/web/static/src/js/core/ajax.js:65:18
then/</</<@http://88.99.170.219:8069/web/static/lib/jquery/jquery.js:3276:89
fire@http://88.99.170.219:8069/web/static/lib/jquery/jquery.js:3119:58
fireWith@http://88.99.170.219:8069/web/static/lib/jquery/jquery.js:3231:49
then/</</<@http://88.99.170.219:8069/web/static/lib/jquery/jquery.js:3283:104
fire@http://88.99.170.219:8069/web/static/lib/jquery/jquery.js:3119:58
fireWith@http://88.99.170.219:8069/web/static/lib/jquery/jquery.js:3231:49
done@http://88.99.170.219:8069/web/static/lib/jquery/jquery.js:9275:42
callback@http://88.99.170.219:8069/web/static/lib/jquery/jquery.js:9685:57

**Comment by simahawk** [comment]
which modules? have you refreshed your cache?

**Comment by josepmy** [comment]
Cache from Browser? Yes

**Comment by pedrobaeza** [comment]
Sorry, but you have screwed up your installation because of the deployment method, and this is not the place for teaching you how to do it. You can check that the module is working in our OCA runbot.

**Comment by josepmy** [comment]
Yes. Excuse. Where can I found docs about deploy OCA modules?

**Comment by pedrobaeza** [comment]
OCA modules are Odoo modules. They are deployed the same as the rest.
