### ISSUE TITLE
[Question] [web_widget_x2many_2d_matrix] how to implement on 2 step wizard

### ISSUE THREAD

**Issue by bunhin** [OCA/web#1329]
Hi,
I want to implement this web_widget_x2many_2d_matrix on 2 steps wizard for advanced stock transfer multi warehouse. The purpose is to create stock transfer from a warehouse to many other warehouses for some selected (filtered) products where the transfer quantity to each destination warehouse will be filled using [web_widget_x2many_2d_matrix]  

On step 1, wizard  will  get input from user to select source warehouse, and filter products based on minimum on hand qty at the source warehouse, product category and which sold qty less from input value,  and get input value to filter destination warehouses which have on-hand-qty of previous selected product equal to zero or less than user input value

Base on step 2, the  web_widget_x2many_2d_matrix shall be populated with  column = destination warehouses while  products as rows, and cell value is the qty to be transferred

On clicked create button, the wizard will generate stock transfer from source warehouse to each destination warehouse and of each cell quantity of the products

Other option to is  to put source and destination warehouse together in the column of [web_widget_x2many_2d_matrix],  the  cell value positif (>0) to be source warehouse and if cell has negatif input value (<0) to be picked as destination warehouse, the absolute value is the transfer qty from or to the warehouse of each products.

please inform whether it can be done with the wizard? and some brief clues will be very helpful to me 

Thank you

**Comment by pedrobaeza** [comment]
Sorry, but these are generic questions about development, and you should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here, as this is an issue tracker.

Closing this by the reason above.

**Comment by bunhin** [comment]
i see, thank you
