### ISSUE TITLE
Any ways to open act window in popup with readonly form view?

### ISSUE THREAD

**Issue by rameshwordhakal** [OCA/web#1331]
Reference Issue :  #314 

My issue to similar to this. This issue is closed but, I can't get right answer for this question.

I am using Odoo 12.
I would love some suggestions and tricky ideas to solve this problem.

**Comment by pedrobaeza** [comment]
Sorry, but this is an issue tracker, not a question solver. The issue you are referencing was a discussion for implementing it.
