### ISSUE TITLE
[12.0] [Question] [web_responsive] Redircet to app dashboard instead of index box?

### ISSUE THREAD

**Issue by siyuancn** [OCA/web#1332]
I installed the web_responsive for the version 12.0.

it will redirect to the index box after login.

I want to know how can set the homepage to the app dashboard instead of the index box ?

**Comment by pedrobaeza** [comment]
I don't get what "index box" means for you, but you can check in runbot (https://runbot.odoo-community.org/runbot/162/12.0), that it's redirected to homepage just the same as regular Odoo.
