### ISSUE TITLE
web_tree_dynamic_colored_field: override field

### ISSUE THREAD

**Issue by bealdav** [OCA/web#1333]
Simple question:
Is it possible to use a similar override ? It seems no ! ?
```xml
<xpath expr="//field[@name='o2m_fields_ids']/tree/field[@name='myfield']" position="attributes">
  <attribute name="options">{"bg_color": "orange: missing_qty &gt; 0"}</attribute>
</xpath>
```

ping @hbrunn @guewen 
Thanks

**Comment by pedrobaeza** [comment]
Issue tracker shouldn't be used for this kind of questions IMO

**Comment by bealdav** [comment]
How to join people, then ?

**Comment by pedrobaeza** [comment]
For me contributors list is the medium for these things.

**Comment by DudhatShivam** [comment]
Hello,
I try to give 2 conditions but not working perfectly
how can I solve this things

![Inventory Report - Odoo (4)](https://user-images.githubusercontent.com/10597339/70933531-29e55280-2062-11ea-9062-f7010ee21d06.png)
