### ISSUE TITLE
[web_widget_color_tree_field] Field bg color based on var value

### ISSUE THREAD

**Issue by viandanteoscuro** [OCA/web#1335]
module: web_widget_color_tree_field
version: 8.0

How i can specify multiple bg_color based on specific field value?

I have a fiend "spedizione" that cas assume values like 1,2,3

So... for 1 i want ti display red bg color, for 2 orange and so on...

```xml
<field name="ritardo" string="Ritardo" bg_color="red:spedizione=='1'"/>
<field name="ritardo" string="Ritardo" bg_color="green:spedizione=='2"/>
<field name="ritardo" string="Ritardo" bg_color="orange:spedizione=='3'"/>
```

I want achieve this but in only one field column... to avoid column duplication.

Can i achieve this?

**Comment by pedrobaeza** [comment]
I suppose that you have to put one field with all the values split by `;`, but these kind of questions must be done on forum or mailing lists, not here in the issue tracker that is for bugs or debating RFCs.
