### ISSUE TITLE
web_export_view "Export current view" exports with image filed.

### ISSUE THREAD

**Issue by iceship** [OCA/web#136]
I'm using the 'web_tree_image' module.

But I couldn't export image field.

Is there any way that export to excel with image?

Thank you

**Comment by pedrobaeza** [comment]
Not for now. If you want to develop it...

**Comment by lukebranch** [comment]
@iceship ,

Do you need an image thumbnail in the excel spreadsheet, or just base64?

If you're just looking for a method to add an image to an excel spreadsheet I suggest using Aeroo reports.

You'll need to create a custom report template to place the image on the spreadsheet, however I use this quite often for invoices, product catalogs and other reports.

I'll post a few templates as examples on this forum post soon:

https://www.odoo.com/forum/help-1/question/8-0-how-can-i-install-the-official-aeroo-reports-alistek-for-odoo-version-8-solved-76044

**Comment by iceship** [comment]
Thanks a lot!
 I'll try to use Aeroo reports.

**Comment by lukebranch** [comment]
@iceship ,

no problem. i'd recommend subscribing to that forum post I mentioned above. I'll post some updates and a link to another forum post with some basics on getting started with building Aeroo reports templates in the next few days when I can find an hour or two to spare.

In the meantime i'd recommend hitting the help.odoo.com forum and the forum on alistek.com, and this tutorial:

http://www.alistek.com/wiki/index.php/Main_Page

it's best if you have a basic understanding of python if and foreach loops, as well a the structure of the model you're pulling data from (just switch on developer mode in Odoo so you can investigate) for building invoices, catalogs, and the like, and if you want to add an image, you'll need a placeholder image to which you'll need to add some basic python code to.

If you run into any issues feel free to post back on the forum post I mentioned above and i'd be glad to help out with whatever I can.
