### ISSUE TITLE
I can't pick color 

### ISSUE THREAD

**Issue by enzymz** [OCA/web#1360]
module: web_timeline
version: 12.0

**Steps to reproduce**
- ...

**Current behavior**

**Expected behavior**

**Comment by pedrobaeza** [comment]
Steps to reproduce the problem?

**Comment by mastrobirraio** [comment]
I have the same problem.
I've downloaded the widget directory inside my extra-addons directory, I've followed the procedure of README, but when I open the form to create a model I don't see the picker. Where I've wrong?

**Comment by pedrobaeza** [comment]
Which picker? There's no color picker in web_timeline. Closing as not enough information.
