### ISSUE TITLE
[12.0] web_responsive: not able to see long char fields

### ISSUE THREAD

**Issue by LoisRForgeFlow** [OCA/web#1363]
For example if you have a very long name in a product, with web_responsive you see a first line and a ellipsis (meaning that part of the text is hidden), when you click on it to be able to read the whole text it is impossible because it immediately gets hidden again.

![web_responsive_long_name](https://user-images.githubusercontent.com/23449160/64333803-a97d7300-cfd7-11e9-8ced-0dc21de1062f.gif)

Note that in the gif I click just once each time the text is expanded and collapsed just few tenths of a second after.

**Comment by Tardo** [comment]
This is done in CSS and shows all the content while you keep the click. This is good because doesn't need javascript, but maybe it's a bit confusing...

https://github.com/OCA/web/blob/12.0/web_responsive/static/src/css/web_responsive.scss#L353

**Comment by pedrobaeza** [comment]
Maybe an explanation in the README?

**Comment by LoisRForgeFlow** [comment]
I see, that was not intuitive for me, sorry, it is actually not that bad as you can even copy the full name without any problem if you click the beginning and drag until the end. However, let me ask: do you think this is better than showing everything in several lines (default Odoo without web_responsive)?

**Comment by LoisRForgeFlow** [comment]
Another idea, can't you add to that css for oe_title a wider width by default?, because since the form view is expanded it is very common that you waste a lot of space to the right of the name. Maybe not the most efficient, but to give you an idea, for me "width: 70%;" at oe_title works really good.

**Comment by pedrobaeza** [comment]
Don't forget that this is for having a mobile proper responsive view, so -1 for increasing unconditionally the width, but if possible depending on the screen width, then ok

**Comment by Tardo** [comment]
This is the default behavior (without web_responsive):
-- Product Form:
![2019-09-06-162258_1920x1080_scrot](https://user-images.githubusercontent.com/731270/64435631-1f123d80-d0c3-11e9-8cc7-7fd739d2ac75.png)

-- Project Task Form:
![2019-09-06-162321_1920x1080_scrot](https://user-images.githubusercontent.com/731270/64435665-2d605980-d0c3-11e9-872c-fcf12dd3ddaf.png)

---
_With web_responsive_

-- Product Form (With 70%):
![70_](https://user-images.githubusercontent.com/731270/64436219-31d94200-d0c4-11e9-8cfa-56a690f6f627.gif)

-- Project Task (With 70%)
![70_proj](https://user-images.githubusercontent.com/731270/64436253-46b5d580-d0c4-11e9-928f-7f84778cbf22.gif)

---
_With web_responsive_

-- Product Form (With 100% & padding-right if have avatar):
![100_pad](https://user-images.githubusercontent.com/731270/64436321-651bd100-d0c4-11e9-998d-c2c794752711.gif)

-- Project Task (With 100%):
![100_](https://user-images.githubusercontent.com/731270/64436352-77960a80-d0c4-11e9-831d-0a0e108f597c.gif)

---

For me "100%" looks fine...

**Comment by pedrobaeza** [comment]
70% is for having room for smart-buttons box. Not sure about putting this at 100%, as it will mean always 2 lines at least (and with a lot of smart-buttons, it will mean a lot). Please try in res.partner with a lot of installed modules (like in runbot) to see.

**Comment by LoisRForgeFlow** [comment]
> Don't forget that this is for having a mobile proper responsive view, so -1 for increasing unconditionally the width, but if possible depending on the screen width, then ok

Yes, I don't know which would it be the best option, just pointing out that there is much room between the name and smarts buttons and I think it would be good to use it.

> 70% is for having room for smart-buttons box

Exactly, it is kind of random but the goal was to left space for a plenty-of-buttons button box.

**Comment by pedrobaeza** [comment]
Please read my last comment about my guess about why that 70%

**Comment by Tardo** [comment]
Yeah 70% looks better:
![long_title](https://user-images.githubusercontent.com/731270/65951290-1271d280-e440-11e9-9d91-81229b7a4b71.gif)

With 100%:
![2019-10-01-114109_1920x1080_scrot](https://user-images.githubusercontent.com/731270/65951496-75fc0000-e440-11e9-8420-00d9b67e3216.png)

**Comment by pedrobaeza** [comment]
So then nothing to do I guess?

**Comment by Tardo** [comment]
Change oe_title to use 70% instead of use fixed 400px

**Comment by pedrobaeza** [comment]
Ah, OK. Maybe it needs a minimum width also?

**Comment by Tardo** [comment]
Ok, i finally use other rule, check it here: https://github.com/OCA/web/pull/1391
