### ISSUE TITLE
[web_widget_x2many_2d_matrix] Select value from selection or from many2one

### ISSUE THREAD

**Issue by norlinhenrik** [OCA/web#1365]
I would like to select a value from a drop-down list instead of typing a value.
- If field_value is a selection field, show selection drop-down list.
- If field_value is a many2one field, show many2one drop-down list. Dynamic domain based on the values of field_x_axis and field_y_axis.

@hbrunn @pedrobaeza @simahawk @tschanzt @Yajo @tarteo @alexey-pelykh 
I see that you are contributors for [web_widget_x2many_2d_matrix](https://github.com/OCA/web/tree/12.0/web_widget_x2many_2d_matrix)
How easy or difficult would it be to implement drop-down list in the matrix?

I would like to start a crowdfunding to fundraise for this.
How much would I have to fundraise?

**Comment by hbrunn** [comment]
did you actually try to just stick in a selection field there? To my knowledge, since v11 we just have the framework render the appropriate widget for the field type, so I'd expect this to work already. The dynamic domain also might fall out of this machinery already.

**Comment by hbrunn** [comment]
PS: If this works for you, please PR an amendment to the readme saying something to that effect so that others won't have the same doubts as you have

**Comment by ghost** [comment]
@hbrunn thanks for your suggestions and for the help wanted label.

[https://github.com/OCA/web/blob/12.0/web_widget_x2many_2d_matrix_example/models/x2m_demo.py#L34](https://github.com/OCA/web/blob/12.0/web_widget_x2many_2d_matrix_example/models/x2m_demo.py#L34)
Changing the value to type `selection` or `many2one` results in the same error below on clicking the button `Try x2m 2d matrix`.

Error:
Uncaught TypeError: Cannot read property 'attrs' of undefined

http://127.0.0.1:12000/web/content/364-ca2711c/web.assets_backend.js:2475
Traceback:
TypeError: Cannot read property 'attrs' of undefined
    at Class.applyAggregateValue (http://127.0.0.1:12000/web/content/364-ca2711c/web.assets_backend.js:2475:240)
    at Class._renderTotalCell (http://127.0.0.1:12000/web/content/364-ca2711c/web.assets_backend.js:2465:46)
    at Class._renderFooter (http://127.0.0.1:12000/web/content/364-ca2711c/web.assets_backend.js:2463:276)
    at Class._renderView (http://127.0.0.1:12000/web/content/364-ca2711c/web.assets_backend.js:2449:344)
    at Class.prototype.<computed> [as _renderView] (http://127.0.0.1:12000/web/content/350-78e571f/web.assets_common.js:3538:488)
    at Class._render (http://127.0.0.1:12000/web/content/364-ca2711c/web.assets_backend.js:1580:178)
    at Class.start (http://127.0.0.1:12000/web/content/364-ca2711c/web.assets_backend.js:1276:335)
    at Class.prototype.<computed> [as start] (http://127.0.0.1:12000/web/content/350-78e571f/web.assets_common.js:3538:488)
    at http://127.0.0.1:12000/web/content/350-78e571f/web.assets_common.js:3684:52
    at http://127.0.0.1:12000/web/content/350-78e571f/web.assets_common.js:802:681

**Comment by hbrunn** [comment]
as I didn't do the port myself I'd have to dig in the code myself to see what's going on here, so let's see if somebody else can help here from the top off their heads. Might be a bug or you didn't fill the widget with the expected values. You should however post a log in debug mode to get a helpful backtrace

**Comment by yajo** [comment]
AFAIK this is not supported, and I'm not sure it's possible. I don't remember the code fine, so I'm just guessing, but if the name of the field includes the `x2many` word, it probably means that there's something intrinsic to x2m fields required by this widget.

**Comment by hbrunn** [comment]
that's to designate the type of field the widget operates on, not what kind of field it displays within the matrix. I base my assumption it should work for any field type on https://github.com/OCA/web/blob/12.0/web_widget_x2many_2d_matrix/static/src/js/2d_matrix_renderer.js#L306-L309 which looks pretty much like being able to deal with any kind of field to me

**Comment by yajo** [comment]
hmm ok it could be.

**Comment by norlinhenrik** [comment]
There are no errors in the server log.
This time I got another client error: 

> TypeError: axis is undefined

[many2one - Try x2m 2d matrix - ERROR.txt](https://github.com/OCA/web/files/3596602/many2one.-.Try.x2m.2d.matrix.-.ERROR.txt)

**Comment by hbrunn** [comment]
You need to turn off column and row totals, those don't make sense for non-numeric fields anyways. I added detecting this and setting the default value of this options in the [PR](https://github.com/OCA/web/pull/1373) linked above, there I also added matrices with a selection and a many2one field to prove the point - what you ask for already works.

Next time you're asked for a debug log when javascript is involved, use debug mode with assets, otherwise the backtrace is still unhelpful.

I spent two hours on this, so if you want to make up on the funding promise, donate that amount times your hourly rate to OCA or Unicef.

**Comment by norlinhenrik** [comment]
@hbrunn thank you so much - I really appreciate your help! :) I just checked out the website for Unicef, and I will give a donation (the service was unavailable right now...)
