### ISSUE TITLE
web_company_color init issue for first use

### ISSUE THREAD

**Issue by awa-si** [OCA/web#1366]
Please change a code for func: _scss_get_sanitized_values() like this. It will generate in right way

`    @api.multi
    def _scss_get_sanitized_values(self):
        self.ensure_one()
        values = dict(self.company_colors)
        values['color_navbar_text'] = self.color_navbar_text or '#FFF'
        values['color_navbar_bg'] = self.color_navbar_bg or '$o-brand-odoo'
        values['color_navbar_bg_hover'] = self.color_navbar_bg_hover or '$o-navbar-inverse-link-hover-bg'
        return values`

**Comment by Tardo** [comment]
Please, can you explain the issue?

**Comment by awa-si** [comment]
Yes, sure. When you install a module it creates a empty field in database, and if you try to update a  empty dict from dict(self.company_colors)  with selected key it throws a key error. Wrote a func like that it creates key:value or updates existing one.

**Comment by Tardo** [comment]
Thanks for report @awwea hope be fixed in the referenced pr
