### ISSUE TITLE
web_export_view - Export all rows of view

### ISSUE THREAD

**Issue by michaeljohn32** [OCA/web#137]
When a user checks the "check all" check box at the top of a tree, web_export_view should export all rows of the related tree view using the domain, not just the currently visible rows.

**Comment by pedrobaeza** [comment]
I don't agree. If you want that behaviour, click on Unlimited on record number and then click again on "Check all". Anyways, technically, to perform what you ask, all the code must change to accomodate to the new approach, so is nothing that cannot be done easily.

**Comment by michaeljohn32** [comment]
As I think about it, that is a reasonable workaround.  Thanks for considering this issue.
