### ISSUE TITLE
[web_timeline] Weekend zoom bug

### ISSUE THREAD

**Issue by Bart-DCBO** [OCA/web#1372]
![timeline_bug](https://user-images.githubusercontent.com/48516635/64783264-b108c300-d567-11e9-9ef7-f0466db19f55.PNG)
![timeline_bug_2](https://user-images.githubusercontent.com/48516635/64783265-b108c300-d567-11e9-91da-93bfd4c2847b.PNG)

When changing the zoom, at some point the grid will group 2 days together.
As you can see at Task 4 and Task 9, due to this grouping the weekend seems to move. This bug could cause confusion with the enduser, since it now seems Task 9 starts on Sunday instead of on Monday.

**Comment by pedrobaeza** [comment]
This seems something of vis timeline JS, not of the module itself.

**Comment by tarteo** [comment]
This is something of visjs and is not a bug.
