### ISSUE TITLE
why? web_m2x_options.done is not a function???

### ISSUE THREAD

**Issue by m5-project** [OCA/web#1376]
What should I do?

![111](https://user-images.githubusercontent.com/42757810/65121839-7351e180-da22-11e9-8a55-d3a7c3a76150.png)

**Comment by pedrobaeza** [comment]
Try on OCA runbot if it's correctly working. You are not even indicating Odoo version, steps to reproduce, etc.

**Comment by m5-project** [comment]
> Try on OCA runbot if it's correctly working. You are not even indicating Odoo version, steps to reproduce, etc.

 Odoo version 13.0alpha1 
On a simplement installé des options web m2x dans odoo.

**Comment by 718981206** [comment]
> Try on OCA runbot if it's correctly working. You are not even indicating Odoo version, steps to reproduce, etc.

Bien que mon anglais soit mauvais, je vous remercie pour votre réponse

**Comment by m5-project** [comment]
> Try on OCA runbot if it's correctly working. You are not even indicating Odoo version, steps to reproduce, etc.

Although my English is poor, thank you for your reply

**Comment by pedrobaeza** [comment]
Really? The module is not migrated to v13, so that's something expected. Please report problems with current migrated versions.
