### ISSUE TITLE
[12.0] web_widget_x2many_2d_matrix gives error on mobile/responsive

### ISSUE THREAD

**Issue by samnimri** [OCA/web#1387]
@hbrunn 

1) right click on a browser chrome/firefox etc. and click "inspect element"
2) click on phone icon to switch to responsive mode
3) open a form which uses web_widget_x2many_2d_matrix and you get error

observable in runbot....

**Comment by hbrunn** [comment]
the problem here is that the widget is to be displayed in kanban mode, which is not supported. You can force displaying it in list mode with `mode="list"` to make it render, but you'll have to invest some work to make it display something that's actually responsive.

**Comment by CasVissers-360ERP** [comment]
I can confirm this bug. Customer reported it because a user was trying to create a timesheet from a mobile device. 

@hbrunn how can I force mode="list"?

**Comment by hbrunn** [comment]
for now, set the attribute on the field in the view. This should be set in the constructor of the widget class  as a workaround, but for a proper fix first somebody should specify what `responsive` means for a matrix (I wouldn't know), and implement that.

**Comment by samnimri** [comment]
thanks @hbrunn . It should at least show something other than error. It could be something non-responsive.

**Comment by pedrobaeza** [comment]
@Tardo can you take a look to this?

**Comment by CasVissers-360ERP** [comment]
@Tardo @pedrobaeza 
Think this should be re-opened. Still facing issue:
https://drive.google.com/file/d/1Lc4Vu0OTE20uFKZTnkaeS8ULuznWPuWv/view

**Comment by CasVissers-360ERP** [comment]
Sorry just found the PR #1404 but still ticket should be open.

**Comment by pedrobaeza** [comment]
Having an opened PR is enough, not an issue and a PR.
