### ISSUE TITLE
[12.0] web_timeline: Loads all records

### ISSUE THREAD

**Issue by tarteo** [OCA/web#1408]
Currently timeline loads all items and not of the current window. This can be avoided by creating a simple domain which filters old / irrelevant records. But it would be nicer if it only loads records based on the current window of the timeline.

**Comment by pedrobaeza** [comment]
Yeah, any idea how to do it?

**Comment by tarteo** [comment]
Not really atm. I think a refactor of this module is needed before this is fixable.
