### ISSUE TITLE
Error thrown when using date filters in search bar.

### ISSUE THREAD

**Issue by 3piece** [OCA/web#1418]
module: web_edit_user_filter
version: 12.0

**Steps to reproduce**
Create a filter for the search bar, i.e. 
in Calendar list view, edit the search view and place in the following filter:
                <field name="start" string="start" filter_domain="[('start','&gt;',self)]"/>
Regenerate asset bundles.
Start to enter a date in the search bar "01", press enter,
Error is thrown.
- ...

**Current behavior**
This happens with any date filter in any model after web_edit_user_filter has been installed.
The filter search still works as expected, but a pop-over error is thrown. 

The following was the first error thrown
`Error: QWeb2 - template['web_edit_user_filter.Popover']: Runtime Error: TypeError: dict.value.value.attrs is undefined

https://odoo.is.awesome/web/content/104297-67c15f1/web.assets_common.js:3374
Traceback:
exception@https://odoo.is.awesome/web/content/104297-67c15f1/web.assets_common.js:3374:7
anonymous@https://odoo.is.awesome/web/content/104297-67c15f1/web.assets_common.js line 3416 > Function:25:29
_render@https://odoo.is.awesome/web/content/104297-67c15f1/web.assets_common.js:3415:296
render@https://odoo.is.awesome/web/content/104297-67c15f1/web.assets_common.js:3415:151
_renderPopover@https://odoo.is.awesome/web/content/104298-13173f3/web.assets_backend.js:3613:153
renderFacets/<@https://odoo.is.awesome/web/content/104298-13173f3/web.assets_backend.js:3614:64
_.forEach@https://odoo.is.awesome/web/content/104297-67c15f1/web.assets_common.js:12:558
renderFacets@https://odoo.is.awesome/web/content/104298-13173f3/web.assets_backend.js:3613:737
OdooClass.extend/Class.include/</prototype[name]</<@https://odoo.is.awesome/web/content/104297-67c15f1/web.assets_common.js:3541:371
proxy/<@https://odoo.is.awesome/web/content/104297-67c15f1/web.assets_common.js:3643:11
triggerEvents@https://odoo.is.awesome/web/content/104298-13173f3/web.assets_backend.js:40:377
trigger@https://odoo.is.awesome/web/content/104298-13173f3/web.assets_backend.js:35:223
_onModelEvent@https://odoo.is.awesome/web/content/104298-13173f3/web.assets_backend.js:68:14
triggerEvents@https://odoo.is.awesome/web/content/104298-13173f3/web.assets_backend.js:40:450
trigger@https://odoo.is.awesome/web/content/104298-13173f3/web.assets_backend.js:35:263
set@https://odoo.is.awesome/web/content/104298-13173f3/web.assets_backend.js:61:103
add@https://odoo.is.awesome/web/content/104298-13173f3/web.assets_backend.js:52:1752
add/<@https://odoo.is.awesome/web/content/104298-13173f3/web.assets_backend.js:876:35
optimizeCb/<@https://odoo.is.awesome/web/content/104297-67c15f1/web.assets_common.js:10:331
_.forEach@https://odoo.is.awesome/web/content/104297-67c15f1/web.assets_common.js:12:558
_.mixin/</_.prototype[name]@https://odoo.is.awesome/web/content/104297-67c15f1/web.assets_common.js:69:526
add@https://odoo.is.awesome/web/content/104298-13173f3/web.assets_backend.js:875:11
select_completion@https://odoo.is.awesome/web/content/104298-13173f3/web.assets_backend.js:901:1113
proxy/<@https://odoo.is.awesome/web/content/104297-67c15f1/web.assets_common.js:3643:11
select_item@https://odoo.is.awesome/web/content/104298-13173f3/web.assets_backend.js:682:339
start/<@https://odoo.is.awesome/web/content/104298-13173f3/web.assets_backend.js:678:99
dispatch@https://odoo.is.awesome/web/content/104297-67c15f1/web.assets_common.js:892:451
add/elemData.handle@https://odoo.is.awesome/web/content/104297-67c15f1/web.assets_common.js:865:173`

The following was with debug=assets

`Error:
TypeError: dict.value.value.attrs is undefined

https://odoo.is.awesome/web/static/lib/qweb/qweb2.js line 469 > Function:13
Traceback:
anonymous/<@https://odoo.is.awesome/web/static/lib/qweb/qweb2.js line 469 > Function:13:62
foreach@https://odoo.is.awesome/web/static/lib/qweb/qweb2.js:180:25
anonymous@https://odoo.is.awesome/web/static/lib/qweb/qweb2.js line 469 > Function:11:23
_render@https://odoo.is.awesome/web/static/lib/qweb/qweb2.js:458:58
render@https://odoo.is.awesome/web/static/lib/qweb/qweb2.js:450:26
_renderPopover@https://odoo.is.awesome/web_edit_user_filter/static/src/js/backend.js:179:35
renderFacets/<@https://odoo.is.awesome/web_edit_user_filter/static/src/js/backend.js:225:22
_.forEach@https://odoo.is.awesome/web/static/lib/underscore/underscore.js:145:9
renderFacets@https://odoo.is.awesome/web_edit_user_filter/static/src/js/backend.js:218:15
OdooClass.extend/Class.include/</prototype[name]</<@https://odoo.is.awesome/web/static/src/js/core/class.js:123:38
proxy/<@https://odoo.is.awesome/web/static/src/js/core/mixins.js:278:23
triggerEvents@https://odoo.is.awesome/web/static/lib/backbone/backbone.js:204:57
trigger@https://odoo.is.awesome/web/static/lib/backbone/backbone.js:146:19
select_completion@https://odoo.is.awesome/web/static/src/js/views/search/search_view.js:659:24
proxy/<@https://odoo.is.awesome/web/static/src/js/core/mixins.js:278:23
select_item@https://odoo.is.awesome/web/static/src/js/widgets/auto_complete.js:212:18
start/<@https://odoo.is.awesome/web/static/src/js/widgets/auto_complete.js:50:26
dispatch@https://odoo.is.awesome/web/static/lib/jquery/jquery.js:4641:58
add/elemData.handle@https://odoo.is.awesome/web/static/lib/jquery/jquery.js:4309:63`

**Expected behavior**
This should not throw an error.
Also un-installing the module does not immediately remove the broken function from the system, it required  update=all and update=base to be run on the server.

**Comment by i-vyshnevska** [comment]
I have made some fix
https://github.com/i-vyshnevska/web/commit/0ca6b38c053454948583d6ce66a03c5b9ccb7b82
but it is still broken in many places
