### ISSUE TITLE
[11.0] web_responsive issue after installing it on Odoo 11 docker on windows 10 

### ISSUE THREAD

**Issue by MohsenWaleed** [OCA/web#1420]
I have installed docker desktop on windows 10 and Odoo 11 is working without any issue, I have added web_responsive into /mnt/extra-addons folder trough mounted folder on the host and once I installed the module, it's installed but I got the below error and the layout of the odoo page is not working. I tried to restart odoo and postgress instances but the error still raising:

How can I solve it?

WARNING Odoo11 odoo.addons.base.ir.ir_qweb.assetsbundle: (b'', b'ParseError: Unrecognised input in - on line 7342, column 17:\n7341 body {\n7342     width: 100%;f\n7343     height: 100%;\n\n')This error occured while compiling the bundle 'web.assets_backend' containing:
    - /web/static/lib/bootstrap/less/variables.less
    - /web/static/lib/bootstrap/less/mixins/vendor-prefixes.less
    - /web/static/lib/bootstrap/less/mixins/buttons.less
    - /web/static/lib/bootstrap/less/mixins/clearfix.less
    - /web/static/lib/bootstrap/less/mixins/size.less
    - /web/static/src/less/variables.less
    - /web/static/src/less/utils.less
    - /web_editor/static/src/less/web_editor.variables.less
    - /web/static/src/less/import_bootstrap.less
    - /web/static/src/less/bootstrap_overridden.less
    - /web/static/src/less/webclient_extra.less
    - /web/static/src/less/webclient_layout.less
    - /web/static/src/less/webclient.less
    - /web/static/src/less/domain_selector.less
    - /web/static/src/less/model_field_selector.less
    - /web/static/src/less/progress_bar.less
    - /web/static/src/less/dropdown.less
    - /web/static/src/less/dropdown_extra.less
    - /web/static/src/less/tooltip.less
    - /web/static/src/less/debug_manager.less
    - /web/static/src/less/control_panel.less
    - /web/static/src/less/fields.less
    - /web/static/src/less/fields_extra.less
    - /web/static/src/less/views.less
    - /web/static/src/less/views_extra.less
    - /web/static/src/less/pivot_view.less
    - /web/static/src/less/graph_view.less
    - /web/static/src/less/form_view.less
    - /web/static/src/less/form_view_extra.less
    - /web/static/src/less/list_view.less
    - /web/static/src/less/list_view_extra.less
    - /web/static/src/less/kanban_dashboard.less
    - /web/static/src/less/kanban_column_progressbar.less
    - /web/static/src/less/kanban_view.less
    - /web/static/src/less/kanban_view_mobile.less
    - /web/static/src/less/web_calendar.less
    - /web/static/src/less/search_view.less
    - /web/static/src/less/search_view_extra.less
    - /web/static/src/less/data_export.less
    - /web/static/src/less/base_settings.less
    - /web/static/src/less/report_backend.less
    - /base_import/static/src/less/base_import.less
    - /web_diagram/static/src/less/diagram_view.less
    - /web_editor/static/src/less/web_editor.common.less
    - /web_editor/static/src/less/web_editor.backend.less
    - /web_responsive/static/src/less/main.less
    - /web_responsive/static/src/less/navbar.less
    - /web_responsive/static/src/less/app_drawer.less
    - /web_responsive/static/src/less/form_view.less
    - /web_responsive/static/src/less/variables.less
    - /web_settings_dashboard/static/src/less/dashboard.less
2019-10-25 13:57:38,007 1 INFO Odoo11 odoo.models.unlink: User #1 deleted ir.attachment records with IDs: [349]
2019-10-25 13:57:38,138 1 INFO Odoo11 odoo.modules.registry: At least one model cache has been invalidated, signaling through the database.

**Comment by MohsenWaleed** [comment]
I have solved it, there is extra character in main.less file in my version of web_responsive

**Comment by vancouver29** [comment]
@MohsenWaleed how did you find out that the error comes from `main.less`? And what exactly is this extra character ?

**Comment by ap-wtioit** [comment]
@vancouver29 from the error message above:
```
...
\n7341 body {\n7342 width: 100%;f\n7343 height: 100%;\n\n
...
```
i would guess that translates to the following css:
```
body {
width: 100%;f
height: 100%;


```
the `f` after the `width: 100%;` would be invalid in this case. and the you try to find the line that ends with `;f` in all your files

**Comment by vancouver29** [comment]
@ap-wtioit Thank you for the quick response :). I have the following error, So you might know what is wrong here?

```
\nParseError: Unrecognised input. Possibly missing something in - on line 5299, column 1:\n5298 }\n5299 \n\n')This error occured while compiling the bundle 'web.assets_frontend' containing:
    - /web/static/lib/bootstrap/less/variables.less
    - /web/static/lib/bootstrap/less/mixins/vendor-prefixes.less
    - /web/static/lib/bootstrap/less/mixins/buttons.less
    - /web/static/lib/bootstrap/less/mixins/clearfix.less
    - /web/static/lib/bootstrap/less/mixins/size.less
    - /web/static/src/less/variables.less
    - /web/static/src/less/utils.less
    - /web_editor/static/src/less/web_editor.variables.less
    - /web/static/src/less/import_bootstrap.less
    - /web_editor/static/src/less/web_editor.common.less
    - /portal/static/src/less/website.ui.less
    - /portal/static/src/less/website.wrapwrap.less
    - /portal/static/src/less/bootstrap.extend.less
    - /portal/static/src/less/portal_frontend.less
    - /website/static/src/less/website.ui.components.less
    - /website/static/src/less/website.snippets.less
    - /website/static/src/less/website.zoomodoo.less
    - /website_form/static/src/less/website_form.less
    - /website_mail/static/src/css/website_mail.less
    - /website_rating/static/src/less/website_rating.less
    - /theme_sky/static/src/scss/options/nav/option_navigation_right.less
    - /theme_sky/static/src/scss/options/nav/navigation.less
    - /theme_sky/static/src/scss/theme-color.less
    - /theme_sky/static/src/scss/font.less
    - /theme_sky/static/src/font/style.css
    - /theme_sky/static/src/scss/style.less
    - /theme_sky/static/src/scss/footer.less
    - /theme_sky/static/src/scss/homepage.less
    - /theme_sky/static/src/scss/responsive.less
    - /payment/static/src/less/payment_form.less
    - /sale/static/src/less/sale_portal.less

```

**Comment by ap-wtioit** [comment]
@vancouver29 with this message it's not that easy, something at the end of a file before a closing `}`, syntax highlighting in your editor might help you. however it feels to me that such issues are not really an issue of OCA/web unless you can point to some module of this repo that would be errornous. and that seems highly unlikely to me, especially because you asset file seems to contain none of the modules for this repo (as far as i can see).
