### ISSUE TITLE
web_responsive mobile display

### ISSUE THREAD

**Issue by eguane** [OCA/web#1444]
Hi, when trying to add a new reception manually into inventory menu, it's possible to create a new one but impossible to add product line.
Add new line option is not present when on mobile display with chrome browser.
In my example I try to add a new reception directly in inventory menu without purchase order picking list.
Odoo 12 / android mobile scanner / chrome. 
Thanks

**Comment by pedrobaeza** [comment]
Try on runbot and put screenshots. Any way, this sounds as there's no kanban view there, which is not something of web_responsive itself.

**Comment by eguane** [comment]
it's probably because I modified the default view in invoice and product to be list and not kanban then the list view is inherited for receipt and diplayed without the add line.
![image](https://user-images.githubusercontent.com/35990301/69285495-55a32300-0bf1-11ea-95f4-f2d2ed2e9c00.png)

**Comment by pedrobaeza** [comment]
Then you have your answer :wink: 

Provide a kanban view for that and you will see something in mobile.

**Comment by eguane** [comment]
Pedro, for you information, it was necessary to update stock module to
retrieve it back functionning well.
Maybe because I have installed web responsive after stock module or not...
!

Thanks for your help


Le jeu. 21 nov. 2019 à 00:46, Pedro M. Baeza <notifications@github.com> a
écrit :

**Comment by pedrobaeza** [comment]
Good to know. Update a module restores standard things that have been touched.
