### ISSUE TITLE
[web_timeline] Can't change colors

### ISSUE THREAD

**Issue by pedrocs-exo** [OCA/web#1446]
Hi,

I can't change the color of project tasks no matter what I change on the colors attribute of the timeline tag. Can someone please confirm? I happens on both 10.0 and 12.0.

For example, I was expecting red bars with the following mod: 
colors="#ff0000: user_id==false; #ff0000: user_id==true;"

Thank you!

**Comment by alexis-via** [comment]
I confirm this bug on v10.0. Colors is always blue, whetever the colors attribute.

**Comment by alexis-via** [comment]
I understand the bug now: it doesn't work on M2O fields. In web_timeline.js, in the _each loop, the IF on this line of code https://github.com/OCA/web/blob/10.0/web_timeline/static/src/js/web_timeline.js#L248 will not match for M2O field ; for a M2O field, evt[color.field] will be an array [ID, display_name]. If you change evt[color.field] to evt[color.field][0], it will work.

**Comment by alexis-via** [comment]
A temporary workaround if you want to set a color on a M2O field: define a new field fields.Integer(related='m2o_field.id', readonly=True) and use the new integer field in the timeline view for the colors attribute.
