### ISSUE TITLE
[web_responsive] v12.0.1.3.4 search windows

### ISSUE THREAD

**Issue by eguane** [OCA/web#1453]
Well, maybe it's better to open a new window when searching with a mobile screen, but I really don't like the new way when I'am behind my computer with full screen and always necessary to switch between search windows and the result. For my point of view, really not user friendly.

**Comment by pedrobaeza** [comment]
That only happens on mobile, so you should check your computer how is reporting to the window its size.

Closing as no issue.

**Comment by eguane** [comment]
Well, i'am on Ubuntu with chromium and Never see this type of issue.

Le ven. 29 nov. 2019 à 02:10, Pedro M. Baeza <notifications@github.com> a
écrit :
