### ISSUE TITLE
Module credits missing since v9

### ISSUE THREAD

**Issue by JayVora-SerpentCS** [OCA/web#1459]
Hello Team,

https://github.com/OCA/web/tree/9.0/web_action_conditionable This modules' credits have lost the real credit track since v9.

https://github.com/OCA/web/tree/8.0/web_action_conditionable has it well credited.

Can we please get it corrected?

Thanks.
Cc: @pedrobaeza @ovnicraft

**Comment by pedrobaeza** [comment]
I don't see any contribution from Onestein in 9.0 version.

**Comment by JayVora-SerpentCS** [comment]
I was under an impression that we carry the credits : 
1. Of the initial developer
2. Of the Sponsor specially

Thanks.

**Comment by pedrobaeza** [comment]
You must see in which moment Onestein started to be credited in 8.0 branch. Was it after the 9.0 migration? I don't know even if it deserves to be there (as the module exists, how many changes they did for being there?)

**Comment by JayVora-SerpentCS** [comment]
not sure, its post 9.0.
IMHO, sponsor name must be kept missed!
https://github.com/OCA/web/blob/8.0/web_action_conditionable/README.rst#id5

**Comment by pedrobaeza** [comment]
Well, if you think it's incorrect, do the proper PR. Any way, these versions are very old, so you should go to the latest available version for that.

**Comment by ovnicraft** [comment]
@JayVora-SerpentCS i wrote `web_action_conditionable` for v8.0 but i lost track on it. 
commits can help us :-)
