### ISSUE TITLE
web_advanced_search_x2x one2many field error

### ISSUE THREAD

**Issue by szufisher** [OCA/web#146]
after install web_advanced_search_x2x  successfully, 
for one2many field, there is error message

 Odoo Client Error

Error: cannot call methods on autocomplete prior to initialization; attempted to call method 'widget'

http://localhost:8080/web/js/web.assets_common/fc0ec0a:216

**Comment by hbrunn** [comment]
please activate debug mode and post the error message it provides then

**Comment by rafaelbn** [comment]
@szufisher please reproduce issue and post here as indicated. If not please close issue. We cannot reproduce this error.

**Comment by hbrunn** [comment]
closing due to obious lack of interest from the side of issue creator
