### ISSUE TITLE
Port / backport : web_domain_field for V12

### ISSUE THREAD

**Issue by legalsylvain** [OCA/web#1464]
Hi all. I'd like to use web_domain_field module for V12.
For instance there is a
- a V10 merged module https://github.com/OCA/web/tree/10.0/web_domain_field
- a V11 PR need fixing https://github.com/OCA/web/pull/1019
- a V13 PR that seems OK https://github.com/OCA/web/pull/1434

I'd like to know which is best (and easy ;-)) way to port / (backport) the module. From V13 to V12 ? or from V10 / V11 to V12.

thanks for your answers.

CC : original authors : @lmignon, @rousseldenis 

BTW, thanks for this great contribution. Seems a very good module.
Don't understand why it's not a core feature.

**Comment by lmignon** [comment]
@legalsylvain A backport from 13 to 12..... (not sure but IMO there is less diff into tthe js between 12 and 13 than between 11 and 12)

An other way should be to have this functionality into odoo ... https://github.com/odoo/odoo/pull/17328/files
