### ISSUE TITLE
web_responsive wrong shortcuts in template

### ISSUE THREAD

**Issue by kos94ok-3D** [OCA/web#1469]
Steps to reproduce:
1. Install web_responsive
2. Open Shortcuts menu
![изображение](https://user-images.githubusercontent.com/33932458/71486627-fb186a80-281f-11ea-8cf3-898f04ada81b.png)
![изображение](https://user-images.githubusercontent.com/33932458/71486641-0a97b380-2820-11ea-9efd-551ba597d22c.png)

I think is a good idea update UserMenu.shortcuts template
Hi, @VincentSchippefilt, @Yajo, @Tardo  what do you think about it?

**Comment by yajo** [comment]
Absolutely.

**Comment by Tardo** [comment]
Feel free to do a PR ;)
