### ISSUE TITLE
Multi company web_responsive

### ISSUE THREAD

**Issue by celebraciones** [OCA/web#1472]
Odoo version: 13.0
Browser: Safari iOS 13.3

Multi company: User has granted access to more than 1 company

Issues: 
- There seems to be no way to select a different company from the top-right menu.
- The logout button is gone.
![Captura de Pantalla 2020-01-01 a la(s) 14 45 50](https://user-images.githubusercontent.com/29007788/71645960-71482180-2ca5-11ea-8bb5-99f38ff4edc4.png)

**Comment by yajo** [comment]
Are you testing in a real mobile browser or in a desktop browser in mobile mode? If it's a desktop, did you hit F5 after resizing the browser?

**Comment by celebraciones** [comment]
It is in a real mobile browser (actually two different ones). In Safari desktop happens the same with smaller screens like iPhone (iPad mini is ok).

**Comment by Tardo** [comment]
This is fixed here: https://github.com/odoo/odoo/pull/38146

Update your Odoo 13.0 base

**Comment by pedrobaeza** [comment]
Then we can close this.
