### ISSUE TITLE
pop-up dialog covers document viewer

### ISSUE THREAD

**Issue by sciallo** [OCA/web#1473]
Loving the new side document viewer!

It would be nice if pop-up dialogs would stay over the form view (or better yet if they were movable) so we could still see all information in the document we're viewing. For example as in the screenshot when we're trying to fill an address from a vendor's invoice.

![Screenshot_20200103_104738](https://user-images.githubusercontent.com/17577898/71734406-ed637600-2e19-11ea-8540-8054148e6e46.png)

**Comment by pedrobaeza** [comment]
That's not the idea and it goes against Odoo design in popup menus. Change views for not being in popup but editable on tree.

**Comment by LoisRForgeFlow** [comment]
@sciallo You might be interested in this module: https://github.com/OCA/web/tree/13.0/web_dialog_size. It allows to move and resize dialogs.

**Comment by sciallo** [comment]
Thanks @LoisRForgeFlow !!
