### ISSUE TITLE
web_widget_x2many_2d_matrix doesnt respect sequence fields.

### ISSUE THREAD

**Issue by agent-z28** [OCA/web#1474]
Especially for the Matrix Widget, where you have Zip Codes or Names, it is very import to have a propper sequence. The Widget should support a field sequence for x as for y- fields

**Comment by pedrobaeza** [comment]
In theory, the widget respects the `_order` defined in the model. Can you be more specific about your problem?

**Comment by pedrobaeza** [comment]
And also always indicate Odoo version.

**Comment by mojahed4e** [comment]
How can we sort the x and y-axis?
