### ISSUE TITLE
[12.0] web_responsive: document viewer not closed with Esc when maximized

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/web#1476]
Steps to reproduce:

- Preview an image attachment clicking on it.
- Maximize it with the corresponding button.
- Press "Esc".
- It doesn't close the preview. On not maximized and with standard, it closes it.

**Comment by pedrobaeza** [comment]
Arrow keys for navigation between attachments don't work as well.

**Comment by Tardo** [comment]
This is solved
