### ISSUE TITLE
Timeline view couldn't be loaded

### ISSUE THREAD

**Issue by vjskibin** [OCA/web#1497]
After installation both modules (project_timeline and web_timeline) by clicking on clock button i get an error:
![image](https://user-images.githubusercontent.com/23342324/73049615-1e215300-3e8e-11ea-826f-ea94465e458d.png)
(Timeline view couldn't be loaded)

**Comment by vjskibin** [comment]
Odoo version 11.0

**Comment by vjskibin** [comment]
After rebooting the server everything works fine :)

**Comment by ghost** [comment]
author closed it..
