### ISSUE TITLE
[13.0] web_responsive Menu toggle doesn't open after one click

### ISSUE THREAD

**Issue by AlexeyS001** [OCA/web#1513]
It works fine until I click on a menu item.
Video:
https://youtu.be/Lqcmu1zFT38

Odoo 13

**Comment by AlexeyS001** [comment]
I took a video with inspector if it helps
https://youtu.be/okqOFjE0zTA

**Comment by AlexeyS001** [comment]
Any update?

**Comment by Tardo** [comment]
Sorry i can't reproduce this issue... browser? can you reproduce it on runbot?

**Comment by isacben** [comment]
I was able to reproduce the issue when I put just the 'web_responsive' folder in my custom addons path, instead of the full 'web' repository.

I guess the correct way is to clone or download the full 'web' repo and add it to the addons paths list. Then install the web_responsive module.

**Comment by netpedro-com** [comment]
@AlexeyS001 version downloaded from https://odoo-community.org/shop/product/web-responsive-2681 has this bug. But version downloaded from github does not.
