### ISSUE TITLE
[13.0] web_domain_field invalid path to static/lib/js

### ISSUE THREAD

**Issue by lck** [OCA/web#1526]
Path to pyeval.js is invalid:

13.0/web_domain_field/static/lib/js/pyeval.js

the valid path should be:

13.0/web_domain_field/static/**src**/js/pyeval.js

as declared in web_domain_field/views/web_domain_field.xml

**Comment by legalsylvain** [comment]
could you make a PR ? thanks !

**Comment by sudhir-erpharbor** [comment]
Thanks for reporting the issue. The issue is fixed in the PR #1527
