### ISSUE TITLE
web_responsive Apps Drawer not closing!

### ISSUE THREAD

**Issue by SaravananSakthivel** [OCA/web#1528]
Version [12.0] 
Moduel web_responsive

App Drawer is not closing if click on the app icon and menu which is a direct action menu from the top bar.
It is working fine if it is menu which has child menu.It doesn't work on the cases of direct action menu

**Comment by pedrobaeza** [comment]
Can you please put a video of what you are referring to?

**Comment by SaravananSakthivel** [comment]
Hi @pedrobaeza 
Please have a look at the video of the issue and i am using latest version

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/3658948/75092101-a2a0e780-559a-11ea-8de2-52027dd071a9.gif)

Also attached the a video of another issue. Multiple times have to click on the app icon to view accounting menu

![ezgif com-video-to-gif(1)](https://user-images.githubusercontent.com/3658948/75092282-18f21980-559c-11ea-97ee-8453501f839c.gif)

**Comment by Tardo** [comment]
:/ Github has not closed this commit

**Comment by pedrobaeza** [comment]
Because it was not merged in the default branch, but another. Remember we have to forward port it to v13.
