### ISSUE TITLE
[11.0] web_m2x_options search_more doesn't work in Odoo 11

### ISSUE THREAD

**Issue by n17** [OCA/web#1539]
Hello!
 
I would like some fields to always show the "Search more..." line.
If I understand correctly, then installing your `web_m2x_options` module and adding
`"show_more": True` to the field's `options` dictionary in the view should achieve this. However, doing so doesn't have any effect for me.
Adding `"limit": 0` to the `options` dictionary does make "Search more..." always show up, but it also prevents any records from being displayed above the "Search more..." text. This is not an ideal solution.

**Comment by mlaitinen** [comment]
This was fixed in `10.0` but was refactored in `11.0` and doesn't work as expected anymore: #651
