### ISSUE TITLE
[12.0] web_widget_digitized_signature on_clear is not a function

### ISSUE THREAD

**Issue by rubencabrera** [OCA/web#1542]
How to reproduce:
Use the `widget="signature"` in a boolean field for a form view. Open the form view, use the signature field and save. Once you do that (and when you open that view again) you'll get:

```
TypeError: self.on_clear is not a function

http://localhost:8069/web/content/1726-0872756/web.assets_backend.js:3174
Rastreo de error:
_render/<@http://localhost:8069/web/content/1726-0872756/web.assets_backend.js:3174:206
dispatch@http://localhost:8069/web/content/1574-d90d846/web.assets_common.js:892:451
add/elemData.handle@http://localhost:8069/web/content/1574-d90d846/web.assets_common.js:865:173
```

I'm using OCB. 

Searching on odoo base, I've found the `on_clear` function used to be in `addons/web/static/src/js/views/form_widgets.js` but that doesn't exist anymore.

**Comment by kos94ok-3D** [comment]
Use binary instead of boolean.
![изображение](https://user-images.githubusercontent.com/33932458/75894142-760f8a00-5e3c-11ea-8b17-5df4116abc02.png)

**Comment by rubencabrera** [comment]
D'oh, sorry I missed that. Will change and close as soon as I test if it hasn't been closed yet. Thanks for the quick response!

**Comment by rubencabrera** [comment]
Yep, that fixed it, thanks and sorry again for missing that.
