### ISSUE TITLE
Using web widget bokeh chart with odoo web portal?

### ISSUE THREAD

**Issue by andylemay** [OCA/web#1548]
Hi OCA,
I'm successfully using the bokeh_chart widget in a couple of models and views.  Working nicely--Thank you!
Now I'm trying to use one of those charts in a web portal to create user nice dashboard.  Looking at the source of the output web page...The script code for the chart goes into the web page but nothing is displayed and it appears that the 'bokeh_chart' field widget is not functioning.
I'm getting into odoo so probably a simple misunderstanding on my part about how it all works!
Any help would be appreciated.
Thanks 
Andy

in normal View this works just fine

><page string="Module Graph">
>      <div>
> 	    	<field name="modules_chart" widget="bokeh_chart" nolabel="1"/>
> 	</div>    
> </page>

**CURRENT CODE FOR THE WEB PORTAL**
**Controller**
```
# -*- coding: utf-8 -*-
from odoo import http

class evms(http.Controller):
    @http.route('/evms/console', auth='public')
    def serverList(self, **kw):
        evmsSystem = http.request.env['evms.system']
        return http.request.render('evms.ListServers', {
             'systems': evmsSystem.search([])
        })
```
**Template**
```
<?xml version="1.0" encoding="UTF-8"?>
<odoo>
    <template id="ListServers">
        <title>EVMS systems</title>
        <t t-foreach="systems" t-as="system">
          <div>
              <t>
                <span t-field="system.modules_chart" t-options='{"widget": "bokeh_chart","nolabel": "1"}'/>
              </t>
          </div>
          <p><t t-esc="system.id"/></p>
          <p><t t-esc="system.name"/></p>
        </t>
    </template>
 </odoo>
```
Also tried a few format variants with '<t t-esc=...' ,' <t t-raw=...' here.

**Output**
It's a bit big to show here but you basically see the main div and script with all the code and parameters for the graph.  What appears to be missing is the head and tail code.  If I add this in to the page the graph shows.

**Comment by andylemay** [comment]
Good news and a little update as my investigation continues!

Got it working!!! ...  with this... in my template

```
<?xml version="1.0" encoding="UTF-8"?>
<odoo>
    <template id="ListServers" name="My EVMS Dashboard">
        <t t-call="website.layout">
            <link
                rel="stylesheet"
                type="text/css"
                href="/web_widget_bokeh_chart/static/src/lib/bokeh/bokeh-1.1.0.css"
            />
            <link
                rel="stylesheet"
                type="text/css"
                href="/web_widget_bokeh_chart/static/src/lib/bokeh/bokeh-widgets-1.1.0.css"
            />
            <link
                rel="stylesheet"
                type="text/scss"
                href="/web_widget_bokeh_chart/static/src/scss/custom-bokeh.scss"
            />
            <script
                type="text/javascript"
                src="/web_widget_bokeh_chart/static/src/lib/bokeh/bokeh-1.1.0.js"
            />
            <script
                type="text/javascript"
                src="/web_widget_bokeh_chart/static/src/lib/bokeh/bokeh-widgets-1.1.0.js"
            />
            <script
                type="text/javascript"
                src="/web_widget_bokeh_chart/static/src/lib/bokeh/bokeh-api-1.1.0.js"
            />
            <script
                type="text/javascript"
                src="/web_widget_bokeh_chart/static/src/js/web_widget_bokeh_chart.js"
            />
            <t t-set="title">My EVMS Dashboard</t>
            <div class="oe_structure">
                <div class="container">
                    <t t-foreach="systems" t-as="system">
                      <div>
                            <t   t-raw="system.modules_chart"/>
                      </div>
                      <p><t t-esc="system.id"/></p>
                      <p><t t-esc="system.name"/></p>
                    </t>
                </div>
            </div>
        </t>
    </template>
```

so now need to tray and understand how to get it working with a named field widget "bokeh_chart".  notice in the original defn in web_wodget_bokeh_chart.xml the top is 

```
id="assets_backend"
name="web_widget_bokeh_chart assets"
inherit_id="web.assets_backend"
```

presumably I need the right defn of the above now.  Will keep investigating.

**Comment by KevinMcMenamin** [comment]
Any chance you could share an example for the back-end Odoo screen as I am quite interested in using

**Comment by andylemay** [comment]
Hi Kevin, 

This is just a screenshot of the top of the page.  It was not particularly pretty and I've added a map.

![Screenshot 2020-05-21 at 13 50 08](https://user-images.githubusercontent.com/5936400/82556461-091dad80-9b6a-11ea-9a6f-62c135fff3f1.png)
