### ISSUE TITLE
Studio broken

### ISSUE THREAD

**Issue by MLDMoritz** [OCA/web#1558]
Navigate around in studio, click some stuff.

```
/web_studio/static/src/js/web_client.js:457
Uncaught TypeError: controller.widget.exportState is not a function

```

**Comment by legalsylvain** [comment]
Hi. Sorry, your bug report is not complete. First could mention which version of odoo you are using, and which OCA modules. 
Could you also explain how to reproduce the problem with runbot ? 

thanks.

**Comment by Tardo** [comment]
No reply... can this be closed?
