### ISSUE TITLE
[13.0] web_responsive: Menu without icons

### ISSUE THREAD

**Issue by rjakutis** [OCA/web#1562]
I do not see icons in main menu, only text.

![Annotation 2020-03-27 134101](https://user-images.githubusercontent.com/62749036/77752707-bbd10400-7030-11ea-8890-45958d5c7fbd.png)

**Comment by pedrobaeza** [comment]
Can you try to reproduce the problem in runbot (admin/admin)?

https://runbot.odoo-community.org/runbot/162/13.0

**Comment by rjakutis** [comment]
I tried runbot, there is no problem, I see main menu with icons after click on left-top icon.

**Comment by pedrobaeza** [comment]
Then it seems something on your end: bad deployment or custom module interfering, but I'm afraid it's out of the scope of this issue tracker, so closing. Try reinstalling or starting from a fresh DB.

**Comment by rjakutis** [comment]
I have fresh installation, there is no custom modules. As I understood, there is no support on this module.

**Comment by pedrobaeza** [comment]
There's limited voluntary support for bugs in the module in this issue tracker, not for deployment questions. For that, there are also voluntary efforts in Odoo forums or mailing lists, not here.

**Comment by rjakutis** [comment]
I found the problem. All I needed was to restart the odoo service.
