### ISSUE TITLE
[13.0][web_responsive] Discuss app not responsive

### ISSUE THREAD

**Issue by hgarridoco** [OCA/web#1566]
I'm testing this app and compare with odoo 12.0 and in 12.0 discuss app could be use in mobile, but with odoo 13.0 can't because it haven't make full responsive actions. Is this correct?

Tested in runbot.

![image](https://user-images.githubusercontent.com/16115608/78383447-af245100-75d8-11ea-882d-3288b45758c1.png)

**Comment by hgarridoco** [comment]
Any update?

**Comment by pedrobaeza** [comment]
No. If you expect to have it fixed soon, you can propose a PR fixing it, pay someone to do it, or simply wait until a voluntary is able to do it.

**Comment by hgarridoco** [comment]
I only ask. In this moment I'm looking for fix it. I don't expect any work, only info.

Keep calm.

**Comment by pedrobaeza** [comment]
That's the standard answer, nothing without calm.

**Comment by Tardo** [comment]
@hgarridoco 
Discuss 'Mobile Mode' has been removed from Odoo CE 13.0, i'm working on a custom implementation to have a usable view on mobiles.
