### ISSUE TITLE
[13.0] [web_responsive] Cannot access Apps > Updates

### ISSUE THREAD

**Issue by sergiuga** [OCA/web#1567]
When trying to go to Apps > Updates I get the below error message: 

Sorry, you are not allowed to access documents of type 'Attachment' (ir.attachment). This operation is allowed for the groups: - User types/Internal User - (Operation: read, User: 175650)

**Comment by legalsylvain** [comment]
Did you reproduced this bug on the OCA runbot ?

**Comment by sergiuga** [comment]
> Did you reproduced this bug on the OCA runbot ?

No, it occurs only in my environment. I have a Centos7 server, but I don't think it's relevant. 
I have this error on a fresh install, without any other custom modules installed.
