### ISSUE TITLE
web tree view presenting download link instead of picture

### ISSUE THREAD

**Issue by shriramrs31** [OCA/web#157]
I  installed both the apps web_tree_image and product_image_list_view and I am still getting only download links instead of images in tree view. In sale order line, I am able to see an image. But when I edit the product.template tree view (warehouse -> products) to add "<field name="image_small" widget='image'/>" I am seeing only download link instead of the images. 

After some debugging, I found out that "row_data[this.id].value" in js returns the size string ("xxxx bytes"/"xxxx kB",..) instead of the binary value. This results in 

 img src="data:image/png;base64,127 kB" width="64px" height="64px" 

Notice the string"127 kB" after base64. Here the value of field should be printed out.

I am using bitnami odoo instance 8.0-8 which uses odoo nightly version 8.0-20150423

**Comment by pedrobaeza** [comment]
Please use latest version.
