### ISSUE TITLE
[12.0]web_readonly_bypass questions

### ISSUE THREAD

**Issue by flotho** [OCA/web#1571]
Hi Everyone, 

AFAICS, there is no v12 plan for migration of web_readonly_bypass . Is it a native behaviour in Odoo or would it be usefull to port it ?

Regards

**Comment by pedrobaeza** [comment]
Yes, native: `force_save=1`.

**Comment by flotho** [comment]
Damned,

Is Wikipedia your name ;)

**Comment by flotho** [comment]
Thankkksss
