### ISSUE TITLE
[odoo12.0] web_responsive  Menu button is not available

### ISSUE THREAD

**Issue by qzmxs** [OCA/web#1574]
module: web_responsive
version: 12.0

**Steps to reproduce**
- ...
![image](https://user-images.githubusercontent.com/55458897/79078948-6a1dbe80-7d3e-11ea-8d04-d731886ad3e7.png)

This menu button is on the left, which prevents it from being used normally,
**Current behavior**

**Expected behavior**

**Comment by pedrobaeza** [comment]
That screenshot is not from web_responsive
