### ISSUE TITLE
[13.0] web_responsive does not have keyboard shortcuts

### ISSUE THREAD

**Issue by MrTango** [OCA/web#1582]
In the default theme, when i press the ALT-Key many menu actions have an overlay with keyboard shortcut. As soon as i install the web_responsive addon this does not work anymore. I don't know if that was ever supported with this addon, but it would be nice if that would work.

**Comment by pedrobaeza** [comment]
The combination keys have been changed to Alt+Shift for not collapsing with standard browser shortcuts. Please see the README.

**Comment by MrTango** [comment]
thx for the hint, works, sorry for the noise ;)
