### ISSUE TITLE
[BUG][13.0] web_m2x_options in tree view (O2M)

### ISSUE THREAD

**Issue by acsonefho** [OCA/web#1586]
**Bug:**
Into O2M editable tree views, Odoo let the user to display/hide some columns (ex: into sale order about `order_line`). When this module is installed, some fields doesn't trigger anything (the field still ticked, and nothing happens);

**How to reproduce:**
- Install fresh DB with `sale` module (with demo data to have some examples);
 `click-odoo-initdb -c odoo.cfg --new-database odoo-test -m sale_management --no-cache`
- Go on sale order form view and try to hide/display some `order_line`'s column (it should work);
- Now install the `web_m2x_options` module;
- Go back to sale order form view and try to do the same (it works on some column but not all of them);

In some case I also have this JS traceback:
```
Traceback:
TypeError: Cannot read property 'offsetParent' of null
    at https://odoo.dev/web/static/src/js/views/list/list_editable_renderer.js:573:20
    at Array.forEach (<anonymous>)
    at Class._computeDefaultWidths (https://odoo.dev/web/static/src/js/views/list/list_editable_renderer.js:571:22)
    at Class._freezeColumnWidths (https://odoo.dev/web/static/src/js/views/list/list_editable_renderer.js:673:18)
    at https://odoo.dev/web/static/src/js/views/list/list_editable_renderer.js:1226:22
```

**Comment by acsonefho** [comment]
@bodedra @hbrunn @Yajo if you have an idea about this bug?
Thank you :)

**Comment by yajo** [comment]
No idea for now sorry...

**Comment by acsonefho** [comment]
Seems fixed with an Odoo update :)
