### ISSUE TITLE
web_responsive - 13.0.2.0.1

### ISSUE THREAD

**Issue by icf20** [OCA/web#1593]
for some odd reason odoo is pushing update notification for the version stated above yet there is no release to be found on the download section https://odoo-community.org/shop/product/web-responsive-2681

**Comment by pedrobaeza** [comment]
Just do `git clone` instead of downloading this (or download from GitHub the module). Probably OCA apps store is not updated yet as it creates a mirror. Any way, not an issue to be handled here.

**Comment by icf20** [comment]
>  Any way, not an issue to be handled here.

@pedrobaeza  where i should report this?

**Comment by pedrobaeza** [comment]
You can put an email to support@odoo-community.org
