### ISSUE TITLE
[12.0] Date input autocomplete overlaps with datepicker

### ISSUE THREAD

**Issue by enricostano** [OCA/web#1596]
![2020-04-28-100407_1920x1080_scrot](https://user-images.githubusercontent.com/748971/80462843-9d17a300-8937-11ea-8cba-7d701e75aab0.png)

Hi, how do you manage this issue? It only happens in Chrome, not in Firefox.

I can create a module to add something similar to the following code:
```js
$('.o_datepicker_input').on('click', function(e) {
  e.preventDefault();
  $(this).attr("autocomplete", "off");
});
```
But I'm just wondering if there is a better solution.

Also, not sure if I should also open an issue to https://github.com/odoo/odoo

Thanks!

**Comment by pedrobaeza** [comment]
This doesn't belong here, but odoo/odoo (it's not something of any modules of this repository). Any way, this has been notified previously there, and there's no solution except disabling Chrome auto-complete. The problem is that disabling it in Odoo has more side effects than benefits AFAIK.

**Comment by ohplz** [comment]
> ![2020-04-28-100407_1920x1080_scrot](https://user-images.githubusercontent.com/748971/80462843-9d17a300-8937-11ea-8cba-7d701e75aab0.png)
> 
> Hi, how do you manage this issue? It only happens in Chrome, not in Firefox.
> 
> I can create a module to add something similar to the following code:
> 
> ```js
> $('.o_datepicker_input').on('click', function(e) {
>   e.preventDefault();
>   $(this).attr("autocomplete", "off");
> });
> ```
> 
> But I'm just wondering if there is a better solution.
> 
> Also, not sure if I should also open an issue to https://github.com/odoo/odoo
> 
> Thanks!

where do u added this code at ?
got same issue here. thx!
