### ISSUE TITLE
[13.0] ability to paste a list of values in the search bar

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/web#1615]
We've heard various times this requirements. We have a list of product codes / customers / whatever in an XLSX / CSV that we want to search for in odoo. We'd like to paste the value into the search bar, and the list would be parsed into "OR" values.

What do you think?

**Comment by pedrobaeza** [comment]
Not sure if this should be a direct option in the search bar or through a new operator in the custom search dropdown.
