### ISSUE TITLE
[11.0] web_widget_x2many_2d_matrix doesn't work well with mobile browsers

### ISSUE THREAD

**Issue by ronozoro** [OCA/web#1617]
Hi OCA,
I'm successfully using the web_widget_x2many_2d_matrix widget in a couple of models and views . Working nicely

--Thank you!

Currently I'm facing problem with opening the widget from mobile i got this error 

web.assets_backend.js:5189 Uncaught TypeError: Cannot read property 'type' of undefined

This happen on the init_matrix function while checking the type of x and y and from mobile they are always Undefiend

The error happen when i try to open the form view of timesheet (hr_timesheet_timesheet module by OCA) 

--Kind regards

**Comment by pedrobaeza** [comment]
Yes, the widget is not adapted for mobile, as it's not easy how to show it. As this is a known issue, let's close this. PRs are welcome that adds this feature.
