### ISSUE TITLE
[13.0] [web_responsive] Sticky header in list tree view works bad on iOS Chrome 83 and Safari

### ISSUE THREAD

**Issue by vbezl** [OCA/web#1626]
Hi there,

Just installed Odoo 13 and web_responsive (latest commits).
Header sticks, but does not remain sticky (slides down for some reason) - see screencast attached.
This is only on iOS:
iOS Chrome 83
iOS Safari

Android Chrome - works.

![ezgif com-crop](https://user-images.githubusercontent.com/6523179/85677423-33660c00-b6d0-11ea-8571-c060d51781b7.gif)

**Comment by pedrobaeza** [comment]
I think this is a problem of the browser itself, isn't it, @Tardo?

**Comment by Tardo** [comment]
@pedrobaeza I can't reproduce this issue (i don't have the software). So... maybe add this issue in the roadmap? And yes, appears to be a problem in how Safari handles the 'sticky' positions.

**Comment by pedrobaeza** [comment]
Added to the roadmap

**Comment by kos94ok-3D** [comment]
@Tardo  Is https://github.com/OCA/web/pull/1082 need yet?
this PR broke the sticky header on the IOS
