### ISSUE TITLE
[12.0] Notification duplicated

### ISSUE THREAD

**Issue by onmywaytoheaven** [OCA/web#1632]
Hi!
First of all, thanks for your work.

I have some problems with the web_notify module. Idk why, but i got all notification twice. 
I already reinstalled the module, but that did not help.

I cannot reproduce it in runbot for obvious reasons

![изображение](https://user-images.githubusercontent.com/43062804/87045360-78299100-c200-11ea-864c-68bf8822b618.png)

**Comment by onmywaytoheaven** [comment]
P.S. I have Odoo 12 installation

**Comment by simahawk** [comment]
@onmywaytoheaven thanks for reporting. Can you provide more details?
web_notify is a technical module which can be used by other modules to display notifications. 
What's your context? What are you doing to get there?

**Comment by onmywaytoheaven** [comment]
Well, im calling web_notify methods from my custom module (logic is pretty simple - loop in users and call). At first i was thinking, that i got some bugs in my module which lead to duplication. But no - even if i call for example `user.nofity_success()` from odoo-cli i got notification twice. 

I have just install web_notify on clean odoo12 instance - and its ok. Got only one notification. Then, its probably something wrong with my production server.
