### ISSUE TITLE
web_company_color fails with SVG logo

### ISSUE THREAD

**Issue by kenayagi** [OCA/web#1641]
The web_company_color module throws an error when a SVG logo image is uploaded:

```
Odoo Server Error
[...]
  File "/usr/local/lib/python3.7/dist-packages/PIL/Image.py", line 2822, in open
    raise IOError("cannot identify image file %r" % (filename if filename else fp))
OSError: cannot identify image file <_io.BytesIO object at 0x7fa79610c6d0>
```

**Comment by simahawk** [comment]
It's not web_company_color. It's PIL (the python lib for images) that does not support SVG.
You'd need an extra implementation to handle them. Just convert it to PNG and upload again.
You could add this info to known issues here https://github.com/OCA/web/tree/13.0/web_company_color#id2
