### ISSUE TITLE
[13.0][web_responsive] [BUG] Display icon menu

### ISSUE THREAD

**Issue by tutula1** [OCA/web#1643]
I use macbook without the problem below, but when running odoo on windowns there is an error as below

![image](https://user-images.githubusercontent.com/12744580/87894377-c0e91180-ca6c-11ea-9566-d77ddba58148.png)

**Comment by pedrobaeza** [comment]
That's not `web_responsive`, but other module (maybe on top of it), but you must put the issue on the other place (or use vanilla `web_responsive`).

**Comment by tutula1** [comment]
Srorry, @pedrobaeza 
![image](https://user-images.githubusercontent.com/12744580/87911970-b3488180-ca96-11ea-918c-10741fd78878.png)
On macbook
![image](https://user-images.githubusercontent.com/12744580/87912041-d410d700-ca96-11ea-99e4-035c19f83ef6.png)
On windows
![image](https://user-images.githubusercontent.com/12744580/87912061-e1c65c80-ca96-11ea-98a1-e5d994ff8bfd.png)

**Comment by pedrobaeza** [comment]
But that colors are not web_responsive ones, so you have altered somehow the module...

**Comment by tutula1** [comment]
@pedrobaeza I have uninstall other module web_responsive, now only module web_responsive

**Comment by pedrobaeza** [comment]
And why it appears in green? Please try to reproduce your problem in the "Try me on runbot" button of the README. You are also not even saying which Odoo version.

**Comment by tutula1** [comment]
![image](https://user-images.githubusercontent.com/12744580/87913951-1ee01e00-ca9a-11ea-99db-6f860d83db86.png)
I install module https://github.com/OCA/web/tree/13.0/web_company_color

**Comment by tutula1** [comment]
@pedrobaeza 
On macbook
![image](https://user-images.githubusercontent.com/12744580/87915702-b181bc80-ca9c-11ea-9c4c-9eebbc918ca6.png)
On PC windows
![image](https://user-images.githubusercontent.com/12744580/87915829-d6762f80-ca9c-11ea-804f-6f7730d01953.png)

**Comment by pedrobaeza** [comment]
Which browser? You should remove the other module for being sure no interference is happening.

**Comment by tutula1** [comment]
http://3430951-13-0-f43e73.runbot1-2.odoo-community.org/
I use Chrome for Macbook and PC Win

**Comment by pedrobaeza** [comment]
@Tardo do you consider this a thing?

**Comment by Tardo** [comment]
I can't reproduce it on windows + chrome 83 + http://3430951-13-0-f43e73.runbot1-2.odoo-community.org/

**Comment by tutula1** [comment]
@Tardo 
On Windows + chrome
![image](https://user-images.githubusercontent.com/12744580/88004525-61086e80-cb31-11ea-9129-50efd7433ba8.png)
On Macbook
![image](https://user-images.githubusercontent.com/12744580/88004557-74b3d500-cb31-11ea-9fd8-1be43d5f7b33.png)

**Comment by tutula1** [comment]
My friend's Windows PC doesn't have this error
