### ISSUE TITLE
Show image in m2o dropdown

### ISSUE THREAD

**Issue by sudhir-erpharbor** [OCA/web#1644]
I am wondering if is there any way / module to show image in the m2o dropdown field?

Ex: Showing flags in res.country m2o field or showing product image in product m2o.

With the name_get method we can alter the text but what about showing image as well?

**Comment by hoangtrann** [comment]
there is a new widget in odoo 14 which provides similar feature as describe above [PR](https://github.com/odoo/odoo/pull/50789). But this widget will render the avatar on read-mode but not in the edit mode nor in m2o dropdown

**Comment by sudhir-erpharbor** [comment]
Thanks for the update. I was able to develop a module in v10 to v12 having this feature. The module will work with m2o field of any object having binary field with the name "image".

**Comment by eLBati** [comment]
> Thanks for the update. I was able to develop a module in v10 to v12 having this feature. The module will work with m2o field of any object having binary field with the name "image".

Hi @sudhir-erpharbor did you publish it somewhere?
Thanks!

**Comment by sudhir-erpharbor** [comment]
> > Thanks for the update. I was able to develop a module in v10 to v12 having this feature. The module will work with m2o field of any object having binary field with the name "image".
> 
> Hi @sudhir-erpharbor did you publish it somewhere? Thanks!

@eLBati It is published on app-store.
https://apps.odoo.com/apps/modules/15.0/ehcs_m2o_dropdown_image/
