### ISSUE TITLE
[13][web_responsive]Unable to display icon

### ISSUE THREAD

**Issue by sevate** [OCA/web#1656]
[Ubuntu 20.04] Custom module path is../odoo/custom_addons/.. 
[Issue] Unable to display icon.png image located in ../static/description/
[Question] Should custom module be located only inside ../odoo/Addons default module location for icons to display in web_responsive UI

image attached
![webresp](https://user-images.githubusercontent.com/16322142/89672123-d762ea00-d901-11ea-8287-1df8f47725c8.jpg)

**Comment by pedrobaeza** [comment]
The problem is not with web_responsive not addons path, but the way you have declared the icon in the menu entry.

Please check how is done in other addons.
