### ISSUE TITLE
[8.0] web_advanced_search_x2x - Javascript error

### ISSUE THREAD

**Issue by rafaelbn** [OCA/web#166]
module: web_advanced_search_x2x
version: 8.0

**Steps to reproduce**
- Install project module
- Go to project -> tasks
- Unfold advanced search
- Select "stage" field
- click on the down arrow

**Current behavior**

The following client error appears:

`Uncaught Error: NameError: name 'project_id' is not defined`

**Expected behavior**

The drop-down appears allowing to select the stage

**Comment by rafaelbn** [comment]
cc @hbrunn

**Comment by rafaelbn** [comment]
Hi, any ideas to solve this issue? Thanks
cc @antespi

**Comment by hbrunn** [comment]
@rafaelbn please turn on debug mode and post the js backtrace of this problem. I assume the addon should evaluate a context or domain here while it doesn't.

**Comment by rafaelbn** [comment]
Hi @hbrunn ,

Message is : https://runbot-saas.antiun.net/web/static/lib/py.js/lib/py.js:370

Any clue?

Thanks

**Comment by rafaelbn** [comment]
Sorry I didn't see fix... I'm going to test it. thanks!

**Comment by rafaelbn** [comment]
Solved in https://github.com/OCA/web/pull/253
