### ISSUE TITLE
[12.0][web_notify] bus_notification hit twice

### ISSUE THREAD

**Issue by AdBotha** [OCA/web#1661]
**Description**: When calling the method to notify any user. The bus_notification method is hit twice. This results in two notifications being displayed for the user. See below:
![notify_twice](https://user-images.githubusercontent.com/51331509/90242111-b2540700-de2c-11ea-95cf-6359e74b2309.png)

**Comment by hoangtrann** [comment]
Can you provide more details about the issue,  how you are using it and could you re-produce the issue on [runbot](http://3434983-12-0-bd3f72.runbot1-2.odoo-community.org/web/login?db=3434983-12-0-bd3f72-all&login=admin&redirect=/web?debug=1) ?

**Comment by AdBotha** [comment]
Could not get it going on runbot, but got it going on local. Seems like it was another web_client inherit that cause the issue. No double push notification. Closing.
