### ISSUE TITLE
[BUG] Filter partner added message last x days

### ISSUE THREAD

**Issue by source-promo** [OCA/web#1669]
Hi,
I noticed that if I am trying to filter e.g. all partner where a message was added e.g. today its not working properly.
I have no idea what result it does return, but its defintely does not retun the expected records. If I am combining this filter with another AND filter condition I expect to either return less records or the same amount or records but I think its NOT possible having a filter with AND and returning more records than with a single filter condition (this is the behavior I am expeting for OR filter)

Please check this video:
https://share.vidyard.com/watch/oiNKyJVmy49isTDPJTHqKk?

As you can see I filter for all records with a message created today. Result is 38 records which is fine
Now once I add an additional AND condition to ensure its customers only I expect to return 38 records or less. But the result is 43 records instead.

I have seen similar behavior for the filtering of message created date before and I really dont trust this filter anymore and I believe there is some issue!

I hope somebody can help with this! Thanks in advance!

**Comment by pedrobaeza** [comment]
Which module in this repo? Which version?

**Comment by source-promo** [comment]
@pedrobaeza  Sorry! It is Advanced search v. 12.0.1.1.0

Also after some testing I believe this is a general bug with all search in one2many fields.
I have the same / similar issue using this module and searching for all contacts with an opportunity created e.g. within last 2 month.

**Comment by pedrobaeza** [comment]
The problem is not with the module, but with Odoo itself and its way of processing domains. Probably fixed in upper versions.

**Comment by source-promo** [comment]
@pedrobaeza can you please specifiy in more details what the issue exactly is?
So if its Odoo code I would like to understand in which scenario this is caused (when I can trust the search an when not).
Also is there any Odoo bug ticket open?

**Comment by pedrobaeza** [comment]
I didn't remember the details, but it seems it's such problem. My colleague @Tardo investigated about it, but he's on holidays.

**Comment by source-promo** [comment]
@Tardo can you help me with this issue?

**Comment by source-promo** [comment]
@pedrobaeza Do you know if @Tardo is still on holidays? It would be great to get this information.

**Comment by pedrobaeza** [comment]
No, he's not, but he's busy and this a best effort thing.

**Comment by chrizzTs** [comment]
@Tardo can you help on this?

**Comment by Tardo** [comment]
@chrizzTs can you reproduce it on runbot?
