### ISSUE TITLE
web_ckeditor4 -- missing usage note. How to enable and configure to use this module in Odoo 10.

### ISSUE THREAD

**Issue by Mist3** [OCA/web#1673]
Hi, 

The usage information section  at module page (https://apps.odoo.com/apps/modules/10.0/web_ckeditor4/ ) is for sure for people who like puzzles and sandboxes ;-). 

Unfortunately I am not the case - can someone, please, provide me with step by step instruction how to install, enable and configure the web_ckeeditor4 for Odoo 10.0? I would like to replace summernote with this module.

**Comment by pedrobaeza** [comment]
It's just install and enjoy that editor instead of the summernote one.

**Comment by Mist3** [comment]
> It's just install and enjoy that editor instead of the summernote one.

In my case I had to edit view by adding widget="text_ckeditor4" (as wrote in ODOO 8 instruction). Even if you only need to install extension and use it, it should be clearly written in the documentation.

**Comment by pedrobaeza** [comment]
Uhm, that sounds weird, as it was enabled by default if I don't remember bad. @hbrunn
