### ISSUE TITLE
Update of a record in a tree inside a form trigger reload of the form resetting current record position

### ISSUE THREAD

**Issue by sergiocorato** [OCA/web#1679]
The page of stock moves inside the out is reset to first, instead of remaining where the user is workig, see:

![wh_out](https://user-images.githubusercontent.com/7657311/92590376-6619ac80-f29c-11ea-830c-de05d09535e6.gif)

Is there a way to remove this behavior? Probably it happens everywhere.

**Comment by sergiocorato** [comment]
moved to https://github.com/OCA/OCB/issues/943

**Comment by legalsylvain** [comment]
moved to https://github.com/odoo/odoo/issues/57353 ;-)

**Comment by sergiocorato** [comment]
thanks! (yeah, I put it wrong to raise some attention ;D )
