### ISSUE TITLE
[13.0][web_widget_x2many_2d_matrix] field_label_x_axis & field_label_y_axis not used.

### ISSUE THREAD

**Issue by adamwojt** [OCA/web#1680]
Came across this issue and I am not entirely sure if this is behaviour that was planned for label option.

### To replicate

1. Create matrix with `field_label_x_axis` or `field_label_y_axis`, pointing to Char field.
2. Fill computed or not computed Char field with desired label text.
3. Make sure it's present in tree, example:

**_XML_** 

```xml
<field 
    name="line_ids" 
    widget="x2many_2d_matrix" 
    field_x_axis="product_id"
    field_y_axis="partner_id"
    field_label_x_axis="product_matrix_label"
    field_value="amount_received"
>

    <tree>
        <field name="partner_id"/>
        <field name="product_id"/>
        <field name="amount_received"/>
        <field name="product_matrix_label"/>
    </tree>
</field>
```

**_PYTHON_**
```python
#... on `line_ids` model
    product_matrix_label = fields.Char(compute="_compute_product_matrix_label")

    @api.depends("product_id")
    def _compute_product_matrix_label(self):
        for line in self:
            line.product_matrix_label = (
                f"{line.product_id.name} {_('Received')} (kg)"
                if line.product_id
                else "Total (kg)"
            )
#...
```

### Behaviour:

Label field is not getting used by matrix. In above example, product name will be used instead and if it's empty `Product` will be displayed. 

Please note that I tried non-computed field for label that I filled with text manually and same thing happens.

### Desired Behaviour:

Display label field text instead.

### Possible causes:
Not JS expert but apart from `init_params`, label fields are not present anywhere else...
![image](https://user-images.githubusercontent.com/45100954/92709897-fcfb6d00-f35f-11ea-9749-b18937b17495.png)

**Comment by adamwojt** [comment]
I did [fix](https://github.com/versada/web/commit/55dc19f3b5787c2504a1aeef03007dc384b9ca71) as part of feature for one of our customers. It works but given I am not JS expert - it might not be best fix. 
https://github.com/versada/web/tree/13.0-fix-web_widget_x2many_2d_matrix-label-field

**Comment by simahawk** [comment]
@adamwojt tnx for reporting. Could you open a PR?
