### ISSUE TITLE
Can`t preview * .pdf

### ISSUE THREAD

**Issue by digitalliuzg** [OCA/web#1701]
worker_loader.js:71 Refused to execute script from 'http://localhost:8269/web/static/lib/pdfjs/src/shared/util.js' because its MIME type ('text/plain') is not executable.
(anonymous) @ worker_loader.js:71
worker_loader.js:71 Uncaught DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'http://localhost:8269/web/static/lib/pdfjs/src/shared/util.js' failed to load.
    at http://localhost:8269/web/static/lib/pdfjs/src/worker_loader.js:71:5

**Comment by legalsylvain** [comment]
Hi. Could you be more precise ?
- version used, and ee / ce ?
- wich oca modules are you using ?
- step to reproduce on runbot instance ?
Thanks !

**Comment by digitalliuzg** [comment]
odoo 12,13  community and enterprises on odoo/odoo/addons/web on Google Chrome and FireFox 
![image](https://user-images.githubusercontent.com/11321237/95804813-56c3ce00-0d36-11eb-821c-b44e3c1dfbd6.png)
![image](https://user-images.githubusercontent.com/11321237/95804904-9d192d00-0d36-11eb-9ad3-45b5ffb41a69.png)
![image](https://user-images.githubusercontent.com/11321237/95804983-d356ac80-0d36-11eb-992a-255b848beaf7.png)
![image](https://user-images.githubusercontent.com/11321237/95805005-e7021300-0d36-11eb-8c5c-347a7ef2ce37.png)
![image](https://user-images.githubusercontent.com/11321237/95805240-7b6c7580-0d37-11eb-9e9e-66ca8105f3ce.png)
![image](https://user-images.githubusercontent.com/11321237/95805317-b4a4e580-0d37-11eb-8e87-678a156e2677.png)

**Comment by pedrobaeza** [comment]
Sorry, but the module you mention doesn't belong to this repository. In any case, it seems your deployment problem, as that is working properly, and you can try it on runbot for seeing it.
