### ISSUE TITLE
[RFC] web_responsive: Visual differentiation on Send message/Log note

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/web#1715]
We all have performed any time the mistake of sending a message vs logging a note. It's not critical in one way, but it can be in the other.

One of our customers proposes to make a visual differentiation (maybe through colors). I'm not convinced of the effectiveness of this solution as our minds tend to discriminate this with the time.

But what do you think?

**Comment by flotho** [comment]
Hi @pedrobaeza , not critical actually but very usefull especially when you need to inform your colleagues

**Comment by pedrobaeza** [comment]
Already done
