### ISSUE TITLE
[13.0]: [web_responsive] : Not responsive

### ISSUE THREAD

**Issue by SalouaSahnoun** [OCA/web#1736]
- I can't select an activity in mobile mode
- I can't add product on sale order line
(see screenshots attached)
![activity](https://user-images.githubusercontent.com/49914567/99467868-92f2db80-293f-11eb-9c14-7d7ea25eab81.PNG)
![product](https://user-images.githubusercontent.com/49914567/99467877-99815300-293f-11eb-9393-996fbaac88e8.PNG)

**Comment by pedrobaeza** [comment]
I don't have any problem doing the same things. Have you tried on runbot clicking on the "Try me on runbot" button in the README?

**Comment by SalouaSahnoun** [comment]
yes it works on runbot but not on my odoo server ! should i update something or install any packages?

**Comment by pedrobaeza** [comment]
Then I'm afraid you have something incorrect in your end: outdated code, third-party addons that breaks this module or bad deployment, but nothing to do with the module itself, so closing.
