### ISSUE TITLE
[8.0] web_ckeditor4 javascript error in Webkit based navigators when saving

### ISSUE THREAD

**Issue by lefeverd** [OCA/web#176]
module: web_ckeditor4
version: 8.0

**Steps to reproduce**
- Open a record containing a text_html widget in a Webkit based navigator (Chrome, Safari)
- Edit, leave the value in the text_html empty
- Save

**Current behaviour**
It raises the following error:
TypeError: undefined is not an object (evaluating 'self.editor.name').

**Expected behaviour**
The record should be saved without errors

 /cc @StefanRijnhart

**Comment by StefanRijnhart** [comment]
@lefeverd can you test #186 and post your review? I have set it to Work-in-progress until I have your confirmation that this fixes the issue.
