### ISSUE TITLE
[13.0] Can't see all submenu for long submenu in web responsive 

### ISSUE THREAD

**Issue by hitrosol** [OCA/web#1783]
I would like to report that  condition after I installed the web_responsive and try to see the sub menu of the wms: Inventory --> Configuration --> Shopfloor --> Shopfloor mobile app. 

The submenus can't be displayed even hidden because it's too long.
![image](https://user-images.githubusercontent.com/5949936/105354848-bc700200-5c23-11eb-89cd-cdc75155c9cc.png)

**Comment by Tardo** [comment]
Thanks for report.

**Comment by pedrobaeza** [comment]
See #1785 for the fix. @Tardo don't forget to "link" the PR.
