### ISSUE TITLE
web_pwa_oca not installable on chrome if SVG pwa_icon is set

### ISSUE THREAD

**Issue by eLBati** [OCA/web#1789]
Steps:

 - Install web_pwa_oca
 - Set an SVG file in `pwa_icon` in `res.config.settings`

Google Chrome reports

![image](https://user-images.githubusercontent.com/1033131/105579495-64521080-5d87-11eb-9f66-6cc1eb8ef99b.png)

and the "add to home screen" banner does not appear.

By the way, about icons, `apple-touch-icon` should be configurable too.

**Comment by pedrobaeza** [comment]
That's very weird, as I'm using SVG icons for this without problem. Maybe the SVG itself is not reporting a default size in its content?

**Comment by eLBati** [comment]
Actually I don't know how to check this.
What requirements should the SVG follow to be correcly used in `web_pwa_oca`?

**Comment by pedrobaeza** [comment]
I generate/save them with Inkscape and have no problem.
