### ISSUE TITLE
web_advanced_search_x2x automatically excludes inactive records

### ISSUE THREAD

**Issue by clonedagain** [OCA/web#179]
If I use web_advanced_search_x2x for example in reporting>invoice analysis, to search for articles with certain features (for example a specific pricelist), it automatically also restricts to the active articles only.
Inactive articles are excluded and can't be re-included afterwards.
If want to include inactives, I must search for products with "my criteria AND (active=true OR active=false)".

It would be nicer to not exclude inactive records by default.

**Comment by hbrunn** [comment]
This is odoo's standard behavior, to change this, we'd have to put `{'active_test': False}` into the context by default. I dont think this is a good idea, because then we'd also see objects that are inactive for good reasons.

**Comment by clonedagain** [comment]
I'm not convinced it's right to accept and extend Odoo's default behavior in this case.
The behavior users expect is that the _main_ model is filtered on "Active=True", not the related models.
i.e. when a partner is inactive, you can still find it's related invoices.

The problem is that, as it is now, the implicit criteria "active=True" makes the "user experience" inconsistent.
For example:
- search for invoices in period X => finds results for all partners
- search for invoices in period X and partner "in selection (category = 'ABCD')" => finds results for only the active partners in the category ABCD

Would you be kind enough to reconsider your position?

**Comment by pedrobaeza** [comment]
I agree with @clonedagain about the reasoning on the feature, but I think that there's a technical problem to implement this correctly. @hbrunn, is this correct?

**Comment by hbrunn** [comment]
In most cases, it should be enough to put `active_test: False` in the context, analyze the current search domain if it contains the active field, the model if it has an active field, and finally add `('active', '=', True)` if all this checks go right.
But still, we'll run into subtle weirdnesses as described in https://github.com/odoo/odoo/issues/3939 - especially the explanation linked in the second last post.

I simply don't think there's a general way to exclude inactive records we actually don't want to see while including other active records we do want to see, and making this explicit doesn't seem like a big issue to me, so from my side, I won't invest time in addressing this. If somebody else will, I'll be happy to review.

**Comment by pedrobaeza** [comment]
Well, looking at the issue, this is only due to the child_of operator and the partner hierarchy implementation, which is not one of the allowed in the advanced search, so I still think that we can provide this facility in the module, and 99% of cases will be correctly treated.

**Comment by hbrunn** [comment]
wontfix for reasons stated above
