### ISSUE TITLE
[13.0] web_pivot_computed_measure error

### ISSUE THREAD

**Issue by manuelcalerosolis** [OCA/web#1813]
Testing this module, I get the following error.

![Peek 05-02-2021 11-31](https://user-images.githubusercontent.com/3088246/107023086-7039cb80-67a6-11eb-8bea-ee024066c135.gif)

**Comment by pedrobaeza** [comment]
Operation not valid for that measures, as it contains False values.

**Comment by pedrobaeza** [comment]
It's a question of data integrity. That shouldn't happen on a regular DB, and if so, you have to fix it.

**Comment by pedrobaeza** [comment]
Closing as no directly related to the module.
