### ISSUE TITLE
[12.0]PWA : 404 on service-worker.js

### ISSUE THREAD

**Issue by flotho** [OCA/web#1826]
Hi,

I have some strange logs when pwa module is available **but not installed** :
```
"GET /service-worker.js HTTP/1.1 - 404
```
Is it normal, it looks like it could cause some disconnection in the client side.

Thanks for your advice

**Comment by legalsylvain** [comment]
Looks weird. Did you tried to reproduce on runbot, uninstalling web_pwa module ?

**Comment by flotho** [comment]
Hi @legalsylvain , I faced the same logs in 14.0 even if the module is not installed :
![image](https://user-images.githubusercontent.com/1043935/182310618-3d48504b-6996-4acb-ae48-88d45fb632df.png)

from your point of view could it cause timeout issue for the longpolling process ? I have tab browser freezing after a few moments and no specifics logs except this.

Regards
