### ISSUE TITLE
installed module web_pwa_oca did not see any new menu on install pwa

### ISSUE THREAD

**Issue by robinhli** [OCA/web#1833]
I have odoo 13 run on my laptop, it can be accessed by my mobile at same wifi range.
I have setup the system parameters as described in readme.
I installed the module web_pwa_oca, but did not see any menu, and don't know how to install.

**Comment by pedrobaeza** [comment]
https://support.google.com/chrome/answer/9658361?co=GENIE.Platform%3DDesktop&hl=en
