### ISSUE TITLE
[BUG] 12.0 - web_responsive - Odoo Enterprise - Tree check box

### ISSUE THREAD

**Issue by mileo** [OCA/web#1837]
Hi,

I think that the last feature of web_responsive:

![image](https://user-images.githubusercontent.com/1975978/110012800-ac0d7580-7cff-11eb-812c-9d512edf8081.png)

Is not compatible with Odoo Enterprise:

![image](https://user-images.githubusercontent.com/1975978/110012861-c0ea0900-7cff-11eb-9950-1659bf922d1b.png)

**Comment by pedrobaeza** [comment]
`web_responsive` is per se incompatible with `web_enterprise`, so you mustn't install both together.

**Comment by legalsylvain** [comment]
So, it is possible to add an exclude key in the manifest, don't you think ?

**Comment by pedrobaeza** [comment]
Well, it was not excluded because there was some voices saying that they want both together anyway (or due to a weird dependency chain), but as said, we can't and should provide such compatibility. Anyway, if you are able to compatibilize both, a PR is welcome.
