### ISSUE TITLE
Implementing color picker in forms / calendar items

### ISSUE THREAD

**Issue by Yenthe666** [OCA/web#185]
Hi guys,

The module 'web_widget_color' is really great and cool. I was wondering if it would be possible to add support for (calendar) items in kanban view? There is currently nothing built that gives the ability to modify colors on calendar items and/or calendar users.
Give me some ideas / input and I will try to contribute. I personally need the ability to set colors on agenda items so I'll try to extend it in this module?

With kind regards,
Yenthe

**Comment by Yenthe666** [comment]
@ah-taktik, @OSguard and @pedrobaeza could you guys give input on this please? :+1: 
One of the things that I already tried in the popup for calendar items:

```
  <div t-name="CalendarView.quick_create" class="oe_calendar_quick_create openerp">

    <div class="form-group">
        <label for='name' class='control-label'>Event summary:</label>
    <input name='name' class="form-control"/>
        <!--This will show up but will not work and no color picker is showing up. -->
        <field name='color' widget="color" class="form-control"/>
    </div>     

    <t t-if="widget._buttons">
      <div class="oe_calendar_quick_create_buttons">
        <button class="openerp oe_button oe_highlight oe_calendar_quick_create_add ">Create event</button>
        <button class="oe_button oe_form_button oe_link oe_calendar_quick_create_edit" ><span>Edit Event <![CDATA[]]></span></button>
      </div>
    </t>
  </div>
```

But somehow the color picker is not even showing up.

**Comment by Yenthe666** [comment]
@dreispt a little ping to you too :blush:

**Comment by dreispt** [comment]
@Yenthe666 I'm sorry, I'm not familiar with that module.

**Comment by Yenthe666** [comment]
No problem @dreispt , it was just a wild attempt! If you know anybody feel free to drop them a ping. I'd love to build this and share it with OCA / the community.

**Comment by pedrobaeza** [comment]
For this, the widget should be modified for being registered in the calendar view, but it requires a bit of development.

**Comment by pedrobaeza** [comment]
I close this issue until further development.
