### ISSUE TITLE
web_responsive  ODOO 14

### ISSUE THREAD

**Issue by pgy866** [OCA/web#1852]
web_responsive
https://apps.odoo.com/apps/modules/14.0/sublime_web_responsive/
  You can download it here. Why doesn't GITHUB have the source code?
Haven't transplanted yet? thank you very much

**Comment by pedrobaeza** [comment]
That one has nothing to do with OCA. Check on pull requests about them one here.

**Comment by pgy866** [comment]
@pedrobaeza 
Thank you； 
seeing it write the project homepage as https://github.com/OCA/web,
I misunderstood
