### ISSUE TITLE
web_responsive 14.0 issue on safari 

### ISSUE THREAD

**Issue by robinhli** [OCA/web#1870]
odoo 14.0, web_responsive 14.0 installed.
browse on android chrome, no issue
browse on apple safari, can't display. pic as follows:

Error:

Traceback:
Error: The string did not match the expected pattern.

![image](https://user-images.githubusercontent.com/34515177/111903365-ece5e800-8a7c-11eb-8c05-6f786f4aa654.png)

**Comment by SplashS** [comment]
@robinhli Thank you for your feedback.
I've tested last 14.0 runbot on iOS Safari 14.4.1. Sorry, but I can't reproduce this problem.
Please give more details. The best case is to reproduce it on runbot. (Currently available here https://runbot.odoo-community.org/runbot/repo/github-com-oca-web-162).
It's interesting what you did to get this error, in which Odoo App it happened, what version of iOS do you have.
If you can't provide all of this information, please share the available information.
