### ISSUE TITLE
[12.0] web_pwa_oca - Won't be installable soon

### ISSUE THREAD

**Issue by llabusch93** [OCA/web#1872]
Hey guys,
chrome says in the logs that the pwa module will loose it's purpose soon:
Site cannot be installed: Page does not work offline. Starting in Chrome 93, the installability criteria is changing, and this site will not be installable. See https://goo.gle/improved-pwa-offline-detection for more information.
So I guess this module will not be doing anything useful after Chrome passes V93? Or is offline mode already in the making?

Cheerio,

**Comment by pedrobaeza** [comment]
There's still enough time until Chrome 93, but some kind of hack will be needed indeed.

**Comment by llabusch93** [comment]
This issue here is not stale it all, but becomes more urgent over time. We are on Chrome 94.0 already...

**Comment by pedrobaeza** [comment]
But it's working...

**Comment by llabusch93** [comment]
Mhhhhh true. So we wait until we get a report that it stopped working?

**Comment by pedrobaeza** [comment]
No, I'm closing it. If this ever doesn't work, anyone can open an issue again.
