### ISSUE TITLE
Can't start russian translation on weblate

### ISSUE THREAD

**Issue by SplashS** [OCA/web#1887]
I'm not sure about correct place for this issue.
I'm trying to start russian translation for web_responsive and I haven't permissions according to system message.
I did all suggestions from https://odoo-community.org/page/translate

**Comment by pedrobaeza** [comment]
Have you sent the email for asking for such permission?

**Comment by SplashS** [comment]
Yes. I've sent another email with more detailed request.
First letter I sent was in bot manner :)

**Comment by pedrobaeza** [comment]
Well, take into account that it's manually process by OCA's secretary, so it can take a bit. Anyway, I have used some remaining power I still have from my time in board for granting you already the permission in Weblate, so you don't have to wait!
