### ISSUE TITLE
web_pivot_computed_measure can't measure count

### ISSUE THREAD

**Issue by robinhli** [OCA/web#1888]
currently it seems it only support quantity measure. can it support measure on the count?

**Comment by pedrobaeza** [comment]
Count is not a "computed measure" coming from other measures. It should be included in the report itself.

**Comment by robinhli** [comment]
Yes. Count is there. I would like count can be used as a member to compute, such as I would like to compute 2* count, or some other quantity / count etc. 
Now, I can't select count to compute.
