### ISSUE TITLE
[12.0] [web_notify] Too many longpolling requests

### ISSUE THREAD

**Issue by sagar-bista** [OCA/web#1890]
We have one issue with the web_notify module. We are getting too many requests in odoo from the browser

**Current Behaviour**
Too many unnecessary longpolling requests called from browser.

**Expected Behaviour**
Only Necessary and required longpolling requests should be called.

Steps to Reproduced issue

1. Add in config
	> workers = 2 (Without worker issue will not reproduce)
2. Run odoo and create fresh database.
3. Install web_notify module
4. Open 5 to 7 tab in chrome browser (open any page of odoo in all tab)
5. Open developer window in each and every tab and go to the network window(Ctrl+Shift+I).

![inspect](https://user-images.githubusercontent.com/55094782/113612591-ac39c180-966d-11eb-96f1-b50142aa1cdd.png)
![network](https://user-images.githubusercontent.com/55094782/113612625-b78ced00-966d-11eb-80fa-9fa5913424ce.png)

6. Hard Refresh all chrome browser tab one by one quickly (Ctrl+Shift+R) 6 to 7 times.   
7. Check every tab one by one and check in network Requests you will get multiple longpolling requests from one tab.

Please Refer video for more info.

https://user-images.githubusercontent.com/55094782/113612863-0175d300-966e-11eb-9f48-6084630e0425.mp4

Info
Odoo vesion	        : 12.0 (Community or Enterprise Doesn't matter)
Module Version	: 12.0.1.0.1
Chrome Version	: 89.0.4389.90
python		        : Not version specific Python3.4+

Note: With or without nginx same issue will occurred.

I hope i have provided you sufficient info.

**Comment by DonFeraRRi** [comment]
Check longpolling port 8072 if it's open. 8072 is the longpolling port. Further you might also be facing bus.bus. or not?

**Comment by sagar-bista** [comment]
> Check longpolling port 8072 if it's open. 8072 is the longpolling port. Further you might also be facing bus.bus. or not?

Same issue has been occurred in local machine too. so it's doesn't matter 8072 port is open or closed.

**'Exception: bus.Bus unavailable'** Exception is there because we have configured worker=2 in odoo config and accessing via IP or localhost.
If we configure domain/nginx than **'Exception: bus.Bus unavailable'** Exception will not occur but longpolling issue is still there.

**Comment by jbaudoux** [comment]
https://github.com/odoo/odoo/pull/69067

**Comment by sagar-bista** [comment]
It's working 

REF: 
https://github.com/odoo/odoo/pull/69067/commits/2e532a301e4f75669e00e009ddb526d3373ff5dd

Thank you @jbaudoux
