### ISSUE TITLE
[13.0/14.0] web_responsive: Ctrl+click not opening in new tab

### ISSUE THREAD

**Issue by joao-p-marques** [OCA/web#1891]
In the app dashboard, `Ctrl+click` doesn't open in a new tab.

Tested in Firefox and Chromium.
Both `Right Click + "Open in new tab"` and `Click on mouse scroll wheel` work fine, but `Ctrl+click` opens the app in the current tab.

ping @pedrobaeza @Tardo

**Comment by pedrobaeza** [comment]
Maybe @SplashS can take a look, being the migrator of it.

**Comment by joao-p-marques** [comment]
Just confirmed it also happens to me in 13.0
@pedrobaeza do you have the same problem?

**Comment by pedrobaeza** [comment]
Oh, true! @Tardo then it's something about migration to 13.0 or later restyling. Can you check?

**Comment by Tardo** [comment]
This happens on all version i think... tested on 11.0 & 12.0 with same results.

Middle Click !== CTRL Click
- Middle Click (Hard mode) -> Is the same as context menu 'Open in a new tab'
- CTRL Click (Soft Mode) -> js code can change the behaviour

Other links in Odoo has the same behaviour.

**Comment by pedrobaeza** [comment]
OK. Do you think we should consider that or leave as it is now?

**Comment by Tardo** [comment]
Leave it as is. This happens because 'preventDefault' is called on the click event.

**Comment by pedrobaeza** [comment]
OK, let's live with this "restriction".
