### ISSUE TITLE
[14.0] web_drop_target  no longer refresh chatter after drop files

### ISSUE THREAD

**Issue by youring** [OCA/web#1901]
Current Behaviour
Drop files into form view, chatter not refreshed automatically, runbot [link](http://3476512-14-0-8137e3.runbot2-3.odoo-community.org/web/login)

Expected Behaviour
Chatter attachment reload after dropping files as previous version, works in v13 at least on [runbot](http://3477846-13-0-74fa01.runbot1.odoo-community.org/web/login)

Steps to Reproduced issue
For example, open a partner form view.
Drop a image to the form, no image show up in the chatter, you have to do a browser refresh or switch record forth and back.

**Comment by pedrobaeza** [comment]
For me it's working. Anyway, the idea is to completely remove such option, as Odoo already does it natively (dropping on "Adding files" once unfolded). As is, there's a hidden dependency `mail` that we should respect or drop as said.

cc @victoralmau

**Comment by youring** [comment]
Thanks for explanation.
Yes, it's working in the backend, but from UX/UI perspective, it's a degradation.
+1 for remove such option if it's conflict with native dropping.

**Comment by spadae22** [comment]
V14 native dropping is not working in v14, at least now how v8 using - https://github.com/leblanc-simon/odoo-attachment-dragdrop.git attachment_dragdrop

"as Odoo already does it natively (dropping on "Adding files" once unfolded)"  what does unfolded mean?

If  I drop a PDF on a Vendor view, the PDF just opens in Chrome. I can add to Documents that apply to the contact, but that is the long way around. 
TX,
ER

**Comment by pedrobaeza** [comment]
You have to drop it on the attachment area.

**Comment by spadae22** [comment]
@pedrobaeza Thanks!
