### ISSUE TITLE
[12.0] web_responsive on Safari: ListView thead will not sticky when scrolling

### ISSUE THREAD

**Issue by mardisiaw** [OCA/web#1902]
When browse using Safari, ListView thead (table header) will not sticky when vertical scrolling.

To Fixed: (file web_responsive/static/src/css/web_responsive.scss)
delete line 607
  position: sticky;

and add:
.o_list_view thead {
  position: sticky;
}

**Comment by kos94ok-3D** [comment]
Relate to: https://github.com/OCA/web/issues/1626

**Comment by metalmonkey69** [comment]
> When browse using Safari, ListView thead (table header) will not sticky when vertical scrolling.
> 
> To Fixed: (file web_responsive/static/src/css/web_responsive.scss)
> delete line 607
> position: sticky;
> 
> and add:
> .o_list_view thead {
> position: sticky;
> }

Tested with this fix and confirmed working on IOS chrome and Android chrome
