### ISSUE TITLE
[13.0] web_disable_export_group: The Export All button should be disable.

### ISSUE THREAD

**Issue by HirenDangar** [OCA/web#1907]
![Screenshot from 2021-04-28 19-04-58](https://user-images.githubusercontent.com/16575953/116415612-36350e80-a857-11eb-89a5-752e8eb0c766.png)
**Steps**:

- Install the **web_disable_export_group** module.
- Uncheck the **Export Button**  security access for user.

**Current behavior:**

- The user is not able able to export but having access for **Export all** record on the Top-up button.

**Expected behavior:**

- On the uncheck the **Export Button** user should not able to access the **Export all** button too. The **Export all** button should be disable or hide.

![Screenshot from 2021-04-28 19-04-42](https://user-images.githubusercontent.com/16575953/116415685-44832a80-a857-11eb-8e1e-aae82675ff3b.png)

![Screenshot from 2021-04-28 19-04-58](https://user-images.githubusercontent.com/16575953/116415706-48af4800-a857-11eb-9c0c-acad8f6fdf77.png)

**Comment by pedrobaeza** [comment]
Yes, it's a missing feature. Are you adding such feature in a PR?

Take into account that it's very easy for an average user to copy/paste things from the browser, so it's like putting fences to an open field, but anyways...

**Comment by Dangar-Serpentcs** [comment]
Pull request:- #1908

**Comment by pedrobaeza** [comment]
Solved in #1975
