### ISSUE TITLE
web_environment_ribbon, hides menu bar 

### ISSUE THREAD

**Issue by bealdav** [OCA/web#191]
Thanks for you nice work on it, but.

module: web_environment_ribbon
version: 8.0
current firefox 

**Steps to reproduce**
- install the module

**Current behavior**
The ribbon hides the menu bar

**Expected behavior**
Could you add a margin-top, please

**Comment by pedrobaeza** [comment]
In my tests I haven't had any special problem clicking on the parts I want. It's right that the ribbon makes impossible to click what is behind it, but as the ribbon itself is thin, it doesn't hide completely any element. Maybe this behaviour changes across browsers?
