### ISSUE TITLE
[RFC] web_responsive: Change behavior of html widget

### ISSUE THREAD

**Issue by etobella** [OCA/web#1919]
When using the html widget, it is hard to manage it as a second scroll bar is created if the data inside the widget is big enough, as you can see:
![old_behaviour](https://user-images.githubusercontent.com/28590170/117119541-84d03480-ad92-11eb-8b34-644569a9c9f3.gif)

We could make the widget overflow like this:

![new_behavior](https://user-images.githubusercontent.com/28590170/117119526-7da92680-ad92-11eb-941f-e1c98b983a48.gif)

the code necessary to do this is small, and we can make it work with options if needed.

One option was to create a specific module, but as we are talking of only 13 lines of JS I think we could insert it inside `web_responsive`

@Yajo @pedrobaeza @OCA/web-maintainers

**Comment by etobella** [comment]
The necessary code to make this happen with options was:
```javascript
odoo.define("my_demo_module.fields", function(require) {
    "use strict";
    var backend = require("web_editor.backend");
    backend.FieldTextHtmlSimple.include({
        _getSummernoteConfig: function() {
            var result = this._super.apply(this, arguments);
            if (this.nodeOptions.automatic_summernote_height) {
                result.height = undefined;
            }
            return result;
        },
    });
});
```

**Comment by pedrobaeza** [comment]
@Tardo @SplashS what do you think about this?

**Comment by Tardo** [comment]
I think this will make other views more cumbersome to manage. Other modules can place fields after another field that uses this widget.

Would it be possible to disable the scroll action of elements inside the "main" container that are not active (no focus)?

**Comment by etobella** [comment]
> I think this will make other views more cumbersome to manage. Other modules can place fields after another field that uses this widget.

Well, it will change the size according to the size of each field if it is bigger than the minimum px, The size is independent for each one. Right now it is harder to read all in this case, as you need to click on each field and start scrolling.

> Would it be possible to disable the scroll action of elements inside the "main" container that are not active (no focus)?

I am not sure, as the widget is generated on the start, not when clicking.

However, changing the behavior can be somehow crazy. If you have two HTML fields big enough, you will need to click on the first to read it all (the scroll is working only when clicking, but the new behavior will be making it big). When you start reading the second field, everything will be resized, I don't know if this is the expected behavior :disappointed:

**Comment by SplashS** [comment]
I think we can make suggested by @etobella behavior only for mobile. In this case fields will be placed in one column and there will not be reordering of fields on size change.
On desktop current behavior seems to be acceptable to me.

**Comment by etobella** [comment]
Well, in this case, it would be interesting to allow to apply the behavior using an option, it can be interesting in some cases (at least for me :wink: )

**Comment by etobella** [comment]
I will make a small PR with it then :tada:

**Comment by yajo** [comment]
According to last conversation in #1921, I close.
