### ISSUE TITLE
[12.0] requirement.txt  problem

### ISSUE THREAD

**Issue by matteoopenf** [OCA/web#1928]
Hi There,

This requirement on odoo.sh create a problem, because not allow install the properly version of matplotlib
https://github.com/OCA/web/blob/d49286056f7dde911a4d4e56766e56465813d526/requirements.txt#L6
https://github.com/OCA/web/blob/d49286056f7dde911a4d4e56766e56465813d526/requirements.txt#L7

I propose move the version of requirement on manifest of the module that need this requirement

12.0: https://github.com/OCA/web/pull/1930

**Comment by yajo** [comment]
OK, go ahead.

**Comment by matteoopenf** [comment]
> OK, go ahead.

will you do the revert?

**Comment by matteoopenf** [comment]
HI @Yajo , if you want I do the pull request you should said me the specific version for each module otherwise I will remove only matploit on requirement.txt

**Comment by matteoopenf** [comment]
Hi @Yajo, i update the post with the pull request

**Comment by pedrobaeza** [comment]
Removing the requirement is not correct. The solution should be another. You are not even specifying which is the problem/error you get.

**Comment by matteoopenf** [comment]
> Removing the requirement is not correct. The solution should be another. You are not even specifying which is the problem/error you get.

Odoo.sh when you add the repository try to install both requirement and the build failed

**Comment by pedrobaeza** [comment]
That's a problem of Odoo.sh, that should be reported and fixed there, not here.

**Comment by matteoopenf** [comment]
> That's a problem of Odoo.sh, that should be reported and fixed there, not here.

@pedrobaeza  I think is  a problem all for the people use the same file in continus integration and continus delivery, If you agree I move the requirment in the module  web_widget_mpld3_chart

**Comment by pedrobaeza** [comment]
`requirements.txt` is needed for the whole repository. You can't move such thing to a module. As said, the error is on Odoo.sh, that is not able to parse correctly the file according to what you are saying, so you must report the problem to that platform, not to break the rest of the things outside Odoo.sh for making it work to you.

**Comment by matteoopenf** [comment]
I will open a ticket to Odoo Sa, anyway we can leave the requirement and specific the version on manifest of the module.
In this way I keep the requirement and user read the exact version from manifest of module.
Do you agree?

**Comment by pedrobaeza** [comment]
No, that's not possible. That doesn't work. We need the same as you to be in the requirements.txt file, not in the manifest. In fact, in v12, the `external_dependencies` manifest key is not allowing pip requirements specification.
