### ISSUE TITLE
[12] [13] web_responsive show icons in one column

### ISSUE THREAD

**Issue by fgarcia-humanoide** [OCA/web#1938]
[12] [13] web_responsive show icons in one column

![respons](https://user-images.githubusercontent.com/7599709/120211554-575f9500-c231-11eb-998c-cfc89dff687e.JPG)

**Comment by pedrobaeza** [comment]
That colors are not web_responsive, so something has been manipulated.

**Comment by fgarcia-humanoide** [comment]
Same result without legion enterprise theme. Yesterday it worked fine in more than 10 instalations, The problem started today.  Is it only my problem? Nobody else?

![Capturaadsfa](https://user-images.githubusercontent.com/7599709/120212711-9b06ce80-c232-11eb-884d-96ef4abaa1f6.JPG)

**Comment by pedrobaeza** [comment]
Start indicating browser version and OS at least.

**Comment by fgarcia-humanoide** [comment]
browser
Google Chrome está actualizado
Versión 91.0.4472.77 (Build oficial) (64 bits)

OS
Windows 10

The problem only appears in chrome , in firefox works fine.

**Comment by pedrobaeza** [comment]
Let's reopen for now.

**Comment by fgarcia-humanoide** [comment]
I am very ashamed

The problem was caused by a chrome extension called epub reader

After uninstalling it, the problem is solved.

Sorry
