### ISSUE TITLE
[13.0][BUG] web_responsive: History tab in Discuss module is always empty!

### ISSUE THREAD

**Issue by vbezl** [OCA/web#1939]
Hi everyone,

If you go to Discuss module and click on History tab - it is always empty (if you look on desktop - there is content present).

**Comment by pedrobaeza** [comment]
What do you mean with "desktop"? Please specify complete steps to reproduce the problem in OCA runbot.

**Comment by vbezl** [comment]
I mean if you browse from mobile device - it's empty (see attached). If you browse from non-mobile browser - it's ok.
![A976674C-73C5-4045-9EC7-A1A05C34453B](https://user-images.githubusercontent.com/6523179/120700986-082c9500-c4bb-11eb-8108-3f5e3acf8799.png)

**Comment by pedrobaeza** [comment]
Which browser and version? Try with another browser to see.

**Comment by vbezl** [comment]
I've tried on iOS safari and chrome  + Android Chrome.
I've just tested it on Odoo OCA runbot - check it out:
http://3484095-13-0-f7967a.runbot2-3.odoo-community.org/web#action=97&active_id=mailbox_history&cids=1&menu_id=79

<img width="1028" alt="Screen Shot 2021-06-03 at 11 32 56 PM" src="https://user-images.githubusercontent.com/6523179/120708459-45495500-c4c4-11eb-9511-6ffa48e4605b.png">

**Comment by pedrobaeza** [comment]
OK, I confirm the problem. It has other related problem:

![Peek 04-06-2021 08-25](https://user-images.githubusercontent.com/7165771/120755651-87978400-c50e-11eb-8667-b46055d5aeb0.gif)

When moving from desktop to mobile, the section is not correctly kept.
