### ISSUE TITLE
Exports current view 8 fails to export from sales order tree view in odoo 8

### ISSUE THREAD

**Issue by comansa** [OCA/web#1948]
When click over "Export current view",inorder to export the odoo 8.0 sales order tree view shown registers, got an error from browsers
Chrome
Odoo Error del cliente
Uncaught TypeError: Cannot read property 'value' of undefined
http://192.168.1.224:8069/web/static/src/js/view_list.js:2266

Safari
Odoo Error del cliente
TypeError: undefined is not an object (evaluating 'row_data[this.id].value')
http://192.168.1.224:8069/web/js/web.assets_backend/f0f8c4a:3497

Firefox
Odoo Error del cliente
TypeError: row_data[this.id] is undefined
http://192.168.1.224:8069/web/js/web.assets_backend/f0f8c4a:3497

I attach an screen capture of the module and the tree view on export fails.

![Error export_current_view](https://user-images.githubusercontent.com/30575681/121318190-50104980-c90b-11eb-904c-efde9152f5bb.png)
![Module export current view](https://user-images.githubusercontent.com/30575681/121318201-51417680-c90b-11eb-8d53-3cad9e41d12a.png)

**Comment by legalsylvain** [comment]
Hi. could you reproduce the problem on runbot ? 

thanks.
