### ISSUE TITLE
[14.0] options doesn't work as intended with Many2one field, if field is inside an element with class="oe_title"

### ISSUE THREAD

**Issue by ghost** [OCA/web#1953]
`options` attribute doesn't work as intended with Many2one field as a child of an element with `class="oe_title"`

Steps to reproduce:

Use a many2one field inside an element with `class="oe_title"` and add `options`, I used `no_open`  alone, then tried `no_create` as well. Both don't work.

<img width="576" alt="Screen Shot 2021-06-14 at 10 36 24 PM" src="https://user-images.githubusercontent.com/20691929/121956151-1010f280-cd61-11eb-8514-6108ef52971c.png">

https://user-images.githubusercontent.com/20691929/121959562-42bcea00-cd65-11eb-8154-ac2fce4074ee.mov

**Comment by pedrobaeza** [comment]
I'm afraid such options are not thought for any possible combination of HTML + widget. Only regular `<field>` declaration will work with them.

Closing as limitation of the views.

**Comment by ghost** [comment]
Thank you @pedrobaeza
