### ISSUE TITLE
[14.0] web_advanced_search Many2one selection on Filters missing

### ISSUE THREAD

**Issue by jeroenev** [OCA/web#1957]
Looks like they didn't migrate this part to Odoo14 because it wasn't super clear from the comment where it was used. https://github.com/OCA/web/pull/1909#issuecomment-828997442 

The functionality this enabled in v13 is to have a many2one dropdown when adding a filter for a many2one field.

**Comment by pedrobaeza** [comment]
cc @rven

**Comment by rven** [comment]
@pedrobaeza I know, we are working on it!

**Comment by pedrobaeza** [comment]
Thanks!

**Comment by rven** [comment]
@pedrobaeza The functionality is implemented.
It should be good that some Odoo javascript gurus (@Yajo) would check this implementation.

**Comment by jeroen7s** [comment]
Latest PR should add this functionality back for Odoo14

**Comment by pedrobaeza** [comment]
Closing this as #2003 has been opened.
