### ISSUE TITLE
Web Responsive

### ISSUE THREAD

**Issue by spadae22** [OCA/web#1960]
Loaded new db, mobile is fine, but deskop, if you click any app - Error:

Traceback:
TypeError: Cannot read property 'isMobile' of undefined
    at QWeb.eval (eval at _compile (http://34.231.110.183:8069/web/static/lib/owl/owl.js:1696:28), <anonymous>:20:53)
    at QWeb.fn (http://34.231.110.183:8069/web/static/lib/owl/owl.js:1567:45)
    at QWeb.render (http://34.231.110.183:8069/web/static/lib/owl/owl.js:1617:32)
    at Object.__owl__.renderFn (http://34.231.110.183:8069/web/static/src/js/model.js:482:20)
    at PatchableClass.__render (http://34.231.110.183:8069/web/static/lib/owl/owl.js:4411:37)
    at PatchableClass.__prepareAndRender (http://34.231.110.183:8069/web/static/lib/owl/owl.js:4399:22)

**Comment by legalsylvain** [comment]
could you reproduce the problem on runbot ?

**Comment by spadae22** [comment]
Is there a enterprise runbot?
ER
--







E.R. Spada II  owner  |   ***@***.*** ***@***.***>ugeconsulting.com  |  Direct.  518 365 7854 |  Fax.  518 459 7025
EUGE Consulting  | 107 Everett Road  |  Albany, New York 12205  |  http://www.e <http://www.digital-page.com/>ugeconsulting.com

CONFIDENTIALITY NOTICE: This e-mail message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential and privileged information.  Any unauthorized review, use, disclosure or distribution is prohibited.  If you are not the intended recipient, please contact the sender by reply e-mail and destroy all copies of the original message.

**Comment by pedrobaeza** [comment]
This module is not for using with enterprise theme. Both are incompatible.

Closing meanwhile no further evidence is presented.

**Comment by spadae22** [comment]
HI,
Well can we add that to the readme?
ER

**Comment by steven-bouillon** [comment]
Absolutely agree. I've tried installing this on multiple enterprise environments and finally started uninstalling other modules to find the culprit. OCA so far has been amazing with documentation but this is a glaring oversight. Thanks for posting this issue @spadae22

**Comment by robinhli** [comment]
I have not installed any enterprise theme, but have same issue.
this is not show when I run on PC(even simulate mobile), only on mobile.
