### ISSUE TITLE
[14.0] web_advanced_search. JS files are not loaded in assets_backed.

### ISSUE THREAD

**Issue by BT-mgomez** [OCA/web#1987]
Hello,

In our case, the module web_advanced_search does not work because the JS files are not loaded in the assets_backed.
I checked it, and they are loaded as usual using the xpath expression:
xpath expr="." position="inside"

But seems to not be working in some cases. I was able to solve it locally changing it by:
xpath expr="script[last()]" position="after"

Can you take a loot at it please?

**Comment by pedrobaeza** [comment]
Sorry, this can only be valid if you are able to reproduce it on OCA runbot.
