### ISSUE TITLE
web_m2x_options: search_more not working if values under limit

### ISSUE THREAD

**Issue by vha** [OCA/web#1994]
Module: web_m2x_options

Odoo version: 14.0

Issue: The "Search more" button on a many2one field doesn't show up when setting "search_more" to True if the number of values in the dropdown is under the limit (7 by default).

Expected: When I set the search_more to true, I expect the button to appear regardless of the limit.

Solution: I've changed the condition to always show if search_more is set. 

https://github.com/OCA/web/blob/cef972152c969d0347232048e1e13ccf74516441/web_m2x_options/static/src/js/form.js#L238

Currently:
`if (values.length > self.limit)`

Proposed change:
`if (values.length > self.limit || can_search_more) `

I can submit a PR if you think this is an appropiate solution.

**Comment by SilvioC2C** [comment]
@vha I came here to open this same issue, but I already have modified the code to force display (or hide) the "Search More..." option when `search_more` param is defined either in node's options or globally via `ir.config_parameter`, so I will open a PR in a few minutes.
Also, I believe this issue can also be found in previous versions but I wasn't able to test them yet.
