### ISSUE TITLE
[web_responsive] Embed app icons in CSS (in app drawer)

### ISSUE THREAD

**Issue by diggy128** [OCA/web#1995]
Current behavior: web_responsive embeds application icons as BASE64 encoded images inline in html. Caching is not possible and request response time is high.

Proposed behavior: Create dynamic CSS creating a CSS class for each application e.g. .app-icon-sale using
`background-image: url(data:image/png;base64,...encoded png file...);` to show the icons **thus** having them cached in CSS (assets) and reducing load_menus request response time.

Up until now I can only think of a controller dynamically creating a css excerpt having the app classes to be served as a dynamic file.

What do you think about this?

**Comment by legalsylvain** [comment]
:+1:

**Comment by pedrobaeza** [comment]
cc @Tardo @SplashS

**Comment by SplashS** [comment]
@diggy128 Hello!
Can you describe the problem more clear?
As I can see base64 encoded icons are loaded by `/web/webclient/load_menus/` controller. It is part of `web` module. So `web_responsive` module doesn't add any additional network traffic to load app icons comparing to pure 14.0. It just uses already loaded data from menu descriptors.

So I can suggest that you meant to reduce network traffic comparing to 14.0 without `web_responsive`.
I can suggest you to enable browser cache for `/web/webclient/load_menus/<hash>` location in your load balancer configuration to achieve your target.

**Comment by legalsylvain** [comment]
Indeed, installing web_responsive doesn't seems to change a lot the size of the dowloaded data. 

- On localhost (12.0 CE), with ``purchase`` and ``point_of_sale`` installed.

![image](https://user-images.githubusercontent.com/3407482/126991117-4a5a6de3-2c0b-4020-b53e-e3dba9155222.png)

- adding ``web_responsive`` : 

![image](https://user-images.githubusercontent.com/3407482/126991016-621621d0-8c7c-4452-9f31-db691b6188d3.png)


>  I can suggest you to enable browser cache for /web/webclient/load_menus/<hash> location in your load balancer configuration to achieve your target.

I'm not sure to understand. Scanning the network, the only request that contains ``load_menus`` is that one.
``web/dataset/call_kw/ir.ui.menu/load_menus``

**Comment by SplashS** [comment]
> I'm not sure to understand. Scanning the network, the only request that contains `load_menus` is that one.
> `web/dataset/call_kw/ir.ui.menu/load_menus`

`web/dataset/call_kw/ir.ui.menu/load_menus` is used in 12.0. There is no hash in url, so load balancer cache is unavailable for this version.
`/web/webclient/load_menus/` in 13.0 and higher. Url contains hash and can be cached in browser via load balancer configuration.

@diggy128 what version of odoo do you have?

**Comment by diggy128** [comment]
We are on v12.
Doesn't 
`<img class="o-app-icon"
             t-attf-src="data:image/png;base64,#{app.web_icon_data}"/>`

That is set in web_responsive add up to the size of the load_menus response?

I had up to 3sec loading time for that request (over a slow 3G network).

AFAIK web doesn't pull icons in that request as the menus in vanilla odoo don't show any.

Furthermore since icon data are not resized, you can have an app that has a 2Mpixel icon downloaded for the menu only to be resized afterwards in css (stupid, but happened to me).

**Comment by SplashS** [comment]
> Doesn't
> `<img class="o-app-icon" t-attf-src="data:image/png;base64,#{app.web_icon_data}"/>`
> 
> That is set in web_responsive add up to the size of the load_menus response?

No, `web_responsive` doesn't add anything to `load_menus` response. You can check that `web_icon_data` exists in pure 12.0. This data is used only in enterprise version of odoo, but controller responses it in community.
So I think the problem described by you is not the problem of `web_responsive`.

Unfortunately in 12.0 `load_menus` is a obvious PRC-call and can not be cached by load balancer as I wrote above.
I can suggest you to shrink size of the app icons. You can do it in source code of your modules or in `Settings -> Technical -> Menu Items` (but it will be overwriten on modules update).
Please tell what your module have such big icon?

**Comment by SplashS** [comment]
> I had up to 3sec loading time for that request (over a slow 3G network).

I think we may leave this issue as a feature request. Or maybe it is for another module? Something in https://github.com/OCA/server-ux f.x.

**Comment by pedrobaeza** [comment]
I won't do anything for v12, as it's becoming old. Is this problem reproducible in 13.0 or 14.0?

**Comment by SplashS** [comment]
Starting from 13.0 menus are loaded via custom controller `/web/webclient/load_menus/<hash>`.
It can be cached in browser by load balancer configuration.
Nginx example:
```
location ~ ^/web/webclient/load_menus {
    expires 1d;
}
```

**Comment by pedrobaeza** [comment]
But does it suffer from embedded content? We can replace it with img links to static resources (`/web/static/src/description/icon.png`) and then use browser image cache.

**Comment by SplashS** [comment]
> But does it suffer from embedded content? We can replace it with img links to static resources (`/web/static/src/description/icon.png`) and then use browser image cache.

If we make direct links to icons in `web_responsive` we:
1. Increase number of requests.
2. Made icons loaded one by one when AppMenu is opened (user can wait for AppMenu is ready).
3. Twice network transferred data since `load_menus` controller make response with all base64 encoded icons, and then we will load each icon one by one again.

I think browser cache for `load_menus` response is the best solution. But it is available only starting from 13.0.

**Comment by pedrobaeza** [comment]
OK, thanks for the extra explanations. Then I'm OK to leave it as is. I think we can close this then.

**Comment by diggy128** [comment]
My two cents here: Since icon data is already in the response in core odoo, my request doesn't make much  sense as the response will still have that data in it. Changing that would probably require monkey patching that is out of scope.

Since the issue is handled in v13 with proxy cache we can close this now.
