### ISSUE TITLE
Responsiveness issue in Contact Module

### ISSUE THREAD

**Issue by MNakrani245** [OCA/web#2006]
There are issues with the contact of the company,

Do this operation on any mobile devices,

in the main contact menu, open any company that has child companies,
and open that child record,

That record's image will not look proper, for reference here is the link to the short video.
https://drive.google.com/file/d/1NhU01nyGuUhjHR_6dL8lzuNYlZWkZPYn/view?usp=sharing

**Comment by pedrobaeza** [comment]
Which Odoo version?

**Comment by MNakrani245** [comment]
It’s odoo 14 community, using OCA responsive module here is the link,
https://apps.odoo.com/apps/modules/14.0/web_responsive/

**Comment by pedrobaeza** [comment]
I'm not able to reproduce such problem in runbot: http://3498032-14-0-397e62.runbot2.odoo-community.org/web#id=14&action=300&model=res.partner&view_type=form&cids=1&menu_id=202

Maybe you haven't refreshed your tab after switching to mobile view?

**Comment by MNakrani245** [comment]
![image](https://user-images.githubusercontent.com/47133742/129481459-bad4fa55-91b8-4575-b33d-bd7a023a7f27.png)

Here is the same URL SS I have attached, please get some time and look at the image, as well as the video that I've added to the first post.

It's available in "Azure Interior" company --> "Brandon Freeman" record, and open that wizard in that please have a look with the image.

I've already hard refresh the page after switch into the mobile view.

![image](https://user-images.githubusercontent.com/47133742/129481533-3d8a202d-b168-4f8b-b8ac-ba2168d0cfea.png)


Thanks

**Comment by pedrobaeza** [comment]
Unless you give more details on how to reproduce it, nothing can be done. Start with the browser, version, OS...

**Comment by MNakrani245** [comment]
Here I've created a short preview of it:
https://drive.google.com/file/d/1NhU01nyGuUhjHR_6dL8lzuNYlZWkZPYn/view?usp=sharing

And the rest of the details like:
OS: Ubuntu 18.04 LTS
browser: Chrome -- Version 92.0.4515.107 (Official Build) (64-bit)

**Comment by pedrobaeza** [comment]
I have tried with both Firefox and Chromium and not able to replicate. Anyways, you should try with a real mobile, not on a computer.

**Comment by MNakrani245** [comment]
![3AFBB6C5-90D3-47E7-9F0F-3930708DD0D5](https://user-images.githubusercontent.com/47133742/129526108-1c326cc8-db67-476a-ae21-e22412df5b32.png)

here it is: it’s iphone 6s+

On the above link that you had provide me, just open any child contact of azure interior and have a look.

Thanks

**Comment by pedrobaeza** [comment]
The image is not well centered, but there's no lateral scroll, so for me that's not a big issue.

**Comment by MNakrani245** [comment]
I understand, so can you tell me what’s the way or properties that I’ve to use for fixing this things?

**Comment by pedrobaeza** [comment]
First try to locate the style that wastes this, and then go to the affected CSS. If you find the conflicting, you can make a PR for amending this in the module.

**Comment by MNakrani245** [comment]
Thank you
