### ISSUE TITLE
[web_responsive] Menu icons not shown

### ISSUE THREAD

**Issue by vasi26ro** [OCA/web#2018]
Menu icons missing in main menu.
![image](https://user-images.githubusercontent.com/43593951/132436547-05e5b1f2-e2a1-4f28-8c40-fb76b6ff896f.png)

Odoo version: Odoo 13.0-20210308 (Community Edition)
web_responsive version: 13.0.2.7.0

**Comment by pedrobaeza** [comment]
You have a bade deployment of the module. Maybe you are using the "Import module" option, which doesn't serve, or bad addons path or incorrect permissions. Anyways, nothing with the module itself. Check all these things and ask in forums for further help.

**Comment by legalsylvain** [comment]
Hi vasi. FYI, this problem can occur when there are some problems with your filestore.

**Comment by vasi26ro** [comment]
Thank you for your fast response. 
@legalsylvain I will take a look because I have some an error with filestore.
