### ISSUE TITLE
[RFC] widget to display html fields in Odoo 12 (web_ckeditor4 ?)

### ISSUE THREAD

**Issue by legalsylvain** [OCA/web#2019]
Hi all, 

In old versions of odoo, I used to use the module ``web_ckeditor4`` ([last version 10.0](https://github.com/OCA/web/tree/10.0/web_ckeditor4)) that allows to use the [ckeditor4](https://github.com/ckeditor/ckeditor4) library for html fields.

I didn't found in Odoo 12.0 (and later) that module, and no work around it.

Is there a new way to display html fields ? the default odoo widget (``widget="html"``) is very poor.

CC : @quentinDupont. Ref ticket : apps/deck/#/board/144/card/1843

**Comment by pedrobaeza** [comment]
Although not being exceptional, summernote (Odoo html default widget) has been enough for me. On v15 a new internally cooked HTML editor has landed.
