### ISSUE TITLE
Error in branches

### ISSUE THREAD

**Issue by pere-aquarian** [OCA/web#2030]
Hi, team, 

I don't know if it is the right place, but I want to inform about something that could be critical: The fact is that no branch but the default one is available to download nor clone. 

When I try to download the 13.0 branch of the web repo, I get the following (it downloads the 14.0 branch): 
![imagen](https://user-images.githubusercontent.com/84047887/133991032-30628dbc-9dc6-473d-b5ce-9aae70281368.png)

If I try the same via git, the 13.0 branch is not available. 
![imagen](https://user-images.githubusercontent.com/84047887/133990372-71cc81f0-50c1-4c3d-a29a-569eb9d845bb.png)

Hope it is a temporary issue or it happens only to me. 

Thank you!

**Comment by pedrobaeza** [comment]
It's true that the GitHub UI always downloads default branch, but that's a bug in GH part that we are not able to fix. You can report it to them.

Doing the clone with git, it works perfectly:

![Selección_009](https://user-images.githubusercontent.com/7165771/133992443-6bd7bf04-858b-4054-81ab-486284a1e774.png)

Closing as not being related with the modules themselves.

**Comment by legalsylvain** [comment]
damn'it I was answering, but you're definitively too fast, @pedrobaeza.  ;-)

**Comment by pere-aquarian** [comment]
Thanks a lot, @pedrobaeza , 

I know that it is on GH side; I will find the way to comunicate that properly. I will thin twice next time to not get you involved on that. 

Talking about the clone, it seem to be (fortunatelly) a temporary error: no problem now executing exactly the same (history) command. Download still wrong. 

Anyway, thanks a lot @pedrobaeza and @legalsylvain for your fast answer and availability. 

Cheers,
Pere
