### ISSUE TITLE
[RFC] Split web_responsive into smaller modules

### ISSUE THREAD

**Issue by jcdrubay** [OCA/web#2051]
web_responsive is a fantastic module with a lot of great features, yet it is becoming bigger and bigger and therefore harder and harder to upgrade and maintain.

Do you think it could be a good idea to split it into smaller menus for features with little or no inter-dependencies?

I am thinking for instance about the following 2 modules which could be extracted

- splash_app_menu: only replaces the default app drop-down menu
- web_sheet_full_width: this module already exists on his own

then web_responsive could depend on these modules.

Since v15 upgrades are coming soon, it could be a good time to refactor.

Since v15 ad v16 will gradually introduce OWL, splitting might facilitate the transition.

**Comment by pedrobaeza** [comment]
For me it's a no. Everything should be packed together as the responsive experience IMO.

**Comment by jcdrubay** [comment]
Thanks @pedrobaeza for sharing your point of view.

How about having "competitor" modules which leave side by side with web_responsive?

These modules could have a similar forewords as for web_sheet_full_width:

> This module feature and many other features and improvements to the web backend are included in web_responsive module. Before installing this module, please consider Web Responsive as a better alternative.

Would that be accepted or rejected by OCA/web maintainers?

Also, isn't the web_responsive module becoming more web_oca rather than web_responsive?

**Comment by pedrobaeza** [comment]
For me, `web_sheet_full_width` shouldn't exist, as not having full responsive experience is a nonsense, but has been kept by the insistence and migration provided by some of you. Enterprise module equivalent (`web_enterprise`) is also packed as one. Installing 3 or more modules to get the same as before is not my favorite approach. Why would you want to do that?

Renaming to `web_oca` may be confusing as well, but if most of you want it...

**Comment by jcdrubay** [comment]
> Why would you want to do that?

- smaller modules would be easier to upgrade and maintain 

With v14, it took 5 months for web_responsive to be merged:
https://github.com/OCA/web/pull/1819

I imagine that big modules discourage contributors to roll-up their sleeves.

**Comment by pedrobaeza** [comment]
I don't think it's something related to the size of the module, as the main effort was already done, but nobody pushed enough in that moment as there won't be any rush for them. Splitting the module in several pieces won't accelerate it IMO, as at the end, you should know the same for all the pieces be fitted together, and even worst, you would need to duplicate some code for pasting all together.

**Comment by jcdrubay** [comment]
Closing as it seems inappropriate.
Thanks again @pedrobaeza for taking the time to answer this proposal.
