### ISSUE TITLE
[13.0][BUG] web_drop_target changes made a regression in mail_drop_target

### ISSUE THREAD

**Issue by LoisRForgeFlow** [OCA/web#2057]
Since this commit 1c0c2609dd94f23106432a189a7fb09f5ee05e6e the dependent module [mail_drop_target](https://github.com/OCA/social/tree/13.0/mail_drop_target) stopped working as expected. Before the emails dragged and dropped into the chatter were added to the chatter conversation, now they are attached as regular files.

Before that change:
![Peek 2021-10-21 09-31](https://user-images.githubusercontent.com/23449160/138231897-758dff77-889d-4aa6-9fcb-6b71a1f09095.gif)

After that change:
![Peek 2021-10-21 09-26](https://user-images.githubusercontent.com/23449160/138231911-2eeca1ca-d769-4ecb-a9c8-8b80389a4e7a.gif)

cc @Tardo

**Comment by pedrobaeza** [comment]
I have to say that I have never used that module, and now that I see it in action, the feature that is adding is barely a sacrilege, as it's deforming the intention of the chatter. Anyways, we should repair it for those that use it, but I strongly recommend to not do it.

**Comment by LoisRForgeFlow** [comment]
You might be right but as you also are saying, the feature was already there and this has been a regression.

Thanks for the quick reaction as always!

**Comment by LoisRForgeFlow** [comment]
Closed via #2065
