### ISSUE TITLE
PWA cache module 

### ISSUE THREAD

**Issue by amunoz-pdc** [OCA/web#2068]
I'm trying to understand the web_pwa_cache module and make the app work offline.
I installed all 4 modules (web_pwa_oca, web_pwa_cache, sale_pwa_cache, product_pwa_cache) and made a new PWA in my Chrome browser but did not manage to make it work. (The offline switch is not appearing in the top-right user menu)

Are there any updates/news regarding these modules? When will there be a stable release? Is there any documentation regarding this module?

**Comment by pedrobaeza** [comment]
Probably you are not loading through the PWA icon.

**Comment by amunoz-pdc** [comment]
I did start the PWA through the icon.
I'll add some context on how I installed/started everything.
1. Installed all 4 PWA modules on a new database.
2. Installed the WPA through the browser (Chrome)
3. Start the application from browser apps and also from the desktop icon.
4. The Offline switch is not appearing in the top-right user menu.

This is how I install the PWA
![image](https://user-images.githubusercontent.com/72432692/140065497-f10c882e-d4fb-48e5-b4a7-88d1f601496d.png)
<br>
After starting the PWA, Offline switch is not appearing.
![image](https://user-images.githubusercontent.com/72432692/140065803-20ccd23a-6c07-4838-b06f-b5fcf6085cea.png)
<br>
Maybe I am missing a step or an additional module?

**Comment by amunoz-pdc** [comment]
By the way, I am using Chrome Version 94.0.4606.71 (Official Build) (64-bit) and Odoo Version 13.0.2020.10.16
Maybe this Odoo version is not supported?

**Comment by pedrobaeza** [comment]
Have you put your user with the PWA cache group?

**Comment by amunoz-pdc** [comment]
I added the user to the PWA group and now I see the offline switch.
When I open the PWA it is in offline mode. When I try to switch it to online mode, I get these errors:
![image](https://user-images.githubusercontent.com/72432692/140739039-f7f24b4e-c566-433a-a3ae-d73ffaed8367.png)

Do you know what this error means?

**Comment by pedrobaeza** [comment]
Wait until the next push of the PR, and update everything. Anyways, this should be handled in the PR itself, so closing.
