### ISSUE TITLE
[13.0]web_responsive module bug

### ISSUE THREAD

**Issue by j209** [OCA/web#2080]
After installing web_responsive module on odoo 13 the page disappeared!

![odoo13_bug](https://user-images.githubusercontent.com/18129232/141674482-4ee61e67-4fd7-4f29-b28a-fd3dfbb4b3e4.gif)

**Comment by pedrobaeza** [comment]
It seems something specific of your deployment (or your browser with a blocker extension). Please try to reproduce the problem in the OCA runbot with a browser without extensions.

Closing meanwhile.

**Comment by j209** [comment]
I cheched with firefox and edge browser and I always encountered the problem.

**Comment by pedrobaeza** [comment]
Are you able to reproduce it in OCA runbot?

**Comment by j209** [comment]
web_responsive is not available for v13 !!

![image](https://user-images.githubusercontent.com/18129232/141676961-0c52721d-903e-4e2f-9699-25a164d4ed6f.png)


I am trying to reproduce it in OCA runbot.

**Comment by pedrobaeza** [comment]
You just have to click on the badge in the top of the readme

**Comment by j209** [comment]
Solved!
thanks a lot for your quick response.
