### ISSUE TITLE
[14.0] web_responsive: contact view of res.partner have very narrow fields

### ISSUE THREAD

**Issue by alexis-via** [OCA/web#2100]
## Module
web_responsive

## Describe the bug
There is a **recent** regression, probably due to a code change in odoo v14: the layout of the contact pop-up on partner form view is broken: input fields are very narrow.

![web_responsive_v14_bug](https://user-images.githubusercontent.com/1157917/143870862-71432dc3-0a62-4675-b70a-1178ce084395.png)

## To Reproduce
**Affected versions**: 14.0 with up-to-date code

1. create a new DB (do NOT install the module web_responsive)
2. Go to the form view of a partner, click on the button to add a Contact => the layout of the input fields is OK
3. Add the module web_responsive
4. Go to the form view of a partner, click on the button to add a Contact => the layout is broken: the input fields are very narrow

**Comment by pedrobaeza** [comment]
@Tardo is it possible to not use such width on popups?

**Comment by pedrobaeza** [comment]
The same should happen on v13

**Comment by Tardo** [comment]
@alexis-via please, can you check the fix? thanks.

**Comment by alexis-via** [comment]
@Tardo YOU ROCK! Thanks for the fix, it works great, I approved the PR.
