### ISSUE TITLE
14.0 web_widget_ckeditor wrapping issue

### ISSUE THREAD

**Issue by leemannd** [OCA/web#2114]
## Module
web_widget_ckeditor

## Describe the bug
Into odoo forms there are a lot of nested groups. When you're adding a field using ckeditor widget the widget it taking too much width. It is taking too much, because of the label of the field.
The following structure will not work:

```
          <group name="A">
            <group name="B">
              <field name="ab"/>
              <field name="cd_using_ckeditor_widget"/>
            </group>
            <group name="C">
              <field name="xy"/>
            </group>
          </group>
```

**Comment by ivantodorovich** [comment]
This can be closed now 👍🏻
