### ISSUE TITLE
[14] web_responsive installs but cannot access to apps on backend

### ISSUE THREAD

**Issue by timnis** [OCA/web#2149]
## Module
web_responsive

## Describe the bug
Try to install web_responsive to my clean dev server but got following error when accessing apps
`Error:

Traceback:
Error: scope.device is undefined
anonymous@http://10.0.0.245:8069/web/content/199-11a67f5/web.assets_common.js line 973 > Function:20:5
fn@http://10.0.0.245:8069/web/content/199-11a67f5/web.assets_common.js:955:173
render@http://10.0.0.245:8069/web/content/199-11a67f5/web.assets_common.js:962:20
useModel/__owl__.renderFn@http://10.0.0.245:8069/web/content/227-b432222/web.assets_backend.js:1338:147
__render@http://10.0.0.245:8069/web/content/199-11a67f5/web.assets_common.js:1291:33
__prepareAndRender@http://10.0.0.245:8069/web/content/199-11a67f5/web.assets_common.js:1289:29`

## To Reproduce
**Affected versions**:

1. install web_responsive
2. go to Sales
3.

**Expected behavior**
Able to go to Sales and web_responsive works

**Additional context**
Odoo 14 Enterprise, python 3.6, up to date web_resposive

**Comment by ap-wtioit** [comment]
Can you test if the bug also happens when you use `/web?debug=assets`. This should result in a better Traceback as it will load the original assets instead of the combined ones.

**Comment by legalsylvain** [comment]
AFAIK, web_responsive is not compatible with enterprise version.

**Comment by timnis** [comment]
> Can you test if the bug also happens when you use `/web?debug=assets`. This should result in a better Traceback as it will load the original assets instead of the combined ones.

it gives 
`Error:


Traceback:
Error: scope.device is undefined
anonymous@http://10.0.0.245:8069/web/static/lib/owl/owl.js line 1795 > Function:20:5
fn@http://10.0.0.245:8069/web/static/lib/owl/owl.js:1666:45
render@http://10.0.0.245:8069/web/static/lib/owl/owl.js:1716:32
useModel/__owl__.renderFn@http://10.0.0.245:8069/web/static/src/js/model.js:482:20
__render@http://10.0.0.245:8069/web/static/lib/owl/owl.js:4570:37
__prepareAndRender@http://10.0.0.245:8069/web/static/lib/owl/owl.js:4558:22`

**Comment by timnis** [comment]
> AFAIK, web_responsive is not compatible with enterprise version.

I didn't found any mention of it :)

**Comment by youring** [comment]
web_responsive is born to fill the gap of web client UI between Odoo CE and EE. And IMHO it gives the community users a free, robust experience with a better mobile responsive UI.
Initially and most importantly the App drawer, search menu... then sticky headers and misc enhancement.
These features mostly covers EE web client features and maybe even better, which will probably leads to conflict with EE modules(web_enterprise, etc)...
So when installing OCA modules, esp. web related modules with odoo EE, conflict becomes the primary concern.

Now it seems necessary to add "excludes": ["web_enterprise"] in the manifest.

**Comment by pedrobaeza** [comment]
Included the incompatibility in 077231f767274c3aa2fbec4a1a4904bb1ad487a3
