### ISSUE TITLE
web_sheet_full_width not working in odoo 15.

### ISSUE THREAD

**Issue by kamaleshsharepoint** [OCA/web#2170]
After installing web_sheet_full_width to odoo 15.
it still its not showing full width in form view.
Please check the below screenshot.
Chatter is still coming in side.
![Screenshot of Odoo - S00036 (1)](https://user-images.githubusercontent.com/100822070/159273283-82a67b11-fb88-4678-ac18-ffc2638e566d.jpg)

**Comment by legalsylvain** [comment]
Hi. AFAIK, that's not the purpose of the module.
if you configure chatter at the right, it is normal to see it at the right.

kind regards.

**Comment by kamaleshsharepoint** [comment]
Hi @legalsylvain 
Then how can i set chatter at bottom always?

**Comment by legalsylvain** [comment]
maybe you could take a look on the description of that module : https://github.com/OCA/web/tree/15.0/web_responsive

**Comment by kamaleshsharepoint** [comment]
Hi @legalsylvain 
this modules is worked for Community version right?
because i am not able to install it on 15 enterprise

**Comment by legalsylvain** [comment]
>   because i am not able to install it on 15 enterprise

indeed. it's incompatible.

**Comment by kamaleshsharepoint** [comment]
@legalsylvain is there any module which shows form view in full width odoo 15 enterprice?

**Comment by legalsylvain** [comment]
enterprice : nice play on words ! 

I don't know, but you should not look on oca modules, better in appstore. compatibility of oca web modules is only assured with CE.

kind regards;
