### ISSUE TITLE
[14.0] fullscreen app menu issue (Style Error)

### ISSUE THREAD

**Issue by SaFi2266** [OCA/web#2188]
odoo version: 14.0-20220401 (Community Edition) docker image
When install web_responsive module, a screen with error show for second and vanished then the full screen app menu become listed big icons menu (not overlay)

![Screenshot from 2022-04-09 07-33-53](https://user-images.githubusercontent.com/5728273/162556495-3ed34e59-b53a-4003-91a2-ed87249f9228.png)

the error says
The style compilation failed, see the error below. Your recent actions may be the cause, please try reverting the changes you made.
```
Error: argument `$color` of `rgba($color, $alpha)` must be a color
        on line 14941 of /stdin, in function `rgba`
        from line 14941 of /stdin >> background-color: rgba(gray("white"), 0.05);
   ----------------------------------^
```
This error occured while compiling the bundle 'web.assets_backend' containing:
    - /web/static/lib/bootstrap/scss/_functions.scss
    - /web/static/lib/bootstrap/scss/_mixins.scss
    - /web/static/src/scss/bs_mixins_overrides.scss
    - /web/static/src/scss/utils.scss
    - /web/static/src/scss/primary_variables.scss
    - /mail/static/src/scss/variables.scss
    - /web/static/src/scss/secondary_variables.scss
    - /web/static/src/scss/bootstrap_overridden.scss
    - /web/static/lib/bootstrap/scss/_variables.scss
    - /web/static/src/scss/import_bootstrap.scss
    - /web/static/src/scss/bootstrap_review.scss
    - /web/static/src/scss/webclient_extra.scss
    - /web/static/src/scss/webclient_layout.scss
    - /web/static/src/scss/webclient.scss
    - /web/static/src/scss/domain_selector.scss
    - /web/static/src/scss/model_field_selector.scss
    - /web/static/src/scss/progress_bar.scss
    - /web/static/src/scss/dropdown.scss
    - /web/static/src/scss/dropdown_extra.scss
    - /web/static/src/scss/tooltip.scss
    - /web/static/src/scss/switch_company_menu.scss
    - /web/static/src/scss/debug_manager.scss
    - /web/static/src/scss/control_panel.scss
    - /web/static/src/scss/fields.scss
    - /web/static/src/scss/fields_extra.scss
    - /web/static/src/scss/file_upload.scss
    - /web/static/src/scss/views.scss
    - /web/static/src/scss/pivot_view.scss
    - /web/static/src/scss/graph_view.scss
    - /web/static/src/scss/form_view.scss
    - /web/static/src/scss/form_view_extra.scss
    - /web/static/src/scss/list_view.scss
    - /web/static/src/scss/list_view_extra.scss
    - /web/static/src/scss/kanban_dashboard.scss
    - /web/static/src/scss/kanban_examples_dialog.scss
    - /web/static/src/scss/kanban_column_progressbar.scss
    - /web/static/src/scss/kanban_view.scss
    - /web/static/src/scss/web_calendar.scss
    - /web/static/src/scss/search_view.scss
    - /web/static/src/scss/search_panel.scss
    - /web/static/src/scss/dropdown_menu.scss
    - /web/static/src/scss/search_view_extra.scss
    - /web/static/src/scss/data_export.scss
    - /base/static/src/scss/onboarding.scss
    - /web/static/src/scss/attachment_preview.scss
    - /web/static/src/scss/notification.scss
    - /web/static/src/scss/base_document_layout.scss
    - /web/static/src/scss/special_fields.scss
    - /web/static/src/scss/ribbon.scss
    - /web/static/src/scss/base_settings.scss
    - /web/static/src/scss/report_backend.scss
    - /base_import/static/src/scss/base_import.scss
    - /base_setup/static/src/scss/settings.scss
    - /mail/static/src/scss/emojis.scss
    - /mail/static/src/variables.scss
    - /mail/static/src/scss/discuss.scss
    - /mail/static/src/scss/composer.scss
    - /mail/static/src/scss/thread.scss
    - /mail/static/src/scss/systray.scss
    - /mail/static/src/scss/mail_activity.scss
    - /mail/static/src/scss/many2one_avatar_user.scss
    - /mail/static/src/scss/activity_view.scss
    - /mail/static/src/scss/kanban_view.scss
    - /mail/static/src/components/notification_list/notification_list_item.scss
    - /mail/static/src/bugfix/bugfix.scss
    - /mail/static/src/components/activity/activity.scss
    - /mail/static/src/components/activity_box/activity_box.scss
    - /mail/static/src/components/activity_mark_done_popover/activity_mark_done_popover.scss
    - /mail/static/src/components/attachment/attachment.scss
    - /mail/static/src/components/attachment_box/attachment_box.scss
    - /mail/static/src/components/attachment_list/attachment_list.scss
    - /mail/static/src/components/attachment_viewer/attachment_viewer.scss
    - /mail/static/src/components/chat_window/chat_window.scss
    - /mail/static/src/components/chat_window_header/chat_window_header.scss
    - /mail/static/src/components/chat_window_hidden_menu/chat_window_hidden_menu.scss
    - /mail/static/src/components/chat_window_manager/chat_window_manager.scss
    - /mail/static/src/components/chatter/chatter.scss
    - /mail/static/src/components/chatter_container/chatter_container.scss
    - /mail/static/src/components/chatter_topbar/chatter_topbar.scss
    - /mail/static/src/components/composer/composer.scss
    - /mail/static/src/components/composer_suggested_recipient/composer_suggested_recipient.scss
    - /mail/static/src/components/composer_suggested_recipient_list/composer_suggested_recipient_list.scss
    - /mail/static/src/components/composer_suggestion/composer_suggestion.scss
    - /mail/static/src/components/composer_suggestion_list/composer_suggestion_list.scss
    - /mail/static/src/components/composer_text_input/composer_text_input.scss
    - /mail/static/src/components/dialog/dialog.scss
    - /mail/static/src/components/discuss/discuss.scss
    - /mail/static/src/components/discuss_mobile_mailbox_selection/discuss_mobile_mailbox_selection.scss
    - /mail/static/src/components/discuss_sidebar/discuss_sidebar.scss
    - /mail/static/src/components/discuss_sidebar_item/discuss_sidebar_item.scss
    - /mail/static/src/components/drop_zone/drop_zone.scss
    - /mail/static/src/components/emojis_popover/emojis_popover.scss
    - /mail/static/src/components/file_uploader/file_uploader.scss
    - /mail/static/src/components/follow_button/follow_button.scss
    - /mail/static/src/components/follower/follower.scss
    - /mail/static/src/components/follower_list_menu/follower_list_menu.scss
    - /mail/static/src/components/follower_subtype/follower_subtype.scss
    - /mail/static/src/components/follower_subtype_list/follower_subtype_list.scss
    - /mail/static/src/components/mail_template/mail_template.scss
    - /mail/static/src/components/message/message.scss
    - /mail/static/src/components/message_author_prefix/message_author_prefix.scss
    - /mail/static/src/components/message_list/message_list.scss
    - /mail/static/src/components/message_seen_indicator/message_seen_indicator.scss
    - /mail/static/src/components/messaging_menu/messaging_menu.scss
    - /mail/static/src/components/mobile_messaging_navbar/mobile_messaging_navbar.scss
    - /mail/static/src/components/notification_group/notification_group.scss
    - /mail/static/src/components/notification_list/notification_list.scss
    - /mail/static/src/components/notification_popover/notification_popover.scss
    - /mail/static/src/components/notification_request/notification_request.scss
    - /mail/static/src/components/partner_im_status_icon/partner_im_status_icon.scss
    - /mail/static/src/components/thread_icon/thread_icon.scss
    - /mail/static/src/components/thread_needaction_preview/thread_needaction_preview.scss
    - /mail/static/src/components/thread_preview/thread_preview.scss
    - /mail/static/src/components/thread_textual_typing_status/thread_textual_typing_status.scss
    - /mail/static/src/components/thread_typing_icon/thread_typing_icon.scss
    - /mail/static/src/components/thread_view/thread_view.scss
    - /mail/static/src/widgets/discuss/discuss.scss
    - /mail/static/src/widgets/form_renderer/form_renderer.scss
    - /mail_bot/static/src/scss/odoobot_style.scss
    - /mail_bot/static/src/bugfix/bugfix.scss
    - /partner_autocomplete/static/src/scss/partner_autocomplete.scss
    - /sms/static/src/bugfix/bugfix.scss
    - /snailmail/static/src/bugfix/bugfix.scss
    - /snailmail/static/src/components/snailmail_notification_popover/snailmail_notification_popover.scss
    - /web_responsive/static/src/scss/web_responsive.scss
    - /web_responsive/static/src/scss/search_view_mobile.scss
    - /web_responsive/static/src/scss/kanban_view_mobile.scss

**Comment by pedrobaeza** [comment]
Are you able to reproduce the problem in runboat OCA instance?

**Comment by SaFi2266** [comment]
@pedrobaeza 
> 

How can I do that?

**Comment by pedrobaeza** [comment]
Click on the try me on runbot button with admin/admin

**Comment by SaFi2266** [comment]
> Click on the try me on runbot button with admin/admin

It's works fine on **runboat** after uninstall/reinstall
but my issue regarding to official odoo with build version I mentioned above not to OCA edition
btw
[![Runbot: Try Me](https://img.shields.io/badge/runbot-Try me-875A7B.png)](https://runbot.odoo-community.org/runbot/162/14.0) button on odoo app store is unclickable

**Comment by pedrobaeza** [comment]
You are probably doing something incorrect in the deployment, like using "import module" option, but nothing to do with the module itself. Go to forums to ask for help.
