### ISSUE TITLE
[15.0] web_responsive: form views look messed up

### ISSUE THREAD

**Issue by yassinelachgar** [OCA/web#2233]
## Module
web_responsive

## Describe the bug
All form views look messed up and fields are stacked vertically.

## To Reproduce
**Affected versions**: 15.0

1. Install web_responsive module
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/62101920/174060090-94a20af3-446c-406b-a428-3cec96044bd8.png">

**Expected behavior**
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/62101920/174059745-b692a144-2570-44c7-b424-ba365451dd45.png">

**Comment by legalsylvain** [comment]
Hi @yassinelachgar. 
Not sure to understand your expected behaviour. If you set the chatter on the right part, the expected behaviour should display it. Don't you think ?

**Comment by yassinelachgar** [comment]
> Hi @yassinelachgar. Not sure to understand your expected behaviour. If you set the chatter on the right part, the expected behaviour should display it. Don't you think ?

In older versions of web_responsive, even if you set the chatter on the right side the form view looks like screenshot in expected behavior.

**Comment by pedrobaeza** [comment]
For your screen with, it's normal that both columns don't fit in the remaining space, so that seems the expected behavior. Which resolution by the way?

**Comment by yassinelachgar** [comment]
> For your screen with, it's normal that both columns don't fit in the remaining space, so that seems the expected behavior. Which resolution by the way?

A regular 15.4 inch 2280 x 1800.
A bit weird imo since the same screen works fine with older versions.

**Comment by pedrobaeza** [comment]
That screenshot can't be with such huge resolution. You may have the window not maximized or the resolution is not that one.

**Comment by yassinelachgar** [comment]
I guess I have to set `chatter_position` to `normal`, it fixed the problem. Although it's only temporary.

**Comment by Ngquang** [comment]
@yassinelachgar IMO, with this setting, it make users feel better UX, they can switch position of chatter. Make them feel free

![Screenshot from 2022-06-20 08-35-54](https://user-images.githubusercontent.com/90305443/174510720-405e30d1-ec05-47f9-b2fa-cf8d806eb6ca.png)

**Comment by yassinelachgar** [comment]
> 

I agree, but as you can see in version 15.0 the UI looks messed up 🤕

**Comment by Ngquang** [comment]
@yassinelachgar i found this PR https://github.com/OCA/web/pull/2058 about MIG `web_responsive` to 15. It's changed a lot and need more contribute to stable.

**Comment by pedrobaeza** [comment]
I insist that such indicated resolution shouldn't have any problem.

**Comment by yassinelachgar** [comment]
> I insist that such indicated resolution shouldn't have any problem.

I respect you insistence 👍 I'm just saying that the same screen with same resolution works fine with older versions of the module.

<img width="255" alt="image" src="https://user-images.githubusercontent.com/62101920/174634709-7a6e714d-164a-45d9-a5ac-e6d4f28f5d46.png">

**Comment by pedrobaeza** [comment]
But the screenshot of Odoo doesn't correspond to such resolution

**Comment by pedrobaeza** [comment]
I have less resolution and I see both groups in the same row.

**Comment by ap-wtioit** [comment]
@yassinelachgar which Browser and Mac OS are you using? @pedrobaeza the resolution of "retina" displays doesn't seem to translate 1:1 to programs / screenshots. it looks like the 2880x1800 would translate to 960x600 (px, divided by 3, for the program / browser / css pixels) (with a higher resolution rendered to the user)

Unfortunately my Mac OS Hardware is pretty old (no retina) so unless we have somebody with a fruit computer or experience with "retina" displays this might take a while.

**Comment by yassinelachgar** [comment]
> @yassinelachgar which Browser and Mac OS are you using? @pedrobaeza the resolution of "retina" displays doesn't seem to translate 1:1 to programs / screenshots. it looks like the 2880x1800 would translate to 960x600 (px, divided by 3, for the program / browser / css pixels) (with a higher resolution rendered to the user)
> 
> Unfortunately my Mac OS Hardware is pretty old (no retina) so unless we have somebody with a fruit computer or experience with "retina" displays this might take a while.

I am using chrome, but tested Firefox and Safari. Problems persists.
Also, I tested it on multiple macOS machines at work, they all had the problem.

**Comment by pedrobaeza** [comment]
If it translates to such low resolution, then it's normal that two groups don't fit in the same row. The width of the label was expanded two versions ago.
