### ISSUE TITLE
[15.0] web_responsive: User Menus Customization Home Action displayed in all APPs

### ISSUE THREAD

**Issue by Ranamiu** [OCA/web#2269]
User Menus Customization Home Action chosen action displayed in every Odoo APP instead of home "page" only.

## Module
Web Responsive

## Describe the bug
The chosen action set in User Menus Customization Home Action should be displayed only when the user enters the system for the first time and not be repeated every time the user accesses any APP following the first system access.

## To Reproduce
Affected versions: Odoo CE 15.0-20220725

1. Install and activate Web Responsive 15 (OCA)
2. Settings > User and Companies
3. Go to User Admin (same with rest of internal users).
4. In user Admin > Preferences > Menu customization > switch to any Action.

As a result:
When entering any Odoo APP, the chosen action in Home Action is being repeated in each App.

**Expected behavior**
The chosen action in Home Action should be displayed only when an internal user enters the system for the first time and should not be repeated every time a user accesses any APP.

Thanks in advance

**Comment by pedrobaeza** [comment]
I don't get the problem. Maybe some screenshots?

**Comment by Ranamiu** [comment]
Hola Pedro, send you screenshots.

1st screenshot: Admin Menus Customization > Home Action to be Discuss
2nd screenshot: Sales Odoo APP as Home Action is being set to Discuss

Thanks for your attention
Best Regards

![web-responsive](https://user-images.githubusercontent.com/29396762/182593497-f98c46de-0ffb-4081-9a81-b9ddf81a74e4.png)

![web-responsive1](https://user-images.githubusercontent.com/29396762/182593516-523c1aed-61a2-4c51-9adc-2c5c2c4ab644.png)

**Comment by pedrobaeza** [comment]
Understood. @SplashS what do you think?

**Comment by Ranamiu** [comment]
Hi Pedro @pedrobaeza, @SplashS ;

Have been trying and trying again, let me please add this is probably  NOT a bug from this addon (OCA responsive)

Have been trying on any other back-end theme, and same bug.

I guess it is a bug concerning any new theme being added to default Odoo 15.

We also tried on latest Odoo 15.0-20220829 (Community Edition), same issue as we change default back-end theme.

Please, might you help leting Odoo guys know about this?

Thanks in adavnce

**Comment by SplashS** [comment]
Hello!
I've tested the last 15.0 source with the last web_responsive code.
If I set Discuss as Home Action, Discuss only shows at the start. Other navigation works well.
So I couldn't reproduce problem you shown on screenshot.
Maybe details of other installed modules or videocast of reproduction can shed some light on the problem details.

**Comment by Ranamiu** [comment]
Hi @SplashS, 

First of all, thanks for following this up.

Might you please indicate exactly which Odoo version and OCA web-responsive have you tested?

As previously indicated, we tried on latest both default Odoo 15.0-20220829 (Community Edition),  no any added module except of OCA Responsive on lastest version available as we report this bug.

Our test: 

- Odoo 15.0-20220829 (Community Edition),
- OCA web_responsive-15.0.1.1.1 (official download right now at Odoo APPs module page)

Please, let us know exactly which version you have tested.

Thanks in advance  !!

Appreciate your great work at OCA.

Greetings

**Comment by SplashS** [comment]
Hi @Ranamiu 
I've tested again last GitHub version of Odoo Community (at 20220925) and last version of web_responsive (15.0.1.1.1)
Still can't reproduce.
I used fresh db. I installed web_responsive. Then I set Discuss Home action for Mitchel Admin. After that Discuss appears at first screen.
I tried to navigate through interface, reload page. Menu shows correctly, Discuss appears only for the first time.   
Please give more details about your test.

**Comment by Ranamiu** [comment]
Hi @SplashS, greetings of the day!!

Glad to know you fix it !

Many thanks

Just download last week latest version of web_responsive-15.0.1.1.3 and this issue is being fixed.

A big thanks for your work.

Best regards
Ranamiu
