### ISSUE TITLE
[14.0] web_drop_target does not work anymore

### ISSUE THREAD

**Issue by marylla** [OCA/web#2283]
## Module
web_drop_target

## Describe the bug
You cannot add an attachment via drag and drop. The browser turns black and shows this exception:

```
Fehler:
Uncaught TypeError: Cannot read properties of null (reading 'jsID')

https://kaelin-demo-v14.elegosoft.com/web/content/2710-e280df2/web.assets_backend.js:6428
Rückverfolgung:
TypeError: Cannot read properties of null (reading 'jsID')
    at Class._onBodyFileDragover (https://kaelin-demo-v14.elegosoft.com/web/content/2710-e280df2/web.assets_backend.js:6428:980)
    at HTMLBodyElement.dispatch (https://kaelin-demo-v14.elegosoft.com/web/content/2709-a3da94f/web.assets_common.js:1740:447)
    at elemData.handle (https://kaelin-demo-v14.elegosoft.com/web/content/2709-a3da94f/web.assets_common.js:1726:166)
```

I found the PR and commit causing it: 
 #1976
https://github.com/OCA/web/pull/1976/commits/9bd63dd24ae7c8f8eb9eefd0078b9e19b55cf0cb
Several modules were updated here including web_drop_target.

I think this was a mistake:
```
            if (
                _.isEmpty(this._get_drop_items(ev)) &&
                this._checkDragOver() &&
-               (controller == undefined || controller.jsID === this.controllerID)
+               (controller === undefined || controller.jsID === this.controllerID)
            ) {
                const drop_zone_offset = this.$drop_zone.offset();
                const overlay_css = {
```

## To Reproduce
**Affected versions**: 14.0

1. Open current runboat: http://oca-web-14-0-50876718b0ee.runboat.odoo-community.org/
2. Go to any object with message chatter and try to upload a file via drag and drop.

**Expected behavior**
The attachment upload should just work. :P

**Comment by marylla** [comment]
@KKamaa @hbrunn I added you in this issue because you did the commit or merged the PR #1976. Can you fix please?

**Comment by chandni299** [comment]
We can also add one more condition for the value `controller === null` like below as we have value `null` for the variable `controller` when using add the attachment via drag and drop of the file.
```
if (
                 _.isEmpty(this._get_drop_items(ev)) &&
                 this._checkDragOver() &&
-                (controller === undefined || controller.jsID === this.controllerID)
+                (controller === undefined || controller === null || controller.jsID === this.controllerID)
             ) {
                 const drop_zone_offset = this.$drop_zone.offset();
                 const overlay_css = {
```

**Comment by KKamaa** [comment]
> @KKamaa @hbrunn I added you in this issue because you did the commit or merged the PR #1976. Can you fix please?

Hey @marylla I'm suspecting this is not an issue related to merge but an issue that was already there before with drag and drop. In the commit the changes where only js lint that were existing on on web_drag_drop target and not the functional part.
Also a conditional checker would help to check for null values before trying to use them

**Comment by KKamaa** [comment]
As @chandni299 @marylla suggested adding `controller === null` to the if will solve it

**Comment by pedrobaeza** [comment]
Standard v14 allows to drag and drop attachments when that part is unfolded. That's why this is not included here.

**Comment by marylla** [comment]
@pedrobaeza Well, that's true that we can drag&drop attachments without this module, but still:

1. This module is a dependency in other modules, e.g. dms.
2. The runboat shows this issue too if this module is installed. 
3. If we don't need this module, why is it available? Other modules should remove the dependency then.

We fixed it locally already but...
Why closing this issue if it is not really resolved yet? :(

**Comment by pedrobaeza** [comment]
This module is the base for allowing drag and drop in certain places, like DMS, but it shouldn't provide itself any feature. For any feature related to chatter, things should go in `mail_drop_target`, not here.

**Comment by marylla** [comment]
@pedrobaeza This module currently somehow provides a feature and it is now broken in 14.0.
Well, I tried...
