### ISSUE TITLE
web_disable_export_group is useless because you can allways export data

### ISSUE THREAD

**Issue by fgarcia-humanoide** [OCA/web#2290]
## Module
web_disable_export_group

## Describe the bug
It disables the Action menu export, but you can allways export the screen view with the small bunton.

![useless](https://user-images.githubusercontent.com/7599709/189590521-fc12afa8-2244-43ba-878f-351dcf6be77e.JPG)

## To Reproduce
**Affected versions**: all

**Comment by pedrobaeza** [comment]
You are not indicating version, but it was removed for v13 in #1975

**Comment by fgarcia-humanoide** [comment]
It was version 13. After updating it works ok.

Thank you.

**Comment by fgarcia-humanoide** [comment]
Should I close the issue?

**Comment by pedrobaeza** [comment]
Please first of all, always update, and then check again.
