### ISSUE TITLE
Web Responsive Odoo V15 - Additional Actions Formatting Issue

### ISSUE THREAD

**Issue by SirSkyr** [OCA/web#2326]
Summary:
On PC the dropdown of the additional actions button doesn't expand to fit any of the overflow and only covers 2/3rd of each action item, whereas it seems to fit the action item on mobile but only shows one item. Scrollbar doesn't generate for the totality of the action items rather only has 2 arrows so in action dropdowns with many options, is highly tedious.

Module:
Web Responsive

Describe the bug:
scss formatting issue with additional actions dropdown button

To Reproduce:
Odoo Community V15

1. Install the module and go into any list view
2. Select any item and click on additional actions to open its dropdown

Expected behavior:
Correct fitting around at least one action item on PC view, 

Additional context:
Linux Ubuntu, Python 3

**Comment by pedrobaeza** [comment]
Please give more details.

**Comment by SirSkyr** [comment]
The details have been updated, forgot to replace the headings. I have attached a photo of what I am describing @pedrobaeza 
![Web Responsive, Action Button](https://user-images.githubusercontent.com/85331763/198904468-9a14b3fe-f946-4314-b8ce-7203e4398219.png)

**Comment by SplashS** [comment]
@SirSkyr, hello!
Please try to reproduce problem on the last build on runboat. https://runboat.odoo-community.org/webui/builds.html?repo=OCA/web&target_branch=15.0
At the moment it seems like you have side effect from some 3rd party module you have installed.

**Comment by SirSkyr** [comment]
@SplashS Thanks for following up, I was worried that might be the case. I have no idea how I'm going to reproduce it as I have close to 60-70 3rd party modules installed. Do you think there is any chance, I could potentially make a theme module and attempt to override the formatting of the button dropdown?

**Comment by SirSkyr** [comment]
After some further testing throughout today, I have found no repeatability or linkage to web responsive.  Thank you for your time, I apologize for any undue error checking on your behalf. It seems to be an issue from something else, and seeing as web responsive was the only module installed that implemented a new UI or affected the CSS directly it is extremely odd. 

All the best

**Comment by SirSkyr** [comment]
Fixed It, Turns out that the sales, inventory and purchase all in one report modules by cybrosys was replacing the dropdown menu buttons with incomplete settings for the dropdown menu resulting in removing the pre-existing css settings.
