### ISSUE TITLE
[15.0] web_responsive: Down-Arrow icon missing on ecommerce product menu bar of internal users

### ISSUE THREAD

**Issue by Ranamiu** [OCA/web#2333]
First of all thank you for this usefull addon !
Appreciate your work. 

Down-Arrow icon is missing on ecommerce product menu bar of internal users. User can clic on in order to diplsay "Edit in back-end". However arrow icon is missing.

## Module
Web Responsive (web_responsive)

## Describe the bug
Arrow icon is missing on ecommerce product menu bar of internal usersr. User can clic on in order to display "Edit in back-end". However arrow icon is missing.

## To Reproduce
**Affected versions**:Tested on Web Responsive 15.0.1.1.3 - Odoo 15.0-20221029 (Community Edition)

1. Install Web Responsive 15.0.1.1.3 (latest version available).
2. Install eCommerce.
3. Create any Product and clic on "Got to Website".
4. Down-Arrow icon is missing on ecommerce product menu bar of internal users.

**Expected behavior**
Down-Arrow icon to be displayed on ecommerce product menu bar of internal users 

Many thanks

Please find here screen shots:
![edit-backend2](https://user-images.githubusercontent.com/29396762/200901711-f826dcae-db07-4e75-9908-c3c86d6c6286.png)
![edit-backend](https://user-images.githubusercontent.com/29396762/200901714-626d280b-53fb-46d2-8611-0ba44730e0d6.png)

**Comment by pedrobaeza** [comment]
I confirm the problem on runboat. You are still able to click on the zone, but not arrow is shown.

@SplashS can you please check?

**Comment by Ranamiu** [comment]
Hi @SplashS , @pedrobaeza: 

Many thanks

Appreciate

**Comment by pedrobaeza** [comment]
Please try the pull request in runboat and check if it works.

**Comment by Ranamiu** [comment]
Tried on local installation and can confirm OK, being fixed.

Thank you @pedrobaeza for following up.

Appreciate
