### ISSUE TITLE
[web_responsive] hide browser address bar on mobile

### ISSUE THREAD

**Issue by diggy128** [OCA/web#2334]
**Is your feature request related to a problem?**
When on a mobile device you lose screen estate because of the space occupied by the address bar.

**Describe the solution you'd like**
Hide the browser address bar when scrolling, much like the form header part.
Ideally there could be an option to view page full screen (eg like [here](https://techwithtech.com/full-screen-chrome-android/))

**Comment by pedrobaeza** [comment]
This is not a responsive feature. Use PWA for that.
