### ISSUE TITLE
Whats going to happen to web_responsive in version 16.0

### ISSUE THREAD

**Issue by nimarosa** [OCA/web#2336]
Version 16.0 is responsive directly from odoo code. Also the UI changed, so i think that will be a big migration. What i like about web_responsive is the apps drawer, i don't like the community version dropdown. 

Are we going to migrate the module to 16.0 or makes sense to create another module with interface improvements? Since responsiveness is now a base feature of odoo.

**Comment by pedrobaeza** [comment]
Yes, the app switcher plus other tweaks like keyboard shortcuts from v15 responsive may be helpful to be in an OCA module. @SplashS was the last one working on it, and I don't know if he plans to do something for this version.

**Comment by SplashS** [comment]
Hello!
Yes, I plan to do migration for web_responsive.
I have migrated app switcher. I’m left with migrating Attachment Viewer and some tweaks like sticky table header and footer.

The biggest one problem now that Activity view didn’t ported to owl and has no responsive search bar in 16.0. I plan to migrate some code to make it responsive. 

So I think that web_responsive name should stay here.

Let me take this opportunity to ask a couple of questions:

1. web_responsive has option for user to place chatter on the right or on the bottom of form. Should we keep this option for 16.0?
2. App switcher in enterprise now uses command palette for keyboard search. web_responsive has separate code for this and I see long term problem for this duplication. May be we should use command palette for this too?
3. App switcher in enterprise realized as separate action. In web_responsive we have legacy behavior of dropdown. This leads to some problems, like form validation happens only on app click but not on app switcher opening. May be we should use similar behavior?

**Comment by youring** [comment]
Hello @SplashS Thank you for the long term contribution! 

1. web_chatter_position https://github.com/OCA/web/pull/2260 exist in V15, but it's incompatible with web_responsive. I think it will need some clean up to be co-work with the new web_responsive. So, IMO chatter position to be in a split module.
2. it's too techy for me as a functional user to comment, but I think it good to change earlier than late to cope with EE.
3. form validation on app click is more reasonable fmpov. But still comply with EE maybe better in the long run.

BTW, i have an idea just for you all. Make a new repo for backend theme related stuff since the web root folder seems now a little bit crowded :)
web_theme_classic
web_theme_responsive (web_responsive), or split the functions to web_app_switcher(web_drawer), web_keyboard_shortcut, etc...and do pr in odoo core for responsive stuff.
web_chatter_position
web_sheet_full_width
web_dialog_size 
web_company_color
...

Just my 2 cents.

**Comment by pedrobaeza** [comment]
Thanks for continuing the work, @SplashS 

Answering your questions:


> web_responsive has option for user to place chatter on the right or on the bottom of form. Should we keep this option for 16.0?

I think we can rip such feature, and let a future compatibility with `web_chatter_position` for those wanting both.

> App switcher in enterprise now uses command palette for keyboard search. web_responsive has separate code for this and I see long term problem for this duplication. May be we should use command palette for this too?

Tested on runbot, and the search seems a bit more limited. Example: typing "projecttask" doesn't find the task menu inside project section. But if this is going to light a lot the development, we can assume the loss.

> App switcher in enterprise realized as separate action. In web_responsive we have legacy behavior of dropdown. This leads to some problems, like form validation happens only on app click but not on app switcher opening. May be we should use similar behavior?

I like to not having to discard the edition of my current record if I click on the app switcher, and only when clicking on the final action, the message appears. This behavior allows me to this flow:

- I'm editing a record.
- I remember something and open the app switcher to search for the menu and ctrl+click opens it in another tab.
- I close the app switcher with Esc and continue in this tab with the edition.

So if this behavior can be continued easily, I prefer it. If there's a technical challenge for that, then another thing that we can assume.

About splitting this module across several ones, I think we can keep it together being very close "fine-tunings".

**Comment by nimarosa** [comment]
Hello @SplashS thanks for your response and great web_responsive module, i use it a lot. 
About your questions: 

> 1. web_responsive has option for user to place chatter on the right or on the bottom of form. Should we keep this option for 16.0?

I think that if we have another module for that, we can remove it from web_reponsive. I always use chatter on the right, i don't know if this is the default or not. I like the functionality but if only module covers it, great. 

> 2. App switcher in enterprise now uses command palette for keyboard search. web_responsive has separate code for this and I see long term problem for this duplication. Maybe we should use command palette for this too?

I like the web_responsive way of doing it. Like Pedro said, i would like to maintain that functionality but if it's very complex or you think we should remove it, it's okay for me. 

> 3. App switcher in enterprise realized as separate action. In web_responsive we have legacy behavior of dropdown. This leads to some problems, like form validation happens only on app click but not on app switcher opening. Maybe we should use similar behavior?

I also vote for dropdown behaviour. In v16, edit mode is done only by clicking on the field, so opening the drawer must not cancel the edition or changes made. So i think we can maintain that for web_responsive, and also think it's the a better way of doing it. 

---

About the other suggestions in this thread about splitting the module, i think we should not. web_responsive module it's great at it is and splitting it will be more hassle to fast install and have everything available. 

Also a suggestion, i noted that in v14 version (i don't know v15) when you open a menu or drawer app with ( right-click > open in new tab ) the main menus are not shown, reloading the page fixes it but i think it's a easy fix to do. 

Another one will be, allow choosing the app-drawer background or maybe add business logo. But it's not a crucial one, such one I will like to see. 

Thanks for your good work and let us know if you need any help.

**Comment by liebana** [comment]
Hello! We're also giving a thought to this issue. Any updates or news not commented? @SplashS

**Comment by legalsylvain** [comment]
here is a first try of migration, FYI. : https://github.com/OCA/web/pull/2405

**Comment by phutungthanhlong** [comment]
I've got this error when install the module on odoo.sh

> Failed to load registry Traceback (most recent call last):   File "/home/odoo/src/odoo/odoo/modules/registry.py", line 90, in new     odoo.modules.load_modules(registry, force_demo, status, update_module)   File "/home/odoo/src/odoo/odoo/modules/loading.py", line 455, in load_modules     modules.button_install()   File "<decorator-gen-73>", line 2, in button_install   File "/home/odoo/src/odoo/odoo/addons/base/models/ir_module.py", line 76, in check_and_log     return method(self, *args, **kwargs)   File "/home/odoo/src/odoo/odoo/addons/base/models/ir_module.py", line 447, in button_install     raise UserError(msg % (module.shortdesc, exclusion.exclusion_id.shortdesc)) odoo.exceptions.UserError: Modules "Web Responsive" and "Web Enterprise" are incompatible.

**Comment by rvalyi** [comment]
> I've got this error when install the module on odoo.sh
> 
> > Failed to load registry Traceback (most recent call last):   File "/home/odoo/src/odoo/odoo/modules/registry.py", line 90, in new     odoo.modules.load_modules(registry, force_demo, status, update_module)   File "/home/odoo/src/odoo/odoo/modules/loading.py", line 455, in load_modules     modules.button_install()   File "", line 2, in button_install   File "/home/odoo/src/odoo/odoo/addons/base/models/ir_module.py", line 76, in check_and_log     return method(self, *args, **kwargs)   File "/home/odoo/src/odoo/odoo/addons/base/models/ir_module.py", line 447, in button_install     raise UserError(msg % (module.shortdesc, exclusion.exclusion_id.shortdesc)) odoo.exceptions.UserError: Modules "Web Responsive" and "Web Enterprise" are incompatible.

Well this is exactly what it means: if you have Odoo Enterprise you cannot use the OCA web_responsive module. A few modules like this overlap and are not compatible between the OCA and Odoo EE, but that's only a few modules, web_responsive is one of them.

**Comment by pedrobaeza** [comment]
Module already migrated, and the other question is off-topic, so closing.
