### ISSUE TITLE
[14.0][BUG]support_branding: error when accessing any page without admin permissions.

### ISSUE THREAD

**Issue by HekkiMelody** [OCA/web#2360]
## Module
support_branding

## Describe the bug
Cannot access any page due to not being able to read ir.config_settings. Most likely due to calls in javascript such as this one:
https://github.com/OCA/web/blob/0253aa72c554cbaf68080725dd091ce74162bf9a/support_branding/static/src/js/user_menu.js#L11-L24

## To Reproduce
**Affected versions**: 14.0

1. Install support_branding
2. Login as demo user (or any user without Administrative privileges)

![image](https://user-images.githubusercontent.com/78726989/207291305-e6b5b85c-4a2a-4ebd-8cc8-95b09847f3d3.png)

**Comment by KKamaa** [comment]
@aleuffre this bug has been fixed [here](https://github.com/OCA/web/pull/2399), sorry for the late reply.

**Comment by HekkiMelody** [comment]
Thanks a lot, I'll take a look!

**Comment by thomaspaulb** [comment]
@OCA/web-maintainers This is fixed and can be closed.
