### ISSUE TITLE
15.0 web_responsive issue with displaying filters

### ISSUE THREAD

**Issue by mthiermann** [OCA/web#2377]
Issue with displaying filters 
if the text of a field which is already filtered is to long, it is impossible to filter another field because of incorrect rendering

<img width="645" alt="Bildschirm­foto 2023-01-02 um 09 37 28" src="https://user-images.githubusercontent.com/92148479/210209199-167b608b-eaa1-4c67-8b02-c3508c41f9f0.png">

**Comment by minhthie** [comment]
![image](https://user-images.githubusercontent.com/122088215/212290197-786dd64c-d7f3-4c65-bac4-a4e81614ee45.png)
I'm trying to reproduce the issue but it seems to work fine. Could you provide more details on how to reproduce it?

**Comment by mthiermann** [comment]
Filter a field with a long name string. Example, filter in contacts the field "Companies that refers to partner" with an value then apply. Try now to filter another field. For me it looks like in the screenshot and it is no longer possible to filter any further field.

<img width="1342" alt="Bildschirm­foto 2023-01-13 um 11 03 33" src="https://user-images.githubusercontent.com/92148479/212293001-0521ff4d-75aa-4d7f-bb3d-6b3c09452fb3.png">

**Comment by minhthie** [comment]
![image](https://user-images.githubusercontent.com/122088215/212294175-35416879-c076-45f6-9a35-daaf3ec045ce.png)
For me it works just fine. I'm using Chrome. What browser do you use? Maybe try switching your browser

**Comment by mthiermann** [comment]
oh, yes it works fine in chrome, my fault. I'm mostly using Safari and on linux Epiphany. Both using webkit..

**Comment by pedrobaeza** [comment]
Safari is not supported officially. Switch browser or contribute with the needed patch to make it compatible.
