### ISSUE TITLE
web_export_view : standard export function not working after install this

### ISSUE THREAD

**Issue by GoodERPJeff** [OCA/web#239]
# openerp 8.0
# install web_export_view
# on module list, more-export, select a field to export, then select excel format

result:
## Uncaught SyntaxError: Unexpected token T

http://localhost:4069/web?#page=0&limit=80&view_type=list&model=ir.module.module&action=37:7

export as csv format is working

export excel format without web_export_view is working

**Comment by eLBati** [comment]
Hello @OpenERPJeff , just tried the step you describe on
http://3117128-8-0-99c83e.runbot1.odoo-community.org/web?db=3117128-8-0-99c83e-base
and I am able to download the excel file.
So, I can't reproduce the error

**Comment by GoodERPJeff** [comment]
Thank you for you reply!

I did check my version and found there is a old version module(8.0.1.2 at Feb 2015) in my addons path

I removed it and install newest version in my db, it works now

I guess this patch fixed this issue https://github.com/OCA/web/commit/fc0c62e411361b25de8f5498323e3a5afb46795a
