### ISSUE TITLE
Module not supported in Odoo v16

### ISSUE THREAD

**Issue by paulo-novobi** [OCA/web#2393]
module: web_m2x_options
version: 15.0

**Steps to reproduce**
- Install the web_m2x_options module on Odoo v16
- Create the following system parameters:
      - web_m2x_options.create: False
      - web_m2x_options.create_edit: False
      - web_m2x_options.m2o_dialog: False
      - web_m2x_options.limit: 10
      - web_m2x_options.search_more: False
      - web_m2x_options.field_limit_entries: 5

**Current behavior**
Search more, create o create and edit still appears in the many2one fields 

**Expected behavior**
Search more, create o create and edit should not appears in the many2one fields

**Comment by legalsylvain** [comment]
Hi. V15 module can not work on V16 instance. 
no bug here !
Thanks !
