### ISSUE TITLE
[15.0] web_responsive module Blank page

### ISSUE THREAD

**Issue by bvanjeelharia** [OCA/web#2410]
## Module
web_responsive

## Describe the bug
A blank page opens up on pressing Alt + A (shortcut for home page) if there is no app opened before.

## To Reproduce
**Affected versions**:15.0

1.Login to an odoo instance with web_responsive module installed
2.Once the home page(backend) is loaded, press Alt+A 
3.A blank page would open up

**Expected behavior**
Nothing should happen if there's no app opened prior to pressing Alt+A on home page.

**Comment by pedrobaeza** [comment]
Is this reproducible on runboat?

**Comment by bvanjeelharia** [comment]
@pedrobaeza , yes its reproducible on runboat

**Comment by pedrobaeza** [comment]
OK, seen. It's the same as clicking on the AppSwitcher icon. Which behavior do you expect? I don't see this as something bad, as we don't need to pre-load for example the discuss app if you are not going to navigate to it. I see that you say that is fixed for 16.0. How did you fix it?

**Comment by bvanjeelharia** [comment]
I expect the system not to take me to a blank page.For 16.0, I have made changes so that the system doesn't open up the blank page. Instead it stays on the home page.

**Comment by pedrobaeza** [comment]
OK, then please apply the same fix in a new PR to 15.0. Another controversial feature is to leave the AppSwitcher opened when landing on Odoo after login. I don't like too much that option.

**Comment by bvanjeelharia** [comment]
Ok, I will apply the same fix in a PR.Once I apply this change the AppSwitcher wouldn't be opened when landing on Odoo after login
