### ISSUE TITLE
[15.0] web_responsive module header from attachment viewer visible on home page

### ISSUE THREAD

**Issue by bvanjeelharia** [OCA/web#2416]
## Module
web_responsive

## Describe the bug
If you open the attachment viewer on any of the documents and if you go to homepage(backend),header from attachment viewer isvisible on home page

## To Reproduce
**Affected versions**:15.0

1.Open the attachment viewer on any of the documents
2.Go to the home page
3.The header from attachment viewer is still visible , which covers the system tray

**Expected behavior**
The attachment viewer header should not be visible once we are on the home page.

**Comment by bvanjeelharia** [comment]
Also, affecting version 14.0 and 13.0 as well

**Comment by bvanjeelharia** [comment]
@pedrobaeza , can you please check this

**Comment by pedrobaeza** [comment]
Hi, @bvanjeelharia. I can only confirm what you say, but I'm afraid I don't have the skills for solving it, not knowing JS in depth or the CSS structure.

**Comment by bvanjeelharia** [comment]
Hey, @pedrobaeza , I already have the solution for the same, would raise a PR for it

**Comment by bvanjeelharia** [comment]
Also found another bug wherein if you open an attachment in attachment viewer and go to the home page(without closing the attachment viewer) and go to some other app, it would show up the same attachment

**Comment by pedrobaeza** [comment]
Fixed by #2424
