### ISSUE TITLE
Odoo 16 Enterprise : Missing dependencies:      Array [ "@odoo/owl" ]

### ISSUE THREAD

**Issue by zohaibrehman** [OCA/web#2420]
I installed a odoo 16 E and after creating a database then logging in the page does not display anything. 
On inspecting the browser i see these errors:

![image](https://user-images.githubusercontent.com/16989790/221894348-e5980a89-11c8-4b73-87ed-1bf49b6013f7.png)

Not sure what is the reason for the error.

**Comment by pedrobaeza** [comment]
This is not related to any module on this repository, and less being enterprise. Please put the issue in its proper place.
