### ISSUE TITLE
[15.0] Start page now is always Inbox (Conversations)

### ISSUE THREAD

**Issue by jrg-io** [OCA/web#2423]
## Module
web_responsive

## Describe the bug
Since last version, when access to the site, it always opens by default the Inbox, into the Conversations app. Before this version, the dashboard was opened with access to every application available (more convenient for most users, imho).

## To Reproduce
**Affected versions**: 15.0.1.1.6

1. Navigate to your Odoo site.
2. Inbox page is opened.

**Expected behavior**
The dashboard is opened, with icons for every application available.

**Comment by pedrobaeza** [comment]
This is something intended, as the home action defined at user level (inbox if not defined) was not accessible. This behavior is consistent also with previous versions.

Why is this a problem?

**Comment by jrg-io** [comment]
@pedrobaeza this is what I see with previous version with empty value for home action:

![image](https://user-images.githubusercontent.com/17880216/222289810-bb0a458b-4c6a-4b3c-aa7a-4474ec183eee.png)

AFAIK this action is not selectable from the Home action user preferences, and for me is very useful to get the list of available applications as main screen.

**Comment by pedrobaeza** [comment]
Well, that's only one click away, so it's not a big deal. You can contribute anyway with such extra feature, but respecting the original behavior, or stay in the previous revision.
