### ISSUE TITLE
[16.0][BUG] web_responsive : menus for dates in filter show on top of opened menu

### ISSUE THREAD

**Issue by remi-filament** [OCA/web#2436]
## Module
web_responsive

## Describe the bug
When clicking on Filters menu and selecting an existing filter with dates (meaning it opens a submenu for selecting granularity), the submenu is shown on top of the line (although after the text). 

Filters :
![image](https://user-images.githubusercontent.com/30716308/223751133-01c52ed8-7d77-4c07-b899-5c64bad6c308.png)

## To Reproduce
**Affected versions**: 16.0

1. Open CRM app (for instance, any object with predefined filter on date has the same behavior)
2. Click on filter, then select Creation Date > (or any Date filter)

**Expected behavior**
Submenu is expected to show on the right of the first level menu (after >), like it is done in Group by field (and by default in Odoo) :
Group by :
![image](https://user-images.githubusercontent.com/30716308/223751311-c022f2ac-c8a6-425d-b3bf-aed5d8208a27.png)

**Comment by youring** [comment]
Maybe line 183 in web_responsive/static/src/components/control_panel/control_panel.scss caused this. Just commented out this line and haven't found any side effect.
`            width: auto;`

BTW, while testing on this issue, I found another bug in odoo core. FTR: https://github.com/odoo/odoo/issues/114716
