### ISSUE TITLE
[16] Disable autocomplete on date fields.

### ISSUE THREAD

**Issue by sta0003** [OCA/web#2438]
**Is your feature request related to a problem?**
If so, please provide clear and concise description of what the problem is.
Unable to select dates as auto-complete fields of the web browser cover whole selection area.
**Describe the solution you'd like**
A simple addon that disables the webbrowsers ability to provide autocomplete to date selection fields

**Describe alternatives you've considered**
Found a solution for odoo 12 but has not been upgraded to odoo 16

**Comment by legalsylvain** [comment]
Hi. @sta0003 

it is not necessary to open tickets to request that modules be migrated. (https://github.com/OCA/sale-workflow/issues/2360)

You can open a PR if you have the skills to do the migration, or ask an integrator to do the work, if you have the budget.

kind regards.
