### ISSUE TITLE
[16.0][BUG] web_responsive: Is not applying correctly the translations on button "+ Create"

### ISSUE THREAD

**Issue by kikopeiro** [OCA/web#2439]
## Module
web_responsive

## Describe the bug

After installing the web_responsive module I have detected that the text of the "+ CREATE" button appears without translation". Translation doesn't seem to be the problem

![Selección_736](https://user-images.githubusercontent.com/4610000/224015888-46015c28-1143-4a7d-a5ca-519ee977dec4.png)

and...

![Selección_737](https://user-images.githubusercontent.com/4610000/224018077-2a303262-63a3-4e70-8ae3-055e1b445ea9.png)

Without web_responsive module the button appears to be different

![Selección_734](https://user-images.githubusercontent.com/4610000/224016767-57415b7c-8133-4221-9075-2e6a254c6f91.png)

and in this case the translation is working OK

![Selección_733](https://user-images.githubusercontent.com/4610000/224016902-456fa82c-b1f7-4cfa-947a-39b40345e812.png)

## To Reproduce
**Affected versions**: 16.0

1. Without web_responsive installed -> Button "New" appears
2. Install module web_responsive -> Button "New" has become button "+ Create"
3. Change language in user preferences (for example Spanish)
4. Button "+ create"  appears withou translation

**Expected behavior**
Button "New" and other buttons on header as appears without module web_responsive installed

**Comment by kikopeiro** [comment]
CC @bvanjeelharia

**Comment by legalsylvain** [comment]
Hi. 

odoo changed recently the name of the button on the stable V16 version. (fev, 23, 2023).

See : https://github.com/odoo/odoo/pull/112118

So the naming is not aligned anymore.

well, that's not a "bug" of the module, but indeed, it could be aligned.

regarding translation, you should anyway use weblate to translate term of OCA modules.

**Comment by kikopeiro** [comment]
> Hi.
> 
> odoo changed recently the name of the button on the stable V16 version. (fev, 23, 2023).
> 
> See : [odoo/odoo#112118](https://github.com/odoo/odoo/pull/112118)
> 
> So the naming is not aligned anymore.
> 
> well, that's not a "bug" of the module, but indeed, it could be aligned.
> 
> regarding translation, you should anyway use weblate to translate term of OCA modules.

Thanks @legalsylvain for the explanation, I understand the problem of the difference in the texts of the buttons.... OK!

However, regarding the translations they don't seem to be applying correctly to that button despite being correctly translated in the corresponding "po" file -> https://github.com/OCA/web/blob/16.0/web_responsive/i18n/es.po#L61

**Comment by pedrobaeza** [comment]
On the code, it can be changed to `+ New` for being aligned. The idea of this feature is to let only the + on small devices. The problem could be that the text is not applied with translation (lazy or not).

**Comment by legalsylvain** [comment]
> The problem could be that the text is not applied with translation (lazy or not).

Maybe it's because there is a space before "create". (just an idea, not tested).
https://github.com/OCA/web/blob/16.0/web_responsive/static/src/legacy/xml/form_buttons.xml#L41
https://github.com/OCA/web/blob/16.0/web_responsive/static/src/legacy/xml/form_buttons.xml#L66
https://github.com/OCA/web/blob/16.0/web_responsive/static/src/legacy/xml/form_buttons.xml#L105

**Comment by hugosantosred** [comment]
I've been testing the translation making changes to the form_view template.

The problem seems to happen when the web_responsive.icon_button template is rendered, the label comes untranslated to this template and rendering that label variable with the t-esc (also tried with t-out) is not using the translation system.

I've changed the template to use the Create text directly instead of label variable and the text is translated. For example with this code (Only for test purposes) works:

```xml
<t t-name="web_responsive.icon_button" owl="1">
        <i t-attf-class="fa fa-#{icon}" t-att-title="label" />
        <span class="d-none d-sm-inline"> Create</span>
    </t>
```

**Comment by bvanjeelharia** [comment]
Yes @hugosantosred , that is the case

**Comment by bvanjeelharia** [comment]
> > The problem could be that the text is not applied with translation (lazy or not).
> 
> Maybe it's because there is a space before "create". (just an idea, not tested). https://github.com/OCA/web/blob/16.0/web_responsive/static/src/legacy/xml/form_buttons.xml#L41 https://github.com/OCA/web/blob/16.0/web_responsive/static/src/legacy/xml/form_buttons.xml#L66 https://github.com/OCA/web/blob/16.0/web_responsive/static/src/legacy/xml/form_buttons.xml#L105

That is not the problem, its what @hugosantosred mentioned

**Comment by bvanjeelharia** [comment]
@legalsylvain , can we have a separate icon button defined for each of the button templates(as shown by @hugosantosred) rather than calling a separate template with t-esc as its working this way and not otherwise

**Comment by liebana** [comment]
@bvanjeelharia do you want us to make the proper changes or do you rather do it by yourself?

**Comment by bvanjeelharia** [comment]
@liebana , you can make the changes, thanks !

**Comment by hugosantosred** [comment]
@bvanjeelharia Changes done in #2473

**Comment by liebana** [comment]
> @liebana , you can make the changes, thanks !

Here you go!
