### ISSUE TITLE
Suggestion table head float

### ISSUE THREAD

**Issue by angelmoya** [OCA/web#246]
I would be nice if table head were float, like in this link:

http://mkoryak.github.io/floatThead/

**Comment by angelmoya** [comment]
I try to add js lib in xml, and then put this code in javascrit console and works... but I don't how can I do a module with this code

``` javascript
var $table = $("table.oe_list_content");
$table.floatThead({
    scrollContainer: function($table){
        return $table.closest('.wrapper');
    }
});
```

**Comment by angelmoya** [comment]
I'm working in #247

**Comment by pedrobaeza** [comment]
Closing as there is a PR on progress.
