### ISSUE TITLE
[14.0] [BUG] web_sheet_full_width in enterprise 14

### ISSUE THREAD

**Issue by odooNextev** [OCA/web#2477]
We noticed that in EE v14 web_sheet_full_width doesnt'work.
We followed @Jerther suggestion and with his code it's work.

#2239
```
.o_form_view {
    @include media-breakpoint-up(md) {
        display: block;
    }
    @include media-breakpoint-up(xl) {
        display: block;
        .o_form_sheet_bg > .o_form_sheet {
            max-width: 100% !important;
        }
    }
    @include media-breakpoint-up(xxl) {
        display: block;
        .o_FormRenderer_chatterContainer {
            width: auto;
            max-width: 1474px;
        }
    }
    .o_form_sheet_bg {
        width: auto !important;;
    }
}

```

Works well here and has been since v14!

_Originally posted by @Jerther in https://github.com/OCA/web/issues/2239#issuecomment-1180737259_

**Comment by legalsylvain** [comment]
Hi. @odooNextev. Thanks for providing a bugfix. Could you make a PR ? 
thanks !

**Comment by pedrobaeza** [comment]
And it should be compatible with both community and enterprise, being community the main one.

**Comment by legalsylvain** [comment]
> And it should be compatible with both community and enterprise, being community the main one.

:+1: Otherwise, I think you can make a dedicated module ``web_sheet_full_width_ee`` and put a link on the readme of the OCA module to mention that an extra module is required to ensure compatibility with EE.
