### ISSUE TITLE
[16.0][BUG] web_responsive: create button not translated

### ISSUE THREAD

**Issue by stmar** [OCA/web#2478]
## Module
web_responsive

## Describe the bug
When the module is not installed, the create button is translated. When the module is installed, the create button is not translated anymore.

## To Reproduce
16.0

**Comment by legalsylvain** [comment]
Hi. You should use oca weblate to translate the terms of the module. 

Thanks !

**Comment by pedrobaeza** [comment]
And use the latest version where it was changed to `New` IIRC.

**Comment by stmar** [comment]
Hi. The installed language is french and the module already offers the french translation. The term "Create" is translated in the po file but it is not applied.

**Comment by stmar** [comment]
Sorry the code was not uptodate. It's ok now. Thanks
