### ISSUE TITLE
[16.0] web_m2x_options: to much  get_web_m2x_options calls

### ISSUE THREAD

**Issue by fmdl** [OCA/web#2494]
When you load a page there are lot call to get_web_m2x_options

![image](https://user-images.githubusercontent.com/16716992/235946812-7bd6d505-6830-4d26-98d4-051f6b6a9b22.png)

Can you reduce that ?

@anothingguy

**Comment by rinaldifirdaus** [comment]
found the same issue here, and it impacts to performance when opening some page became much slower.. especially when the page has many records.

**Comment by anothingguy** [comment]
yes, I think this is an improvement instead of a bug. I will work on it soon, thanks for the report

**Comment by fmdl** [comment]
@anothingguy do you have find a solution ?

Regards

**Comment by rinaldifirdaus** [comment]
@anothingguy , any update for this improvement?

**Comment by auroraeosrose** [comment]
At this point it makes the extension unusable because of the extra load.  I would categorize this as a bug, not an improvement.  It didn't do this in v14.

**Comment by nguyenminhchien** [comment]
Hello,
i have added this PR https://github.com/OCA/web/pull/2575 to fix this issue
