### ISSUE TITLE
[15.0][16.0] web_responsive: Hotkeys Z and X overlapping

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/web#2504]
Since v15, the hotkeys for previous and next records were changed to Z / X instead of P / N (https://github.com/OCA/web/pull/2058#issuecomment-950364154). The goal of this is to control everything with one hand on QWERTY/AZERTY keyboards.

But this has a side effect, which is that if there can be certain elements using such keys already. Example:

![Selección_037](https://github.com/OCA/web/assets/7165771/f8b1a8f0-c1d4-41aa-8d93-b7fd949e8cbd)

Possible options:

1. Restore pager shortcuts to standard P / N.
2. Forbid the use of Z / X in other places. Not sure how...

I would go for 1, but let's see what others think.

**Comment by pedrobaeza** [comment]
@SplashS @bvanjeelharia @Tardo @Yajo

**Comment by Tardo** [comment]
There are two ways to define these keys:
- accesskey
- data-hotkey

Seeing the number of places where 'data-hotkey' is used, I agree that it would be best to restore the standard.

**Comment by yajo** [comment]
I prefer option 1 too.

**Comment by liebana** [comment]
:+1: to option 1

**Comment by mohamedhagag** [comment]
option 1 plz
defaults are always good
