### ISSUE TITLE
[web_respnosive]: WHY change the default keys ??

### ISSUE THREAD

**Issue by mohamedhagag** [OCA/web#2517]
https://github.com/OCA/web/blob/d30d75b3b01c7a85597c070e0552f582a1a804cd/web_responsive/static/src/components/hotkey/hotkey.xml#L31
https://github.com/OCA/web/blob/d30d75b3b01c7a85597c070e0552f582a1a804cd/web_responsive/static/src/components/hotkey/hotkey.xml#L36

## Why we change the default keys ??!!
Any reason for this ? or it's only for the **sake of being different** ??!!

**Comment by pedrobaeza** [comment]
## Why don't you do a little search before posting? 


It's the latest issue: #2504
