### ISSUE TITLE
[16.0] web_responsive: Document viewer and web browsers incompatibilites

### ISSUE THREAD

**Issue by kikopeiro** [OCA/web#2524]
## Module
web_resposive
## Describe the bug

Working with Chromium (not Chrome) or Firefox web browser,  when open an PDF (for example invoice) with document viewer the invoice form is shown in non editable mode.

### Firefox
![Selección_871](https://github.com/OCA/web/assets/4610000/fb8f4d1e-f36b-4a4d-82c5-75fbb51b3dce)

### Chrome

![Selección_872](https://github.com/OCA/web/assets/4610000/0d24febd-57c8-4cfb-ba60-c90cf3956c40)

## To Reproduce
**Affected versions**: Odoo 16 community (at least)

1. Open an invoice and attach a pdf file
2. Try to edit the invoice with the document viewer openned

**Expected behavior**

While using document viewer, it must allow to edit the invoice

**Comment by youring** [comment]
Hi @kikopeiro I have tested on [runboat](https://runboat.odoo-community.org/webui/builds.html?repo=OCA/web&target_branch=16.0) with Firefox Developer Edition, not reproducible.

**Comment by ap-wtioit** [comment]
@youring can reproduce it on http://oca-web-16-0-387e7d238732.runboat.odoo-community.org/web#id=3&cids=1&menu_id=115&action=231&model=account.move&view_type=form

Chrome: 
![image](https://github.com/OCA/web/assets/38032588/a7697160-41eb-48d6-89a0-51cd1c62d3a6)

Firefox:
![image](https://github.com/OCA/web/assets/38032588/cf25eedd-2031-4aea-98ce-06ec8e6ecd99)

The following CSS is not applied in Firefox to `.o_DialogManager_dialog`:
```css
@media (min-width: 1533px) {
    .o_web_client .o_DialogManager_dialog:not(:has(.o_AttachmentDeleteConfirm)) {
        position: static;
    }
    ...
}
```
which is this line https://github.com/OCA/web/blob/16.0/web_responsive/static/src/components/attachment_viewer/attachment_viewer.scss#L9

And that is consitent with:
* https://stackoverflow.com/q/73936048/925125
* refering to https://caniuse.com/?search=has

Looks like to support Firefox we cannot use `:has` yet

**Comment by youring** [comment]
Oh... I forgot that i have enabled layout.css.has-selector.enabled in Firefox advanced preferences (about:config) a few months ago.
Firefox doesn't support :has class by default.
Seems this need to be declared in readme/usage.

**Comment by pedrobaeza** [comment]
Isn't an alternative way to do the same in the module without that `:has` feature?

**Comment by kikopeiro** [comment]
Seems `:has` feature is supported!


![Selección_1650](https://github.com/OCA/web/assets/4610000/ccf1d9b5-9603-4e4d-9db6-d18c6a146d71)


https://developer.mozilla.org/es/docs/Web/CSS/:has?_gl=1*1ak9hr8*_ga*MTcwMTM5MjM0My4xNzE0NDAyNTk0*_ga_MQ7767QQQW*MTcxNDQwMjU5My4xLjAuMTcxNDQwMjU5My4wLjAuMA..
