### ISSUE TITLE
web_export_view Is this module available for version 15?

### ISSUE THREAD

**Issue by cnunezd** [OCA/web#2529]
**Is your feature request related to a problem?**
If so, please provide clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
![WhatsApp Image 2023-06-09 at 12 19 34 PM](https://github.com/OCA/web/assets/71851428/d45550ad-47de-4cc5-a0dc-273a96401c1d)

Add any other context about the feature request here.

**Comment by legalsylvain** [comment]
No.
See https://github.com/OCA/web/tree/15.0
