### ISSUE TITLE
Can I creat a 

### ISSUE THREAD

**Issue by seblveb** [OCA/web#2550]
Hello, I would like to ask if I can create a branch for Odoo 13 to adapt the 'web_calendar_color_field' module for the 13.0 Community version.

**Comment by pedrobaeza** [comment]
This is not how it works if you want to contribute to OCA. Check https://odoo-community.org/resources/code.

But this is open source, so you can do the things the license allows you to, which includes the manipulation of the source code while you don't close it or change the license.
