### ISSUE TITLE
Not working in Odoo 15 Enterprise

### ISSUE THREAD

**Issue by tariqivis** [OCA/web#2556]
module: web_pivot_computed_measure
version: 15.0

**Steps to reproduce**
installed on V15 Enterprise
- ...

**Current behavior**
when i check on odoo pivot view, computed measure option is not there.

**Expected behavior**
Expecting the same as defined in the description

**Comment by pedrobaeza** [comment]
I don't think the problem is with enterprise itself (but it could be). The compatibility is only expected with Odoo community and OCA ecosystem. Check on the runboat pointed by the README if the problem you find is reproducible, and if so, then you can report it back here. Meanwhile, closing this.

**Comment by tariqivis** [comment]
This module will not work with spreadsheet module.
