### ISSUE TITLE
Odoo 16: Dark Mode Permission Issues for Non-Admin Users

### ISSUE THREAD

**Issue by traderpedroso** [OCA/web#2586]
The dark mode is causing permission issues for non-administrative users. Is there something I can do to allow all users access to the dark mode option without compromising security and restrictions? I'm using Odoo 16.

**Comment by legalsylvain** [comment]
> The dark mode is causing permission issues for non-administrative users

could you elaborate ? or provide step to reproduce on runboat ?

**Comment by traderpedroso** [comment]
> > The dark mode is causing permission issues for non-administrative users
> 
> could you elaborate ? or provide step to reproduce on runboat ?

I simply set up a sample user, either a sales representative or a marketing user, without administrative rights. When this user attempts to enable dark mode, they receive a notification that they don't have permission.

**Comment by legalsylvain** [comment]
Tested on runboat. indeed.

![image](https://github.com/OCA/web/assets/3407482/85515767-b2d4-4d96-bbf1-016999501beb)

I guess the function ``SELF_WRITEABLE_FIELDS`` should be overloaded.
https://github.com/odoo/odoo/blob/16.0/odoo/addons/base/models/res_users.py#L295

could you provide a patch ? 

Thanks ! 

regards.

**Comment by ajjayymahato** [comment]
@traderpedroso @legalsylvain  Is anyone working on this issue or can I work on this? If yes please assign this to me.

**Comment by vincent-hatakeyama** [comment]
Fixed by https://github.com/OCA/web/commit/41736b109fbcdbe40644b62f7dd2f8dca3cc2828
