### ISSUE TITLE
[16.0] web_advanced_search: Uncaught Javascript Error > FIELD_OPERATORS[genericType] is undefined

### ISSUE THREAD

**Issue by Highcooley** [OCA/web#2611]
With the module web_advanced_search installed, accessing the filter menu (not even the advanced filter) will regularly throw the error "Uncaught Javascript Error > FIELD_OPERATORS[genericType] is undefined"

## Module
web_advanced_search

## Describe the bug
web_advanced_search introduces the field.type "relational" which apparently is not declared in FIELD_OPERATORS:
Object { binary: (2) […], boolean: (2) […], char: (6) […], json: (6) […], date: (9) […], datetime: (9) […], id: (1) […], number: (8) […], selection: (4) […] }

## To Reproduce
**Affected versions**: 16.0

Steps to reproduce the behaviour:
1. install web_advanced_search
2. Access e.g. the Accounting Reconciliation View
3. Set a custom filter (no need to set an advanced filter) e.g. to label is set
4. Click on the filter again and try to change it

**Expected behaviour**
The filter should be editable without throwing an error

**Additional context**

**Comment by pedrobaeza** [comment]
Maybe it's something of your specific DB with other modules installed. Are you able to replicate the problem in the runbot link?

**Comment by scrimo** [comment]
i got the same problem on a database which was upgraded from version 12.0.
when i uninstall web_advanced_search module, everything works fine.
when web_advanced_search module is installed, as soon as i click in the odoo default filter function on a relational field, the javascript error is thrown.

edit: tried uninstall and install again - same error

**Comment by pedrobaeza** [comment]
Do you have `date_range` installed? Can it be https://github.com/OCA/server-ux/issues/722?

**Comment by Highcooley** [comment]
Oh yes I have

**Comment by pedrobaeza** [comment]
Then we have "guilty". Let's track the problem in the other issue.
