### ISSUE TITLE
web_responsive Odoo online error 500 after install

### ISSUE THREAD

**Issue by yveveke** [OCA/web#2615]
## Module
The name of the module that has a bug.

web_responsive

## Describe the bug

I use Odoo online. Put my account in developer mode so I could install the module that I downloaded at https://apps.odoo.com/apps/modules/16.0/web_responsive/
I couldn't find the setting to put the chatter on the right, explained on the forum https://www.odoo.com/nl_NL/forum/help-1/odoo-12-chatter-on-the-right-side-not-at-the-bottom-171683
So I removed myself from developer mode and from then on, all links at /web give me a fatal error type 500

## To Reproduce
**Affected versions**:

Odoo online. Latest version 16

1. Install the module 
2. Exit developmer mode

**Expected behavior**

A setting at my profile, to move the chatter to the right

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by legalsylvain** [comment]
are you using web_responsive with odoo enterprise version ?

**Comment by pedrobaeza** [comment]
And Odoo online doesn't support custom modules. The import module option is only for data modules.
