### ISSUE TITLE
Clarification on the Necessity of web_responsive in Odoo 17

### ISSUE THREAD

**Issue by hafizhlf** [OCA/web#2665]
**Context**
In Odoo 17, there has been a significant improvement in the responsiveness of the overall user interface. The core system now adequately adapts to various screen sizes, making it more user-friendly on different devices.

**Proposed Solution**
Considering the enhanced responsiveness of Odoo 17, it is recommended to reassess the necessity of the web_responsive module. Users might benefit more from focusing on the Apps menu app, ensuring its compatibility and optimizing its features for a seamless experience on different screen sizes.

**Screenshot**

![image](https://github.com/OCA/web/assets/15645495/0f4e48aa-a295-4210-a8b9-273511d261fe)

**Comment by pedrobaeza** [comment]
Well, `web_responsive` should be adapted to this version in the color scheme, and the features, removing those that are native, or adding new needs for a continuity on the expected behavior.

**Comment by pedrobaeza** [comment]
Are you going to work on the migration then?

**Comment by hafizhlf** [comment]
At the moment, I'm unable to commit to the migration task due to other priorities. However, I'll keep communication open and may contribute from time to time when possible. Thank you for understanding.
