### ISSUE TITLE
[16.0] preview issues pdf on customer invoice/vendorbill in combination with addon  web_responsive

### ISSUE THREAD

**Issue by ThijsvOers** [OCA/web#2682]
## Module
web_responsive

## Describe the bug
Module web_responsive causes unwanted changes to the standard printpreview options for customer invoices/vendor bills.

1. I have tested this on this on runboat. Before uninstalling the web_responsive module I did not see the printpreview directly on opening the form as described in the readme. 
2. In the readme it says that I can maximize the preview. There is a maximize button, but then it maximizes in a way that i can no longer edit the vendorbill
3. When I open the printpreview I cannot see or use the chatter.

When I uninstall web_responsive all mentioned features are standard available again

I have added screenshots for points 1, 2 and 3 and also the standard view without web_responsive (the last screenprint shows the requested and wanted view)

![max view](https://github.com/OCA/web/assets/30256071/ce3a28e7-81dd-46d4-9c4f-f028eb05435e)
![No chatter](https://github.com/OCA/web/assets/30256071/effe2c51-2956-4b32-9913-41896931aff9)
![no direct preview](https://github.com/OCA/web/assets/30256071/a618045d-bec2-4ea5-a62d-b43ea7095400)
![standard](https://github.com/OCA/web/assets/30256071/929aecfb-fe68-455b-8a00-cbe41c2f3553)

**Comment by pedrobaeza** [comment]
The first point is on purpose: we don't want that any attachment is opened by default. And I don't see how maximizing the preview will have the form editable if it's on the background. Finally, the chatter is not pretended to be used while previewing any attachment.

**Comment by ThijsvOers** [comment]
Thank you for answering my remarks
