### ISSUE TITLE
[16.0] web_reponsive: the HTML styling toolbar doesn't appear when composing messages from chatters

### ISSUE THREAD

**Issue by marielejeune** [OCA/web#2709]
## Module
web_responsive

## Describe the bug
One wants to send a message from the chatter of any model. He opens the "full composer" to get the mail.compose.message wizard.
When writing the message body in the HTML field, it is impossible to open the HTML styling toolbar that allows to put some text in bold, italic, underlined...

## To Reproduce
**Affected versions**: 16.0

1. Install web_responsive
2. Take any model inheriting from mail.thread and having a chatter in its view
3. Compose a mail message by using the "Full Composer" (open the mail.compose.message wizard)
4. Write any text, select it.

**Expected behavior**
When selecting the text, the HTML toolbar should appear, allowing to put the text in bold, italic ...

Video of the normal behavior (tested today on Runboat on the OCA/sale-workflow repo):

[expected_behavior.webm](https://github.com/OCA/web/assets/89970854/81c47711-c150-4f98-9cb1-0e9d2ba0d244)

Video of the bug (tested today on the OCA/web runboat):

[bug_behavior.webm](https://github.com/OCA/web/assets/89970854/5c322a1e-d64a-4758-a18e-fc9d5ffb15e1)

**Comment by pedrobaeza** [comment]
As stated in other issue, the conflicting code is:
```scss
body:not(.o_statusbar_buttons) {
    .oe-toolbar {
        z-index: 0 !important;
    }
}
```

**Comment by pedrobaeza** [comment]
@bvanjeelharia you were the one adding that SCSS. Can you tell us the reason for adding it?

**Comment by bvanjeelharia** [comment]
@pedrobaeza , I had added this change as the toolbar would overlap with the statusbar on the formview as it had a higher z-index value when you zoomin a bit.With this change the statusbar would be visible irrespective of the toolbar.Check the screenshot without this change:
![Screenshot from 2024-01-09 19-45-22](https://github.com/OCA/web/assets/88703470/81493fd2-375e-419f-a30e-005ccbe2bd75)

Screenshot with this change:
![Screenshot from 2024-01-09 19-44-58](https://github.com/OCA/web/assets/88703470/256f36c8-64ee-4b82-8ae2-1120973b0579)

In the second screenshot , you can see that the statusbar is always visible(sticky statusbar) and the toolbar goes behind the statusbar

**Comment by pedrobaeza** [comment]
@bvanjeelharia I think the problem comes with the position of the floating bar: it shouldn't be there. That can be a side effect of other changes in this module. Please check without it to know how it works, and please tell us if there's a solution.

**Comment by gaineleanor** [comment]
Commenting out this configuration does not affect layer visibility.

**Comment by bvanjeelharia** [comment]
> Commenting out this configuration does not affect layer visibility.

Even after zooming in and scrolling up as can be seen from the screenshots that I have attached?

**Comment by gaineleanor** [comment]
> > Commenting out this configuration does not affect layer visibility.
> 
> Even after zooming in and scrolling up as can be seen from the screenshots that I have attached?

yes

**Comment by ivs-cetmix** [comment]
Actually the control panel appears behind the wizard. This is rally creates a lot of problems while using wizards that have HTML fields in them (

**Comment by youring** [comment]
Seems already fixed by https://github.com/OCA/web/pull/2734,  @marielejeune 
But still exist on v17, 
https://github.com/OCA/web/blob/e08356ee55df53dd6744ef21105caf5687c2271f/web_responsive/static/src/legacy/scss/web_responsive.scss#L155

**Comment by pedrobaeza** [comment]
You can fw-port the same patch then.

**Comment by marielejeune** [comment]
Fixed by https://github.com/OCA/web/pull/2734
