### ISSUE TITLE
Missing web_widget_text_markdown for newer versions

### ISSUE THREAD

**Issue by mohs8421** [OCA/web#2711]
In the branches up to 14.0 the markdown module is available, but it is no longer provided for the versions 15.0+
I would like to use markdown to allow easier formatting of some fields in version 16.

So my questions are simple:
* Why was the module removed?
* What should I use instead?
* Should there be some documentation on how to use markdown in newer versions (if the module is obsolete there)?

**Comment by pedrobaeza** [comment]
The module is not migrated by anyone, so that's why it's not there.

**Comment by mohs8421** [comment]
If that is the only reason, I will do it. Is there anything I have to have in mind while doing this?

**Comment by zamberjo** [comment]
See guidelines [15.0](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0),  [16.0](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0), ...
