### ISSUE TITLE
causes a problem where the toolbar does not appear when text is selected in the editor within a popup window. web_responsive.scss file, specifically in lines 373-377. 

### ISSUE THREAD

**Issue by gaineleanor** [OCA/web#2715]
Describe the Bug
There's an issue with the web_responsive.scss file, specifically in lines 373-377. The code block:

scss
Copy code
body:not(.o_statusbar_buttons) {
    .oe-toolbar {
        z-index: 0 !important;
    }
}
causes a problem where the toolbar does not appear when text is selected in the editor within a popup window.

**Comment by pedrobaeza** [comment]
Please put screenshots of the depicted problem.

**Comment by pedrobaeza** [comment]
And Odoo version...

**Comment by gaineleanor** [comment]
Hello Pedrobaeza,

The z-index of the toolbar is set to 0, which is why the buttons for formatting adjustments are not being displayed. They are being sent to the back layer.
odoo16
![image](https://github.com/OCA/web/assets/59348227/474905d8-e195-4aa3-a284-2f03543ac525)

**Comment by gaineleanor** [comment]
'target': 'new',

**Comment by pedrobaeza** [comment]
Duplicated of #2709
