### ISSUE TITLE
[17.0] web_responsive: Main document preview is activated by default

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/web#2745]
Hi @LazarusUA, it seems the auto-preview of the main attachment when entering a document like vendor bill is not deactivated, like it was in v16, and making other features like the possibility of previewing other attachments or seeing the chatter in the right are killed.

Can you please check to include that inhibition?

**Comment by TesaLazarenko** [comment]
Hi @pedrobaeza, I will look at it in my next free time and fix it.

**Comment by TesaLazarenko** [comment]
Hello @pedrobaeza, sorry for the long reply, here is the PR:https://github.com/OCA/web/pull/2795

**Comment by cvinh** [comment]
The ability to have to supplier invoices automatically opened is great for acountants
Is there any possibility to keep the automatic opening but allow the other chatter features available as well ?
@etobella 
@coco-invitu

**Comment by cvinh** [comment]
I tested the issue before the PR with supplier invoices
I have a issue only when there is a message in the chatter (like invoice received by email) : the chatter features are usable but the form view is hidden.
In the case the attachment is added manually, I see no issue
