### ISSUE TITLE
Tested with Aeroo Templates?

### ISSUE THREAD

**Issue by diezcode** [OCA/web#275]
Hi, I have try to test the ckeditor4 modul with aeroo templates. 
But the aeroo templates are printed with the html-codes from the editor.
for example:

<p></p> .

Have anyone a fix for the aeroo Templates ? or something?
Thanks...

**Comment by lukebranch** [comment]
@diezcode ,

Could you provide a bit more information about what you're trying to do with Aeroo, and your environment?

I'm not involved with the OCA, or Aeroo for that matter, but from reading your issue report it's a little hard to understand what issue you're having without the context.

**Comment by diezcode** [comment]
I don't know if I'm on the right place, I think it's a Aeroo-Reports problem, but I try it here.
Thank you for your fast answer.

I have a textfield in odoo then I add the widget="text_ckeditor4" to this textfield. Now I can use the ckeditor4 and make my text , bold, with colors etc...

Then I have a Aeroo-Template configurated to this textfield. When I'm printing this Textfield as Aeroo without the ckeditor , I get the message back that I write in this textfield. Now with the ckeditor, I get the message again but with all the html-tags like <.p.>.<./.p.> etc...

How Can fix this. I use wkhtmltopdf on odoo.

**Comment by lukebranch** [comment]
@diezcode ,

Could you post an example of what you're trying to do online (eg. https://gist.github.com/) so I can take a look? A screenshot of the issue might also help me understand as well.

**Comment by pedrobaeza** [comment]
Closed by inactivity.
