### ISSUE TITLE
[17.0]Can this module be migrated to the 17.0 version ??

### ISSUE THREAD

**Issue by Aberrahman** [OCA/web#2757]
## Module
The name of the module that has a bug.

## To Reproduce
**Affected versions**:

1.
2.
3.

**Expected behavior**

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by rvalyi** [comment]
Yes

**Comment by pedrobaeza** [comment]
And 18 when it arrives.

**Comment by Aberrahman** [comment]
is compatible now with 17.0 or it requires modification to be migrated

**Comment by pedrobaeza** [comment]
It should be checked, and for that, the first step is to know which module.

**Comment by Aberrahman** [comment]
i am talking about the web_responsive module

**Comment by pedrobaeza** [comment]
https://github.com/OCA/web/tree/17.0/web_responsive
