### ISSUE TITLE
[16.0] web_responsive: The web responsive will revert back to odoo base behaviour when we reload the page from website.

### ISSUE THREAD

**Issue by xavier-dass** [OCA/web#2810]
## Module
web_responsive

## Describe the bug
The new web responsive will revert back to odoo base behaviour when we reload the page from website.

## To Reproduce
**Affected versions**: 16.0

![web_responsive_reload_page](https://github.com/OCA/web/assets/14051028/b9fbf272-82c3-4ae3-b6ae-e48c17865481)

**Comment by pedrobaeza** [comment]
I'm not able to reproduce what you say in my own instance, or I don't have very clear the steps to reproduce it. Please write down all of them and also try it in runboat, not on your instance.

**Comment by xavier-dass** [comment]
Clikck on website Icon and it will redirect to the website module.  Once you enter the website module, just reload and see the home menu.  It reverts to the odoo base responsive view.  I attached a gif file that shows how to trigger the issue.  I used oca runboat instant to simulate it.

![web_responsive_issue](https://github.com/OCA/web/assets/14051028/09f67ee9-acc0-4801-bf0a-0d2ae12a3309)

**Comment by pedrobaeza** [comment]
That has nothing to do with `web_responsive`. I have just tried in standard community or enterprise edition in runbot, and it's doing the same:

![Peek 01-05-2024 17-48](https://github.com/OCA/web/assets/7165771/b6dd6082-1709-477d-946d-d9421e88bf18)

**Comment by killday** [comment]
I'm having the same problem and it is coming from setOpenState method in the apps_menu.esm.js

**Comment by pedrobaeza** [comment]
Are you able to reproduce in a standard runboat/fresh with only OCA instance?
