### ISSUE TITLE
web_advanced_search_x2x ..question

### ISSUE THREAD

**Issue by jaronemo** [OCA/web#282]
I install this module: web_advanced_search_x2x

my odoo instance show this error

![image](https://cloud.githubusercontent.com/assets/8476734/12082588/cd1e37be-b2cf-11e5-8ca4-bb3312c1dd86.png)

how can resolve this question?

**Comment by hbrunn** [comment]
seems like this file is missing on your installation. Check if it exists in the file system

**Comment by jaronemo** [comment]
web.assets_backend?

**Comment by hbrunn** [comment]
no, `web_advanced_search_x2x/static/src/css/web_advanced_search_x2x.css`. This should have come as part of the download

**Comment by jaronemo** [comment]
Ok,I will check it.Thanks

Date: Tue, 5 Jan 2016 01:39:16 -0800

**Comment by jaronemo** [comment]
Dear Sir
I check this module....on my server

![image](https://cloud.githubusercontent.com/assets/8476734/12119615/b74f3120-b407-11e5-901b-3f744ca6e544.png)

it's here

**Comment by hbrunn** [comment]
next option would be that the permissions are messed up in a way that the file is not readable for the user odoo runs at. in case you don't run your server as jason, su to the user in question and try if you can cat the file.

**Comment by jaronemo** [comment]
Dear Sir
Sorry....
This problem has been solved.Resolved as follows:Re-copyRestart odooinstallation

Date: Tue, 5 Jan 2016 08:07:23 -0800

**Comment by hbrunn** [comment]
@jaronemo glad to hear it's solved, then it probably indeed was a permission problem. Please close the issue then
