### ISSUE TITLE
[17.0] web_responsive: When becoming superuser

### ISSUE THREAD

**Issue by mohamedhagag** [OCA/web#2904]
Steps:

1- login
2- switch to superuser putting `/web/become`
3- The error `Uncaught (in promise) Error: The following error occurred in onWillStart: "is_redirect_home[0] is undefined"` appears.

https://github.com/OCA/web/blob/90aed8b1a415bc3254afc23285d2413d1124ac96/web_responsive/static/src/components/apps_menu/apps_menu.esm.js#L34

**Comment by pedrobaeza** [comment]
Is it reproducible on runboat? Steps to reproduce it? Don't expect quality answers if the quality of your issue report isn't.

**Comment by mohamedhagag** [comment]
> Is it reproducible on runboat? Steps to reproduce it? Don't expect quality answers if the quality of your issue report isn't.

How to access runboat ?

If I open runboat.odoo-community.org I get JSON reply not found !!

**Comment by mohamedhagag** [comment]
> Is it reproducible on runboat? Steps to reproduce it? Don't expect quality answers if the quality of your issue report isn't.

Yes it's reproducible on runboat
http://oca-web-17-0-90aed8b1a415.runboat.odoo-community.org/web

Steps:
1- login
2- switch to superuser

It will show empty page , and we must clear site cookies & data to get it working again and must login as normal user !

**Comment by houssine78** [comment]
@mohamedhagag does the provided fix resolve your issue ? in that case could you close this issue ?
