### ISSUE TITLE
[17.0] Contacts One2Many not allowing multiple select at Tagsfield on mobile

### ISSUE THREAD

**Issue by kokhoe-lee** [OCA/web#2941]
## Module
Contacts > Tags Field, on mobile phone

## Describe the bug
when user clicks on Tags field , "Select" button is greyed out thus users cannot select multiple options at one time. This happens on mobile

## To Reproduce
**Affected version: 17.0**:

1. on mobile phone, go to Contacts, click any Contacts 
2. select Tags, and click on "Search More" https://prnt.sc/GvqdZ4B21Sm8
3. Issue: unable to select multiple

**Expected behavior**
User should be able to check multiple boxes and Select, to save the Tags to Contacts

**Comment by chienandalu** [comment]
Is this related to an OCA module?

**Comment by kokhoe-lee** [comment]
hi Chienandalu, it will be on Web_responsive module since it is mobile-related

**Comment by chienandalu** [comment]
As I tested, this isn't a web_responsive bug. The same behavior exists in core or in web_enterprise. I'd start opening the issue on Odoo or, better, proposing a bugfix to core

**Comment by kokhoe-lee** [comment]
Thanks for the advice chienandalu
