### ISSUE TITLE
[web_ckeditor4] Cannot read property 'getComputedStyle' of undefined

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/web#299]
Symptoms:
When a user closes the sales order line detail window the following message appears:
Uncaught TypeError: Cannot read property 'getComputedStyle' of undefined

Steps to reproduce:
- Install modules "sale", "sale_note_flow" (https://github.com/OCA/sale-reporting), web_ckeditor4 
- Assign to admin user to group "Properties on lines".
- Create a sales order and add a line (pop-up window appears). Add a product and save. 
  Error message is shown.

**Comment by pedrobaeza** [comment]
Is this still happening? Or the problem got solved with latest module version?

**Comment by pedrobaeza** [comment]
No answer, so I close.
