### ISSUE TITLE
[8.0] web_widget_x2many_2d_matrix: multi values in both X and Y result in client error.

### ISSUE THREAD

**Issue by kittiu** [OCA/web#301]
I have tried this module. With following syntax,

`<field name="crossovered_budget_line" widget="x2many_2d_matrix" field_x_axis="period_id" field_y_axis="activity_id" field_value="planned_amount" />`

If we have multiple values in X (activity) and only 1 value in Y (period), it works fine.

![067](https://cloud.githubusercontent.com/assets/1973598/12696824/89de359e-c7a6-11e5-8d97-a358a6d372a9.png)
![068](https://cloud.githubusercontent.com/assets/1973598/12696826/9a6fc1b6-c7a6-11e5-9ba9-23c19126b933.png)

Or vice versa, 1 value in X and multiple values in Y, it works too.

![069](https://cloud.githubusercontent.com/assets/1973598/12696828/b3afd4cc-c7a6-11e5-9672-e1bc4bd2a6b8.png)
![070](https://cloud.githubusercontent.com/assets/1973598/12696829/b52871e2-c7a6-11e5-939d-a479ce6f87e5.png)

But as soon as I have multiple values in both X and Y, it gives error,

![071](https://cloud.githubusercontent.com/assets/1973598/12696834/c6fb21ee-c7a6-11e5-8154-a21819046845.png)

**Comment by hbrunn** [comment]
the widget expects a balanced matrix, that is, there's a value for every x/y combination it encounters. Do you have that? Please post the code you use to generate values

**Comment by kittiu** [comment]
Thanks for the prompt reply, and sorry I just come back to check. Yes, now, it seem to be as what you said. If I have all combination, it will work.
By the way, I am using it with budget screen, and in real life, it will not possible nor convenient to add value for every combination.

Here is the code I use,

`<field name="crossovered_budget_line" widget="x2many_2d_matrix" field_x_axis="period_id" field_y_axis="activity_id" field_value="planned_amount" />`

Is it technically possible to achieve that? (and disable the field with None value x/y, so won't have problem user try set the value)

**Comment by hbrunn** [comment]
well, a lot of the javascript code expects that the matrix is balanced, and ui wise, it will look quite weird if this is not the case. So if you can't fill in the missing values, I don't think this widget is the right choice for you.

**Comment by ecosoft-odoo** [comment]
Thank you for clarification. That's ok. I think we can still use it (no other solution can come close), we will at the back auto create the missing value, and it should work too.
