### ISSUE TITLE
ckeditor configuration

### ISSUE THREAD

**Issue by bealdav** [OCA/web#303]
module: web_ckeditor4
version: 1.1

Nice addition to Odoo ecosystem, thanks

**Current behavior**
The full version of ckeditor is ok, but how to customize it ?

**Expected behavior**
What is the best way to customize the editor and choose an other package (ie standard) ?
I would like avoid to change 'config.js' in the lib folder to not break git pull command ?

**Comment by pedrobaeza** [comment]
This can go to the "Known issues" section, but AFAIK, it's not possible to select the editor to use.
