### ISSUE TITLE
[8.0] Window action target `new` -- Readonly option

### ISSUE THREAD

**Issue by codingforfun** [OCA/web#314]
Currently popups opened via `ir.actions.act_window` using option `target='new'` always open in edit mode. This make perfect sense for wizards, but sometimes we also need to show form view of objects linked somehow to another object. E.g. by triggering a button on a form view returning a window action. In this case the popup shouldn't open in edit mode. 

Currently there seam to be no standard way of doing this. 
As a workaround I've seen the solution of creating a custom form view with each field set to read only explicitly (module [mail_full_expand](https://github.com/OCA/social/blob/8.0/mail_full_expand/views/mail_full_expand.xml)). However this needs a lot of boiler plate code. A better solution would be if it would work with the models generic form view. 

After reviewing the code involved, I see two options to solve this pragmatically. 
1.) Add a new target option, e.g. `target='popup'` that behaves like `new` but opens in `view` mode instead of `edit` mode. This involves very few changes to JS code. 

2.) Add `readonly` option to `ir.actions.act_window`. This would be a more generic solution, but also would involve more code changes. 

I would really like to hear your opinions about that.

**Comment by codingforfun** [comment]
@pedrobaeza @hbrunn 
I'm thinking about implementing this, because I need for a current project. What do you think about this? Which approach would you prefer? Thx.

**Comment by codingforfun** [comment]
@OSguard 
ping

**Comment by hbrunn** [comment]
if you have control over the actions, you can pass this in the `flags` dictionary of the action (https://github.com/OCA/OCB/blob/8.0/addons/web/static/src/js/views.js#L374) which will be merged at some place with the view's `options` dictionary, so you should be able to simply write `'flags': {'initial_mode': 'view'}`: https://github.com/OCA/OCB/blob/8.0/addons/web/static/src/js/view_form.js#L116

But this doesn't work for `ir.action.act_window`s living in the database, in that case, you could use a server action that returns the the action with the flags you want.

So if you need any coding at all, I'd suggest to do a variation of (2) where you add a serialized field called `flags` that allows people to set any of those. This will also make it simple to add more stuff in the future.

**Comment by codingforfun** [comment]
> so you should be able to simply write 'flags': {'initial_mode': 'view'}

@hbrunn 
Nice idea. Unfortunately this isn't working because it gets overridden here:
https://github.com/OCA/OCB/blob/8.0/addons/web/static/src/js/views.js#L697

https://github.com/OCA/OCB/blob/8.0/addons/web/static/src/js/views.js#L697 also is the part of the code I thought to implement approach (1)

A workaround I found looks like that: 

```
'flags': {'form': {'options': {'mode': 'view'} } }
```

However this is not a nice general solution. 
Solving this via a general flags field sounds like a nice idea. 
Apprach (1) however would match that there is already a read only option for the `inline` target.

**Comment by pedrobaeza** [comment]
Is this finally solved in any way?

**Comment by codingforfun** [comment]
I solved this for my original project following the approach @hbrunn suggested, but didn't code any further.

**Comment by pedrobaeza** [comment]
I close this then
