### ISSUE TITLE
[8.0][BUG] web_advanced_search_x2x - Exception with domains in models

### ISSUE THREAD

**Issue by angelmoya** [OCA/web#317]
Searching a field with domain in model, exception appears because Odoo is not able to locate fields of domain.

For example:

In model:

```
    state_id = fields.Many2one(
        'res.country.state',
        string='State',
        required=True,
        domain="[('country_id','=',country_id)]")
```

Error searching values of states:

```
Uncaught Error: NameError: name 'country_id' is not defined
```

**Comment by hbrunn** [comment]
weird, this sounds exactly like #166 You probably run the latest version? Please put a breakpoint at https://github.com/OCA/web/blob/8.0/web_advanced_search_x2x/static/src/js/web_advanced_search_x2x.js#L79 so see what's going on here

**Comment by angelmoya** [comment]
Sorry for the noise, I updated code before create this issue, and update in database with -u web_advanced_search_x2x, but maybe chache mantain js or watelse... after restart and -u all it is work well
