### ISSUE TITLE
web_m2x_options code does not agree with the specification

### ISSUE THREAD

**Issue by jan-sedivy** [OCA/web#342]
Hi,
please correct me, if I am wrong, but I see in the module documentation
https://www.odoo.com/apps/modules/8.0/web_m2x_options/
that there should be new options available at the field level called "create" and "create_edit", but there are none such used in the get_search_result(). Instead the function looks for no_create, no_create_edit and no_quick_create not mentioned in the documentation.
On top of it, the condition 
if (!no_quick_create && ((m2x_create_undef && can_create) || m2x_create)) {
seems a bit odd to me as looks like the the m2x_create (self.view.ir_options['web_m2x_options.create'] == "True") entirely overrides the can_create parameter returned probably from the access right checking. That sounds quite dangerous to me.

So I would like to propose the following update:
The "create" and "create_edit" options are taken into account and have higher priority than the global web_m2x_options, while still keeping the backwards compatibility for no_create, no_create_edit and no_quick_create. I had implemented this on our system and it finally behaves as expected.

I am not sure I can push my changes to your repository, so I am attaching the diff file of web/web_m2x_options/static/src/js/form.js

[form.txt](https://github.com/OCA/web/files/213652/form.txt)

regards,
  Jan

**Comment by michaelkarrer81** [comment]
+1 - would be very nice if this would be merged

**Comment by jan-sedivy** [comment]
There was a small copy-paste error it the above attached diff. Here is a fixed version we use already for several months [form_fixed.txt](https://github.com/OCA/web/files/323078/form_fixed.txt)

**Comment by pedrobaeza** [comment]
Please make a PR for these changes.

**Comment by jan-sedivy** [comment]
should be there as #434

**Comment by pedrobaeza** [comment]
Closing as there's a PR
