### ISSUE TITLE
[9.0] help_popup :  templateViewManagerAction does not exist

### ISSUE THREAD

**Issue by msalim-c** [OCA/web#343]
Hello,
The installation of help_popup module failed because of ViewManagerAction that don't exist any more in Odoo v9 community edition. 
Is their any solution to correct this issue ?
Best regards.

**Comment by pedrobaeza** [comment]
The module is not migrated, so that's why it fails. A proper migration is needed. You can do it yourself, wait for someone to do it, or pay someone to do it for you.

**Comment by msalim-c** [comment]
Thanks for your response.
