### ISSUE TITLE
[8.0] [web_ckeditor4]  Script error :0

### ISSUE THREAD

**Issue by mad-odoo** [OCA/web#350]
Hello,

I am facing an bug while using web_ckeditor4.
http://goo.gl/UPUvoU

**Current Behaviour and steps to reproduce:**
1) Open a orderline form from sale order
2) Write somewhat longer description about product with some misspelled words.
3) Now enable SCAYT 
4) Keep misspelled words as it is and click on Save button. You will get an error as shown in screenshot.

**Expected Behaviour:**
While clicking on Save button if misspelled found, then there should be a warning message like     *\*    Misspelled found.*\* OR It should save normally without error  http://goo.gl/UPUvoU.

**Comment by pedrobaeza** [comment]
This should be fixed now.
