### ISSUE TITLE
web_widget_digitized_signature addon doesn't work on mobile devices

### ISSUE THREAD

**Issue by levkar** [OCA/web#353]
It's something in js library level.

Current Js library (http://keith-wood.name/signature.html) doesn't work on mobile devices. Serpent already updated code with jSignature (https://github.com/willowsystems/jSignature):

https://github.com/JayVora-SerpentCS/SerpentCS_Contributions-v8/tree/8.0/web_digital_sign

**Comment by pedrobaeza** [comment]
@JayVora-SerpentCS, can you update the OCA module with this?

**Comment by levkar** [comment]
@pedrobaeza  @JayVora-SerpentCS 

I already made a PR here:

https://github.com/OCA/web/pull/394

**Comment by pedrobaeza** [comment]
OK, I close this issue and continue with the PR. I can't say too much about the widget itself, as I don't use it.

**Comment by levkar** [comment]
PR works with few glitches caused by Javascript library. There is no perfect solution for getting signature from browser.

**Comment by vcloud9ray** [comment]
@JayVora-SerpentCS - is there an easy way to make the signature square smaller?  Like the width and height be made smaller for smaller devices?

**Comment by pedrobaeza** [comment]
We have reworked the module in https://github.com/OCA/web/tree/9.0/web_widget_digitized_signature and it's fully functional on mobiles.

**Comment by vcloud9ray** [comment]
👍

**Comment by vcloud9ray** [comment]
@pedrobaeza I don't see this at https://github.com/OCA/web/tree/10.0 at all - as either ported or unported - do you know anything about it?  Wanting to know if it was intentionally dropped from v10 migration plans or not.

**Comment by pedrobaeza** [comment]
No, it's just that the module landed on v9 after the v10 branch creation, You have the full commit history rescued on #725
