### ISSUE TITLE
8.0 - Proposal of new module to force saving form fields

### ISSUE THREAD

**Issue by ghost** [OCA/web#359]
Hi contributors, in different odoo projects, I add an issue with web fields in form view.

When a field is readonly, Odoo does not save it to the database. So, for example, if you have an onchange that triggers a modification on that field, you end up with unexpected behavior.

My solution for that is to override the method _process_save of openerp.web.FormView in javascript code. I add a new option "force_save" on the field to tell the web client to save the field in any surcumbstances.

I would propose a new module implementing that feature if this interests the community. Or maybe a module already exists for that.
Let me know.

**Comment by pedrobaeza** [comment]
It's already done in https://github.com/OCA/web/tree/8.0/web_readonly_bypass

**Comment by ghost** [comment]
@pedrobaeza thanks
