### ISSUE TITLE
[8.0] web_ck4editor ck4editor version

### ISSUE THREAD

**Issue by intero-chz** [OCA/web#361]
Why does the readme say it's version 4.6.6 when it actually is 4.5.4?

How hard is it to upgrade to a newer version? I really want to upgrade, but never looked deeper into this module. Can you please provide me some information on that topic?

kind regards

**Comment by pedrobaeza** [comment]
You should check if the calls to the initialization and so on have changed from one version to the other. It requires some JS knowledge.
