### ISSUE TITLE
[8.0] web_dialog_size default maximize has no effect

### ISSUE THREAD

**Issue by sbidoul** [OCA/web#365]
Apparently, the README of web_dialog_size is inconsistent.

It says both `By default, all dialog boxes are expanded.` and `By default, the module respects the caller's dialog_size option. If you want to override this and have all dialogs maximized by default, set the configuration parameter web_dialog_size.default_maximize to 1.`.

In my test, dialogs are expanded by default, but `web_dialog_size.default_maximize` seems to have no effect.

@pedrobaeza @hbrunn any opinion/advice on this?

**Comment by pedrobaeza** [comment]
I remember that the option was included to allow to configure the dialog size at your instance. Maybe the value should be `false`, `False`, or `0` to activate it?

**Comment by sbidoul** [comment]
@pedrobaeza If I understand well, since ir.config.parameter are strings, "false", "False", "0" all evaluate to `true` in javascript. And this code has no effect.https://github.com/OCA/web/blob/3f947ac8c5a60e2f6fa9641c2f72faf69ab9d987/web_dialog_size/static/src/js/web_dialog_size.js#L19 ?

**Comment by pedrobaeza** [comment]
Then it seems that the only option is to remove the key right now. The JS code can be improved to allow one of these values or execute some kind of eval.

**Comment by sbidoul** [comment]
Does not work for me. Even without the key, dialogs are all expanded. I just tested on runbot.

**Comment by pedrobaeza** [comment]
Uhm, then it needs to be definitively fixed... Can you...?

**Comment by sbidoul** [comment]
@pedrobaeza I tried to debug the js code, and for every dialog it falls there https://github.com/OCA/web/blob/3f947ac8c5a60e2f6fa9641c2f72faf69ab9d987/web_dialog_size/static/src/js/web_dialog_size.js#L13 so the default_maximize is never evaluated.

I don't know where this "large" option is coming from.

**Comment by pedrobaeza** [comment]
My knowledge of JS is limited so we need a JS magician like @hbrunn

**Comment by hbrunn** [comment]
https://github.com/OCA/OCB/blob/8.0/addons/web/static/src/js/chrome.js#L92, so if this is not set to some other value by the caller, it will indeed maximize. I don't really have an opinion if it's better to adapt the readme to the facts or change the code. What do you think? Maybe overwrite the value with a config parameter named `default_dialog_size`?

**Comment by sbidoul** [comment]
@pedrobaeza @hbrunn I propose #366
