### ISSUE TITLE
[8.0] web_widget_x2many_2d_matrix

### ISSUE THREAD

**Issue by max3903** [OCA/web#375]
Hello,

I am trying to configure the sale order view to display one dimension (size: XS, S, M, L, XL) as the columns and the product template (dress) and the other dimensions (Color) as lines.

I have also installed the following modules: https://github.com/OCA/sale-workflow/tree/8.0/sale_order_add_variants

How do I customize the view to achieve this?

**Comment by hbrunn** [comment]
what have you tried? Mind you that this widget as it is needs all combinations of your values being available already in the x2many it's meant to display, so you'll probably have to prepopulate this in `default_get` or the like.

**Comment by max3903** [comment]
@hbrunn I tried adding the widget in the order_line and product fields. No success. I understand from your question that some development are required. It answers my question at this point. Thanks!
