### ISSUE TITLE
Update module Internet (web) in Odoo8

### ISSUE THREAD

**Issue by studentule** [OCA/web#399]
Hi,

When update module Internet (web) from Settings / Installed Modules / Internet (web) Odoo8 give this infos:

The value "LGPL-3" for the field "ir.module.module.license" is not in the selection

Please advise!

PS need the Internet (web) update for this one: web_advanced_search_x2x

**Comment by pedrobaeza** [comment]
You need to update your Odoo base installation.

**Comment by pedrobaeza** [comment]
You need to update your Odoo base installation.

**Comment by studentule** [comment]
I'm Newbie on this: update Odoo base installation, because:

I use Synology NAS 216 play and not an usual server.

Please advise!

**Comment by pedrobaeza** [comment]
Sorry, but this is out of the scope of the issue. You should update the code of your Odoo base installation. It depends on the followed procedure (deb, git...).
