### ISSUE TITLE
Blueprint: Community Web v2

### ISSUE THREAD

**Issue by lasley** [OCA/web#403]
I am creating this issue to track the progress of the development relating to creating a fully mobile compliant backend interface for Odoo. 

Following are the blocker tasks:
- [x] [A module that provides an app drawer and new menu bar for mobile compliant navigation](https://github.com/OCA/web/pull/396) 
- [x] An update to the module that adds responsive styling using Bootstrap LESS variables in the existing Odoo LESS attributes
- [x] An update to the module that adds a menu search feature to include secondary menus, replacing the existing simplistic primary menu search

Not a blocker, but definitely a nice to have as part of this project:
- [ ] [A module that provides a JS DataModel capable of Public User sessions](https://github.com/OCA/web/pull/402)
- [ ] [A search widget to allow for searching of any menu by name (or even better, descriptions?)](https://github.com/OCA/web/pull/714)
- [ ] A somewhat universal keyboard shortcut system

cc @dreispt @antespi @pedrobaeza @Yajo

**Comment by rvalyi** [comment]
@lasley IMHO consider achieving this on the future v10 only: in v10 finally Odoo web module is the same in the Enterprise and Community editions (they updated the web module in community) so it should be far easier to achieve. As for the folks stuck on 9.0, they may consider migrating to v10 instead as it should not be that hard this time.

**Comment by yajo** [comment]
v10 is scheduled to October, so it's not a bad idea @rvalyi, but could you please elaborate a bit on _why_ the v10 web module makes this easier to achieve?

**Comment by rvalyi** [comment]
@Yago because v9 community web module didn't evolver over over v8. v9 enterprise is web friendly but it's a fork of the community web module. Meaning you will have hard time achieving Enterprise like features using the spoilt community web module. In v10 on the contrary the Enterprise web module is built on top of the revamped community web module, meaning that the OCA can more easily complete it to bring it on par with the Enterprise.

**Comment by lasley** [comment]
Thanks for the elaboration @rvalyi - this is a huge revelation & definitely saves a bunch of work.

Could you provide a bit more insight into what is planned (or point me to a spot to look), specifically:
- Will there be an Apps Screen in Community similar to that in Enterprise now?
- Have they unified the web and website widgets in any way, or is there still a divide as we see today?

If we wait for Odoo 10, we can for sure knock off the first two of the requirements:
- the `t-operation` for class add/remove - although this might be a decent feature to have maybe..
- adding bootstrap classes to all widgets

**Comment by rvalyi** [comment]
@lasley all I know is from some Twitter announcement and and git commit in the master web module where they announced what I told. Also I had seen the Enterprise web module once and what was committed in master really matches parts that was missing in community 9.0.

Now there is still lots of features in the Enterprise version only, this is clear if you try their saas demo vs the community master. The community isn't responsive I think, there is no apps launcher etc.. But as the base is now common, replicating Enterprise features should be far easier on master than on 8.0 or 9.0.

**Comment by yajo** [comment]
Thanks for the info, but today I have checked the HTML output of the same form in community master vs enterprise master and it's almost the same.

I see no bootstrap classes anywhere.

So I realized they took a different approach. They must have simply created a responsive LESS theme using their core selectors. If we do the same, we can skip steps 1 and 2. I think it's a very good approach. And it will not matter v9 or v10.

**Comment by nhomar** [comment]
Hello.

Why force use bootstrap classes if we have already all Less/Sass avilables?

IMHO manipulate the DOM namespace will bring huge quantity of non expected behavior.

https://github.com/odoo/odoo/tree/9.0/addons/web/static/src/less

It means by the end the change is make responsive the original Less attributes, it iwll bring more work in term of test/try but less job and better compatibility.

regards.

**Comment by lasley** [comment]
Interesting thought @nhomar - I agree that this seems like the cleanest approach that pretty much amounts to making a generic, non-customizable theme. LESS would still technically allow us to leverage the wonders of Bootstrap as well, just as mixins instead of DOM classes.

Maybe I'm getting ahead of myself, but it's definitely within scope of an OCA web interface - do we also need a nice OCA theme to complement all this? Does anyone know of an open source theme example for Odoo 9? Admittedly this whole concept is shrouded with marketing spiel in my mind 😑

**Comment by pedrobaeza** [comment]
We were talking about making Odoo widgets bootstrap compatible and that was the idea for injecting the operations, or am I confused with the scope?

About an open source theme, I know this one: https://github.com/Openworx/themes/tree/9.0/united_backend_theme

**Comment by lasley** [comment]
Scope of this issue is for a v2 of web for OCA that conforms to current UI standards (mainly mobile), which boiled down to a few tasks - two of which were focused around the injection of bootstrap classes into the widgets on the DOM to allow for the mobile compliance.

There is the valid point that we can have some far-reaching consequences with the plan of manipulating the DOM in such a heavy handed manor. Although as I'm thinking about it more, I think this may have some issues of its own - mainly in terms of site performance.

As it is now Odoo will probably never pass a PageSpeed test, but adding more LESS will move us further into the direction of oblivion. I just ran an audit of the backend & 4333 (93%) CSS rules are unused. Seems we may want to instead try to limit these and work within what we have.

I'm certain I can make a fully compliant interface using only Bootstrap classes; the real question is how easy those classes are going to be to inject, where they need to be added, and how scalable/future proof such an implementation is.

Thanks for the theme example! I'm astonished at how simple this is. Will go over more of it later today. I'm not going to include the theme in this scope as I'm looking at it though, just more of a back of the mind thing while I'm in all this other code.

**Comment by yajo** [comment]
About what you said of making a _non-customizable_ theme, that's not exactly true.

Given Bootstrap 3 comes from LESS directly in v9, it inherits its ability of [using variables before they get assigned](http://lesscss.org/features/#variables-feature-lazy-loading). That means you can use any of [bootstrap variables](https://github.com/twbs/bootstrap/blob/v3.3.6/less/variables.less) in your theme, no matter if they are defined or not, and still let some theming to be applied to your LESS as a submodule, with absolutely no problem.

So, after all, this task becomes just adding responsiveness to current backend widgets by using just LESS.

**Comment by lasley** [comment]
Well that's nifty, I have yet to delve into LESS. I was admittedly trying to hold off because Bootstrap 4 is SASS instead 😑 . 

Ok so I do think this is a solid plan then, I'll update the main issue & start looking through all these variables.

**Comment by yajo** [comment]
[Yes, and bootstrap 5 will be PostCSS](https://twitter.com/mdo/status/591364406816079873), this people is a bit indecisive :laughing:

Today [there's an official Sass port of BS3](https://github.com/twbs/bootstrap-sass), but the really important thing is that [Odoo uses the LESS version](https://github.com/odoo/odoo/tree/9.0/addons/web/static/lib/bootstrap/less), so we should stick to that for now. [Tools to convert from LESS to Sass are available](https://lmddgtfy.net/?q=less2sass), so don't worry too much.

**Comment by jgrandguillaume** [comment]
Hi,

I was wondering how much days you think it'll take to build all this... I know this question is kind of stupid one, but I'm not familiar with webdevs and I need an order of magnitude here. The reason is I might have a sponsor for that, so my idea (just an idea for now) would be to crowdfunds a responsive and clean community webclient.

Any hints or advices for me here ?

Thanks,

Joël

**Comment by JordiBForgeFlow** [comment]
I asked a company specialized in web responsive apps in odoo. They say, to do properly it is in the order of magnitude if 6 months. Very complex. We'll need to join forces and have an experienced frontend team if we want to succeed.

**Comment by lasley** [comment]
My eval is the same as @jbeficent - the App Drawer initiative was only one piece of a rather large puzzle. We're almost done there, with the big item of redesigning the LESS next up to the chopping block.

Realistically the LESS could probably be hacked together in a matter of days (<1k lines), but testing against all the widgets in all edge cases is going to be the real kicker.

We also need to do something about the heavy use of Modals, which are not considered to be mobile compliant. This will require some creative design that I haven't quite nailed down yet.

Obviously any and all help/ideas are welcome, and funding does help immensely. This has been a side project for the most part.

**Comment by pedrobaeza** [comment]
I see this no trivial task, but not for that scale. One person full time will need one month for the work, not 6. 6 months is more a deadline date, because as @lasley said, this has been a side project for all of us till now.
