### ISSUE TITLE
[10] web_widget_digitized_signature

### ISSUE THREAD

**Issue by eLBati** [OCA/web#414]
I'm opening this just to let you know that we started working on porting `web_widget_digitized_signature` to v10 and we'll make a PR as soon as the 10.0 branch will be available.

If someone is interested, we can share the code

**Comment by eLBati** [comment]
Also, we would like to know if it is possible to change the license of the module to LGPL.
Is it possible? How should it be done? Should we contact the copyright owners + OCA board?
Thanks

**Comment by dreispt** [comment]
My opinion: 
the Authors can (re)license it. I think the Author here is .Serpent Consulting Services.
Serpent's CLA to the OCA allows the board to license that work, but that is expected to be a "just in case" possibility, and should be considered only if really needed.
My advice is to contact the Authors (Serpen CS) and propose the relicensing.

cc @gurneyalex

**Comment by gurneyalex** [comment]
@eLBati you need to contact the copyright owners. This includes Serpent CS and the people listed as contributors in the README file. All and every of them should agree. 

A way of having this could be to ask them to say so on a github issue and to refer to that issue on the commit changing the license.

**Comment by pedrobaeza** [comment]
As the PR has been done in https://github.com/OCA/web/pull/438, I close this.
