### ISSUE TITLE
Web modules missing from Apps Store

### ISSUE THREAD

**Issue by lasley** [OCA/web#452]
It was reported in #439 that web_widget_color for v10 is not on the Odoo Apps store.

Looking a bit further, it seems that our sync is not working properly. I searched for another module, [web_sheet_full_width](https://www.odoo.com/apps/modules/category/web/browse?search=web_sheet_full_width), and not even the 9.0 version is showing & [web_environment_ribbon](https://www.odoo.com/apps/modules/9.0/web_environment_ribbon/) is missing its 10.0.

cc @yelizariev

**Comment by pedrobaeza** [comment]
The publication in Odoo apps must be done manually, and it hasn't been done. Imagine that this makes us to create 200 manual records...

**Comment by lasley** [comment]
Well that's highly inconvenient. I thought that Odoo apps were pushed through repo branches automatically? 

Let me know if there's something I can do to help here

**Comment by pedrobaeza** [comment]
I'm afraid not. I will try to reach their Odoo via XML-RPC to see if we can automate this in any way.

**Comment by yelizariev** [comment]
One can contact apps store support team ( apps@odoo.com )
and ask them to export all 9.0 records, replace 9.0 to 10.0 in csv file and import back

**Comment by lasley** [comment]
@yelizariev That will include modules that we haven't ported though I think.

@pedrobaeza I was just playing around with the Apps Store using one of my own repos, and applications are adding automatically as long as I have the branch configured as a separate repo. 

Are we not just configuring repos for OCA, and instead pushing the apps individually? 

I feel like there's something we're missing here, because I did not push anything `vertical-medical`, but the [new 9.0](https://apps.odoo.com/apps/modules/9.0/medical/) version is showing up. I'm pretty sure I'm the only active OCA member in that repo, so I don't know who would have pushed that module up if not me. Or maybe our fearless project leader @nhomar is handling that?

**Comment by pedrobaeza** [comment]
All 9.0 OCA branches were previously activated. The problem comes that we have to create one record per repository branch. Imagine the long list of repositories we have (you only need to go to https://github.com/OCA/ to see them):
- web
- website
- event
- vertical-medical
- ...

That's why I say is a tedious and huge work to do it manually.

But this hasn't have to be done module by module. Publishing full branches, only installable modules are populated to the apps store.

**Comment by lasley** [comment]
Cool thanks for the elaboration @pedrobaeza - I had a feeling I was just misunderstanding the problem. 

I agree that we need a way to publish these branches via XML-RPC, possibly as part of our migrate_branch procedure. I'll play around and see if I can come up with something as well.

**Comment by yelizariev** [comment]
@pedrobaeza could someone register 10.0 branch manually for OCA/web at least, before xml-rpc way is ready. Really need it to resolve dependency issue on app store. I guess I am not the only one.

**Comment by pedrobaeza** [comment]
I prefer to do it all together, but I will try to work on this today.

**Comment by yelizariev** [comment]
I've registered OCA/web#10.0 branch myself 
https://apps.odoo.com/web#id=6726&view_type=form&model=loempia.repo&action=129&menu_id=126

I authorize apps store team to move ownership of the record to OCA if needed. 

web_widget_color 10.0 is available on app store now:
https://apps.openerp.com/apps/modules/10.0/web_widget_color/
![screenshot-apps odoo com 2016-11-01 12-50-54](https://cloud.githubusercontent.com/assets/186131/19882774/d99151a2-a031-11e6-9840-96f50f54c2f0.png)

**Comment by pedrobaeza** [comment]
And how do you exactly have authorized that thing?

**Comment by yelizariev** [comment]
I mean, that I agree to transfer ownership, i.e. if you will ask app store team to do it and they will have doubts, you can reference to my comment.

**Comment by yelizariev** [comment]
@pedrobaeza now one can register batch of repos in once simply using built-in export-import tool. (There were access issues, but support team has resolved them). So, to do it
- export 9.0 branches to csv file
- replace 9.0 to 10.0
- import csv back with ignoring first column **id**
- wait 1 day -- repos has to be scanned

**Comment by pedrobaeza** [comment]
Cool, thanks for telling me this trick! I'll do it ASAP, although I'm having very hard days with work overload .

**Comment by yelizariev** [comment]
@pedrobaeza according to my information, possibility of using import-export to register repos in app store is removed for security reasons. So, xml-rpc is the only way to automate registration now.

**Comment by pedrobaeza** [comment]
Ouch, I should do it when I had the opportunity, hehe. My pile of TODO is increasing more and more...

**Comment by legalsylvain** [comment]
What about include this feature in the module github_connector_odoo ? An xml-rpc call should not be hard to do ?
CC : @gurneyalex.
kind regards.

**Comment by lasley** [comment]
Excellent idea @legalsylvain - just what we need for scaling our repos!

Odoo SA confirmed that this is indeed possible through RPC, so I think this would be a great idea to include into the existing Github integration. 

A bit out of scope in terms of Github itself, but when paired with the context of Odoo it totally makes sense that anyone with this connector installed & monitoring Odoo repos would also want the option to sync said repos with the Apps store.

On that note, I'll finish the second half of my review on that connector in the next few days 😄

**Comment by lasley** [comment]
Alright so this is starting to get on my nerves, so I believe I'm going to make a script to knock this out. Is [`maintainer-tools/oca_projects.py`](https://github.com/OCA/maintainer-tools/blob/master/tools/oca_projects.py#L17) the  most definitive list of module repos we have?

**Comment by pedrobaeza** [comment]
Use this method for getting a dynamic list of repositories: https://github.com/OCA/maintainer-tools/blob/71871be3ff392b3994383b6661f56371f10a5e24/tools/oca_projects.py#L161

**Comment by lasley** [comment]
Cool even better, thanks @pedrobaeza. I'm not going to claim that this solution will be elegant in the least bit, but it will at least work yearly when we need it 😄

**Comment by lasley** [comment]
Oh yeah, especially because XML-RPC is locked down. This is about to be a straight up screen scraper.

**Comment by lasley** [comment]
So I believe this may be impossible, at least without a lot of effort. 

The main issue here is that Odoo Apps is OAuth based login - this seems impossible over XML-RPC. 

I tried screen scraping, but the dance between odoo.com & apps.odoo.com is really maddening using requests and BeautifulSoup 😖

**Comment by pedrobaeza** [comment]
What a pity! I'm going to try to contact them to see if there's any solution.

**Comment by lasley** [comment]
I actually contacted them immediately after this ticket was opened. Here's the reply, but the TL;DR is they don't know either:

> Sorry for the late reply. Right now I don't see why it wouldn't be possible. However, your accounts on apps.odoo.com currently are oauth accounts from odoo.com. So that might be one problem already. You might want to assign an actual password to these accounts, and I'm not sure you can manually do that, do you ?

It pretty much stopped there. I have no vision into their infrastructure that he's asking me questions about, so I figured it was a fool's errand continuing that - particularly because my ticket was closed immediately after their response.

**Comment by pedrobaeza** [comment]
Uhm, it seems a bit vague. I'm thinking about pinging someone like @odony or @mart-e about this thing. Guys, sorry for pinging you outside of Odoo, but it's to follow context. In a nutshell, we are wondering if there's is any way we can mass-update 10.0 OCA branches in Odoo apps account for avoiding to register one by one by hand, and to make this process regular on each new version. Can you help us?

**Comment by dmo-odoo** [comment]
@lasley My question was not specific to the appstore. Oauth and user passwords are standard Odoo features so I don't really know why you thought you could not answer them. I'm going to assume your answer to my question was "No, I can't change the password of my own account", so I need to assign a password to one particular account on apps.odoo.com that you could use for your xmlrpc calls. Can one of you point me to the account (mostly a login email address) you'd like me to request an actual password for so you can use it for xmlrpc calls ?

**Comment by mart-e** [comment]
Hello,

> but the TL;DR is they don't know either

This is not really what we are saying. If you want to make xmlrpc, you must have a local password. This can be done using the "change password" button.
Once you have a xmlrpc access, you can `copy` all your registered repositories just changing the version. Should not be too hard.

**Comment by pedrobaeza** [comment]
Thanks for the information, Martin, and sorry if we have misunderstood your words. I'll try to change the OCA account password that way and connect via XML-RPC to see. I'll let you know if any problem.

**Comment by dmo-odoo** [comment]
@lasley Besides, I did not close your ticket right after replying to it. I replied on November 2nd and the ticket got closed automatically on November 10th after one week with no reply from your part.

**Comment by lasley** [comment]
@dmo-odoo Definitely apologies for the misinterpretation, I understood it to be specific for the App Store. It seems like you're running a more locked down version than I'm used to, but maybe that's just my lack of familiarity with Enterprise.

> I replied on November 2nd and the ticket got closed automatically on November 10th after one week with no reply from your part.

Hrmm maybe I'm thinking of another one then. My apologies on that as well. Full of fail it seems.

Thanks for the help & all that you do, guys.

@pedrobaeza - do you see a way in the OCA account to actually change the pass? There's no link in my account that I can find.

**Comment by yelizariev** [comment]
Hi guys,
I am going to develop simple tool (a module) to work with repositories. It's just a wizard to call ``[Scan Repo]`` button, but anyone could extend it for his own needs. Any idea what is proper place (repository) for such module?
As for now, we have working instruction about changing password and connecting via xmlrpc. Thanks to @dmo-odoo.
https://gist.github.com/yelizariev/9cfddc011e709c4740148a7793f6afc8

**Comment by yelizariev** [comment]
The module is here for a while:
https://github.com/it-projects-llc/addons-dev/pull/186. Direct link: https://github.com/it-projects-llc/addons-dev/tree/misc-addons-8.0-apps_odoo_com/apps_odoo_com

**Comment by pedrobaeza** [comment]
Already included in Apps.
