### ISSUE TITLE
License error for web_widget_image_download v8.0

### ISSUE THREAD

**Issue by Martronic-SA** [OCA/web#455]
Throwing Wrong value for ir.module.module.license: 'LGPL-3'
Fixed using AGPL-3 for License in **openerp**.py

**Comment by yajo** [comment]
Sorry, that addon's license is LGPL-3. That's not a bug :wink:

**Comment by pedrobaeza** [comment]
You have to update your Odoo installation to avoid the error (that license was introduced later, not in the beginning of version 8)

**Comment by Martronic-SA** [comment]
Ok, thank you very much for your replies!
