### ISSUE TITLE
m2x options for view

### ISSUE THREAD

**Issue by AaronHForgeFlow** [OCA/web#466]
An error is showing when opening crm_claim form view, after merging [IMP] 7.0 add m2x options for view: https://github.com/OCA/web/pull/305

To reproduce it:
- Go to runbot http://3271007-7-0-64d3bd.runbot1.odoo-community.org/?db=3271007-7-0-64d3bd-all
- Install crm_claim
- Go to Sales -> After-Sale-Services-> Claims.
- Open a claim or click on "Create" button.

Then you get the following:

![image](https://cloud.githubusercontent.com/assets/19620251/20058342/c9b94c8a-a4f0-11e6-8c45-1bb801aefacf.png)

The error is triggered in this line:

https://github.com/initOS/web/blob/c89ab90c056f116d033b19ab1467d6bdfc0701f7/web_m2x_options/static/src/js/form.js#L40

I realize that the problem in this form is related to the field ref which is defined using the selection=crm._links_get 

It also happens in other form views where the field defined using that property as crm_helpdesk for example.

**Comment by gdgellatly** [comment]
Similar Error, under Opportunities Kanban click any item, and you get TypeError: widget.view is undefined.

This commit should be reverted until the issue resolved.

Copying authors and approvers
@azoellner @hbrunn @pedrobaeza

**Comment by azoellner** [comment]
Hopefully fixed this issue in pull request #493
