### ISSUE TITLE
[10.0 web_favicon] Included in standard Odoo

### ISSUE THREAD

**Issue by cvinh** [OCA/web#483]
Hello all

I think web_favicon has to be deprecated for v10.0 as the setup appears to be included in Odoo v10.0c
Check "Website Administration/Configuration"

Best Regards

**Comment by cvinh** [comment]
My bad, maybe it's included for website and web_favicon is for backend ?
Please confirm

**Comment by pedrobaeza** [comment]
Yeah, that's it.
