### ISSUE TITLE
Issue whit multicompany switching

### ISSUE THREAD

**Issue by agb80** [OCA/web#49]
At this moment I don't have isolate if this is a problem with web_easy_switch_company module or with odoo itself as don't know in deep how the context works. 

The situation is as follows:
1.- User have been working with with company A and switch to company B
2.- User tries to print a quotation or a so and gets and permission denied error on partner object, because user object in report thread have company set to A.

Please advice on how can we debug and correct this situation.

**Comment by legalsylvain** [comment]
Can you do the same process without web_easy_switch_company installed ?

**Comment by legalsylvain** [comment]
Hi, 
Any news about that bug ?

**Comment by pedrobaeza** [comment]
We can close it until further notices
