### ISSUE TITLE
[8.0] web_widget_x2many_2d_matrix: axis order does not respect _order of model

### ISSUE THREAD

**Issue by Cedric-Pigeon** [OCA/web#494]
Hello,

I am using this widget and whatever I do the axis are always sorted by id. Although I have an _order attributes on my model.

Any ideas ?

Thanks

**Comment by hbrunn** [comment]
the qweb template reads the values through a https://github.com/OCA/web/blob/8.0/web_widget_x2many_2d_matrix/static/src/xml/web_widget_x2many_2d_matrix.xml#L15 which is defined in https://github.com/OCA/web/blob/8.0/web_widget_x2many_2d_matrix/static/src/js/web_widget_x2many_2d_matrix.js#L217 - this doesn't care for the order at all. So you'll probably have to save a list of ordered ids somewhere on the widget and use that in the case of a many2one, same applies to the y values.

Ping me on your PR for review
