### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by Alembo** [OCA/web#50]
Dates are exported as "General" format which makes excel calculations a problem. Can you revert this back to the way it was? Export dates as "Date" format.

**Comment by legalsylvain** [comment]
Could you realize a Pull Request with the correct patch that fix this bug ?
Regards.

**Comment by Alembo** [comment]
Sorry but I have no experience with Github. I know that in 7.0.1.0 it was working good. After we updated to 7.0.1.1 we have this problem. Can we just download and overwrite 7.0.1.1 with 7.0.1.0 until u guys fix this?

**Comment by legalsylvain** [comment]
Do you use modules from OCA/Web repository for this extract ? if yes, witch ? and since when there is a problem?
Regards.

**Comment by Alembo** [comment]
From lp:web-addons/7.0 and update was done via GUI.

**Comment by legalsylvain** [comment]
and you use the module 'web_export_view', with the button 'export current view' ?

**Comment by Alembo** [comment]
Yes.
Don't u have this issue?

**Comment by Alembo** [comment]
Do you have a update about this issue? Can I download the earlier version(s) somewhere?

**Comment by pedrobaeza** [comment]
As no PR has been proposed, I close.
