### ISSUE TITLE
'web_color' module doesn't work

### ISSUE THREAD

**Issue by legalsylvain** [OCA/web#51]
Hi all, 

I tried today to use 'web_color' module, but it failed. Description of the module is very small. Are some people that use it in some custom modules ?
Regards.

My code: 

[From Model]

```
class MyModel(Model):
    _columns = {
        'color': fields.char(
            'Color', size=7,
            help="Color of the Price Tag by default. Format #RRGGBB"),
```

[From view]

```
 field name="color" widget="color"
```

[from openerp file]

```
depends = ['web_color']
```

At the end, i have a Javascript error. (Mozilla / Chrome)

```
TypeError: obj is not a constructor
```

**Comment by max3903** [comment]
Yes, we use it here :
https://github.com/OCA/management-system/blob/7.0/mgmtsystem_kpi/mgmtsystem_kpi_view.xml#L108

**Comment by legalsylvain** [comment]
Hi, 
Thanks @max3903 for your quick answer. It works fine in non editable tree view, i didn't tested that, but it's ok. 
In form view and in tree view (editable=xxx), it fails.

Do you have the same issue ?

Regards.

**Comment by max3903** [comment]
I haven't tested it. I guess I would.

**Comment by pedrobaeza** [comment]
I found the same problem. There's a PR with a better widget as the author @karim-omran says that we could replace with: #37

**Comment by legalsylvain** [comment]
Yes, this is a 8.0 PR.
Maybe we can imagine to change for the new lib, for 8.0 serie, to fix the problem.

+++

**Comment by hbrunn** [comment]
I confirm the module doesn't work for forms in 7.0. Backporting the 8.0 module seems the simplest solution to me
