### ISSUE TITLE
[10.0] web_responsive Main menu title

### ISSUE THREAD

**Issue by rousseldenis** [OCA/web#512]
@lasley @danieltorres7  Is it possible to add (if it isn't scheduled yet) the app Title between the toggle button and the first menu element to recall user in which app he is (e.g. 'Sales') ?

As in some cases it is not obvious if applications have the same menus.

**Comment by danieltorres7** [comment]
Yes, it's possible and I already have it working on my custom backend template. Should I create a PR on it @lasley?

**Comment by pedrobaeza** [comment]
Better title or icon?

**Comment by pedrobaeza** [comment]
As I'm seeing, Odoo enterprise uses the title with other font style:

![seleccion_005](https://cloud.githubusercontent.com/assets/7165771/21568584/0634143a-ceb6-11e6-86de-49afb7a57c84.png)

**Comment by danieltorres7** [comment]
Yes, its also available on https://www.odoo.com/apps/themes/10.0/backend_theme_v10/ and other backend themes.

**Comment by rousseldenis** [comment]
@pedrobaeza Exactly what I thought about !

**Comment by danieltorres7** [comment]
![captura de tela de 2016-12-30 14-46-04](https://cloud.githubusercontent.com/assets/18170025/21568834/d865eebe-ce9e-11e6-9ac7-d82d76271e99.png)
![captura de tela de 2016-12-30 14-46-38](https://cloud.githubusercontent.com/assets/18170025/21568836/dc90859e-ce9e-11e6-8a31-98fdfd2f90a8.png)

Here is my web_responsive customizations on App Title.

**Comment by pedrobaeza** [comment]
It seems good enough for me.

**Comment by danieltorres7** [comment]
OK, I will organize things and make some comments on code so I can commit and PR asap...

**Comment by lasley** [comment]
Hooray thanks everyone! This will be an awesome addition IMO

**Comment by lasley** [comment]
We're good to close this I think. Looks like all the features here are in the new, significantly better looking version.
