### ISSUE TITLE
RFC: Odoo Web Dashboards

### ISSUE THREAD

**Issue by dreispt** [OCA/web#525]
I was looking for an open source solution for a web dashboard to have self updated KPIs displayed in a dedicated screen. The `web_dashboard_tile` doesn't meet the requirements for this.

I found [Freeboard](https://github.com/Freeboard/freeboard): it is an extensible JS client webapp, and looks very promising. AFAICT it wouldn't be too hard to plug it in Odoo.

Thoughts? Any other dashboard alternatives you would advise?

**Comment by dreispt** [comment]
An addition inspiring link: the [Panic Status Board](http://panic.com/blog/the-panic-status-board/) and a [HTML/CSS implementation](https://github.com/nickschwab/PanicStrap/tree/master/PanicStrap) of it.

**Comment by legalsylvain** [comment]
Hi  @dreispt, what are the missing features ? Maybe we could improve web_dashboard_tile ? 
Anyway, very interested to review such work.

**Comment by dreispt** [comment]
Web_dashboard_tile would need more widget types: gauges, sparklines/line charts, etc. But that's achievable.
A harder requirement is that it should automatically update itself, preferably without page reloads.
Also, I would like the dashboard to be able to be displayed in full screen, without the menu bars (top and left), and other navigation elements.

**Comment by legalsylvain** [comment]
Interesting !

* For the first point, maybe it's not the purpose of this module, and should be done in an other module. Tiles are very little and I do not figure out how to display correclty a graph in there little squares. (A new module web_dashboard_graph ?) @OSguard, What do you think about that ?

* For the second point, it could be a good improvment of the current module, implementing a reload of data like the ir need action works. We could imagine to set an extra setting in each tile, "refresh_duration", depending of what we want.

* For the third one, I see it more like an extra module, like web_dashboard_tile_fullscreen, that implement some full screen feature like other web_ modules do for the time being. (or maybe an option in the current module). Another way to achieve this goal should be to add an extra option in web_hideleftmenu, with a list of defined action / menu item, where the left menu should be hidden. That could be the more generic way, because this need could be interesting for other Odoo views.

Regards.

**Comment by bealdav** [comment]
> I was looking for an open source solution for a web dashboard

Inside or not ?

Outside:

https://github.com/airbnb/superset/blob/master/README.md
https://github.com/metabase/metabase/blob/master/README.md

**Comment by dreispt** [comment]
> Inside or not ?

I'm not excluding either.
It would be nice to have that feature into Odoo.
But I don't mind setting up a service just for that, that connects to Odoo to get the needed data.

`superset` looks nice and it's Python.

**Comment by dreispt** [comment]
@legalsylvain The first one should be easy: Odoo already implemented large Kanban cards with gauges and line graphs. But the other two ones mean going into JS and CSS-land, and I'm not too familiar with that.

**Comment by bealdav** [comment]
> mean going into JS and CSS-land, and I'm not too familiar with that

So am I, `superset` just do that for us: good brains and activity there.
We only need to focus to materialized sql view to avoid join (unsuported by superset) and that's all: et la magie opère.

**Comment by bealdav** [comment]
> But I don't mind setting up a service just for that, that connects to Odoo to get the needed data.

You can setting up a service for bi and make it available for all your Odoo projects.

Set up can be easy like here: https://github.com/EBII/voodoo/blob/499ea33ba4c6e61da34f9716d8116301d13556c8/voodoo/odoo/docker-compose.yml#L2-L13 for voodoo project with metabase

**Comment by lasley** [comment]
I've used `superset` in the past & like it very much.

The real challenge if you were going to integrate something like that is that it already has a pretty killer UI. Something like the Etherpad integration in projects might work, but I think the page would still be constricted by the standard Odoo frame.

Am I misunderstanding the goals?

**Comment by dreispt** [comment]
@lasley My particular use case does not need to be framed inside Odoo UI, so a something like `superset` running alongside with Odoo would do the trick. I'll be trying that.

**Comment by bealdav** [comment]
We 'll work on February with @legalsylvain on this matter too.
With superset, maybe opensource java BI tools (pentaho, spago, etc) 'll have no future for us.

**Comment by huzzy143** [comment]
@bealdav Is there any update with integrating a dashboard like superset with Odoo. even we want to have a dashboard like superset for analyzing odoo data

**Comment by bealdav** [comment]
Other tool with python/flask and react:
http://bowtie-py.readthedocs.io/en/latest/index.html
https://github.com/jwkvam/bowtie

**Comment by bealdav** [comment]
@huzzy143 sorry no project on this matter for now but there is a new version of superset recently

**Comment by dreispt** [comment]
Great pointer @bealdav !
The Bowtie [comparison page](http://bowtie-py.readthedocs.io/en/latest/comparison.html) also has some nice links.

**Comment by bealdav** [comment]
https://github.com/facebookresearch/visdom with python again

**Comment by andreampiovesana** [comment]
I used superset to show kpi in production, 
but for simple visualization in odoo i found this interesting module
https://apps.odoo.com/apps/modules/10.0/dashboard/
i think this is the good way ...

**Comment by bealdav** [comment]
There is now https://github.com/bokeh/bokeh

**Comment by legalsylvain** [comment]
> We 'll work on February with @legalsylvain on this matter too.

We have worked with akretion Team on february, and the conclusion was that superset (and other tools) was very limited from an SQL Point of View. (join, etc.). Well, basically, it allow to browse your database, but the database is horrible to browse, and it's very difficil for end users.

I so developped a module that provides the possibility to have any result of any request with the core graph tools of Odoo, just writing an SQL Request. (you can use materialized view to reduce display duration).

available here : https://github.com/OCA/reporting-engine/blob/8.0/bi_sql_editor/README.rst

kind regards.

**Comment by dreispt** [comment]
Thank you @legalsylvain, but I'm afraid that the Odoo core graph tools miss an important requirement for my use case: self updating. The goal is to have a live dashboard displayed. Unless there's some JS magic somewhere that achieves the auto updating... :smile_cat:

**Comment by anothingguy** [comment]
> superset (and other tools)  limited from an SQL Point of View

thanks @legalsylvain: i don't understand much this point, I agreed Superset is very limited SQL but what's about other tools ?. Did you try [redash](https://redash.io) (written in python) and [metabase](http://www.metabase.com/) (written in clojure). I have just tried them on demo and they support SQL as i expected, SQL cache feature for "heavy" task. I feel metabase is nicer, supports both database browse  and SQL as well.

**Comment by pedrobaeza** [comment]
> but I'm afraid that the Odoo core graph tools miss an important requirement for my use case: self updating. 
@dreispt using bus you can make a refresh on the view. I think Anybox had a module for auto-refreshing views with this principle.

**Comment by bealdav** [comment]
Python's visualization landscape:

https://www.youtube.com/watch?v=FytuB8nFHPQ

**Comment by gustavovalverde** [comment]
This look like a promising subject. Has someone tested redash or metabase with Odoo? Any visual examples worth showing?

**Comment by pedrobaeza** [comment]
Closing as this doesn't present any PR nor more discussion.

**Comment by bealdav** [comment]
I've just tested redash. A marvellous tool.

Why close  this rfc ?

**Comment by pedrobaeza** [comment]
Because we need to triage things that are stuck. They can be marvelous ideas, but can't stay forever opened if they are not implemented.

**Comment by legalsylvain** [comment]
Hi @pedrobaeza. thanks for this usefull cleanup. (saw a lot of PR / issues closed recently). 
Well about that issue, the need still remains and is important and the discussion is still active. So reopening.

**Comment by pedrobaeza** [comment]
I don't think the discussion is still active, as last useful message was from 15 Aug 2017 (except now the reactions from my closing), but OK, as you want. For sure I will revisit this in 6 months and it will still continue the same.

**Comment by ketra21** [comment]
> Web_dashboard_tile would need more widget types: gauges, sparklines/line charts, etc. But that's achievable.
> A harder requirement is that it should automatically update itself, preferably without page reloads.
> Also, I would like the dashboard to be able to be displayed in full screen, without the menu bars (top and left), and other navigation elements.

hi,I am newer in superset,and want to creat a sparkline table on it,do you have any suggest?

**Comment by grottas** [comment]
FYI: Have you checked this?

https://apps.odoo.com/apps/modules/12.0/ks_dashboard_ninja/

https://dashboardninja.kappso.com/web/login
