### ISSUE TITLE
[9.0] web_responsive: Some bugs + improvements

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/web#540]
The mobile view is still not perfect, as you can see in this screenshot:

![seleccion_026](https://cloud.githubusercontent.com/assets/7165771/22390038/0946f07c-e4e9-11e6-8def-291e41f97771.png)

Other things that can be improved:

* When clicking on a menu, hide all the rolled-up menus to the right button, as you don't want to click there again or scroll down for seeing the part you have click on.
* Hide search view by default under a glass icon or similar, and when clicked, show it. You can click again in the glass icon for hiding.
* Full statusbar widget is very big to be shown as is.

![seleccion_027](https://cloud.githubusercontent.com/assets/7165771/22390274/5955a1d4-e4ea-11e6-8a5f-1ca700d0a040.png)

  It's better to show only active state and click on it for seeing the rest of the states (and allow to click for changing state if clickable).
* The same happens with the buttons in the header. We should group them under a button called "Actions" or similar (web_enterprise called it "Action" in singular, but I prefer in plural if we choose that name).

**Comment by yajo** [comment]
Can you point to how to get to screenshot 1?

**Comment by pedrobaeza** [comment]
In Firefox, go to mobile view, and see a sales order in form view.

**Comment by yajo** [comment]
I checked it; confirmed.

**Comment by yajo** [comment]
I can confirm that problem 1 does not happen in v10.

**Comment by pedrobaeza** [comment]
@lasley would you take care of the rest of the comments here?

**Comment by pedrobaeza** [comment]
Closing as triage and doesn't happen in v10.
