### ISSUE TITLE
'help_online' must reside on website repo, not here

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/web#55]
This module is linked to website repo, not web (in the concept of modifications to web client).

**Comment by legalsylvain** [comment]
Hi Pedro, I don't know this module. In fact it depend of 'website' and doesn't depend of 'web'.
But I don't know if it's a good idea to move a repository in a version used in production. Because if people are using this repository, they will loose the module when pulling last version. 
So maybe we can plan to mark this module "to be moved" and plan the move for the 9.0 serie. 

What is your point of view ?

regards

**Comment by pedrobaeza** [comment]
Well, this module has been merged only a while ago (3 weeks), and v8 use is not still widespread, so I don't think it's going to make a lot of harm, but let others say.

**Comment by foutoucour** [comment]
I agree with @legalsylvain and this refactory should be suggested in master rather in v8.0
It is actually pretty hard to mesure the impact of a such move in the current state

:-1:

**Comment by pedrobaeza** [comment]
It's not a refactory, only a reubication. As I said, this module lives in OCA only for a couple of weeks, and it's for v8. The impact is minimal, but if we keep here, for v9 the movement it's going to be more difficult.

**Comment by legalsylvain** [comment]
Hi again. For V9, we can imagine that we'll do the movement before release, and so without impact.
IE:
we move web/8.0/web_online -> website/9.0/__ unported __.

**Comment by legalsylvain** [comment]
BTW I don't see the OCA/website project (https://github.com/OCA/website) on http://odoo-community.org/page/website.List, do you know where is it ?

**Comment by pedrobaeza** [comment]
OCA web is still not updated for this project. We should warn someone of OCA board of that. @jgrandguillaume, can you check it, please?

**Comment by lmignon** [comment]
@pedrobaeza I understand your concern on a technical point of view. Nevertheless, in a functional point of view, the module allows you to write documentation available from the lists and forms in Odoo. IOW,  it allows you to document your 'forms' and 'lists' based on the module  'web'. The entry point for this documentation is a button placed on these lists and forms. The module doesn't extend the module website, it uses it but it extends the module web by adding buttons on lists and forms.  IMO, oca/web is the good place in a functional POV.

Regards,

lmi

**Comment by Cedric-Pigeon** [comment]
I agree with @lmignon. We didn't add any features to website module or even changed its behavior. We simply use it as a tool. The real added-value of help_online module is on the backend and not on the website side.

**Comment by sbidoul** [comment]
That said, hidden inside help_online is the export feature, which is completely generic and could be factored out as a new website_export module.

But that is left as an exercise for future contributors :smile:

**Comment by pedrobaeza** [comment]
OK, we leave this module here as is.

Thanks for your explanations.
