### ISSUE TITLE
help page missing for the "mass mailing module"

### ISSUE THREAD

**Issue by DidierLACOMBE** [OCA/web#552]
Hello

under 9C community W10

I am using help_online and it works well

But I can't create help page for the "mass mailing module"

Am I missing something ?

The page is created, but the ? button stay in red 

help

thanks

**Comment by pedrobaeza** [comment]
@Cedric-Pigeon I think this one is for you

**Comment by DidierLACOMBE** [comment]
Hello Pedro

I guess this is for VAT reporting
not for missing help page isn'it ?

Many thanks



Didier Lacombe



didier.lacombe303@gmail.com

Tél  : 00 33 (0) 6 20 57 32 20
Fax : 00 33 (0) 4 78 42 11 58



2017-02-08 12:22 GMT+01:00 Pedro M. Baeza <notifications@github.com>:

**Comment by Cedric-Pigeon** [comment]
Hello @DidierLACOMBE ,

We are not aware of such limitations.
I tested your case on runbot and it works succesfully.

It seems something is wrong on your instance.

**Comment by DidierLACOMBE** [comment]
hello

here is the link to the backup wich has the problem

regards

https://drive.google.com/file/d/0BwJb4lZkb0KqWk5UcFFXcmlKcDg/view?usp=sharing

Didier Lacombe



didier.lacombe303@gmail.com

Tél  : 00 33 (0) 6 20 57 32 20
Fax : 00 33 (0) 4 78 42 11 58



2017-02-15 7:36 GMT+01:00 Cédric Pigeon (ACSONE) <notifications@github.com>:

**Comment by pedrobaeza** [comment]
The case should be reproducible on runbot and the author has said that they can't identify the problem, so I close.
