### ISSUE TITLE
web_export_view - null values for Monetary fields

### ISSUE THREAD

**Issue by DarkChamp** [OCA/web#558]
When a field is defined as 'fields.Monetary' and currency symbol is placed before the value (i.e. '$ 55.67', '£ 11.23') then resulting value parsed from QWeb (web_export_view/static/src/js/web_export_view.js:on_sidebar_export_treeview_xls) to controller is null.

For the values where currency symbol is after value (i.e. '0.55€') is parsed and exported correctly.

**Comment by pedrobaeza** [comment]
Can you make the corresponding PR?

**Comment by pedrobaeza** [comment]
Solved in e0fc91a
