### ISSUE TITLE
[10.0] web_responsive conflicts with base_location:  half-hidden field.

### ISSUE THREAD

**Issue by JuanJoseGomez** [OCA/web#574]
The last changes in web_responsive generate some incompatibilities with the presentation of some views.
For example in the res.partner form of the base_location module the zip field (and others) appears half-hidden by another field.

I think the problem may be on line 36 of web_responsive/static/src/less/form_view.less:
white-space: nowrap;
Maybe it should be:
white-space: initial;

![image](https://cloud.githubusercontent.com/assets/7678088/23657478/9ec4469a-033e-11e7-85fd-c32d11eb98ff.png)

**Comment by astirpe** [comment]
cc @tarteo

**Comment by pedrobaeza** [comment]
Already solved with #620
