### ISSUE TITLE
[8.0] : web_group_expand : Error on TREE view

### ISSUE THREAD

**Issue by JayVora-SerpentCS** [OCA/web#580]
The problem appears on Tree view, with multiple clicks:
![screenshot from 2017-03-09 18 38 13](https://cloud.githubusercontent.com/assets/5909386/23907692/f2157e04-08f7-11e7-9784-50c4d3d76d5c.png)
![screenshot from 2017-03-09 18 37 33](https://cloud.githubusercontent.com/assets/5909386/23907694/f21ba612-08f7-11e7-8b8e-a5875bcf1b82.png)
![screenshot from 2017-03-09 18 33 54](https://cloud.githubusercontent.com/assets/5909386/23907693/f2199b1a-08f7-11e7-8722-9ea7bd35c11c.png)

**Comment by pedrobaeza** [comment]
Fixed in #581. Next time, better to just open the PR and put the issue report in it.
