### ISSUE TITLE
[wish] web_environment_ribbon display database name by default

### ISSUE THREAD

**Issue by zeroheure** [OCA/web#586]
This is a very little wish: 
It would be nice if web_environment_ribbon could display database name by default (instead of "TEST")

**Comment by lukebranch** [comment]
this would be pretty handy actually. I have been doing this manually myself.

**Comment by moylop260** [comment]
Database name could be too much big for the ribbon
Do you prefer another option?
Maybe a environment variable

**Comment by lukebranch** [comment]
you're right. yes, I think an environment variable could be handy. Running runbots for customers, this could be really useful, as they tend to get a bit lost sometimes without the ribbon telling them which DB they are in.

**Comment by moylop260** [comment]
In fact, IMHO we should install this module by default for all builds of runbot from MQT

**Comment by pedrobaeza** [comment]
Closing as there's now a PR.
