### ISSUE TITLE
[10.0] web_responsive: accesskey conflict

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/web#587]
On v10, global acceskey for editing a record is 'A' (Ctrl+Shift+A usually in most browsers), but that's the one we are using for the AppDrawer. So we have 2 options:

1) Change our AppDrawer accesskey to other
2) Change standard Odoo edit accesskey back to 'E', which I don't know why really they have changed it without any meaning.

I would be in favor of 2.

**Comment by lasley** [comment]
Bah worst part about undocumented features is that they can change for absolutely no reason whatsoever. 

I agree with option 2. `A` for `Edit` is just weird IMO. I can't find anything occupying the `E` namespace, so I think this change should be safe enough.

**Comment by pedrobaeza** [comment]
Closing for being tracked in #591
