### ISSUE TITLE
[v10] web_export_view: Export only contains the visible lines [80 by default]

### ISSUE THREAD

**Issue by bistaray** [OCA/web#598]
Odoo (which also used to export only the visible lines [80 by default]) is now exporting ALL records, so this behavior is now inconsistent

**Comment by pedrobaeza** [comment]
Do you mean with web_export_view? Please include the module name in the title.

**Comment by bistaray** [comment]
Sorry - yes!

**Comment by pedrobaeza** [comment]
Well, that's not the way it has worked, but it can be good. I have always see this as a "printscreen" export, so exporting what is visible is the correct thing, but the other use can be also interesting. Anyway, to achieve what you want will require a total refactoring, as this extracts data from the HTML DOM via JS, which is not possible exporting all domain.

**Comment by bistaray** [comment]
OK.  Appreciate the fast feedback.  I'll tell my users regular Export is the way to go if they want all records.

**Comment by pedrobaeza** [comment]
The other option is to change the number of displayed records to "Unlimited" and press the button to export.

**Comment by bistaray** [comment]
Yes - works until the number of records overwhelms browser storage.  Thanks again.

**Comment by legalsylvain** [comment]
What about a new button "Export All" ? and rename the other by "Export Selected items".
