### ISSUE TITLE
[10.0] web_tree_many2one_clickable (improvement)

### ISSUE THREAD

**Issue by bistaray** [OCA/web#599]
With the Enterprise Edition, the fields are not significantly different from regular fields:

![image](https://cloud.githubusercontent.com/assets/13910162/25101381/f016bf2e-2368-11e7-9ce7-5fe96715ea18.png)

User feedback was that it was too easy to accidentally click on a many2one without realizing, thinking they were clicking on the record.

What I did was add underline to the field and it makes it much more obvious that the field can be clicked:

![image](https://cloud.githubusercontent.com/assets/13910162/25101430/2549d078-2369-11e7-9141-130ffc9d5c19.png)

I changed /web_tree_many2one_clickable/static/src/js/web_tree_many2one_clickable.js

https://github.com/OCA/web/blob/10.0/web_tree_many2one_clickable/static/src/js/web_tree_many2one_clickable.js#L68

`
                    '<a class="oe_form_uri" data-many2one-clickable-model="%(model)s" data-many2one-clickable-id="%(id)s"><u>%(name)s</u></a>',
`

**Comment by pedrobaeza** [comment]
Can you please make a PR with the improvement?

**Comment by pedrobaeza** [comment]
Closing as no answer
