### ISSUE TITLE
Chrome Fallback on web_widget_image_webcam.flash

### ISSUE THREAD

**Issue by axatech01** [OCA/web#603]
I have been playing with the module and it worled on FF, when testing the module on Chrome it raises an error, so:

Where to set the  **web_widget_image_webcam.flash_fallback_mode**  to 1? , the help refers to "configuration parameter", but where is it localted on Odoo 9?.

Odoo: V9
Browsers tested: FF and Chrome.
Linux Dist: CentOS 7.2

Please help.

**Comment by pedrobaeza** [comment]
In Configuration > System parameters.
