### ISSUE TITLE
[8.0] web_x2m_filter: Moving with pager through records doesn't reapply the filter

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/web#608]
Using https://github.com/OCA/web/tree/8.0/web_x2m_filter, if you move to the next/previous record and you have a filter applied, the filter is not reapplied on the new record. There's 2 options:

* Reset the pressed filter button to the "All" one.
* Reapply the pressed filter.

**Comment by hbrunn** [comment]
did you try doing that in the field widget's setValue function?
