### ISSUE TITLE
[8.0] problem with  web_graph_radar

### ISSUE THREAD

**Issue by gaelTorrecillas** [OCA/web#610]
@yelizariev hello,

I have a problem with  web_graph_radar, the data aren't proportional with the graph, we can get out of it.

![error1](https://cloud.githubusercontent.com/assets/16572874/25376465/9579d276-29a4-11e7-9b6d-d60242814100.jpeg)
ps: this screen has the zoom of mozilla firefox at 110%. All values have a max value at 100.

But with the same values, I notice that without zoom (100%) the values don't have the same proportions.

![error2](https://cloud.githubusercontent.com/assets/16572874/25376871/fb398524-29a5-11e7-937d-76e66fbd902b.png)

do you have an idea to solve this problem? or a possible cause?

**Comment by yelizariev** [comment]
@gaelTorrecillas 
my bet is that some additional settings has to be passed to variable "chart " in code below
```
+            nv.addGraph(function () {
 +                var chart = nv.models.radarChart();
 +
 +                chart.margin({left:200, top:20, bottom:20});
 +
 +                d3.select(self.svg)
 +                    .datum(data)
 +                    .attr('width', self.width)
 +                    .attr('height', self.height)
 +                    .call(chart);
 +
 +                return chart;
 +            });
```

e.g. 

`chart.margin({left:200, top:20, bottom:20}).height(self.height/2).width(self.width/2)
`

**Comment by pedrobaeza** [comment]
Closing as this seems to be something WIP.
