### ISSUE TITLE
[10.0] problem with web_widget_x2many_2d_matrix

### ISSUE THREAD

**Issue by nithwith** [OCA/web#612]
Hello @jesusVMayor , 
I try the module with the current modification (commit : Migration of web_widget_x2many_2d_matrix to 10.0 ) and i can not make it work.
I try this code (like the example) :
` <field name="task_ids" widget="x2many_2d_matrix" field_x_axis="project_id" field_y_axis="user_id" field_value="planned_hours" />`

![2017-04-27 16_14_13-website for sales wms - odoo](https://cloud.githubusercontent.com/assets/19471913/25487510/b7681368-2b64-11e7-8466-dae0df5fb4e4.png)

**Comment by pedrobaeza** [comment]
You probably make something incorrect. Check a working example here:

https://github.com/OCA/sale-workflow/pull/454

**Comment by nithwith** [comment]
I try on the runbot v10, and the module does not work
![2017-04-27 16_14_13-website for sales wms - odoo](https://cloud.githubusercontent.com/assets/19471913/25488338/0df9cd5a-2b67-11e7-8bd8-0648da649add.png)

**Comment by tandrieuxx** [comment]
I have the same problem. Your "working example" has no relation with this issue.

**Comment by pedrobaeza** [comment]
Use the same technique that the example and it should work.

**Comment by nithwith** [comment]
[testMatrix.zip](https://github.com/OCA/web/files/962202/testMatrix.zip)

I have built a module for test the widget and he don't work with me, is it incorrect ?

**Comment by tandrieuxx** [comment]
Examples should explain how to use a module in a simple way, with a simple context, relatively easy to understand. The one provided is the worst !

**Comment by pedrobaeza** [comment]
Well, if you don't like this work that has been provided to you for free, then feel free to use another or at least to improve the documentation to match what you consider a good example.

**Comment by pedrobaeza** [comment]
As last action by my part, I can tell you that your code is incorrect, changing the default method as compute. The only thing not documented is that now project.task has 2 new required fields, that I have added in https://github.com/OCA/web/commit/720a5a84a587ee9159399b9e2567270b3b365709.
