### ISSUE TITLE
[9.0] web_access_rule_buttons - property 'then' of undefined

### ISSUE THREAD

**Issue by psugne** [OCA/web#618]
I installed web_access_rule_buttons addon but got an error:
Uncaught TypeError: Cannot read property 'then' of undefined

What can be wrong?

<img src="http://www.part.lt/img/187aab0939667aa8752de9fd8312d534979.png" />

As I understand I have to change this place:

_odoo.define('web_access_rule_buttons.main', function (require){_

But don't know how.

**Comment by KomarovAlea** [comment]
What version of odoo?
look at odoo\menu\settings.
What version of the module 'web_access_rule_buttons'?
Look at odoo\menu\apps\'web_access_rule_buttons'\version
