### ISSUE TITLE
[10.0] web_widget_x2many_2d_matrix  | Adding/Deleting Attribute Values via table

### ISSUE THREAD

**Issue by blutecsolutions** [OCA/web#636]
First of all, a big thanks to OCA, Tecnativa and whoever participated in developing this Module :) It's brilliant
-

My request is for a  user to have the ability to _add/delete_ attributes to/from a Product template:

In the example i've used product CHEMISE with two Attributes: **Color** and **Size** and they have the following Attribute Values:
Color: C1 - C2 - C3 
Size: 42 - 44 - 46 - 48

![image](https://cloud.githubusercontent.com/assets/26249588/26282245/d73d1efe-3dfc-11e7-814a-f21f335b6600.png)

So by using a plus/minus button we could add or delete attributes on the fly! Or if removing the attribute values, _at least adding extra ones will help._

Thanks.

**Comment by pedrobaeza** [comment]
That would be a feature on the widget itself, but not simply to add, so if you want to work on that, go ahead, but don't expect anyone to do it for now.
