### ISSUE TITLE
web_timeline install

### ISSUE THREAD

**Issue by mareban** [OCA/web#675]
Hi,

I've tried to install the web_timeline widget, and got an error when creating the view "field type doesn't exist" : 

Erreur lors de la validation de la contrainte

Le champ `type` n'existe pas

Contexte de l'erreur :
Vue `project.task.timeline`
[view_id: 637, xml_id: n/a, model: project.task, parent_id: n/a] 

Do i miss something ?

**Comment by pedrobaeza** [comment]
The module is working as you can try on runbot on both versions (you don't indicate which one you are using). Anyway, it's not a problem of the module, but a problem in your installation. Try with a new fresh DB.

**Comment by mareban** [comment]
Well, we use Odoo v10 and it is a brand new installation !!

We download the latest version, copy the web_timeline directory in the Odoo's addons directory, update the application list and install web_timeline !

Is that correct ?

**Comment by pedrobaeza** [comment]
And what about restart the service?

**Comment by mareban** [comment]
Service restarted, and nothing appear on the project/task !!!

Thanks for your help.

**Comment by jcdrubay** [comment]
You should use the module from project repository for this https://github.com/OCA/project/tree/10.0/project_timeline.
It work very well thanks @pedrobaeza :+1:

**Comment by mareban** [comment]
Sorry,

In the configuration, i have a view called web_timeline asset do i have to create a view as mentioned by the documentation ?

The module seems to be installed !

Do i have to activate something somewhere to see a Gantt ??

Thx

**Comment by pedrobaeza** [comment]
See the README.

**Comment by pedrobaeza** [comment]
And the previous comment.

**Comment by mareban** [comment]
Hi,

With the project_timeline it's ok now :-)

Thx very much

**Comment by mareban** [comment]
too fast :-(

each time i change something on the graph, the modification are not kept and i've got a message : "
The operation cannot be completed, probably due to the following:
- deletion: you may be trying to delete a record while other records still reference it
- creation/update: a mandatory field is not correctly set

[object with reference: Project - project.project] 

Any idea please ?

Thx
