### ISSUE TITLE
[10.0] web_advanced_search_x2x: error while selecting "contains" or "not contains" in a x2x field

### ISSUE THREAD

**Issue by simmatica** [OCA/web#676]
![image](https://user-images.githubusercontent.com/18054167/28362174-bef85db0-6c7b-11e7-8d17-6a52569ad293.png)

![image](https://user-images.githubusercontent.com/18054167/28362205-d7c3bbaa-6c7b-11e7-97e0-87b685d4e9b6.png)

**Comment by simmatica** [comment]
Also selecting "is set" or "is not set".

**Comment by pedrobaeza** [comment]
Check latest version in https://github.com/OCA/web/pull/672

**Comment by simmatica** [comment]
Sorry but #672 is not about web_advanced_search_x2x

**Comment by simmatica** [comment]
Same error also in runbot, please give a feedback. Thanks

**Comment by pedrobaeza** [comment]
Yes, it is. See better. It modifies this module to give a better UI.

**Comment by simmatica** [comment]
Ok, I'll try, thanks

**Comment by simmatica** [comment]
Same issue also in #672, in that PR web_advanced_search_x2x is only changed to use the backport module web_widget_domain_v11, but there is the same error with operator "contains", "doesn't contains", "is set", is not set". Can you reopen the Issue please?

**Comment by pedrobaeza** [comment]
Please specify the steps to reproduce the problem.

**Comment by simmatica** [comment]
1. In any views (ex. Contacts o Customers, or any other)
2. Filters
3. Add Custom Filter
4. Select any x2x field (ex. Tags)
5. Change the operator to "Contains"
6. UI raise the error
I've also posted some scheenshot.

**Comment by yajo** [comment]
I'm preparing a fix that will land on #672
