### ISSUE TITLE
[10.0] web_responsive bug with document_page menu

### ISSUE THREAD

**Issue by jorgeveramorales** [OCA/web#679]
Without web_responsive and installin document and document_page module, you can access both menu for documents and pages 
![0](https://user-images.githubusercontent.com/23499444/28491445-102c25b8-6ef2-11e7-869f-dc47edfd5a76.jpg)
![1](https://user-images.githubusercontent.com/23499444/28491456-315b59b6-6ef2-11e7-92d1-d208f821f921.jpg)
With web_responsive, when you go to knowlegde menu, you go directly to page menu and can´t see the document main view.
![2](https://user-images.githubusercontent.com/23499444/28491465-7c9efb62-6ef2-11e7-97cc-a1b4ba6c895f.jpg)
I don´t know if it is a problem with web_responsive or with the document_page.

**Comment by pedrobaeza** [comment]
document_page is bad designed in this case. Odoo doesn't allow this behavior also on its responsive design, so please change document_page for not assigning an action in the parent menu.
