### ISSUE TITLE
web_tree_many2one_clickable extension

### ISSUE THREAD

**Issue by MMstp** [OCA/web#680]
Hi,
I'm using your module [web_tree_many2one_clickable](https://github.com/OCA/web/tree/10.0/web_tree_many2one_clickable) and it's working great for many2one relations. However for references it did not work as expected.
I added the condition `|| this.type == 'reference')` to the function `_format` inside `ListView.Column.include` in the file 'web_tree_many2one_clickable.js' at Line 47:
`if ((this.type == 'many2one' || this.type == 'reference') &&
            (this.widget == 'many2one_unclickable' || this.use_many2one_clickable) &&
            !!row_data[this.id])`

and now the references are also clickable links.

**Comment by pedrobaeza** [comment]
Please make a PR for the reference. For your information, this is not a bug, but a enhancement.

**Comment by pedrobaeza** [comment]
OK, I'm seeing the second part, which should be notified independently from the first. Please split both.

**Comment by MMstp** [comment]
I did as you suggested:
PR [FIX: allow clickable references #682](https://github.com/OCA/web/pull/682#issuecomment-318587073)
(I hope, I did this correct - it's my first PR :) - please tell me if not!

New open issue: [web_tree_many2one_clickable - duplicate link bug #681](https://github.com/OCA/web/issues/681)
