### ISSUE TITLE
web_tree_many2one_clickable - duplicate link bug

### ISSUE THREAD

**Issue by MMstp** [OCA/web#681]
Hi,
while using your module [web_tree_many2one_clickable](https://github.com/OCA/web/tree/10.0/web_tree_many2one_clickable)
I recognized, that when the tree is editable, the link is shown twice, if the field is not editable - which looks really weird: 
![grafik](https://user-images.githubusercontent.com/26869102/28705678-33511f8e-7371-11e7-9ede-a38bda4a7f91.png)

**Comment by pedrobaeza** [comment]
Is this still happening? Which version?
