### ISSUE TITLE
Export the current view to PDF

### ISSUE THREAD

**Issue by max3903** [OCA/web#692]
Hello,

Is there any existing module to export the current view into PDF?

Any plan/interest to add that feature to web_export_view? 

Or do you want it to be in a separate module (web_export_view_pdf)?

Thank you.

**Comment by pedrobaeza** [comment]
Well, having the export to Excel and converting for LibreOffice/Office to PDF is enough for me when needed, but include this option in `web_export_view` (maybe through a dynamic QWeb report), can be good.

**Comment by pedrobaeza** [comment]
Closing as answered and no feedback.
