### ISSUE TITLE
Web Export Current View v10 bug

### ISSUE THREAD

**Issue by davinci41** [OCA/web#693]
hello 

In the module is an error, after entering the user list.

![screenshot_1](https://user-images.githubusercontent.com/25403547/29337647-51752b5e-8212-11e7-9596-d7bf6d4760bd.png)

**Comment by pedrobaeza** [comment]
Please include all the steps to reproduce the problem in runbot.

**Comment by samirajakalidass** [comment]
I'm Also Having the Same Error Help me

![image](https://user-images.githubusercontent.com/11584758/30685603-13e52de2-9ed3-11e7-9a1c-6b6e4c666298.png)

**Comment by pedrobaeza** [comment]
No feedback, so I close.
