### ISSUE TITLE
[10.0] web_widget_domain

### ISSUE THREAD

**Issue by steync027** [OCA/web#695]
Hi community!

Great work on getting the new char domain widget from version 11.0 working in version 10.0. Simply amazing - it adds so much value to the community.

I was looking at the javascript here and I wonder if someone could give me an indication whether it would be possible to get this working in version 9.0 as well? I know the javascript has changed a lot from version 9.0 to 10.0, but if it is possible it will be great to hear if you've got any tips for me.

**Comment by pedrobaeza** [comment]
The best if to check one of the widgets that is migrated to both v9 and v10 to compare changes and apply that changes to this module:

https://github.com/OCA/web/tree/9.0/web_widget_x2many_2d_matrix
https://github.com/OCA/web/tree/10.0/web_widget_x2many_2d_matrix
