### ISSUE TITLE
[10.0][web_shortcut]Technical menus in debug mode are not complete

### ISSUE THREAD

**Issue by flotho** [OCA/web#701]
Hi,

I've installed  /oca/web menus and tried to use the debug mode as usual and all the menus are not available :

![spectacle x25333](https://user-images.githubusercontent.com/1043935/29498454-16578d84-85fd-11e7-9bac-e28aa9e00a11.png)

I don't find what could cause this, any help/advice/tip would be appreciated.

regards

**Comment by pedrobaeza** [comment]
Which module? Please try on vanilla and OCA/web runbot to see if you identify the problem.

**Comment by flotho** [comment]
Hi,
The shortcut module seems to cause this issue on my local DB. I'll gonna have a try on runbot.

**Comment by flotho** [comment]
Hi,
I confirm that the problem is present in runbot :
![spectacle p28785](https://user-images.githubusercontent.com/1043935/30039043-eda182a2-91cb-11e7-988a-f0754ec9bbd4.png)

**Comment by flotho** [comment]
Hi @tarteo ,
Any idea where it could come from ?
regards

**Comment by aldo774** [comment]
I've debug the shortcut module and commenting the implementation of 'current_action_updated', debug menu show all items again.

https://github.com/OCA/web/blob/6dee0183a09e34d640b944a52569f2932a417a94/web_shortcut/static/src/js/web_shortcut.js#L80

**Comment by flotho** [comment]
Hi @aldo774 , any PR from you in the pipe ?

**Comment by aldo774** [comment]
Hi @flotho, I didn't open a PR because I don't know the cause of the problem, I saw that when i commenting the implementation of the event _**current_action_updated**_ the debug menu returns to display all the options, I don't know what this implementation does, but when I comment it I didn't realize any difference in behavior of shortcut module.

**Comment by sebalix** [comment]
I confirm this bug, the module hides some debug menu entries.

**Comment by thomaspaulb** [comment]
@flotho @sebalix @aldo774 I am trying to reproduce this bug, but am unable to do so. Could you be more specific as to what steps you follow (on runbot, or on a local test database) to get this bug?
