### ISSUE TITLE
web_advanced_search_x2x doesn't work with contains filter

### ISSUE THREAD

**Issue by Cedric-Pigeon** [OCA/web#717]
I am using this module and I really like it but it seems that it contains a bug.

On a model if you want to search on a many2one with a filter "contains" a string.
The string is always replaced by false.

Does anyone have the same problem ?

**Comment by pedrobaeza** [comment]
Fixed in #716

**Comment by rafaelbn** [comment]
Solved in https://github.com/OCA/web/pull/716
