### ISSUE TITLE
web_widget_color : nothing popup on new record

### ISSUE THREAD

**Issue by damdam-s** [OCA/web#718]
This widget works well while editing an existing record.

When creating a new record and trying to modify the value, the color picker popup is not displayed.

**Comment by pedrobaeza** [comment]
Odoo version?

**Comment by damdam-s** [comment]
Odoo 10, sorry

**Comment by hongquangminh** [comment]
Hi everyone,

I have the same issue. Have fixed in Odoo 10.0?

**Comment by JordiBForgeFlow** [comment]
We have also reproduced this same issue.

**Comment by hongquangminh** [comment]
I found this PR https://github.com/OCA/web/pull/604 and tested. It working. Can you check it @jbeficent ?

**Comment by ntraficante** [comment]
Hello! I have the same problem in Odoo 11 module. I know I have to make a change in this part of the code (widget.js), but don´t know how to add the "new/create" event (not only the edit/update).

```
 /*
     * Init jscolor for each editable mode on view form
     */
    FormController.include({
        _updateEnv : function (parentID) {
            this._super(parentID);
            jscolor.init(this.$el[0]);
        }
    });
```

**Comment by pedrobaeza** [comment]
Please review the PR for merging it and solving this. In v11 things are very different (different JS API), so it should be handled in a separate issue.
