### ISSUE TITLE
[10.0] BUG web_decimal_numpad_dot

### ISSUE THREAD

**Issue by angelmoya** [OCA/web#724]
This module is translating also in char and email fields.

For example in partner form view:
- On street field you are not able to write "Av. Loquesea"
- On email field you are not able to write "angel.moya@midominio.com"

@Yajo, I'm sorry for not reviewing previous PR

**Comment by pedrobaeza** [comment]
Are you using latest version?

**Comment by angelmoya** [comment]
like a newbie!!!

sorry a lot, I was trying with 1th September versión, previous Yajo refactoring...
