### ISSUE TITLE
web_confirm_window_close in Odoo v10..

### ISSUE THREAD

**Issue by mariothiermann** [OCA/web#727]
..doesn't do anything. 

This module is exactly what i need but if i close the browser or tab with unsaved data nothing happens. All unsaved data are away.

Mario

**Comment by michotm** [comment]
Tested on Odoo Server 10.0-20170816 
it works with firefox but not on chrome

**Comment by devang-dreambits** [comment]
The issue is fixed. Please have a look at #1010 .
