### ISSUE TITLE
Suggestion web-lang a language based CSS

### ISSUE THREAD

**Issue by mohamedhagag** [OCA/web#73]
Dears,

I would suggest the web-lang module to be added to OCA. 

this module adds support for language based css files to load modules and attributes like language direction and styles.

Also there are other general modules like:
- sale and invoice discount information in the web and in reports.
- report-rtl for RTL reports.

https://github.com/mohamedhagag/dvit-odoo8

Regards,

**Comment by pedrobaeza** [comment]
Hi, Mohamed,

Indeed it's very welcome. You have to clone current repository, add your module as a new commit, and make a PR against the general one.

Regards.

**Comment by pedrobaeza** [comment]
As no feedback given, I close this.
