### ISSUE TITLE
TypeError: instance.web.form.One2ManyDataSet is not a constructor

### ISSUE THREAD

**Issue by akhodifad** [OCA/web#744]
I created a custom  This field and widget is used in a one2many field/widget. The problem is now that it just works if you are editing the line of the one2many field. If you are just viewing the form without editing only the id of the selection field is shown as text.
1)TypeError: instance.web.form.One2ManyDataSet is not a constructor
![error1](https://user-images.githubusercontent.com/32675315/31388791-cdd79b54-adec-11e7-830d-2c2e1ff8e991.png)
I have face problem with odoo 10 version for web_widget_x2many_graph model.

**Comment by yajo** [comment]
- Logs should be in assets debug mode to be useful.
- Logs should be full to be useful.
- You didn't indicate the addon that fails.
- You didn't say the odoo version you're using.
- You say it's producing when using own customizations.

For all these reasons, closing. Reopen if you fix the report problems and are able to reproduce in an empty database please 😉
