### ISSUE TITLE
web_responsive: Header overlapped on scroll

### ISSUE THREAD

**Issue by lasley** [OCA/web#756]
REF https://github.com/OCA/web/pull/742#pullrequestreview-69401273

![image](https://user-images.githubusercontent.com/7397578/31617740-e4571682-b244-11e7-8bf7-ec4abdd5c467.png)

**Comment by lasley** [comment]
This will be fixed in  #714 (220ead1)

**Comment by pedrobaeza** [comment]
Closing as solved in the PR.
