### ISSUE TITLE
[11.0] web_responsive: odoo.define_section is undefined

### ISSUE THREAD

**Issue by yajo** [OCA/web#759]
Current 11.0 builds will all fail due to:

 https://github.com/OCA/web/blob/d62b1b563af449317ab9cada65998df4f0707902/web_responsive/static/tests/js/web_responsive.js#L4

Odoo 11.0 changed the way we write widget tests, and in this change, it removed `odoo.define_section`. That's why we are getting [errors such as this one](https://travis-ci.org/OCA/web/jobs/287908508#L942-L945):

```
` AssertionError: ("TypeError: undefined is not a function (evaluating 'odoo.define_section')\n"
`  ' at http://127.0.0.1:8069/web_responsive/static/tests/js/web_responsive.js:4 '
`  '(in global code)\n'
`  '(leaf frame on top)')
```

We have to fix that, and it would be good to add the instructions to https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0 once discovered how to do it.

The good news is that we have lots of good examples available and some introduction in slides 35-41 of @gde-odoo's [presentation at Odoo Experience 2017](https://www.odoo.com/es_ES/slides/slide/the-odoo-js-framework-492).

To start, it seems you have to just use `odoo.define` to run the tests, but I'm not sure the depth of the changes in that file to adapt to new tests, to be honest...

cc @Tecnativa @lasley @angelmoya

**Comment by lasley** [comment]
Yay... another completely undocumented tour system to learn. Thanks Odoo

**Comment by pedrobaeza** [comment]
Well, as stated in Odoo days, they're working on that part now.

**Comment by yajo** [comment]
Yes, at least you can check the JS code and it should contain proper docstrings right now, although you still have to guess the right file to look up to. 😆

**Comment by hgminh95** [comment]
Since this module does not use Odoo Widget, there are only some changes in syntax of javascript test. I have provided a fix. You guys can take a look at #772.
