### ISSUE TITLE
web_export_view "Export current view" should be placed in "More" drop down

### ISSUE THREAD

**Issue by ferdiga** [OCA/web#76]
to be consistent with odoo "More" policy the  "Export current view"  should be placed in the drop down list and not beside (although I find it quite useful to have it as an extra button)

**Comment by pedrobaeza** [comment]
This can be easily achieved if people agrees to do it.

**Comment by nhomar** [comment]
I am agreed with @ferdiga

**Comment by pedrobaeza** [comment]
This can go to "Known issues" section, but no real problem with the module itself. As no PR has been proposed, I close this.
