### ISSUE TITLE
[10.0] web_dialog_size: how maximize only the popup for order lines

### ISSUE THREAD

**Issue by taifu** [OCA/web#762]
First of all: great addon!
I would like to maximize only the popup used to edit the lines of Purchase Order, Sale Order, Invoice Lines, ecc.
If I define the key "web_dialog_size.default_maximize" it works but it maximize also simple warning popup.
I tried to put .dialog_full_screen class on everything in the Purchase Order Form (field order_line, his tree, his form, ecc.) but nothing.
Is this possible or I have to choose between all or nothing?
Moreover: the doc says "By default, the module respects the caller's `dialog_size` option" but in all the sources I do not find anything about this option

**Comment by pedrobaeza** [comment]
Right now, there's no option of individual size choice.

**Comment by taifu** [comment]
Ok! Thanks a lot for your answer.
Perhaps it's better to fix the docs, saying this

**Comment by pedrobaeza** [comment]
Docs don't mention anything about that if I remember well. Any PR for improving them is welcome any way.
