### ISSUE TITLE
[8.0] web_widget_digitized_signature not working on mobile devices

### ISSUE THREAD

**Issue by ghost** [OCA/web#769]
Hi,

We use the digitized signature in two wizards to store user signature.
When using a mobile device only the signature canvas in the wizard moves (page move), no drawing input is recognized.
It seems that the mouse/touch events are not properly handled.

Error appears with iPad, Android 7 Phone (5") and Android 7 tablet (10").
Any ideas?
I use your latest version: branch 8.0 from 28-Jul-2017

Regards,
Michael

**Comment by pedrobaeza** [comment]
Closing as old. Solution would be to backport v9 module that works with mobiles.
