### ISSUE TITLE
[11.0] Drop-Down menu problem

### ISSUE THREAD

**Issue by nogueira-raphael** [OCA/web#773]
Drop-down menus do not roll when they are very large.
In the image example the menu in Settings is quite extensive and you can not scroll to see the whole menu, just what it shows on the screen.

![captura de tela de 2017-10-23 01-32-22](https://user-images.githubusercontent.com/20387443/31872437-5e0a9c4a-b792-11e7-9a45-67a567be02f9.png)

**Comment by pedrobaeza** [comment]
This happens also in other versions. The workaround is to zoom in and zoom out and the scrollbar appears.

@lasley can you check it?

**Comment by lasley** [comment]
I admittedly knew about this one and was just waiting until it bugged someone enough to submit a ticket. I would assume it affects all versions.

Another trick is to resize the window. All of it bubbles into [`handleWindowResize`](https://github.com/OCA/web/blob/11.0/web_responsive/static/src/js/web_responsive.js#L130), which I'm sure I can just call in the init to resolve.

**Comment by lasley** [comment]
#776 for v10. I'll cross port when confirmed
