### ISSUE TITLE
Installing & configuring Project Timeline

### ISSUE THREAD

**Issue by ndkazu** [OCA/web#782]
Hello,
I've installed both modules Project_timeline and web_timeline in Odoo 10 on Windows 7.
I get the Gantt chart display, but I don't get the "date_start, date_end, date_delay, etc..." fields when double-clicking on a record. The web_timelline help file is talking about configuring those fields, even showing an example of xml code, but which file should be modified? details are very scarse. 
another point is the manual mentions the following issue: "Implement a more efficient way of refreshing timeline after a record update", but the timeline is not refreshed at all after modification of the deadlines whatever I do. I've got the feeling that the module is installed but not correctly configured. did I miss a step in the installation/Configuration of the module??

Kazunobu

**Comment by pedrobaeza** [comment]
The fields were added in form view (although they were modifiable directly from the timeline view before) in https://github.com/OCA/project/pull/324, so I don't get the problem. Any way, this should be in OCA/project, not here.
