### ISSUE TITLE
Wrong form.js on web_m2x_options branch 7.0

### ISSUE THREAD

**Issue by gbonline** [OCA/web#784]
Hi, I'm using odoo 7.0  
and with the module, downloaded from 7.0 branch, web_m2x_options, I saw that the "create and edit...." link didn't disappear on fields with many2many_tags widget.
So after some search on the code, I found that the form.js included on this package is wrong.
on the code there are reference  as "widget.view.ir_options_loaded" 
but the ir_options_loaded don't exist on web module of odoo 7.0

From the link below I found the correct version of this module
[https://github.com/0k/web_m2x_options](https://github.com/0k/web_m2x_options)

regards

**Comment by pedrobaeza** [comment]
That version is very old, but you can make a PR making the proper change (or at least informing of that in README). Meanwhile, as stated about the old version, we shouldn't keep opened issues of them.
