### ISSUE TITLE
[RFC] Widget to allow a field to start an action when you press enter (used by barcode readers)

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/web#786]
Hi!
In some scenarios we want to design a wizard that allows a user to enter a code, using a barcode scanner, and once the code has been entered, it should automatically trigger some action.

For example, you have an event and you printed badges. To confirm the attendance to the event you open a wizard that expects a field "barcode_text". As soon as you enter the code, the wizard should be confirmed (and would possibly open a new wizard to enter the next).

This is one example, but we found others, for various scenarios.

My initial thinking is that you would extend the Char widget, so that you could define the field in the form view as follows:
 <field name="barcode_text" widget="barcode" action="confirm">
When the user enters content in "barcode_text", a js would expect an "Enter" envent, and would then call the action with name "confirm".

This type of widget would make it possible to use barcodes for many recurring tasks in odoo.

**Comment by hbrunn** [comment]
how about adding this to the form widget, something like `<form options="{'keycodes': {13: 'my_action'}}">` and the form then sets up listeners. If the widgets don't catch the keypress event themselves, it should bubble up to the form widget, which then handles this exactly like pressing a button with `type='object' name='my_action'`

**Comment by lasley** [comment]
An interesting proposal @jbeficent. Are you thinking of using this solely for wizards dedicated to the defined workflows? If so, maybe something like [`stock_scanner_web`](https://github.com/OCA/stock-logistics-barcode/pull/95)?

If it's just simple fields, there's also the built-in [`barcode.events.mixin`](https://github.com/odoo/odoo/blob/11.0/addons/barcodes/models/barcode_events_mixin.py#L6)  paired with `barcode_events=True` ([docs](https://github.com/odoo/odoo/blob/cd48a806ac636806130efcf5c055f73758cb0902/addons/barcodes/doc/index.rst#barcode-events))

**Comment by JordiBForgeFlow** [comment]
After analyzing @lasley proposal, seems to be exactly what I'm looking for. I will test.

cc @rgarnau

**Comment by pedrobaeza** [comment]
@jbeficent any information about what do you intend to do with this?

**Comment by JordiBForgeFlow** [comment]
It is intended to be used in a very custom approach to pre-invoicing checks
in the healthcare context. Before you send an invoice to a customer you
have to verify that all paperwork is in place, then you barcode the code of
the Encounter, so as tp agree that the related sales orders are good to
invoice.

**Comment by pedrobaeza** [comment]
Uhm, I don't know too much that environment, but having a kind of helpdesk main screen for that and adding the listeners for barcodes can work.

**Comment by lasley** [comment]
Curious - Are you planning on using `stock_scanner_web` or custom events? The helpdesk main screen approach Pedro is suggesting could be accomplished by simply making a contextual scenario I think. Example [here](https://github.com/OCA/stock-logistics-barcode/tree/9.0/stock_scanner_inventory)

**Comment by JordiBForgeFlow** [comment]
I was planning on using the barcode events. Because it is not.going to be a
mobile.operation, but one performed by accounting clerks on the office,
using barcode readers.

But as I said, it is a scenario very specific to a particular customer. The
point is that sometimes you want to capture a barcoding event, capture the
barcode and trigger an action, which is what seems like the barcode
module.from odoo offers.

On Nov 1, 2017 9:40 PM, "Dave Lasley" <notifications@github.com> wrote:

Curious - Are you planning on using stock_scanner_web or custom events? The
helpdesk main screen approach Pedro is suggesting could be accomplished by
simply making a contextual scenario. Example here
<https://github.com/OCA/stock-logistics-barcode/tree/9.0/stock_scanner_inventory>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/OCA/web/issues/786#issuecomment-341235432>, or mute the
thread

**Comment by lasley** [comment]
Yup that's exactly what it's for, and it works quite well. Only issue I've run into is making sure the user focuses the element before scanning. The events don't work as well as anticipated when applied to higher level elements, like the web client itself.
