### ISSUE TITLE
[7.0] web_readonly_bypass on tree view inside form

### ISSUE THREAD

**Issue by Cywaithaka** [OCA/web#788]
For readonly fields inside tree view, the value of readonly fields is not being saved.
To reproduce, test this with sale.order
<record id="sale.action_quotations" model="ir.actions.act_window">
    <field name="context">{'readonly_by_pass': True}</field>
</record>
Then make the price_unit field on sale.order.line (line_id field) to be readonly.
The value of price_unit is not being saved.

**Comment by pedrobaeza** [comment]
That's an already known issue. For 8.0 it was fixed, but not in 7.0, as it's very very old.
