### ISSUE TITLE
Header Nav Bar is lapping position

### ISSUE THREAD

**Issue by iampreethamveigas** [OCA/web#789]
![screenshot_2017-11-03-17-16-58](https://user-images.githubusercontent.com/24918810/32372684-eab7bb96-c0bb-11e7-8c8b-2632b389f87f.png)

any light to this bug..

**Comment by yajo** [comment]
Closing since there's no information on how to reproduce it.

**Comment by iampreethamveigas** [comment]
There was a bug in web_responsive module, in Android chrome the header nav bar is overlapping the main body section when you scroll.
installed latest code.
using in odoo 10 .
tested in Samsung j8 chrome.

**Comment by pedrobaeza** [comment]
Duplicated with #756

**Comment by iampreethamveigas** [comment]
is there any possibilities to fix the bug, i would follow if is there any, i did  went through #756 and dint get any fix so far.

**Comment by pedrobaeza** [comment]
No, it isn't. If it remains opened it's because it's not fixed.

**Comment by iampreethamveigas** [comment]
ok. hope it ll be get fixed  soon.. or probably do some css workaround.

**Comment by pedrobaeza** [comment]
If you are able to fix it, please propose a PR with the fix.
