### ISSUE TITLE
Error while importing module 'web_responsive': ''

### ISSUE THREAD

**Issue by UnixedIT** [OCA/web#794]
Trying to import web_responsive-11.0.1.0.1 module to Odoo 11.0-20171019 (Community Edition) and i'm get this error "Error while importing module 'web_responsive': ''

knowing i have deployed odoo 11.0-20171019 using Bitnami over google cloud platform.

**Comment by pedrobaeza** [comment]
You can't import this module. That's only for data-only modules, which is not the case. Install properly on the server.
