### ISSUE TITLE
Numpad Dot as decimal separator app page is confusing 

### ISSUE THREAD

**Issue by icf20** [OCA/web#804]
the way this is place is confusing on one had here on github the migration is done to version 10 yet on the official app pages there is only version 8 https://www.odoo.com/apps/modules/8.0/web_decimal_numpad_dot/ 

what should i/people make of this ?

**Comment by pedrobaeza** [comment]
This is because Odoo has forbidden to publish the same apps from different repositories. @lasley can you notify about this?

**Comment by lasley** [comment]
Yeah I'm still working with Odoo apps support on the Projects repo too.

This one looks to be migrated from a pre-existing repo from another user though. This is the edge case that is not considered in the Apps store - modules from all versions are restricted to one owner. From what I am understanding, we need the v8 in our repo.

**Comment by lasley** [comment]
Note on my tasklist today is to try to get into the email address that is receiving these fail notifications. Odoo SA advised me it is openerp-community-reviewer@lists.launchpad.net 😆

**Comment by icf20** [comment]
@pedrobaeza so is safe to use this ?

**Comment by lasley** [comment]
Definitely - it's an Odoo Apps store issue that we are currently working with them on

**Comment by pedrobaeza** [comment]
I suppose I can change the email although the account login is openerp-community-reviewer@lists.launchpad.net. Which one should I use?

**Comment by icf20** [comment]
@lasley does OCA provide the .zip files from a repo ?

**Comment by lasley** [comment]
@pedrobaeza We're probably good with that one assuming the password is in KeePass (I haven't looked yet - had to find and install a [Mac KeePass client](https://github.com/mstarke/MacPass) first)

Whatever email we use is going to receive a massive amount of garbage as we sort it all out, which I honestly don't even have a strategy on yet. 

@icf20 - Github has the option to export as zip:

![image](https://user-images.githubusercontent.com/7397578/32959026-1b9bd2c4-cb75-11e7-8a21-626aae933986.png)

**Comment by icf20** [comment]
@lasley oh god, so i need to trust github of this and files/apps are not individually signed

**Comment by lasley** [comment]
@icf20 - Odoo Apps Store isn't signed either, and is directly getting the apps from git repos. Six of one, half a dozen of another.

**Comment by lasley** [comment]
OCA is working on an apps store that could optionally include digital signatures, but that is not something that has ever existed in Odoo environment to date (to my knowledge)

**Comment by pedrobaeza** [comment]
Closing as this is something outside our scope.
