### ISSUE TITLE
[11] web_environment_ribbon yust works for admin, not for other users

### ISSUE THREAD

**Issue by fgarcia-humanoide** [OCA/web#805]
I have installed web_environment_ribbon as admin , and it works.

But loging as a normal user, the ribbon disappears.

**Comment by pedrobaeza** [comment]
I confirm the bug. 

@xavierjimenez can you please check?

**Comment by xavierjimenez** [comment]
Indeed, there's a bug with a non-administrator user. 

I have checked it out and it's an issue with permissions, the user can't access to the ir.config_parameter model (this is where the data of the ribbon is stored).

I have solved it with sudo() calls to the model but I'm not sure if that's an OCA standard.

@pedrobaeza

**Comment by pedrobaeza** [comment]
Yeah, indeed that's the correct change. In the migration guide (https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0) there's a point about that:
> Remove group_ids field in ir.config_parameter records, and read them with sudo() 

Please make the PR changing that.

**Comment by pedrobaeza** [comment]
Fixed in ae45d8f14a832f1a526f11005c106939cb902446
