### ISSUE TITLE
odoo 10.0 web responsive no active i have installeed web_responsive module

### ISSUE THREAD

**Issue by roccocesetti** [OCA/web#827]
Impacted versions:
10.0
Steps to reproduce:
android browser link demo10.ideawork.link
Current behavior:
no web responsive
Expected behavior:
si web responsive
Video/Screenshot link (optional):
![odoo_mobile](https://user-images.githubusercontent.com/4387127/34046532-ae755586-e1ad-11e7-9af5-0c1f4441d8d9.jpeg)
Thank you so much for your reply

**Comment by pedrobaeza** [comment]
As I have already said, web_responsive is for backend, not frontend
