### ISSUE TITLE
[10.0] web_translate_dialog: mixes translations terms

### ISSUE THREAD

**Issue by treviser** [OCA/web#835]
Tried to use the module on 10.0 with 3 languages. Technically, it works, but it mixes translated terms after saving when using more than 2 languages and copy/paste. I had to redo hours of work.

**Comment by pedrobaeza** [comment]
Module is not migrated, so what you are referring can be a side effect of using a 10.0 module in 11.0.

**Comment by treviser** [comment]
Thanks. I just wanted to share the observation, it might be useful.

**Comment by pedrobaeza** [comment]
Yeah, thanks for the info.

**Comment by rousseldenis** [comment]
@treviser Check also if you are not in the case solved by : https://github.com/odoo/odoo/commit/7dfdfa0103872e39d6fde60373c56b9786461489#diff-1e7fea0c1a48e736046cf234118f95d4 (and if you have that commit)

**Comment by treviser** [comment]
Sorry guys, but I've lost control while working for different customers on different versions. My observation is for version 10.0 20180105!

**Comment by pedrobaeza** [comment]
Uhm, then that's a possible real bug. But we need some kind of trace of what you have done for replicating the problem.

**Comment by treviser** [comment]
Gimme a minute.

**Comment by treviser** [comment]
My set-up:
- 3 active languages, en_US, de_DE and fr_FR
- Language of the administrator user is english, language of other users is german, company partner language is german
- Website languages: english, french and german, german is the default ([weisses-roessli-brunnen.twanda-hosting.ch](url))

I'm working as non-admin user with language preference set to german

After translating and saving the translations and the product, the language terms are stored properly (as you can see in the webshop, but the web_translate_dialog shows english, english again (instead of french) and german:

![selection_056](https://user-images.githubusercontent.com/1814941/34680474-78e74cc2-f499-11e7-96e2-6aaa887cd26b.png)

When I change my user language to english, all terms are shown in english, but translated correctly:
![selection_057](https://user-images.githubusercontent.com/1814941/34680538-aa64ecdc-f499-11e7-8e84-20e88ca65dbb.png)

When I change my user language to french: 


![selection_058](https://user-images.githubusercontent.com/1814941/34680610-e132efac-f499-11e7-8e1a-d0c3b19aaa06.png)

So, as I can observe: the translation terms are saved properly in the proper language, but when opening the translate dialog again, the language terms are displayed in the user preference language and all other language terms are displayed in english despite of the correctly saved translations.

**Comment by pedrobaeza** [comment]
Is this field one with `translate=html_translate` argument?

**Comment by treviser** [comment]
It's the field "name" of the object "product.template", if that helps.

![selection_059](https://user-images.githubusercontent.com/1814941/34681304-c02a98d0-f49b-11e7-8e93-097dad70426b.png)

**Comment by treviser** [comment]
@pedrobaeza The same happens to the field" website_description", which is of type "html" (and it seems to have this argument):

![selection_060](https://user-images.githubusercontent.com/1814941/34681853-69c2fdb4-f49d-11e7-89df-6ebec7f1327e.png)

**Comment by pedrobaeza** [comment]
OK, thanks for the information. I have changed title to be in line with the comments. I'm not able to dig further right now, but the issue remains here for further investigation.

**Comment by treviser** [comment]
Thanks for your efforts. I did observe this behaviour for any translatable fields. However, I have learned that it is not necessary to re-enter the translation terms, but just ignore the displayed terms after they are saved. This as a hint for others, before they unnecessarily start to re-enter translations as I did.

**Comment by treviser** [comment]
I have to uninstall the module. It leads to unpredictable displays of language terms also in regular Odoo tree views. I have completely lost control about translations.

**Comment by pedrobaeza** [comment]
Please see if #844 solves your problem

**Comment by ghozinfo** [comment]
I also try to use this module without success u pto now
I've digged a bit further and it seems to behave differently than the original Odoo translation mecanism.

This module calls the /web/dataset/call_kw/product.template/write API call.
The Odoo system calls the /web/dataset/call_kw/ir.translation/write API call.
This maybe explains why the module is not doing what it is supposed to do.
