### ISSUE TITLE
web_export_view Breaks native xls exportation

### ISSUE THREAD

**Issue by pablocm-aserti** [OCA/web#84]
When web_export_view is installed, the xls exportation through "More"->"Export" and changing csv to Excel stops working and raises the following javascript error:

```
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
```

Tested with 6c9f88b794ef968cc8a553f7059371ec59f2aedb and Odoo version 25b1df2

**Comment by pedrobaeza** [comment]
Do you have any suspect?

**Comment by pablocm-aserti** [comment]
The response is a 404 and the native exportation starts working again if you remove the ExcelExport inheritance, so I guess it has to do with the index redefinition.

**Comment by pablocm-aserti** [comment]
When you have both services - /web/export/xls_view and /web/export/xls - pointing to the same index method, only /web/export/xls_view is in the map rules when [looking for the handler](https://github.com/odoo/odoo/blob/f9d8493ee999f27eb33208c5eb4e52c76656d868/openerp/addons/base/ir/ir_http.py#L61), but I have yet to find why. If I rename index to anything else, both paths are present.

**Comment by pablocm-aserti** [comment]
[This](http://werkzeug.pocoo.org/docs/0.10/routing/) might be the problem:

> Each Rule object is instantiated with a string that represents a rule and an endpoint which will be the alias for what view the rule represents. Multiple rules can have the same endpoint, but should have different arguments to allow URL construction.

**Comment by pedrobaeza** [comment]
I see. Can we use the same service name for both things?

**Comment by pablocm-aserti** [comment]
I think we can't, but I haven't seen any drawback to renaming the method. Both native and view exportation work when you rename it.

**Comment by pedrobaeza** [comment]
OK, let's see if there is any problem in the review process that we haven't seen.
