### ISSUE TITLE
[11.0] web_widget_color, doesn't work correctly

### ISSUE THREAD

**Issue by GabbasovDinar** [OCA/web#841]
We have issue with web_widget_color:
Now we activate the widget when a checkbox is active. Piece of our code:
```
<field name="checkbox" nolabel="1" class="oe_inline"/>
<field name="color" widget="color" attrs="{'readonly':[('checkbox','=',False)]}" class="oe_inline"/>
```
When we create new record and then we check the box, the widget is not appear, but when we save the record and edit again we can see the widget and select color.

it works correctly for Odoo 10.0

**Comment by pedrobaeza** [comment]
@etobella you migrated it. Can you check?

**Comment by etobella** [comment]
I am reviewing it. I have found two issues:

- When you are on a list and you want to create a new element. widget_color is not working
- When the widget is under a conditional readonly, it is not working on the modification.

I have a solution for the second one, but I am still working on the first.

**Comment by pedrobaeza** [comment]
@etobella any news?

**Comment by etobella** [comment]
Well, I tried a lot of things, but I am unable to fix the first problem :cry: 
It seems that it is not enabling the widget on reload. I can upload the change that solves the second option, but it will not be solving all the problems.

**Comment by pedrobaeza** [comment]
@simahawk maybe you can help with this

**Comment by simahawk** [comment]
> When you are on a list and you want to create a new element. widget_color is not working

what's happening? Traceback? debugger results?

**Comment by Tardo** [comment]
Fixed issues... needs review.
