### ISSUE TITLE
[10.0] web_widget_x2many_2d_matrix, Sometimes error, asyncrunus call fields_view_get

### ISSUE THREAD

**Issue by javierjcf** [OCA/web#857]
Sometimes, the start method gets called befoere the set_value method, so dictionarie this.fields is not loaded and we get an error beacause can access a field inside of thar dictionary that supposed to be filled.
The error is **Uncaught TypeError: Cannot read property 'type' of undefined**.
We have to open the widget window many times and in one of them we get the error

**Comment by pedrobaeza** [comment]
Version? Maybe you can call that method on the init.

**Comment by javierjcf** [comment]
Hi Pedro,
It's for v10. I tried what you said, but other similar error gets raised. 
I 'm confused about the fact that in theory ,the set_value method should be called before the start method, and i don't understand why refreshing several times the same model and opening the grid, i get different results. I think is about  asyncronus calls problem.
I am using this matrix because of the sale_order_variant_mgmt modue.
I 've checked check it in an empty database if i get the error, and yes, i install sale_order_variant_mgmt, create a empty sale order, and opening and closisng a several times the wizard window i get the error.

**Comment by pedrobaeza** [comment]
But are you sure it's not a problem of not half-loaded resources?

@Yajo can you help with this?

**Comment by javierjcf** [comment]
I'm not sure, cause i don't understand the logic behind framwork web and calls to the set_value method.
It seems to be, that in a database with a lot of data it is more probably to get the error.
Creating a new database, installing sale_order_variant_mgmt with demo data, when opening the grid all seems right. Closing and  reopening repeated times will raise the error. The las time i do this 25 time.
In a project i am working this bug happenns more times.

If a put console.logs in start and get_value methods, when the error is raised is because the order of calls has changed: first start then set_value, so definition of field_view_get it is not loaded, and in the start method it get the failure.

**Comment by javierjcf** [comment]
I attach an image of error. You realaise that i'm using odoo enterprise edition, but i think it happens to me in community as well.

![so013 - odoo - google chrome_918](https://user-images.githubusercontent.com/5653927/35875673-4cf04ae0-0b70-11e8-988e-e4bf4c1d08ea.png)

**Comment by yajo** [comment]
Thanks for the report.

The main culprit is clear here: https://github.com/OCA/web/blob/db12eb2545273292a03201bc1cc30f185b412d28/web_widget_x2many_2d_matrix/static/src/js/web_widget_x2many_2d_matrix.js#L266

`this.fields[this.field_value]` becomes `undefined` and thus the error of `Cannot access property 'type' of undefined`.

Why is it `undefined` in the first place? Hard to say, but most likely a race condition, given https://github.com/OCA/web/issues/857#issuecomment-363492288.

It seems the race condition culprit is this one, which happens inside a promise resolution, but `format_xy_value()` does not wait for any promise to be evaluated: https://github.com/OCA/web/blob/db12eb2545273292a03201bc1cc30f185b412d28/web_widget_x2many_2d_matrix/static/src/js/web_widget_x2many_2d_matrix.js#L100

It's a typical error of async code management. [Check here for an example on how to fix, where the public method asks for a promise to be resolved with the private one.](https://github.com/OCA/website/blob/16c2375e7b23fb339a0928a1f8af3d2511974afd/website_form_builder/static/src/js/snippets.js#L238-L264)

**Comment by javierjcf** [comment]
As i see it, the problem is in the order that framework web calls **set_value** and **start** widget functions.
In the start function is called the method compute_totals, and this methos calls format_xy_values.
In a good situation, ter start method is called allways after set_value is done, so dictionary field is already filled with definition of fields_viw_get, but sometimes, start methos is called before set_value, so then go wrong.
Maybe the dictionary fields should be calculated in the init method instead of set_value?, or playing with priomises, ensure that when start method is called, fields dictionary is already initialiced.

**Comment by houzefa-abba** [comment]
I've had this same issue; my fix: https://github.com/houzefa-abba/web/commit/f6f0673f25bdb653fab69fec89fdc6fa248bc0c3

Haven't gotten around to checking it some more / submitting a PR but it made sense to me to simply remove that `start` function.

**Comment by simahawk** [comment]
we started looking at porting this module to v11 and bumped upon the same issue.
I thought it was due to v11 changes but here I see that I'm not the only one to think that that piece of code is weird :smile: 
@houzefa-abba your fix sounds good as a start (then you should follow Yajo's advises) despite you are dropping some event hooks. Maybe they should be moved to `events` attribute.

/cc @arkostyuk

**Comment by pedrobaeza** [comment]
@hbrunn you were the original creator of this. Maybe you can tell us...

**Comment by hbrunn** [comment]
making me responsible for all the stuff i started would keep me busy. this sounds like an event issue, i propose to inject some printf's and watch in the js console what's going on

**Comment by simahawk** [comment]
@houzefa-abba check this #871 
What I did there for start/init can be cherry-picked and refactored to v10.

**Comment by hongquangminh** [comment]
Can matrix view limit 80 records like tree view?

**Comment by pedrobaeza** [comment]
@minhhq09 please stop with that question in an unrelated thread. As stated before, it's not possible without developing the feature, and it's not simple.
