### ISSUE TITLE
[11]web_decimal_numpad_dot and expenses field dont work like intended 

### ISSUE THREAD

**Issue by icf20** [OCA/web#862]
in expenses on unit field the numpad dot remain a dot instead of comma

![image](https://user-images.githubusercontent.com/17784575/36115889-bf0e06d0-1034-11e8-8f9a-95708a4384f8.png)

**Comment by pedrobaeza** [comment]
Is that standard Odoo? Can you try the same on our runbot ("Try me on runbot" button)?

**Comment by icf20** [comment]
> Is that standard Odoo?

the official docker container 

> Can you try the same on our runbot ("Try me on runbot" button)?

![image](https://user-images.githubusercontent.com/17784575/36126575-692b5c84-1059-11e8-9b7f-888babca2b0d.png)

**Comment by pedrobaeza** [comment]
I'm talking the button in this README: https://github.com/OCA/web/blob/11.0/web_decimal_numpad_dot/README.rst

**Comment by icf20** [comment]
yes that one links to https://runbot.odoo-community.org/runbot/web/162/11.0 and is 404

**Comment by pedrobaeza** [comment]
Strange, try this one http://3317194-11-0-6726c8.runbot2.odoo-community.org/web/login with admin/admin

**Comment by icf20** [comment]
![image](https://user-images.githubusercontent.com/17784575/36127240-a8af8db4-105c-11e8-8b6d-4f2121386714.png)


1 had to load spanish and change user to spanish
2 install the expenses module
3 changed the currency to eur
4

**Comment by pedrobaeza** [comment]
But there's something very strange in the font you have. Are you sure you don't have anything strange in your OS. Which OS? Which browser?

**Comment by icf20** [comment]
![image](https://user-images.githubusercontent.com/17784575/36127344-2f269db0-105d-11e8-8144-1affbe43fa8b.png)

i added a comma(key code 188 / ascii 44) on the same field to see the difference 

> Which OS? 

debian testing

> Which browser?

firefox 52.6.0 

here in chromium

![image](https://user-images.githubusercontent.com/17784575/36127410-8636f67c-105d-11e8-80b8-d76b82a5f81b.png)

**Comment by pedrobaeza** [comment]
OK, I'm able to reproduce it. The problem seems to be the currency widget. @chienandalu please check this problem.

**Comment by icf20** [comment]
gracias por todo 👍

**Comment by chienandalu** [comment]
@icf20 @pedrobaeza You can review the fix here: https://github.com/OCA/web/pull/867
