### ISSUE TITLE
[10.0] web_m2x_options: System parameters values don't work

### ISSUE THREAD

**Issue by carlosdauden** [OCA/web#866]
After this commit:
https://github.com/OCA/web/commit/04e3da24772a6847f2501f03648006f07816af64
the system parameters values are ignored

**Comment by carlosdauden** [comment]
CC @matt454357

**Comment by pedrobaeza** [comment]
@matt454357 please check this and answer or I'll have to revert your commit.

**Comment by pedrobaeza** [comment]
As there's no answer, I'm going to revert the commit, as it's causing issues.
