### ISSUE TITLE
[9.0] web_domain_field: TypeError: second argument to Function.prototype.apply must be an array

### ISSUE THREAD

**Issue by enjaxx** [OCA/web#882]
Basically, I am trying to use an sql statement to create a domain. But that isn't really important. The domain is working well, if I choose the partner_id drop down list, but when I click on the "Search More..." option, the error appears.

It happens in line 3069 in web.assets_backend.js:

`result_domain.push.apply(result_domain,domain_array_to_combine);});return result_domain;}
`

After some debugging I see that domain_array_to_combine stays a string, parsing with parseJSON() doesn't happen here...

Is there a way to fix this for Odoo 9?

Python:

```
template_id = fields.Many2one(comodel_name='pi.query.parameter.template', index=True, string=u'Parameter')
partner_id =  fields.Many2one(comodel_name='res.partner', index=True, string=u'Partner')
partner_id_domain = fields.Text(
        compute='_compute_partner_id_domain',
        string=u'Partner ID Domain',
        readonly=True,
        store=False)

@api.multi
@api.depends('template_id')
def _compute_partner_id_domain(self):
    for rec in self:
        if rec.domain_sql:
            self.env.cr.execute(rec.domain_sql)
            id_list = [x[0] for x in self.env.cr.fetchall()]
            rec.partner_id_domain = json.dumps(
                [('id', 'in', id_list)]
            )
```
View:

```
<field name="partner_id_domain" string="Partner ID Domain" />
<field name="template_id" string="Field"/>
<field name="partner_id" string="Value" domain="partner_id_domain" />
```

**Comment by MosabAwadexp** [comment]
kind of the same problem here, any help??

**Comment by syc-pad** [comment]
Same problem here, with Odoo v15
