### ISSUE TITLE
[10.0] support_branding: Cannot read property 'username' of undefined

### ISSUE THREAD

**Issue by rquevedo** [OCA/web#898]
In branch 10.0, support_branding module inherits CrashManager.error template, but seems that 'session' is not in default context. I do a search in odoo modules and nobody use this variable in xml templates.

**Comment by hbrunn** [comment]
who fixed the problem in #890 already but nobody cared to review yet

**Comment by pedrobaeza** [comment]
#890 merged, so I close.
