### ISSUE TITLE
[10.0] web_widget_x2many_2d_matrix: Limit show record on Matrix

### ISSUE THREAD

**Issue by hongquangminh** [OCA/web#901]
Hello,

My request is limit record show on Matrix view. Like the tree view we have limit 80 record for each page. On Matrix, when i list about 200 record. The page loading script so long.

Thanks,

**Comment by pedrobaeza** [comment]
That's not something planned, because that's not the intended use. @simahawk please add it to the roadmap of your migration to v11, but nothing more will be done for now unless any contributor wants to do it.

**Comment by simahawk** [comment]
@minhhq09 tnx for the suggestion. @pedrobaeza I will.

**Comment by hongquangminh** [comment]
I used matrix for BOM. When use matrix i can overview about Materials and Products.

@jcdrubay Can you consider and contribute this function? :D

**Comment by pedrobaeza** [comment]
@simahawk any news on this?

**Comment by simahawk** [comment]
nope, nothing has been done

**Comment by samnimri** [comment]
Is there a way to increase or remove this limit?

**Comment by jcdrubay** [comment]
For the record: the widget seems to work much faster with Firefox and Safari than with Chrome. (tested in version 15.0)
