### ISSUE TITLE
[11.0] web_sheet_full_width: Chatter is not full width

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/web#904]
As said in the title, the chatter is not using the full width as in previous versions.

@Yajo please look for the style and fix it.

**Comment by yajo** [comment]
I think we should deprecate that addon and merge all stylish thingies into `web_responsive`.

Since v11, the enterprise client has a better responsiveness because the chatter goes to the right of the screen in wide screens, so it's possibly not working there. Then, no need to support both.

**Comment by pedrobaeza** [comment]
Well, that's the enterprise, and I personally don't like that "responsiveness". Please include then both features (sheet full width + chatter full width) in `web_responsive` (as well as search feature).

**Comment by janbec** [comment]
I was looking into the topic and am interested what the status is. We are using enterprise and have a few additional columns in sale order lines which produce a scrollbar at the bottom.

In v10 we used this module to prevent that scenario. But with the chatter on the right, it has no effect.

Would be glad to hear if there are any news? Thanks.

**Comment by pedrobaeza** [comment]
@Yajo can you please check if with new option in web_responsive this module is totally useless?

**Comment by yajo** [comment]
Checked; we should remove the addon; web_responsive is enough now.

**Comment by pedrobaeza** [comment]
OK, we can then "let it die" in this version, but we shouldn't remove it for avoiding breaking current installations that have it installed. Closing this issue then.
