### ISSUE TITLE
[web_widget_float_formula] On_change event not triggered when evaluating formula

### ISSUE THREAD

**Issue by diggy128** [OCA/web#914]
How to reproduce:
- Open any form with a float field that has onchange event (eg sale order) and change the float value with another float.
- Repeat with a formula

Current behavior:
- When user inputs float value directly, the onchange event is triggered and other fields are updated
- When user inputs formula, that field's value is updated but onchange event is NOT triggered and other fields are NOT updated (not even when saving the record).

Expected behavior:
When using a formula, the change of value should trigger the onchange event as it happens with putting a direct value.

**Comment by umitoprojet** [comment]
Are values changing when you trying to change it for second time? It might not changed for the first time. @diggy128

**Comment by diggy128** [comment]
@umitoprojet 
No, They don't. When moving focus out of the field and return to it, The calculation formula is displayed again and even after placing new values, the result gets updated but onchange does not trigger.

F.I.Y. This is on v8 (Community)

**Comment by umitoprojet** [comment]
I faced the same error in v11 and I'm waiting for solution. I've tried to fix it but I couldn't succeed.

**Comment by yung-wang** [comment]
I have the same problem in a journal when I try to reconcile. In invoices it works fine.

**Comment by sanube** [comment]
im also waiting for a fix for v11
