### ISSUE TITLE
[10.0][web_advanced_search_x2x] How to use "In selection" search

### ISSUE THREAD

**Issue by hhgabelgaard** [OCA/web#925]
Hi

In v8, when I used the "in selection" search operator in advanced search, a sub search window of the related records appeared.

In v9, according to this comment https://github.com/OCA/web/pull/555#issuecomment-282376114 on the migration PR, that seems to still be the case

On v10, I can't trigger the sub search window when using "in selection" - Tried it many times on OCA runbot

Is it something obviously I'm missing, or does the feature behave differently? I'm only seeing the domain widget:
![image](https://user-images.githubusercontent.com/7933710/40060324-9fa00900-5856-11e8-9803-d90e19e0f150.png)
What am I missing here?

Thanks!!

**Comment by pedrobaeza** [comment]
In v10, this module now uses web_widget_domain_v11, that allows a direct filter selection in the same window. Just click on "+ Add filter" to start with the "magic" ;)

**Comment by hhgabelgaard** [comment]
Thanks @pedrobaeza 
But the web_widget_domain_v11 is not so user friendly as the old v8 sub search window. 
Eg if I wan tto search for customers from several contries, I ned to know the ID of the country?
![image](https://user-images.githubusercontent.com/7933710/40061977-693f9c3c-585a-11e8-8cdd-6425891d24aa.png)
VS select them on a list:
![image](https://user-images.githubusercontent.com/7933710/40062042-8e2f0de8-585a-11e8-8471-b4a16f235d1b.png)
Giving me:
![image](https://user-images.githubusercontent.com/7933710/40062098-b2592af0-585a-11e8-8cac-4ee38695d2a0.png)
VS the v10 way:
![image](https://user-images.githubusercontent.com/7933710/40062129-cbb406e6-585a-11e8-88cf-0e7d8734982b.png)

Or have I missed the point in web_widget_domain_v11 ?

Or is there not so much "magic" here in v10 as there was in v8?

According to the README a search window should "pops up":

> To search for properties of linked records (ie invoices for customers with a credit limit higher than X):
> open the advanced search options in a search view
> select a one2many, many2many or many2one field
> select operator is in selection
> **in the search view that pops up, select the criteria**
> select the records you want, or select the top corner box to select all matching records with that criteria
> click Select

But maybe that's a leftover from v8 

Do you know if there is any hard technically reasons for not doing it "the old way", or has it just not been done in the migration, due to the availability of the web_widget_domain_v11?

Thanks!

**Comment by pedrobaeza** [comment]
No, use the "contains" operator.
