### ISSUE TITLE
[11.0][web_decimal_numpad_dot] Module breaks tab navigation

### ISSUE THREAD

**Issue by jesusVMayor** [OCA/web#929]
The module breaks the tab navigation on editable tree views.

With the module installed:
![giphy1](https://user-images.githubusercontent.com/5393537/40114782-6d6670ce-590e-11e8-8eaf-7d06af9e891b.gif)

Uninstalling the module:
![giphy2](https://user-images.githubusercontent.com/5393537/40114887-d0d68888-590e-11e8-836d-c41d9e8b6698.gif)

**Comment by pedrobaeza** [comment]
@Yajo can you check?

**Comment by etobella** [comment]
I found the same issue
