### ISSUE TITLE
Change license of web_widget_color to LGPL

### ISSUE THREAD

**Issue by yelizariev** [OCA/web#931]
I see the problem with AGPL that if we make a demo instances for our opensource modules that depend on ``web_widget_color``, we have to provide source for the modules along with the demo. Which means that we cannot really sale it in app store. That seems to be bad for ecosystem. 

The same problem for proprietary modules: people either cannot sale their work\service or have to violate the AGPL licence.

<s>For that reason It's likely that @it-projects-llc would need to develop similar module if ``web_widget_color``'s license is not changed. That sounds bad as well.</s>

List of contributors is quite big, but it seems that the only way to change the license is to get permission from all of them:
https://github.com/OCA/web/commits/7.0/web_color
https://github.com/OCA/web/commits/11.0/web_widget_color
Not full list of contibutors: @petrus-v @rschnapka @adrienpeiffer @pedrobaeza @sbidoul @gurneyalex @njeudy @llacroix @yvaucher @AdilHoumadi

**Comment by yelizariev** [comment]
This module was probably developed by @straga due to described problem https://www.odoo.com/apps/modules/10.0/web_widget_colorpicker/
which has LGPL-3

**Comment by pedrobaeza** [comment]
Well, I don't have problem with this low level component to be relicensed as LGPL, but I haven't develop it. Only maintenance contributions by my part.

**Comment by jssuzanne** [comment]
Hi,

I had develop this module, you may found the original [on bitbucket](https://bitbucket.org/anybox/widget_color).

I allow the usability of this module only under the AGPL License.This module have been paid by my customer. He paid the cost of my work and accept the free distribution for other AGPL project. 

I don't want that this module be relicensed as LGPL.

**Comment by hbrunn** [comment]
case closed I'd say. Thanks @jssuzanne for standing up for real open source!

**Comment by hbrunn** [comment]
PS: the whole discussion is moot anyways because jscolor is gpl licensed if you don't purchase a commercial license

**Comment by jssuzanne** [comment]
@hbrunn No I have never paid the commercial license. I have forgotten the license of jsscolor.

**Comment by yelizariev** [comment]
ok ``¯\_(ツ)_/¯``

**Comment by yelizariev** [comment]
@hbrunn FYI: jscolor has LGPL https://github.com/OCA/web/blob/d16218b6715f71a88d357b33add30785ada35637/web_widget_color/static/lib/jscolor/jscolor.js#L5

**Comment by hbrunn** [comment]
then the website lies: http://jscolor.com/download

**Comment by yelizariev** [comment]
They either changed the license in a later version or OCA has license violation (switch GPL to LGPL)

**Comment by yelizariev** [comment]
> Thanks @jssuzanne for standing up for real open source!

I have to note that this *real open source* approach force us to work on parallel (open source) solution

**Comment by pedrobaeza** [comment]
> then the website lies: http://jscolor.com/download

I think the JS lib version is older and the license has changed. AFAIK, OCA hasn't changed anything.

**Comment by dreispt** [comment]
@yelizariev It is legit to develop (and propose to the OCA) an LGPL implementation of the same feature, based on the LGPL version of jscolor.

**Comment by JordiBForgeFlow** [comment]
@dreispt I think that this is not correct. If you can demonstrate that you have not looked into the original code. Otherwise it is considered a copy. That is, if the new work is pure invention, and the new author just received functional specifications, then you are producing a new artifact. 

That said, if a module is just a few LOC and it is obvious how to make it for a person with some knowledge on the subject, my above statement would be questionable.

**Comment by dreispt** [comment]
@jbeficent I didn't look at the module discussed, so I don't know how complex/original it is.

["Copyright is a legal right that grants the creator of an original work exclusive rights for its use and distribution."](https://en.wikipedia.org/wiki/Copyright). In principle, some originality is needed to be able to claim for copyright.

If a work is trivial, such as is just a for lines of code wrapping around some other work, there may not me enough originality to claim copyright.
You don't have ground to claim that other, also trivial, implementations of the same goal are copies of yours.

If there is original work is LGPL, and then I create a simple derivative work wrapping it for Odoo, I would say it is more questionable to relicense is as AGPL, than to keep the original work's LGPL. However, this is not what happened:

- jssuzzanne created an AGPL module based on a AGPL licensed library.
- Ivan wants to create an LGPL module based on a LGPL lincensed version of the same library.

So, I don't see any reason why it's not leggit for Yvan to do so.

**Comment by yelizariev** [comment]
> jssuzzanne created an AGPL module based on a AGPL licensed library.

@dreispt, current module ``web_widget_color`` uses LGPL  licensed library.

**Comment by yelizariev** [comment]
@straga promised to publish his [module](https://www.odoo.com/apps/modules/10.0/web_widget_colorpicker/) at github, so we are going to use it and contribute to his repository if needed. I don't think that I or @straga is willing to move the module to OCA. At least until @straga stops maintenance

**Comment by yelizariev** [comment]
It seems that there is a license violation from another vendor: https://www.odoo.com/apps/modules/11.0/colors_customization/

* ``colors_customization`` is  OPL-1 
* ``web_widget_color`` is AGPL 


the license is incompatible, so the author offer to install ``web_widget_color`` manually. It's not a violation from the author, but they have a demo link which has AGPL module installed. That means that  ``colors_customization`` must have AGPL too, because it's definitely "distribution" according to AGPL terms.
https://colors.erpbase.ru/ 
demo
demo

**Comment by pedrobaeza** [comment]
Notified to legal@odoo-community.org

**Comment by yelizariev** [comment]
Alternative LGPL module is here: https://github.com/straga/odoo_vik_main/tree/11.0/web_widget_colorpicker
