### ISSUE TITLE
[10.0]Web Responsive:Multiple database display company logo abnormal deviant

### ISSUE THREAD

**Issue by lonelyleaves** [OCA/web#932]
I'm sorry, but when I use this feature, if I have multiple databases, then the logo displayed on this screen cannot be automatically changed based on the database company logo. This is a very distressing issue.

**Comment by pedrobaeza** [comment]
Can you record a video demonstrating that? I'm not having that kind of issues and I suspect is something with your deployment.

**Comment by lonelyleaves** [comment]
[about company_log.zip](https://github.com/OCA/web/files/2022378/about.company_log.zip)

**Comment by lonelyleaves** [comment]
This is my operation video,  Hope to get your help Thank you

**Comment by lonelyleaves** [comment]
![image](https://user-images.githubusercontent.com/16489920/40306758-775672fa-5d32-11e8-9a75-fd96a115a049.png)
The arrow on the right side should display dbname and company_id.This is the method of the web module：    img t-attf-src="/web/binary/company_logo{{ '?dbname='+db if db else '' }}"

**Comment by pedrobaeza** [comment]
The problem you have is because you don't have a proper dbfilter set by domain, and thus this is something expected. A correct deployment implies to do that, because you will find a lot of problems (not only with this module, but with others) if not.
