### ISSUE TITLE
[11] web_timeline : tasks order change by it self

### ISSUE THREAD

**Issue by andreati** [OCA/web#936]
Hi. When I try to scroll left or right until some tasks disappear and then scroll back to make tasks reappear, sometime the order of tasks is changed by them self. Please help.

**Comment by pedrobaeza** [comment]
That's the expected behavior, as the JS control arrange the elements in the layout dynamically according the available space, element size, etc, so there's no fixed order nor distribution.

**Comment by andreati** [comment]
Any suggestion if certain order needed?
