### ISSUE TITLE
web_widget_text_markdown: Lexer passed array instead of string

### ISSUE THREAD

**Issue by dek-odoo** [OCA/web#937]
**Issue:**

Install `web_widget_text_markdown`.
Open any sale order with sale order lines, it will throw js traceback. Issue is with tax_id field inside sale order lines.

An array is passed to the Markdown Lexer instead of string.

**Reproduce:**
The issue can be reproduced on our runbot with this [link](http://3325978-10-0-ed6ffe.runbot1.odoo-community.org/web?debug=assets#id=8&view_type=form&model=sale.order&menu_id=217&action=288).

**Demo:**
I have uploaded [demo video](https://youtu.be/Nc3GPivmxHU) **explaining/debugging** the bug.

Introduced in this [commit](https://github.com/OCA/web/commit/9b515fc408e14c5c375f62e5bef5421970f13a19)

Thank you.

**Comment by njeudy** [comment]
Hello @dek-odoo , I can reproduce this problem .. 
I will only parse markdown for column with widget = markdown to prevent this bug.

thank for reporting

**Comment by dek-odoo** [comment]
:+1:

**Comment by njeudy** [comment]
Begin to work on it #942

**Comment by njeudy** [comment]
Ok think it is not corrected :) test and review needed :)

**Comment by njeudy** [comment]
![image](https://user-images.githubusercontent.com/995787/40862734-bc2ae884-65ed-11e8-9742-18ef16a5c582.png)
