### ISSUE TITLE
Supporting Progressive Web App

### ISSUE THREAD

**Issue by emanjuGbr** [OCA/web#947]
Hi all,
I was wondering if there are any plans to support PWA in near future?

I am really looking forward for this since this replaces the need of a mobile app almost completely.
What would be necessary to support this can anyone give some advice what the necessary steps are and if it is possible within a reasonable effort at all?

**Comment by pedrobaeza** [comment]
You can try https://github.com/OCA/web/tree/11.0/web_responsive for a responsive interface, but not other plans have been announced right now.
