### ISSUE TITLE
web_responsive + editable="bottom": Nos show overflow: auto

### ISSUE THREAD

**Issue by adrianlaraperez88** [OCA/web#948]
Issue:

Install web_responsive + view type tree and editable="bottom" fields .
`<record id="ed_product_tree_view" model="ir.ui.view">
            <field name="name">ed.product.tree.view</field>
            <field name="model">product.product</field>
            <field name="arch" type="xml">
                <tree string="Product" editable="bottom" create="false" edit="false" delete="false">
                    <field name="request_product_qty"/>
                    <field name="is_user_manager" invisible="1"/>
                </tree>
            </field>
        </record>`

No show overflow:scroll in device size.
![example](https://user-images.githubusercontent.com/19626181/41078819-f45fb7b8-69ec-11e8-928e-fda01559353c.png)

Thank you.

**Comment by pedrobaeza** [comment]
Please try without the Openworx theme

**Comment by adrianlaraperez88** [comment]
Sorry I was try in default view in odoo 11 and exist the same problem, only
use the backen theme in the picture.

**Comment by adrianlaraperez88** [comment]
Picture

![screenshot from 2018-06-07 07-24-19](https://user-images.githubusercontent.com/19626181/41096866-ff9af9e4-6a23-11e8-8d3d-8dc1bbbeb0ae.png)

**Comment by pedrobaeza** [comment]
Yeah, but the problem there is a very low resolution + no kanban on that view. You need a minimum resolution and adapt views to have a mobile kanban view.

And please don't spam multiple places (OCA + here).

**Comment by adrianlaraperez88** [comment]
for what do you closed the ticket in two places, no is issued ,this problem
only view when use editable top or button in view tree.

**Comment by adrianlaraperez88** [comment]
I sent it to the two github because I was not sure who the issue was, but
if it bothers you so much that I mention a problem, excuse me, all not we
are master in odoo eat you, apologies

**Comment by pedrobaeza** [comment]
The procedure is to send it to one place. If not suitable, then it's redirected to the proper one. But not the 2 at the same time for spreading the debate

I close it because the reason in https://github.com/OCA/web/issues/948#issuecomment-395388308

**Comment by adrianlaraperez88** [comment]
Ok, for what if not use editable top working fine

**Comment by adrianlaraperez88** [comment]
In odoo ir 2nd issue with editable top

**Comment by adrianlaraperez88** [comment]
Please take 2 min and check this please

**Comment by pedrobaeza** [comment]
As said, on mobile, for a correct interaction, you need a mobile kanban view. Check sales order, where it's implemented.

**Comment by adrianlaraperez88** [comment]
Thanks,
