### ISSUE TITLE
[10.0] web_domain_field: Uncaught TypeError: CreateListFromArrayLike called on non-object

### ISSUE THREAD

**Issue by rousseldenis** [OCA/web#957]
I think there is a limitation in web_domain_field module.

For example, in purchase order form, if you try to apply the computed domain on a line field, the domain will only work for existing lines (when modifying). It crashes on new lines as the domain was not computed at loading for that new line (that's obvious - value = False).

**Comment by rousseldenis** [comment]
@lmignon

**Comment by yao-big** [comment]
Are there any good solutions?

**Comment by yao-big** [comment]
@rousseldenis Have you solved the problem?

**Comment by rousseldenis** [comment]
> @rousseldenis Have you solved the problem?

I think not but this is quite old.

**Comment by yao-big** [comment]
@rousseldenis Have you solved the problem? I want you to help me

**Comment by quzhaojing** [comment]
https://github.com/OCA/web/pull/1738#issuecomment-771371950

i have the same problem on odoo14

**Comment by em230418** [comment]
Reproduced this on 13.0. To escape this, set `default` param in definition of the field, that is used as domain.
