### ISSUE TITLE
[10.0] web_widget_color: Error: Permission denied to access property "nodeName"

### ISSUE THREAD

**Issue by Zelwak** [OCA/web#960]
Hi,
I just installed web_widget_color module and I have a problem.
I added the attribute widget="color" to a field in a form view.
In Edit mode, when I keep clicking on a color and I drag out of the frame, I have the next error:

> **Error: Permission denied to access property "nodeName"**
>http://localhost:8070/web_editor/static/lib/summernote/src/js/core/dom.js:142
>Retraçage :
>makePredByNodeName/<@http://localhost:8070/web_editor/static/lib/summernote/src/js/core/dom.js:142:9
>create@http://localhost:8070/web_editor/static/lib/summernote/src/js/core/range.js:663:24
>reRangeSelect@http://localhost:8070/web_editor/static/src/js/rte.summernote.js:610:13
>summernote_mouseup@http://localhost:8070/web_editor/static/src/js/rte.summernote.js:635:13
>dispatch@http://localhost:8070/web/static/lib/jquery/jquery.js:4640:50
>add/elemData.handle@http://localhost:8070/web/static/lib/jquery/jquery.js:4309:41

EDIT with correct traceback

**Comment by yajo** [comment]
Useless tracebacks. Please check https://github.com/odoo/odoo/wiki/Contributing#tracebacks and reopen when you submit useful ones. Thanks!
