### ISSUE TITLE
Why the web_responsive app drawer is only 80% width?

### ISSUE THREAD

**Issue by dreispt** [OCA/web#965]
Why isn't it 100%, occupying the full window, like in Odoo Enterprise?
Any chance we could change that?

**Comment by pedrobaeza** [comment]
The width percentage can increase to 90% or 95%, but I don't want to renounce to the possibility of hiding the drawer when clicking outside it.

**Comment by dreispt** [comment]
@pedrobaeza OK, I see the motive. Isn't pressing `ESC` enough?

**Comment by pedrobaeza** [comment]
In a mobile?

**Comment by dreispt** [comment]
What if we had an "X" in a corner (at the top right, if possible)?

**Comment by pedrobaeza** [comment]
That will alter the layout in a weird mode IMO, or make it very small to be tapped.

**Comment by dreispt** [comment]
I just had another look and you can dismiss the app drawer with a tap on the top left corner. Looks simple to me.
An improvement to that could be to dismiss the drawer if you tap on any whitespace around the App icons.

**Comment by pedrobaeza** [comment]
I'm not sure about this, but I let others to give their opinion and to implement it if they consider :wink:

**Comment by yajo** [comment]
I like it as it is. It's inspired in Android UI, which is that way too.

If we had to change that, I'd use 100% only in xs screen.

**Comment by tarteo** [comment]
In a project we implemented this module, but for the user it was too big so we reduced the size to like 50% with a simple module. It is certainly an user preference e.g. I also like it smaller than it currently is so a field like "Drawer Size" on the user preferences form would be very cool.

**Comment by pedrobaeza** [comment]
@dreispt can we close this issue?
