### ISSUE TITLE
[9.0]web_ir_actions_act_window_message: Uncaught TypeError: self.inner_widget.active_view.controller.recursive_reload is not a function

### ISSUE THREAD

**Issue by zakiuu** [OCA/web#976]
**Use case:**
- I've a server action declared for my model:
```XML
<record id="my_model_action" model="ir.actions.server">
        <field name="name">My action</field>
        <field name="model_id" ref="model_my_model"/>
        <field name="code"><![CDATA[
action = self.my_action(cr, uid, context['active_ids'],context=context)
]]></field>
    </record>
```
- Of corse we need an `ir.value` record so the action will be added in the `actions` menu
```XML
<record model="ir.values" id="product_template_activate">
        <field name="name">My action</field>
        <field name="key2">client_action_multi</field>
        <field name="value" eval="'ir.actions.server,%d'%my_model_action"/>
        <field name="model">my.model</field>
    </record>
```
- Then inside my model, I use `my_action` method to display the window message:
```Python
    @api.multi
    def my_action(self):
        msg = _("my action message")
        return {
            'type': 'ir.actions.act_window.message',
            'title': _(u"My action title"),
            'message': msg,
            'buttons': [
                {
                    'type': 'method',
                    'name': _('My other action'),
                    'model': self._name,
                    'method': 'my_other_action',
                    'args': [self.ids],
                    'kwargs': {'context': {'active_model': self._name}},
                },
            ],
        }
```
- Then the user will select some records on the list view of my mode, then `actions` menu, then `my action`.
- the message window is well displayed, but if the user clicks on `close` button or `My other action` button, the action is executed but then I've this frontend message error:
```
Uncaught TypeError: self.inner_widget.active_view.controller.recursive_reload is not a function
http://localhost:8069/web/content/20011-fe1ba17/web.assets_backend.js:9227
Retraçage :
TypeError: self.inner_widget.active_view.controller.recursive_reload is not a function
at Object.<anonymous> (http://localhost:8069/web/content/20011-fe1ba17/web.assets_backend.js:9227:42)
at Object.<anonymous> (http://localhost:8069/web/content/19746-3b2cca7/web.assets_common.js:650:681)
at fire (http://localhost:8069/web/content/19746-3b2cca7/web.assets_common.js:644:299)
at Object.fireWith [as resolveWith] (http://localhost:8069/web/content/19746-3b2cca7/web.assets_common.js:649:198)
at Object.deferred.(anonymous function) (http://localhost:8069/web/content/19746-3b2cca7/web.assets_common.js:651:56)
at fire (http://localhost:8069/web/content/19746-3b2cca7/web.assets_common.js:644:299)
at Object.fireWith [as resolveWith] (http://localhost:8069/web/content/19746-3b2cca7/web.assets_common.js:649:198)
at Object.<anonymous> (http://localhost:8069/web/content/19746-3b2cca7/web.assets_common.js:650:874)
at fire (http://localhost:8069/web/content/19746-3b2cca7/web.assets_common.js:644:299)
at Object.fireWith [as resolveWith] (http://localhost:8069/web/content/19746-3b2cca7/web.assets_common.js:649:198)
```
- The error message is clear enough that the list view controller doesn't have `recursive_reload` method ( this method is only available in `form` views). But I don't find any function to do the same in the list views.

**Comment by zakiuu** [comment]
@hbrunn @benwillig any idea?

**Comment by hbrunn** [comment]
call https://github.com/OCA/OCB/blob/9.0/addons/web/static/src/js/views/list_view.js#L519 - so best refactor the code a little to have a function that inspects the controller, if it has `recursive_reload`, call that, if it has `reload_content` call that, log an error in the js console otherwise

**Comment by zakiuu** [comment]
@hbrunn thanks for the replay,

I already have tried to do so, but the `reload_content` doesn't seem to be available in the controller:
<img width="1439" alt="screen shot 2018-07-03 at 11 14 48 am" src="https://user-images.githubusercontent.com/222333/42214095-74e2e764-7eb2-11e8-9498-c2cca55308cb.png">

**Comment by hbrunn** [comment]
how do you deduce this from your screenshot? What you see in the debugger looks like an instance of `ListView`, so it should have the function.

And do yourself the favor to do your debugging in debug mode

**Comment by zakiuu** [comment]
The point of the screenshot ( I did a `console.log` just for the sake to have a clean shot) is to show that `reload_content` is not present in the functions list. And yeah it is a `ListView` and I don't understand why I don't have the method.
Also I've tried:
```JS
self.inner_widget.active_view.controller.hasOwnProperty('reload_content')
```
and it returns `False`

**Comment by hbrunn** [comment]
`hasOwnProperty` can be misleading. what does `self.inner_widget.active_view.controller.reload_content` say?

**Comment by zakiuu** [comment]
@hbrunn You're right, the `hasOwnProperty` was misleading.
I've created a PR to fix this issue: https://github.com/OCA/web/pull/977
