### ISSUE TITLE
web_dialog_size

### ISSUE THREAD

**Issue by nogueira-raphael** [OCA/web#981]
The dialogs can not be dragged according to the application, is it some error or has this feature been discontinued?

**Comment by pedrobaeza** [comment]
It seems so that the feature has gone. @qtheuret you were the one that migrated it. Do you know something about this?

**Comment by qtheuret** [comment]
It seems so that the feature has gone, indeed. Can you assign me on this issue ? I'll check it.

**Comment by qtheuret** [comment]
Something strange : in debug (with assets) mode with a breakpoint on line 31 on JS file, it works. But without the breakpoint, it don't allow dragging. I'll investigate on this.

**Comment by pedrobaeza** [comment]
@Yajo can you help in this?

**Comment by yajo** [comment]
I'm personally not much interested in dragging dialogs.

**Comment by pedrobaeza** [comment]
@Yajo it's very useful for seeing what is behind, which is sometimes needed. Any way, please check the possible reason for this not being working as it was in previous version.

**Comment by Tardo** [comment]
Changing https://github.com/OCA/web/blob/0b0ceb9de33e7f4fe4518878106b955f3f170795/web_dialog_size/static/src/js/web_dialog_size.js#L29 for:
```
opened: function(handler) {
        return this._super.apply(this, arguments).then(function(){
            if (this.$modal) {
                this.$modal.draggable({
                    handle: '.modal-header',
                    helper: false
                });
            }
        }.bind(this));
    }
```
Works.

**Comment by pedrobaeza** [comment]
@Tardo can you please make the PR?

**Comment by qtheuret** [comment]
Thanks @Tardo

**Comment by nogueira-raphael** [comment]
Thanks @Tardo
