### ISSUE TITLE
web_sheet_full_width 11.0

### ISSUE THREAD

**Issue by nogueira-raphael** [OCA/web#982]
Install a web_sheet_full_width application but I did not notice it in the list views, I need to change something to make it work.

**Comment by pedrobaeza** [comment]
List views are already full width. Any way, this module is deprecated in favor of full powered `web_responsive` module.

**Comment by nogueira-raphael** [comment]
Taking advantage of your help @pedrobaeza, you know some application to implement scroll bar in list views, because some visions get very compacted on the screen, making it difficult to read and edit the values.

**Comment by pedrobaeza** [comment]
I don't get your point. web_responsive already put scrollbars when needed...
