### ISSUE TITLE
Sales and Project modules can't be scrolled down/up on iPhone (tested with 7 and 7 Plus)

### ISSUE THREAD

**Issue by rapitkan** [OCA/web#986]
Sales and Project modules are not scrollable on iPhone. There are no problems with Android phones.

For example list of project is not scrollable.
There are only three or four projects on a page even if the pagination says there should be 40. It's because of the rest of them are unavailable because of the scrolling is not working.
You can go to next page using the pagination but the problem is same.

**Comment by tarteo** [comment]
Which module have you installed?

**Comment by rapitkan** [comment]
Hi! I have installed this module: https://www.odoo.com/apps/modules/10.0/web_responsive/

**Comment by pedrobaeza** [comment]
Have you tried on runbot (https://runbot.odoo-community.org/runbot/repo/github-com-oca-web-162)?

**Comment by rapitkan** [comment]
No, I haven't. How does it work? I'm new to runbot. Can I find a fix for the Web Responsive package there or test it or something else?

**Comment by pedrobaeza** [comment]
It's an empty instance with only repository modules with latest code, so you can check cleanly if the problem is outdated code or something that it's choking with other module you have installed. Click on the blue button for the version you are running to try, and login with admin/admin.

**Comment by rapitkan** [comment]
Ok. But I'm not sure if the Web Responsive package is installed there. I think it isn't.

**Comment by pedrobaeza** [comment]
Yes, it is. I have pointed you to the web repository runbot.

**Comment by rapitkan** [comment]
"Sales and Project modules are not scrollable on iPhone." Those modules are not installed on runbot. Is it okay to install them?

**Comment by pedrobaeza** [comment]
OK, go ahead.

**Comment by rapitkan** [comment]
I'm not sure about the Project view but Sales view seems to work properly on iPhone 7 Plus.

**Comment by rapitkan** [comment]
Project view is not working so this issue is still valid.

**Comment by rapitkan** [comment]
What version of https://www.odoo.com/apps/modules/10.0/web_responsive/ is installed here: https://runbot.odoo-community.org/runbot/repo/github-com-oca-web-162 ?

**Comment by pedrobaeza** [comment]
Always latest one. About project issue, can you take some screenshots to see the problem?

**Comment by rapitkan** [comment]
![project view - unscrollable](https://user-images.githubusercontent.com/2033731/43702004-00dd566e-9961-11e8-82ed-9f52736276f8.jpg)

**Comment by rapitkan** [comment]
It's iPhone 7 Plus screenshot above. User is unable to scroll the Project view. There is more than three projects in the page but they are unreachable. Can anyone repeat the problem? Any ideas? I'm using Odoo 10 Community Edition.

**Comment by pedrobaeza** [comment]
I'm not able to reproduce the problem in Firefox and Chrome in Android.

Can you please try another browser like Firefox or Chrome instead of iOS native one to see if it helps?

**Comment by rapitkan** [comment]
Thank you for testing. This is iPhone related problem. I have tested those views with Android (OnePlus 5T) device too and they are working. But they should work with iPhone and iOS too.

**Comment by pedrobaeza** [comment]
Yeah, but as being very specific and without possibility to try (as I don't have an iPhone nor want it :stuck_out_tongue_closed_eyes: ), we can't debug it. If you are able to track the problem and point it or solve it, then it can be solved.

**Comment by rapitkan** [comment]
I'm not iPhone lover either but I'm not sure if I can describe the problem more accurately. If the scrolling problem with Project view can be resolved (screenshot above) every other view will get fixed and be scrollable too I hope.

**Comment by rapitkan** [comment]
I just noticed that someone else has the same problems: https://www.odoo.com/groups/community-59/community-30524050

**Comment by zlycong** [comment]
Have you solved the problem?
