### ISSUE TITLE
[11.0]web_group_expand: Expand/Collapse buttons are not shown when using a standard search (saved as favorite)

### ISSUE THREAD

**Issue by RamlaFtouh** [OCA/web#987]
When we use a standard search that is saved as favorite, the Expand/Collapse buttons are not shown.

**Comment by Tardo** [comment]
Can't reproduce this issue...
This module only works with "grouped" search's... Anyway I don't understand very well what "standard search" means.

**Comment by RamlaFtouh** [comment]
Hello , 
I'm sorry for not being clear in my comment. 

If I have a custom filter (containing groups) that is registered , and used like a default filter ,  the Expand/Collapse options are not available (buttons not shown) when the tree view is loaded for first time
![web_group_expand_issue](https://user-images.githubusercontent.com/30926992/42740194-a5b00a46-889b-11e8-8295-52933c34463e.png)

I think the problem come from web_grroup_expand.js  -> Viewmanager ->_process_search_data function 

Regards.
.

**Comment by Tardo** [comment]
Confirmed and fixed in #993 ... needs review
