### ISSUE TITLE
[11.0] web_responsive: bad layout if form view has no `sheet` tag

### ISSUE THREAD

**Issue by isabellerichard** [OCA/web#988]
module: web_responsive
version: 11.0

**Steps to reproduce**
- install module *account_budget*
- configure *Chatter position* as *sided*
- go to menu of *Budgetary positions* and open form view

**Current behavior**
Form view layout is broken. It seems that this is happening on form views without `sheet` tag.

See picture (taken from [OCA Runbot](http://3331686-11-0-b773d9.runbot2.odoo-community.org/web?debug#id=1&view_type=form&model=account.budget.post&menu_id=252&action=347)):

![image](https://user-images.githubusercontent.com/6168915/42685760-2aa80f00-8694-11e8-9be9-63f4fe625aa8.png)

**Expected behavior**

Layout of form views without `sheet` tag should not be broken.

**Comment by pedrobaeza** [comment]
I remember to use form views without sheet correctly. Maybe is that specific view?

**Comment by yajo** [comment]
Please test (& approve if it works) fix in https://github.com/OCA/web/pull/991. Thanks!

**Comment by isabellerichard** [comment]
Approved! Thanks.
