### ISSUE TITLE
[11.0] web_timeline dragging items unsets date_end

### ISSUE THREAD

**Issue by tarteo** [OCA/web#989]
Dragging an item to a different timespan sets date_end to False.

How to reproduce:
To reproduce drag an item to a different timespan and refresh the timeline view. You can test it with project_timeline of OCA/project

**Comment by pedrobaeza** [comment]
Maybe that can be due to an onchange being triggered

**Comment by tarteo** [comment]
Doesn't seem to be caused by an onchange. In the write argument for vals is date_end False. I'll try to find out and make a PR.

**Comment by tarteo** [comment]
Found out what is causing the unset:
In /addons/project/models/project.py

```
    def write(self, vals):
        now = fields.Datetime.now()
        # stage change: update date_last_stage_update
        if 'stage_id' in vals:
            vals.update(self.update_date_end(vals['stage_id']))
```

The update_date_end method:
```
    def update_date_end(self, stage_id):
        project_task_type = self.env['project.task.type'].browse(stage_id)
        if project_task_type.fold:
            return {'date_end': fields.Datetime.now()}
        return {'date_end': False}
```

**Comment by pedrobaeza** [comment]
Then do you consider it should be as is?

**Comment by pedrobaeza** [comment]
I remember to bypass this somehow on project_timeline

**Comment by tarteo** [comment]
No, it's just not a bug of web_timeline. Indeed I'll bypass it by inheriting the update_date_end method.
