### ISSUE TITLE
web-timeline Create a new event give a TypeError: unhashable type

### ISSUE THREAD

**Issue by nfluckiger** [OCA/web#995]
I had to add a timeline view for the calendar. event type. The timeline work well for everything except that if we try to create an entry with double click on the time line, there is an error. I tried to debug it, I found that the entry is created, but the timeline gave an error when reloading. 
![screen](https://user-images.githubusercontent.com/29856302/42815485-c7715d2e-89c7-11e8-90b2-1c385db6ba77.png)

**Comment by pedrobaeza** [comment]
This is not a problem on the module, but the default values you have to pass for the creation.

**Comment by ecino** [comment]
@pedrobaeza Not sure we can close this so quick. I tested to have an action that displays both calendar and timeline views, so the context is the same (default values). The create in the calendar works but not in the timeline view. The create event works well but the refresh of the timeline fails at that javascript line: https://github.com/OCA/web/blob/10.0/web_timeline/static/src/js/web_timeline.js#L373

This calls a read on Odoo that will fail on interpreting the `fields` parameter (see original error posted).

**Comment by pedrobaeza** [comment]
OK, we reopen it then.
